/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Renders the sprite modules under `src/sprites/` from `design/gen.js`
 * (SPEC D10). Run it by hand after changing the generator:
 * `node design/render.mjs`. The page never loads this; only the art it writes
 * ships. A test re-renders the generator and compares every frame, so the
 * committed sheet cannot drift from its source.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'src', 'sprites');

/** Licence notice every generated module carries. */
const NOTICE = `/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
`;

/**
 * Turn a frame name into a JavaScript identifier: `amp_lean` to `ampLean`.
 *
 * @param {string} name Frame name.
 * @returns {string} The identifier.
 */
function identifier(name) {
  return name.replace(/_([a-z0-9])/g, (_, char) => char.toUpperCase());
}

/**
 * Load the generator. It is the body of a function rather than a module, so it
 * is evaluated rather than imported.
 *
 * @returns {*} What `gen.js` returns: the grid, the ramp, the poses, the
 *   loops, and `renderPose`.
 */
function loadGenerator() {
  return new Function(readFileSync(join(HERE, 'gen.js'), 'utf8'))();
}

/**
 * Write one frame's module.
 *
 * @param {string} name Frame name.
 * @param {string[]} rows The art, top to bottom.
 * @param {{cols: number, rows: number}} sheet Grid the frame sits on.
 * @returns {void}
 */
function writeFrame(name, rows, sheet) {
  const body = rows.map((row) => `  ${JSON.stringify(row)},`).join('\n');
  writeFileSync(
    join(OUT, `${name}.js`),
    `${NOTICE}
/**
 * @file Frame \`${name}\` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by \`design/render.mjs\` from \`design/gen.js\`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a ${sheet.cols} by ${sheet.rows} grid. */
export const rows = [
${body}
];
`,
  );
}

/**
 * Write the module that collects every frame, the loops, and the metadata.
 *
 * @param {string[]} names Frame names, in the generator's order.
 * @param {*} gen The loaded generator.
 * @returns {void}
 */
function writeIndex(names, gen) {
  const imports = names
    .map((name) => `import { rows as ${identifier(name)} } from './${name}.js';`)
    .join('\n');
  const frames = names.map((name) => `  ${name}: ${identifier(name)},`).join('\n');
  const meta = names
    .map((name) => {
      const pose = gen.POSES[name];
      return `  ${name}: { group: ${JSON.stringify(pose.group)}, energy: ${pose.energy} },`;
    })
    .join('\n');
  const loops = Object.entries(gen.LOOPS)
    .map(([loop, list]) => `  ${loop}: ${JSON.stringify(list)},`)
    .join('\n');
  writeFileSync(
    join(OUT, 'index.js'),
    `${NOTICE}
/**
 * @file The ASCII Punk sprite sheet (SPEC D10): every frame, the loops that
 * sequence them, and the grid they share. Generated by \`design/render.mjs\`
 * from \`design/gen.js\`; change the generator, not this file.
 */

${imports}

/**
 * The grid every frame shares. The cell shape is deliberately absent: the stage
 * measures the font it actually got rather than trusting a number from here.
 */
export const SHEET = Object.freeze({
  cols: ${gen.COLS},
  rows: ${gen.ROWS},
});

/**
 * Every frame's art, by frame name.
 *
 * @type {Readonly<Record<string, string[]>>}
 */
export const FRAMES = Object.freeze({
${frames}
});

/**
 * What each frame is: the group it belongs to and how much energy it carries.
 *
 * @type {Readonly<Record<string, FrameMeta>>}
 */
export const FRAME_META = Object.freeze({
${meta}
});

/**
 * The frame sequences, by loop name.
 *
 * @type {Readonly<Record<string, string[]>>}
 */
export const LOOPS = Object.freeze({
${loops}
});
`,
  );
}

const gen = loadGenerator();
const names = Object.keys(gen.POSES);
mkdirSync(OUT, { recursive: true });
let undefinedRows = 0;
for (const name of names) {
  const rows = gen.renderPose(gen.POSES[name]);
  undefinedRows += rows.filter((row) => row.includes('undefined')).length;
  writeFrame(name, rows, { cols: gen.COLS, rows: gen.ROWS });
}
writeIndex(names, gen);
if (undefinedRows > 0) {
  throw new Error(`${undefinedRows} rows render as undefined; a material has a tone but no albedo`);
}
console.log(`wrote ${names.length} frames and an index to ${OUT}`);
