/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Renders the sprite modules under `src/sprites/` from the design
 * project's generator (SPEC D10). Run it by hand after the design changes:
 * `node design/render.mjs`. The page never loads this, and neither do the
 * tests; only the art it writes ships.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'src', 'sprites');

/**
 * The one repair applied to the design project's generator, as a literal
 * replacement so it stays visible. The cigarette material carries a `tone` but
 * no `alb` and is not marked `flat`, so shading multiplies `undefined` and the
 * ramp lookup yields the literal text `undefined` in ten rows of the two smoke
 * frames. See `design/README.md`.
 */
const REPAIR = [
  '  if (mat.flat) return mat.tone;',
  '  if (mat.flat || (mat.alb == null && mat.tone != null)) return mat.tone;',
];

/** Licence notice every generated module carries. */
const NOTICE = `/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
`;

/**
 * Turn a frame name into a JavaScript identifier: `amp_lean` to `ampLean`.
 *
 * @param {string} name Frame name.
 * @returns {string} The identifier.
 */
function identifier(name) {
  return name.replace(/_([a-z0-9])/g, (_, char) => char.toUpperCase());
}

/**
 * Load the design project's generator with the repair applied.
 *
 * @returns {*} What `gen.js` returns: poses, loops, and `renderPose`.
 * @throws {Error} When the repair no longer matches, so a silent NaN cannot return.
 */
function loadGenerator() {
  const source = readFileSync(join(HERE, 'gen.js'), 'utf8');
  if (!source.includes(REPAIR[0])) {
    throw new Error('gen.js no longer contains the line the repair replaces');
  }
  return new Function(source.replace(REPAIR[0], REPAIR[1]))();
}

/**
 * Write one frame's module.
 *
 * @param {string} name Frame name.
 * @param {string[]} rows The art, top to bottom.
 * @param {{cols: number, rows: number}} sheet Grid the frame sits on.
 * @returns {void}
 */
function writeFrame(name, rows, sheet) {
  const body = rows.map((row) => `  ${JSON.stringify(row)},`).join('\n');
  writeFileSync(
    join(OUT, `${name}.js`),
    `${NOTICE}
/**
 * @file Frame \`${name}\` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by \`design/render.mjs\`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a ${sheet.cols} by ${sheet.rows} grid. */
export const rows = [
${body}
];
`,
  );
}

/**
 * Write the module that collects every frame, the loops, and the metadata.
 *
 * @param {string[]} names Frame names, in the generator's order.
 * @param {*} gen The loaded generator.
 * @returns {void}
 */
function writeIndex(names, gen) {
  const imports = names
    .map((name) => `import { rows as ${identifier(name)} } from './${name}.js';`)
    .join('\n');
  const frames = names.map((name) => `  ${name}: ${identifier(name)},`).join('\n');
  const meta = names
    .map((name) => {
      const pose = gen.POSES[name];
      const beat = pose.beat === undefined ? 'null' : JSON.stringify(pose.beat);
      return `  ${name}: { group: ${JSON.stringify(pose.group)}, energy: ${pose.energy}, beat: ${beat} },`;
    })
    .join('\n');
  const loops = Object.entries(gen.LOOPS)
    .map(([loop, list]) => `  ${loop}: ${JSON.stringify(list)},`)
    .join('\n');
  writeFileSync(
    join(OUT, 'index.js'),
    `${NOTICE}
/**
 * @file The ASCII Punk sprite sheet (SPEC D10): every frame, the loops that
 * sequence them, and the grid they share. Generated by \`design/render.mjs\`;
 * edit the design project, not this file.
 */

${imports}

/** The grid every frame shares, and the cell shape it was drawn for. */
export const SHEET = Object.freeze({
  cols: ${gen.COLS},
  rows: ${gen.ROWS},
  charAspect: 0.682,
});

/**
 * Every frame's art, by frame name.
 *
 * @type {Readonly<Record<string, string[]>>}
 */
export const FRAMES = Object.freeze({
${frames}
});

/**
 * What each frame is: its group, how much energy it carries, and where it falls in the bar.
 *
 * @type {Readonly<Record<string, FrameMeta>>}
 */
export const FRAME_META = Object.freeze({
${meta}
});

/**
 * The frame sequences, by loop name.
 *
 * @type {Readonly<Record<string, string[]>>}
 */
export const LOOPS = Object.freeze({
${loops}
});
`,
  );
}

const gen = loadGenerator();
const names = Object.keys(gen.POSES);
mkdirSync(OUT, { recursive: true });
let undefinedRows = 0;
for (const name of names) {
  const rows = gen.renderPose(gen.POSES[name]);
  undefinedRows += rows.filter((row) => row.includes('undefined')).length;
  writeFrame(name, rows, { cols: gen.COLS, rows: gen.ROWS });
}
writeIndex(names, gen);
if (undefinedRows > 0) {
  throw new Error(`${undefinedRows} rows still render as undefined; the repair is incomplete`);
}
console.log(`wrote ${names.length} frames and an index to ${OUT}`);
