/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `amp_lean` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                               `   !|",
  "                                                                               ?n  |J",
  "                                                                            n  ?a  mJ",
  "                                                                        |!  JJ ?8| 8J  !",
  "                                                                        `a| !8??8a?8J nn",
  "                                                                         !8m`a8?8paQ8?8? |m",
  "                                                                          ?oomQo8r8<8o8`J8`",
  "                                                                         n!nqQ8[*:pI8j8w8|",
  "                                                                         !am8x\\|/^<l{jJYa?J`",
  "                                                                        !?`a0Q?`  ]tQqJt#8?",
  "                                                                        `n8oCc\\JmJ|?   <z8n",
  "                                                                          ?oJ|?    ':~|fr#8n`",
  "                                                                          |8:  `!-|ju0b&W8<nm",
  "                                                                          J8},(fu0d*d$$$da-<8",
  "                                                                          |BQCd*0f)J$$hzjYqI8",
  "                                                                          B$$$$$$u}q$$$BQno?*!",
  "                                                                          JbtW%$%\\~_#$$&XvOq0?",
  "                                                                           a(%$$B/1xrtrucXUWo|lp_",
  "                                                                           !oJaZc/tXXUvzYJCp8hadWz.",
  "                                                                            |f1rJuxuLLXJCQQp&dCb8&dI",
  "                                                                            vuxcLQQ#@$%bOOLWdLa&&&8Mf",
  "                                                                           ta0CQwmd*a*aZZ0oMqM&&%B@Bbl",
  "                                                                          +owakdbkZnvXOOdWh#&&%B@%Zl  !Jo%BBBqn'",
  "                                                                         .k%@BB&M88*oo*WdUcm&@@8xl  'O88&&8%BB%Wf",
  "                                                                           `]Cq@@@BLun1)/xvz#&O((X{npWW*bbo&%BB&#u",
  "                                                                    ]\\CC]!      \\wB*\\()1|rvXw*oa*hoo#W#dOZkM%BB8Mk;",
  "                                                                 'x8%%%BBBa|CJoM#*oar//fnXCCbhba8akh#WMokh#8B@B8Mhr",
  "                                                                'd&M88%%%%%%88**#db&hYYJQO0Q#WpwMaYaM&WM#W8B@@@%Mhj",
  "                                                                qMWBMW8WM##*oakaWdq%WqCOYCnc*WCuqo0oM&WMM&%B@$B8#b)",
  "                                                               ~oMWB$#bqMq|Ubv}0M(vh&dQZnfU$@WM8%okoW&W#M&%@@@B&*p:",
  "                                                               +oW88$8\\xdMCZW#bk*&M%8kw0(|f8$MW8%od*W&M#M8B@$@%WaC",
  "                                                               .aM8%@$M#%B%%%%%WaWW88a(,1p[w$MW&%*b#W&M#W8B@$@8Mk)",
  "                                                                J#&%%$%M8BB%%%%%hMW8%o\\i?p1U$8WW%*h#&WM#W%B@$B&*p:",
  "                                                                IaW8%B$W&%B%%%%%*#&&%#z-]pun$BWW%#aM&WMM&%@@@BWaL",
  "                                                                 J#&%%$$M8BB%%%%WaWW%MJ1)Ccj@@WW%*aM&W#M&B@$@%Mk(",
  "                                                                 IoW8%%$%&%*k*8%%hMW%Ww\\/JQn*$MW%*oW&W#M8B@$B8#di",
  "                                                                  J#&%%@$W0|/cXOQ#&&8&dfjX0vd$&W%o*W&M#W%B@@B&om",
  "                                                                  IoW8%%$BXvzcY0Xxw88&kunXpXZ$8W8o#WWM#&%@@@%Whf",
  "                                                                   J#&%%%$*qO0wqY-]1zq&pCzpUC$@W8o#&WMM&B@$@8#d>",
  "                                                                   IoW%%%$$8hwwLj1){{{)zOa*w0&$M8hM&W#M8B@$B&ow",
  "                                                                    J#8%%8$B8Wo*Uvrt|){{1)nOo&@8&aM&W#W8B@@BWhf",
  "                                                                    IoW%%%@$W%B%8Wwcnj/(1{{1)nO#%%8&W#W%@@@%Md>",
  "                                                                     CM8%%8$@&%B%%B8dUvxf\\){{{1)np%BB88%@$@8*w",
  "                                                                     IoW%%%B$&8B%%BW*8*Qcnjt|1{{|rq%BBBB%88Waj",
  "                                                                      CM8%%8$$&%B%B@kWMoWqXvxf\\\\xzm8%%BBB%#*b>",
  "                                                                      Io&%%8%$%8BB%@o##wfhWbJcuzJQo8888%@%Wkm",
  "                                                                       CM8888%$&%B%@Wo#w|]JB%aqdhWBB%%8B@BWhf",
  "                                                                       I*MMWawB@8BBB@k*wv{1fwBB@@$@@@B@@$BWh)",
  "                                                                        CoW#pwo$8%BB@oowQzXJZq&@$$$$$$$$$BMd",
  "                                                                        IaW8WW8%$8BB@WawdJJJ|??Q$B$$$$$$$8o~",
  "                                                                         wW%@@@8$B%B@Bkwq      }$8o8$$$$BX'",
  "                                                                         _M%@$$$8$8BB@owp       $Bao%@%Mw",
  "                                                                          lw$$$$&$$%B@Mwd>      &$*o%B&oz",
  "                                                                            `[[[!0$%%B%qk>      0$#W%BWaj",
  "                                                                                 I%$%B%Wh]      }$W&%%Wk)",
  "                                                                                  L$B%BWaj      >$%W8%Mb>",
  "                                                                                  I&$%B&or       $@W88#d:",
  "                                                                                   C$@%&ow       0$M88*q",
  "                                                                                   '#$88Md       t$M&&om8U(",
  "                                                                                  lYWWW&&8hr'    Y$&&%ab&8WdI",
  "                                                                                 z#M#*#M&&8W#_  v*o*$$8o88&Ma;",
  "                                                                                v*#obpboM&8&MaXC&&%%8&WMBBMMoY",
  "                                                                               }a**kqmpaM888Wodd*#LwCc0p&@##*b:",
  "                                                                               ua*#ohka#&8%8W*brxoqZjxmB$$#o#h|",
  "                                                                               ua#MWMMW&8%%8W#k0ZW%B$@$$$B#8Wo0",
  "                                                                               /a#WWWMW&8%%%&#hh@$$$$$@@B8%8&*k;",
  "                                                                               ~h*MWWWWW&8%%&Map?h#W&&WW&8%%&Ma\\",
  "                                                                                koMWWWMW&8%%8Moq uoM&&WW&88%8WoO",
  "                                                                                ua#WWWMW&8%%8Wod ;h#W&&WW&8%%&#k<",
  "                                                                                }h*MWWMW&8%%8W*b> UoM&&WW&8%%8Max          XJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ)",
  "                                                                                .k*MWWWWW8%%8&*k< ;h#W&&WW&8%8W*d         l_[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[x\"",
  "                                                                                 Uo#WWWMW&8%%&#hj  UoM&&WW&8%%&#h<         C}vqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp|fY",
  "                                                                                 /a#WWWMW&8%%&Mar  Ia#W&&WW&8%8Mox         k0w8%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%Bmwj",
  "                                                                                 ;h*MWWMW&8%%8MaQ   J*M&&WW&8%%&*b         *&&8%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%B@&u",
  "                                                                                  ZoMWWWW&8%%8Wop   Ia#W&&W&8%%&Mh]        *&&8%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%B@&u",
  "                                                                                  na#WWWWW8%%8W*d    J*M&&WW&8%8WoY        *&&8&88888888888888888888888888888888@&u",
  "                                                                                  ~h#WWWMW&8%%&*b>   Ia#W&WW&8%%&#b.       *&&8a*aaaaaaaaaaaaaaaaaaaaaaaaaaaaoo*@&u",
  "                                                                                   k*MWWMW&8%%&#k<    J*W&&WW&8%8Ma[       *&&8a#MMMMMMMMMMMMMMMMMMMMMMMMMMMM%o*@&u",
  "                                                                                   UoMWWWW&8%%&Mhj    Ia#W&WW&8%8WoY       *&&8a#W&&&&&&&&&&&&&&&&&&&&&&&&&&&%o*@&u",
  "                                                                                   }a#WWWWW8%%8Max     J*W&&WW8%%&#k.      *&&8a#W&&&&&&&&&&&&&&&&&&&&&&&&&&&%o*@&u",
  "                                                                                   .h*WWWMW&%%8WoQ     IaM&&WW&8%8Ma[      *&&8a#W&&&&&&&&&&&&&&&8&&&&&&&&&&&%o*@&u",
  "                                                                                    ZoMWWMW&8%8W*p      J*W&&W&8%%&*0      *&&8a#W&&&&&&WWWWW&&&&888&W&&&&&&&%o*@&u",
  "                                                                                    /a#WWWW&8%%&*b      IaM&&WW&&8&Mk:     *&&8a#W&&&&WMMWWWWWW&&&88&WMW&&&&&%o*@&u",
  "                                                                                    ~h#WWWW&8%%&#k<      J*W#M#*M&8Wo\\     *&&8a#W&&&W##MMMMMMWW&&&8&WM#W&&&&%o*@&u",
  "                                                                                     k*MWMWW&&8&#h<      Iaa*opqhW8&#O     *&&8a#W&&W*##MM#**##MW&&88&W#oW&&&%o*@&u",
  "                                                                                     uo*##oa#W8&Mhr       Jh*obb*&%8Mk:    *&&8a#W&&a*###*ahhao#W&&88&W#ohW&&%o*@&u",
  "                                                                                     ~ho*hwwhM88Wox       /o*oa#&%B%Mk>    *&&8a#W&*a*##ohbppbh*MW&88&WM*ho&&%o*@&u",
  "                                                                                     Ia*okdk*&%8Woq       m**aoM8%B8#0     *&&8a#WWka***abqmmqbo#W&888&M*ab#&%o*@&u",
  "                                                                                     C**kbh#&%B%&ow      +a*oa*&%B%Wh]     *&&8a#Woho**ohdwZmqbo#W&888&M#abh&%o*@&u",
  "                                                                                    {o*hbk*&%BB%Wa|      J**aaM8%B8*X      *&&8a#Whho***abqwL/{(nd88%8&W#okp&%o*@&u",
  "                                                                                   Ia*abboW8%B%&*0      .a*oa*&%B%Wk:      *&&8a#Wbho*#*ohbJ?iI1txk%%8&W#okqM%o*@&u",
  "                                                                                   w*okbaW8%BB8#O.      /o*aaM8%B&*z       *&&8a#*bho####*a1?  1ruY%%8&W#okqo%o*@&u",
  "                                                                                  t**kbhM8%BB8#Z.       m*oa*&%B%Mb.       *&&8a#obao#MMMM#{)}1jvXX%%%8W#okqo%o*@&u",
  "                                                                                 +o*hbk#&%BB8Mb;       +o*aaM8%B&o|        *&&8a#*ba*#MWWWWrfruzJLzBB%8WMokwa%o*@&u",
  "                                                                                .w*abk*&%BB%Mk<        J**a*W%B%Md         *&&8a#Wba*#MW&&8bzYC0ZQbBB%8WMobmM%o*@&u",
  "                                                                                v*okboW8BB%Wh~        .a*MM#8%%&a[         *&&8a#Wka*#W&8888owwqwhBBB%8&#abZ&%o*@&u",
  "                                                                               |8%8&&W8%B%Wa~         YB@@$$@%%MO          *&&8a#Woh*#W&88%%%%B8BB@@B%8W#add&%o*@&u",
  "                                                                             ?oBBB@$$@88%&ox        'k%&#MB$$%#h]          *&&8a#WWho#W&8%%BBBBB@@@@B%8W*hq*&%o*@&u",
  "                                                                            -&%MkhW@$@%#M*x         Q&&bOb&$$BMO           *&&8a#W&*o#W&8%BBBB@@@@$@@%&Mobb&&%o*@&u",
  "                                                                           -W8&kZq#B$$%Mbn         lM8&*oWB$$BWb           *&&8a#W&Wo#W&%%B@@@@@$$$@B%&#abM&&%o*@&u",
  "                                                                          _W8&okhM%$$$BMb          0&8M*WB$$$BMd           *&&8a#W&&W#W&%BB@@@$$$$$@B8W*k*&&&%o*@&u",
  "                                                                         'k8&*khMB$$$$%Md         1W8&##8@$$$%*\\           *&&8a#W&&&WW&%B@$$$$$$$$@%&#o#&&&&%o*@&u",
  "                                                                        'b88#kk#%$$$$$8*x         d&8M*WB$$$@&h:           *&&8a#W&&&&WW8B@$$$$$$$@B8M*W&&&&&%o*@&u",
  "                                                                       'b88Mhk*8@$$$$%MZ.        fW8&##8@$$$%#Y            *&&8a#W&&&&&&&8B@$$$$$@B8WM&&&&&&&%o*@&u",
  "                                                                       d&8Mhbo&@$$$$B&a<        '#88M*WB$$$@8a[            *&&8a#W&&&&&&&&&8B@$$@%8&&&&&&&&&&%o*@&u",
  "                                                                      X&8WabaWB$$$$@8*\\         jW8&*#8@$$$BMd             *&&8a#W&&&&&&&&&&&&&&&&&&&&&&&&&&&%o*@&u",
  "                                                                     jW8WobhMB$$$$$%#O         IM88M*WB$$$$8*C]LL]         *&&8a#W&&&&&&&&&&&&&&&&&&&&&&&&&&&%o*@&u",
  "                                                                     qW%&*a#%$$$$$BWh;         fM88WM8@$$$B&M&#*WBk.       *&&8a#W&&&&&&&&&&&&&&&&&&&&&&&&&&&%o*@&u",
  "                                                                    U8W8BBBB$$$$$@8&B@@$pu`    jW%@@@$$$@&*dpppppb&\\       *&&8a%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@**@&u",
  "                                                                   j8Wqqoaa&&&8&W*ooo**#@$WI  r8#hM&aobppppppppph&W[       *&&88BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB88@&u",
  "                                                                   p88*ppppppppppppppppp*$&u  M8appppppppppo#8B$$Bf        *&&8%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%B@&u",
  "                                                                   Q8@$hppppppppppppppooB$W/ ^MB8pppppo#8$$$$WQ/i          w{Y%BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB/jf",
  "                                                                   >&@$$$$$$$$$$$$$$$$$$$@U...U%$B88$$$$$kO1:              kwh$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$pqx",
  "                                                                   .+p$$$$$$$$$$&mmmmmJ\\\\?\"\"^^^z$$$$$Zx(``'''...           W$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$z",
  "                                                                ..'''``|||i^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"]\\]\"^^^^^```'''...",
  "                                                                   ...''''````^^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                                 .................",
];
