/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `bang_down` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                                                              !",
  "                                                                                                                                             Q-",
  "                                                                                                                                            }a    ^",
  "                                                                                                                                        Q  ]$r  ^L[",
  "                                                                                                                                    (  !M\"`8bl f%\\   ^_",
  "                                                                                                                                    X0 uMlW@J^hW(  }qU",
  "                                                                                                                                 tOX08W$#d$pQ$*)[O$0~>}X+",
  "                                                                                                 ^;~~<<iI            ',        t8$$ck$$$bQWd$kb$@kbpBm{",
  "                                                                                               \"<++_+~~<<_~     'l!?}{|      t8$&w\\ ^&$BkwO*aB@#&@kx<",
  "                                                                                              <+_?1(1?+<<+?[  ;]{tjj/-}i   t8WkC)/U  b*8MbZOk%8aao*MQ{",
  "                                                                                            i+_?{/rxt}_<<~-{}  --_?-_~?} 'apZCcx  ?^ mk#8op0OdMMMdY|}}",
  "                                                                                          :++-{/rnr/1?~<>~-}/^  ?____+_( {LOCuft?    cwkM&hwLLookpQr)i",
  "                                                                                        :_+-}\\rnr/1]_~<>>~-}/_  \"[___+~}?Xnj\\(uoBYc0jQLqhWWkmUwo*w[",
  "                                                                                      \"<+-}|jnr/1]_~<>>i>~-{f-[< i?+~<<-zqLLzzoohdZOn icpaW#dOX+",
  "                                                                                    '<+_[|jxr/1]+~<>>iii>~?)1]{]_<1_</Cdbpqn  ^zZzu/   .(popQJU\"",
  "                                                                                   i+_[(jxr/1?+~>>>iiiii>_}jj}f)_+-Ya#8@kZZt   !fuXi  >. lOvurl",
  "                                                                                 l+_](fxr/1?+<>>iiiiii<~_[?({zC}+~zo%$BWd0Ln+  +cvnt. rw1~Oz?",
  "                                                                               :+_?)fxr/1?+<>>iiiii><+-]?~-}tJv{<_pdhhq0CYUuf{}xrftxp@$$MpU]",
  "                                                                             \"<_?1txr/1?+<>>iiiii><+?[_~~-}/j?<<?\\U0LCYvxfjjftt//Z&$&dLn{>^",
  "                                                                           '<++[txx/1?+<>>iiiii>~_]{[_~~-}/j?<~]((/Xnrftf\\)~!--}fdXr|I",
  "                                                                         \"<~~~<<-(1?+<>>iiiii<~-]1({-~~-}\\r?<+{ZZQqOUX/)j{+__`   ':l]",
  "                                                                        i--{1?+<~-[<>>iiii><+?]]{(1?+~-}|r?<_/*WdtYL[+}fx[_++?<",
  "                                                                       ;]-1jj1_<<_{}iiii>~__!l?[))[+~~}(r?<-nWWd}fLi <jzpz<~}]++,..",
  "                                                                       ~]-]1{-~><_}/ii>~-<:  ?]1(}_<~[(j-~?zW*O}cL> ~rj}({_r}<<~_?+<~:",
  "                                                                       ~]_-]-~>><_{t<+?i.   i?{(1?<<[)j+~[ChbU[vC> ~xt-<~]rZu<<<<+--~+?:",
  "                                                                       <]_-]-~>>~?)|+l     ^?}))]~<}1j++{LqwX[Uc> ?xt+<+[]~-+/J|<<~+--+-i",
  "                                                                       }?_nCUc\\+~]/!       +]1(}~<}1f+_|0ZO\\1Xv' }n|<<-}_~~~~1\\]>)><_]-~__",
  "                                                                       )1p#8*q0X)}{       I?{({~>[{/_-rQ0L|(Yn' }n1<~[[+~~~<>iiic0j?[~<<~_?:",
  "                                                                       )ChW@#wLYv)i     `'?}()+i?{(<?vqOCv\\zr' {n[<_{]~~~<>>iii>_}]_~~<<<<+-i",
  "                                                                       )wbhhwLXvz\\     \" <[)(+i]{{+{ZakpmUvf.'1x+~?1-~~<>>iii>~-]-<~~~~~<<<~__",
  "                                                                       )bbakmCzuu{     `:?1(]i]}??/Zooohbq/ \"\\f++}{_~<>>iii><_[->>><<~~~~<<<~+?l",
  "                                                                       -bkabOUcuri    , +}([i][?}fkoooooav \"//<-)}_~>>iiii<+]>?+~<>>><~~~~~<<<+-~",
  "                                                                        bkad0Ycv]    \" ![)[i?[]1coooooooz \"|[~[(}+<>iiii>+?+   !_~<>>><<~~~~<<<~__^",
  "                                                                       ~bkapQXvz    .I']1[i+[}1ckaoooooz \")]_1|[~>>iii>~-+.      ++~<>>><<~~~~<<<+?l",
  "                                                                       ~bkhqLXu)    < _}[i+}{1uLZpkaoo( <1]?||]<>iii>~--;         ,-+<>>><<~~~~<<<~-~",
  "                                                                       +bhhmJzu+   ! I[1<_1}} ^/YQmpk? ~[_}/(_>iii><_[:             !_~<>>><<~~~~<<~__^",
  "                                                                       /bhkZUcv   .! ]{<-}[?    ^/UQ+ +[-(t)~iiii<+]l                 ++~<>><<~~~~<<<+-l",
  "                                                                       nbhbOYvx   _ <[<+]}_       ^! >[[\\t}iiii>+?+                    ,-+<>>><<~~~<<<~_<",
  "                                                                       ubadQXu)  <'^]<~-{l          +[1t\\-iii>~-+.                       !_~<>>><~++++~<<<,",
  "                                                                       xpbwCzu]I:< -<~?[,          _{(t(<ii>~--;                           ++~>>>~?-}|}_<~?~",
  "                                                                      toWMpUXX)_[ l++]}           _1(t]ii><_[:                              ,-~<>}?]|j)_<<-1`",
  "                                                                      bbm0Uczzj[;'+_[+           +1(\\+ii<+]l                                  !_~)?_-?_~><_}?",
  "                                                                      JQQmYxjn/+ i-{1          '+}(1ii>+?+                                      >{]+~~+~<>~])",
  "                                                                      <zJJufjj_<+_{1/         ^-](-i>~-+.                                        ;}-~~+~<><-(",
  "                                                                      ,|xf\\\\[(Qf<<+[/^       ^-[{<>~--;                                           i]+~xqhqC/{!",
  "                                                                      ,1[[]<i\\cj((<<?  'llIl;-[]><_[:                                              ]-zoBBkOJj_",
  "                                                                      ,)[??-~ii>q0LLc?----__+_-++]l                                                I[dbohmLYX/",
  "                                                                      ,)[????_<i[b#k[]]}{}?_++-]{                                                   -JZmqmQUXr;",
  "                                                                       )[????-_~<CX{[[)/t|}-++_-]?                                                  '\\ZmwwOJYv^",
  "                                                                       (}????-+~+?({[[)/t([-++++_?[^                                                 lUZmqZLUX",
  "                                                                       (}????-_~~+(}]?[}}]-___+++_-]>                                                 IZmww0JX~",
  "                                                                       {}???]-_~~+(}]-_________+++_-??                                                 fZmqZCYt",
  "                                                                       +}???]-_~~+}}?_+~~++_____++++_?[^                                                ZmqwQUX\"",
  "                                                                       +{]??]-_~~+]{]_+~~~++______+++_-]>                                               )ZwqOJY]",
  "                                                                       _{]??]-_~~+?1[-_+~~~~++_____++++-??                                               ZmqmLUn",
  "                                                                       >{]??]-_~~+?1],?_++~~~++______+++_?[^                                             )Zwq0JX\"",
  "                                                                       ,1]??]-_~~+?1]  i-_+~~~~++_____+++_-]>                                             ZmwOUc[",
  "                                                                       ,1]??]-_~~+?)]   `_-_+~~~++______+++_??                                            )mwmqOL(",
  "                                                                       ,1]??]?_~~+])[     I?_+~~~~++_____+++_-[^                                          nbkm0Xvc!",
  "                                                                       ')[??]?_~~+]):       <-_+~~~++_____+++_-]>                                         )0C0Qcru",
  "                                                                        )[??]?_~~+](:        ,+-++~~~++_____+++_??                                         ?czXuj]",
  "                                                                        ([??]?_~~+](;          I?_+~~~++_____+++_-[^                                         /t||`",
  "                                                                        ([??]?_~~+](;            <-_+~~~++_____+++-]>                                         \"\"",
  "                                                                        ?}??]?_~~+](;             ,?_+~~~++_____++__--",
  "                                                                        +}???-_+~+]|;               i-_+~~~++_-?---__+?^",
  "                                                                        +}]?---__?[|I                 _-++~~~_[]})1]_+_[+",
  "                                                                        _1[}(([_+-{\\                   ,?_+~~{[[(f/}-+_])`",
  "                                                                        I{[1/\\}_+_[/                     <-+-{[}1)}-+~+?1]",
  "                                                                        [[}))[_~~_[/                      `+{}[{)}?+~<+?)+",
  "                                                                       ;}[1)}-+<<_}(                       '{[}11]_~<~_[\\^",
  "                                                                       {[{({?+~<+?(`                       ?}[{)}-+~<+?)+",
  "                                                                      ~[}))]_~<~-1!                       '{[}1{]_~<~-}(",
  "                                                                     .}[1)}-~<~_}-                        ?}[{1[-+~~+]|`",
  "                                                                     [[{({?+~<+[)                        '{[}1{?+~<~?)+",
  "                                                                    i}[))]_~<+?|                         i}[11[_~<~_}(",
  "                                                                    {[1)}_~<~-):                         {[}){?+~<+]|`",
  "                                                                   -[}){?+<~_{?                         i}]][[_~<~-1~",
  "                                                                  ^?++?-+~<+[[                          _>>>ii<~~_}(",
  "                                                                 ,<<<>i>~_~?{                         l~~--+>i>+??|`",
  "                                                                ++-()->i<?}):                        I_+{jf}~ii~](~",
  "                                                               i__{f/]>i>-)~                        .]__{\\(?<ii~?(",
  "                                                              :-+]1{-<i!>-1:                        -_+?{}_<i!i~?(;",
  "                                                              ?+-{1?<i!!<-(`                       l-+-}{?~i!!i~]\\",
  "                                                             ___})[+>!!i+[}                        ]__]{[_>i!!<_{~",
  "                                                            ~__[){_>i!i<?(                        -_+?{{?<i!!i~]|",
  "                                                           I-+?11?<i!!>_{~                       >-+_[{]+>i!i<_{<",
  "                                                          ^?+-{)[~i!!i~]1                       ^]__]{}-<i!!i~]|",
  "                                                          ]__})}_>i!i<-):                       -_+-}{]~>i!i<_{{",
  "                                                         !?+_}{-<i!!>+}}                       \"[_+?}[_<i!!>~]|`",
  "                                                         ~-+<<~<i!!i~??!::,'                   >_-~<~~<i!!i<_-~>>>i,^",
  "                                                        +_|1_+~<<>>~---___+>_.                _+1r}++~<<>><_????--_i~>",
  "                                                       ^?+?-----------------_~               \"?+-]-----------------i<}`",
  "                                                       .?<<_-------------_+~_LBBBBBBBBBBBBBBBa]~><--------------_+~!<1",
  "                                                        i~i!lllllllllllllll>I                 i+i!!!!!lllllllllllll!-\"",
  "                                                          ,lll\"\"\"\"\"\".                          \"!!lllllllll\"\"\"\"\"\". .",
  "",
  "",
  "",
];
