/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `bang_up` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                            ``",
  "                                                            ?|",
  "                                                        a   nm",
  "                                                     !  mJ  J8",
  "                                                  ?  Jn |8? J8? `J",
  "                                                  ?a!`aJ`8o`Jon mJ  `n",
  "                                                   ?8m|8aaQaaxm|8J ?8!",
  "                                                    ?8o8QoQ08,88q?J8J",
  "                                                   `nJoxo[p;*^mvd8L8`",
  "                                                    !a8o+[;^',vm!-*aJ8?",
  "                                                   `nJ8p}, ^nm!  _/p88J`",
  "                                                    `n8Y~!mm!  l\\uq$Mlum",
  "                                                      nqwJ!  I(nwa$$$O;d|",
  "                                                     `8n`  ,}rL*Yo$MJa0~8`",
  "                                                     `8xl,]fYhLlJ$$B$$hpXm",
  "                                                      m8/}XkBhmu-/%$$bxQoo|    fl",
  "                                                      `a*%$$$$$U-}|tjxucO88   zkWz'",
  "                                                       8 C$QY$$$(/UXzczXUbJ 'qdL&8M)",
  "                                                       nd+|#$$@0jrvk$$8pCmJ_pwQo&&8&0l",
  "                                                        !an|dt|uXcm$$$$$uOkoOZ#&&%%B&Q   `]]]]`",
  "                                                          np|n/xUQm$$@ZqJa*W#W&%B@%0l  |a%%%BBBa(",
  "                                                           j8mJJ0mOb8Q0mhdnq&8B@%Ol  'b&&WMW8BBB8bl",
  "                                                          .#8Bapddpbbk*#CtjxQ8%O-?__?pWWopqkM%BBB8&X'",
  "                                                           i]vLo8&%WbwU|(|trvqMM#*a*#*WMkmmbM%BBBB%8k-",
  "                                                                 \\JB0xj/|\\xzU0bmqWokk#W&#ooM8%%BBBBB%&Y'",
  "                                                    |J%%BBBJ?]upM#ohbLnxuzJQCk&WkM*ck#&8%%%%%%%%%BBBB%8W)",
  "                                                  !h8&88%%%%%%8MoMbb#&ZL0ZmLcaWm1zMUw*&%B@@@BB%%%%%BBBB%&O'",
  "                                                `Z8&MW8%8&WM#oakbMoZa8aJQCtcOBMWoMWw8*W%@@@@@@B%%%%%BBBBB8Wr",
  "                                              `x8&Mh*$M&&#b0Jwm}nkLxJ%#Zmm_rd$&&W%&d%8W%B@@@@@@BB%%%%%BBBB%8bl",
  "                                             |88MhqOO%@p{cBCnmMqkaW&&%MqJ[cr[$BWW%&k#%%88%B@@@@@@BB%%%%%BBBB%&r",
  "                                           (h8WaqOOqhW$#qbBB%%%%%##&W%&b>lnU{h$MW88ho%%B@%8%B@@@@@@BB%%%%BBBB%8k-",
  "                                         !m8WopOOwhM8B$$M&%BB%%%%&hW&88a(+(p)J$&&&8oa%%B@@%W&%B@@@@@@BB%%%%BBBB%&Y'",
  "                                       `Z8&*dZOwh#8B@@$$$M8BB%%%%%*#&&%*X[{pvf$BW&%*d%%B@@%Mkch%B@@@@@@B%%%%%BBBB8k)",
  "                                     `x8&#dZOwk#8B@@$$$$$BW%BB%%%%WaW&%MQ(|LJr*$MW%Mk%%B@@%Mb> (h%B@@@@@BB%%%%%BBB%%Z`",
  "                                    |h&#bmOwk#8B@@$$$$$B%$8&%BB%%%%aM&8&dtfzZuZ$&&8Ww8%B@@%Mb>   (h%B@@@@@BB%88888%BB8r'",
  "                                  ?h&MkmOmk#8B@$$$$$$B8bj/$W8BB%%%%Mo&88hcxnpXX$BW8&p8%B@@%#d>     (a%B@@@@@%#W#kk#8B%Ww.",
  "                                !m8WhwOmb#8B@$$$$$@B&d)   0@W%BB%%%BaW&%*CvcmLJW$M&&k*%B@@8#d>       |a%B@@@M#Wamwo8BB&o\\",
  "                              `J88#wOmb#8B@$$$$$@%&0l     ^&%&%BB%%BM*&8MZXY0mLa$&&8ho8B@@8#d:         |a%B@aM&W##&B@B&oz",
  "                            'U88%BB&h#8B@$$$$$@%WrI        >$&8BB%%%@hW8WdJCL0Zd$BW8o*8@@@8#p            |a%o#&8&&%B@@8ox",
  "                           'dWobo8BBW*@$$$$$@8kj'           z$W%BB%%B##&8hQLLLLL&$W8*d8B@@8*p              |p*&88&%B@@8ox",
  "                           cMMbmk&BB&aW$$$B8b)               b@&%BB%B%aW8o\\`````n$&&Mk8B@@8*q               ;oW888bw%%8or",
  "                           hM&WM&B@@&ab$B&0l                 ^$%8BB%%@aM8*u!iii>[$%WWp8B@@8*w                mM8O<;-(08or",
  "                           vM8&W8B@B&h#Wrl                    }$8%BB%B8o&#m~~~~~~*$*Wp%%@B&*w                uM*+I![tnk#r",
  "                           u#&&W8B@BWkn'                       0$8%B%B@hMMq{~~~~~Y$#Mb&%@B&ow                +#k{[}|rcZMj",
  "                           {#&888%%BWb                         '&B8BB%@M*Mqf~~~~~}$&*ho%@B&om                 a8{}}|rvZMj",
  "                           +*8O>I[vMWp                          ]$%%BBB@aMwX_-][{)W$ho#%@B&or                 C8r}[(jvO#:",
  "                           .o8_i+(x0&Q                           C$8%BB@#*pqfrnvzY*$*ab%@B&ar                 'hv}[)jvOO",
  "                            a8[]{tuOWx                           'M$8BB@%adbZao#JJ\\$Bhk%BB&aj                  ?w}[)fuOJ",
  "                            w8}]{tuZMj                            -$B%BB@obbn`     b$ap%@BWaj                  !#{[1tuOJ",
  "                            18|]{tvZ#:                             Z$%BB@&bpr      t$&p%BBWhj                   8{[{tuOJ",
  "                             mu]{tvZJ                              'B$%B@BhbQ      ^$BaWBBWhf                   mv[{/nOJ",
  "                             Ju]{tvhn                               {$@%B@*kd       b$M#B%Whf                   JU}}\\n0a",
  "                             Ju]{tvh?                                0$BBB%*k<      t$&&%%Mk<                   ?w}}|x08",
  "                             JY]}tvh?                                '&$%BB*ar      ^$BW%%Mk>                   !#11/uJ8",
  "                             |w]}tvh?                                 1$$%B&oQ       b$M8%Mb>                   ?*+>\\jtbJ",
  "                             ?w]}fv*?                                  p$@B8#d       t$&&&W#OU|`                Ju[//cYJ8",
  "                             ?w]}fc8`                                  IW$B%Mk<      ^%MWMWW&&8W0'              npxtjY0pa",
  "                             !k(\\nY8                                    tB$%Waj     'q##oha*W&8&Mo+              nJvcCZC`",
  "                             JOI(fnbn                                  '(o$$&opZ)   Jo*admqh#&88W*k.              ,0mpQ",
  "                             81/(uJm8                                 _pM*#$$&p&ML?)h**adqdaM&88&#h|                +I",
  "                             JUrjY0dn                                Ia*obk@$$%&%&%Mh*MM**#M&8%%&#aX",
  "                              |vcLm|                                 Uo*o&M*abqmXbb\\h*MWWWWW&8%%8Mop",
  "                               vqdX                                  bo##hCwL-uZ{phXk*MW&WWW&8%%8W*b>",
  "                                                                     boM#%8B&qh$%%@Bao#W&WWW&8%%8W#k]",
  "                                                                     Uo##B$$$$$$$$%aXh*MWWWWW88%%&#hx",
  "                                                                     uo#MW%@BBB%&#hj koMW&WWW&8%%8Maq",
  "                                                                     na#MM#M&8%%&#kf /a#W&WWW&8%%8Wod",
  "                                                                     na#MM#M&8%%&#k< ;h*MWWWW&8%%8W*k<",
  "                                                                     }a#MMMM&8%%&#k<  ZoMW&WWW&8%%&#hr",
  "                                                                     ~h#MMMM&8%%&#k<  }a#W&WWW&8%%8MaX",
  "                                                                     ~h#MMMM&8%%&#b>  .k*MWWWW&8%%8Wop",
  "                                                                     ~h*MMMM&8%%&#b>   UoMW&WWW&8%8W*b>",
  "                                                                      k*MMMM&8%%&#b>   ~a#W&WWW&8%%&#h]",
  "                                                                      k*MMMM&8%%&#b>    k*MWWWW&8%%8Max",
  "                                                                      b*MMMMW8%%&#d,    /o#W&WWW8%%8Woq",
  "                                                                      ZoMMMMW8%%&*d     ;h#W&WWW&8%8W*d",
  "                                                                      uoMMMMW8%%&*d      Z*MWWWW&8%%&#k<",
  "                                                                      uoMMMMW8%%&*p      }a#W&WW&8%%8Mhr",
  "                                                                      noMMMMW8%%&*p      .h*W&WWW&8%8WoX",
  "                                                                      }a#MMMW8%%&*q       UoMWWWW&8%%W*d",
  "                                                                      ~a#MMMW8%%&*q       ~a#W&WW&&88&#k:",
  "                                                                      ~a#MMMW8%%&*w        k*M#M#*MW8&#h]",
  "                                                                      ~h#MMMW8%%&oL        /aa*apqhM&8Wox",
  "                                                                       h#MMW&&88Wox        ;ko#addaW88W*0",
  "                                                                       ko##o*W&&#ax         OoMM##W8%%&*d",
  "                                                                       bo*bmd#&8War         /oMWWMW8%%&#d",
  "                                                                       h*ohk*W8%Wor         ~a#WWMW&%%8#b>",
  "                                                                      {o*ah*W%B%&a(          k*WWMW&%%8Mk>",
  "                                                                      w*ohaM8%B8Mb.          J*MWMW&8%8Mh<",
  "                                                                     {o*ah*&%B%&a[           /oMWMM&8%8Mh<",
  "                                                                     w*ohaW8%B8*Y            ~a#WWMW8%%Waj",
  "                                                                    {o*ah#&%B%Mb:             h#WWMW8%%Wor",
  "                                                                    w*ohoW8B%&a|              Z*WWMW8%%&ox",
  "                                                                   {o*hh#8%B8#0               noMWMW&%%&*n",
  "                                                                   w*oh*&%B%Wk:               ~aMW8BB@@%#q",
  "                                                                  {o*haM8%B&o|                .hWBBBB@$$%a",
  "                                                                  d%88%8%B8#0                  *88obo8@$@&c",
  "                                                                ?oB%%@$$8&Wk:                 1W8MpZk&@$@8o[",
  "                                                               _&8*qk&@$BMh|                  cW%%WM&@$$@8*x",
  "                                                              'd8&aqh8$$BWk                   cW%@B%B@$$$%#d",
  "                                                              z&8Mo#%$$$@Wk                   cM%BB%B@$$$BWk:",
  "                                                             _W8&oo&@$$$BMO                   tM%BB%B@$$$B&a[",
  "                                                            'd88#oMB$$$@8o[                   _M8BB%B@$$$@8*x",
  "                                                            z&8Wo*8@$$$BMO                    +#8B@B%@$$$@8#p",
  "                                                           _W8&*oWB$$$@8o[                    +#8B@B%B$$$$%Mk:",
  "                                                          'd88#o#%$$$$BMO                     +*&B@B%B@$$$BWa]",
  "                                                          z&8Woo&@$$$@8a[                      *&B@B%B@$$$B&ox",
  "                                                          *88MoM%$$$$%MO                     'U8W%@@B@$$$$@&MB@@@$#u'",
  "                                                         xW8BBBB$$$$@&#hLLLvi                X8MwqaaaaM&8&Mooooo*#@@b.",
  "                                                        j8#qhaa&&&8&M***###8Bz               *88oppppppppppppppppp&$W\\",
  "                                                        *8&pppppppppppppppppo*:              p8@Bhpppppppppppphooo$$M[",
  "                                                        Q%$oppppppppppppppooWa'              ?&@$$$$$$$$$$$$$$$$$$$Bf",
  "                                                        !a$$$$$$$$$$$$$$$$$$o~................+p$$$$$$$$$$OOOOOO{}[`",
  "                                                         :zk$$&ZZmmmU|||\\\\|^^^^^^\"\"\"\"\"^^^^^^^^^``||?'''...",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^^^^```'''...",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
