/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `bang_down` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                                                              !",
  "                                                                                                                                             J|",
  "                                                                                                                                            ?8`   `",
  "                                                                                                                                        m  ?8m  `J|",
  "                                                                                                                                    |` !8!`ao? |8J   `?",
  "                                                                                                                                    Ja`n8?ar8`m8J  ?mm`",
  "                                                                                                                                 |JJm888a8uvawUJ?J8a|!?J?",
  "                                                                                                 |J%%BB*J!          `?~        |m\\'Lwn? )8<b/t8a0a8m8an`",
  "                                                                                               |h88&8%BBB80'   !?YYMoak      |m/;xo$%;.\"-cd<]n]uJXom|",
  "                                                                                             !h8&MabhM8BB%Ww. 1#awZZqW*]   |aZ1mBhn$$x>;i]qL?::1d888m|",
  "                                                                                           !Z88MapZOqo8B@%WoY  CW&MW&%WX `mc\\rXL$$p%$#/i;~}#n[+|Q8m|??",
  "                                                                                         `x88WopZ0ZpaW%@@B&*d, .p&&&&88k _rtrUOmd$$$$U*{!I_r#n}(c8aJn?",
  "                                                                                        x88WodZ0ZpaM8B@@@B&*pn' +#8&&8%*\\CC0wdC+:rv\\JfC*}l!?JkC88a|",
  "                                                                                      |h8W*dZ0ZpaM8B@@$$$B&oq&*OltM8%@@&ddjrcn++-}\\/Y$*qb+l>[kM|",
  "                                                                                    ?h8&*bm0ZpaM8B@@$$$$$BWha#o#&0a&Bwx[Zw{X$$Bv\\zUQ$$$$@m~}tC8!",
  "                                                                                  !m8&#bmOZpaM8B@@$$$$$$@8*ZOomk&8Wv+>;\"Lp\\Q$$$#ZUv#$$#$$$Qw*a?",
  "                                                                                `U8&#kmOZpaM8B@@$$$$$$@%8#MbhYxo8%X~:`,i/8uJo$$hzYJO$$h*bk*8n`",
  "                                                                              `x8&MhwOZpaM8B@@$$$$$$@%&MW%WowuYaB&}[--1/rmbLQqdCQOZqaku-!rqn",
  "                                                                             |h8MhwOOpaM8B@@$$$$$$B8W#&%%WoqmMBBWpvtjrvYCOd#oddbbhMqQnmpJ|!",
  "                                                                           ?a%8#qOOqaM8B@@$$$$$@B8Mo#8%%WopZMBB#bdwcJLOZZqk%CB@B%8%&C?",
  "                                                                         (a%%%BBWkaM8B@$$$$$$@%&Mako&%%&opZMB%o/\\f1\\ncwkZa8&b- i]/Lqj",
  "                                                                        zWWoaM%B%W#B@$$$$$$@%WMMokaM%%&odOMB8p_![UxjpaomO*&88Mc'",
  "                                                                       {#Wamma8BB&o*$$$$$B8b%%W*kh#8BBobOMB&Qii[ZUr#$WZY}zB%*M8k)]]`",
  "                                                                       v#&MaoWB@B8*d$$@B&O)t$W#hko&BB*kZWBMYi~(Zvjo$MOmoda80aBB%8W%BBn'",
  "                                                                       vM&WMW%@@@&oq@%WXl ^$%MokaWBB*km8%#n-]jmcro$MOw&BBM0\\JBBBB%&&%%M)",
  "                                                                       vM&WM&%@@BWhkkj'   0$W*kh#BBohm8%or{)nwxc*$*0q8B%#M%W%wxpBBB8W&8WX'",
  "                                                                       mM&&&8%B@%Md[     ]$&#hk*%Bohm88d/|\\LZuX@$a0bBB&*&%%%Bhq#$b@B8M&%&bl",
  "                                                                       hM8n~<{LM8*z     '&BMaka%$*ap8WkftfQ0uU@$hQhB%##%%%B@@$$$X/OW#%BBB8M)",
  "                                                                       h&zl,<)jJ8h]     q$W*kh8$MakBMJQavzQzC@$hQ#B8oM%%%B@$$$$@&oM&%%BBBB%&X'",
  "                                                                       h8t--)jvY8d     )$8#hk8$Maa8o/+?f*OYQ$$kO8BWa&%%B@$$$$$B&M&BB%%%BBBB%&bl",
  "                                                                       h8]_?(rzmWz    '$@Mak#$#oWWq\\~~~_)wW$@dm8%*o&%B@$$$$$B8#&@@@@B%%%%BBBB8Wj",
  "                                                                       C8?_]\\nXb*]    w$&ok#$#*W*w]~~~~~+v$@pqB&ho&B@@$$$$@%MzW%B@@@@BB%%%BBBB%&0'",
  "                                                                       '8?_[/uYWc    )$%#h*$M*MaJ~~~~~~~x$@b*%#k*8@@$$$$@%WQ' 'Y8%B@@@@B%%%%BBB%8b_",
  "                                                                       ?b?_{fvC8    I%$Ma*$8**aU?+~~~~~n$@kM8ab#%@$$$$@B&0l     lk8B@@@@BB%%%BBBB8Wj",
  "                                                                       ?m--1jcmJ    b$Wo*$8ooaac|{?+~~0$WaMWbbM@$$$$$B&d1         (&%B@@@@B%%%%BBB%&0'",
  "                                                                       ?m--(xza|   f$B*a@8a*w.!mdx(}-d$M*8*pb&$$$$$B8#1            'Y8%B@@@BB%%%BBBB8b_",
  "                                                                       nm-?|nXW`  I8$MoB&o#J.   !mwxh$M*Wkqh%$$$$@%Mj'               lk8B@@@@B%%%%BBB%Wj",
  "                                                                       Jn_]/uQa   d$&*B%M*u       !$$&*#dqo$$$$@%WQ'                   (&%B@@@BB%%%BBB%8O'",
  "                                                                       Jn_}tcqJ  c$$#BB&o}       ^0$W*aqd&$$$@B&0l                      'Y8%@@@@B%%8%8%BBa)",
  "                                                                       Ju[)rzamU1&$MB%Ww~       ^&$WakqkB$$$B&d1                          lk8B@@@%MWobo8B%Wv",
  "                                                                      nO+>{uvM&&*$%8%Mm.       ^&$Whkq#$$$B8#1                              (&%B@*MMdmh&BB&a;",
  "                                                                      8)|/nXzw&*B$88#u.       ^&$&hkd8$$@%Mj'                                'Y8BhM&WM&B@@8*x",
  "                                                                      azf|vL0k8&$@&*O        >&$&oka$$@%WQ'                                    lZoM8%%8%@@%MO",
  "                                                                      (wxnJZq8B@%8oad       }$$W#b&$@B&0l                                        1o&%%8%B@BWh.",
  "                                                                      ~dLOqqWbfZ@@8#d,     }$$W#o@$B&d1                                           tM8%8*Zw#8o[",
  "                                                                      ~h**MB$qXObd@BW!'?UUUB@W*M$B8#1                                             .qW8O,:?/bWn",
  "                                                                      ~h*MM&B$$@1nM%8WWWWW&&8&W8%Mj'                                               {#8)+-(ju8k",
  "                                                                      ~h*MMMM8B$&8/]*##oa*M&88W#o'                                                  L&C(1(fnk*>",
  "                                                                       k*MMMMW&%@80a**kqwdoW88&WMp'                                                 I##(1)/xQM:",
  "                                                                       k*MMMMW8%%8aa**kqqb*W8888&M*_                                                 j8C)1|ju8`",
  "                                                                       boMMMMW8%%8bo#M*oo#W&&&888&W#c                                                 ?#(1)txp|",
  "                                                                       ZoMMMMW8%%8boMW&&&&&&&&&888&WMp'                                                JC)1|rJm",
  "                                                                       uoMMMMW&%%8ooM&8%%88&&&&&8888&W*_                                               `#(1)fnM!",
  "                                                                       uo#MMMW&%%8MoM&%%%%88&&&&&&888&W#z                                               nC)1\\xqn",
  "                                                                       na#MMMW&%%8Wa*&88%%%%88&&&&&8888&Mp'                                             `#f1(jUa",
  "                                                                       \\a#MMMW&%%8Mar)W&8%%%%88&&&&&&888&W#_                                             nO)1/no!",
  "                                                                       ~a#MMMW&%%8Maj 'XW&8%%%%88&&&&&888&W#z                                            `8f)\\nkn",
  "                                                                       ~a#MMMW&%%8Mhj   -b&88%%%88&&&&&&888&Mp'                                           nd)(1vdJ",
  "                                                                       ~h#MM#W&%%8Mhf     rW&8%%%%88&&&&&888&W#_                                          JL?|tcUW?",
  "                                                                       ;h#MM#W&%%8Mh<      'OW88%%%88&&&&&8888WMz                                         nhxtfYQo`",
  "                                                                        k*MM#M&%%8Mh<        )b&8%%%%88&&&&&888&Mp'                                        nLzcU0f",
  "                                                                        k*MM#M&%%8Mk<         'rW&8%%%88&&&&&888&W#_                                         YZqp:",
  "                                                                        b*MM#M&%%8Mk<           lO&8%%%%88&&&&&888&Mz                                         ++.",
  "                                                                        J*MM#M&%%8Mk>             )W&8%%%%8&&&&&88&&Wd'",
  "                                                                        uoMMMW&8%8#b>              'XW88%%%88&WMMWWW&8M_",
  "                                                                        uo#MMMW&&W#b>                lb&8%%%%&*#okh#&8&#u",
  "                                                                        na*obb*&8Wod                   (W&8%%o**bmpoW88Mh;",
  "                                                                        }o*hqp*&8&*d                    'O&8Wa*ohhoW8%8Mar",
  "                                                                        w*okh#&%%8#d                      -bao*ahoM8%B%Wh(",
  "                                                                       {o*hkoW8BB8*Q                       Ia*oha#&%BB8#d:",
  "                                                                      .a*akaM8%B%Mk;                       Jo*ahoW8%B%Wh(",
  "                                                                      v*okh#&%B%&a[                       Ia*oha#&%B%&*Q",
  "                                                                     Io*hkoW%BB&*x                        Jo*ah*W8BB8Mb:",
  "                                                                     w*akaM8%B8#O                        Ia*ohaM8%B%Wa|",
  "                                                                    to*kh#&%B%Mb.                        to*ah*&%B%&*Q",
  "                                                                   'a*hko&%B%&a<                        .a*ohaM8%B8Mb:",
  "                                                                   C*okaM8BB8ox                         to#M*#&%B%&a|",
  "                                                                  _M88MW8%B8#Y                         !&@@$$$B%B8*0",
  "                                                                'nBBB@$$%8%MZ.                        U%%&W%@$@8WMb:",
  "                                                                b%Wkh&@$BW*h<                        j&8oww*B$$%Mh|",
  "                                                               X&8owpM@$@&a|                        lM8&odkMB$$BWk.",
  "                                                              )&8Mao&@$$@&a<                        d&8Mo*&@$$$BWk>",
  "                                                             lW8WoaMB$$$@&k:                       jW8&*oMB$$$$BMd",
  "                                                            'b8&*h#%$$$$%#Y                       lM88#o#8@$$$@8o\\",
  "                                                            0&8#ho&@$$$@Wk.                      'd&8WooWB$$$$BMb.",
  "                                                           j&8MaaWB$$$$8*\\                       zW8&*o#%@$$$@8o\\",
  "                                                          -W8Woh#%$$$$BMZ                       _M88Mo*&@$$$$BMb.",
  "                                                         'M8&*h*8@$$$@&a<                       d&8W*oM%$$$$@8oz",
  "                                                         fW8&*oW@$$$$%#Y                       +#8%W*#8@$$$$%Mk:",
  "                                                        `h&%BBB@$$$$BWWwLLL/`                 'a&&BBBB@$$$$@8&B@@$$L|",
  "                                                        k8bdaa*&&88W#**###MB&I                b8aZbaa*&&&8&Moooo**W$Bz",
  "                                                       _W%hppppppppppppppppp&v               _W%&kppppppppppppppppp$@*:",
  "                                                       IWB&bpppppppppppppho#8t               !MB$&ppppppppppppppho#$Ba",
  "                                                        YB$$$$$$$$$$$$$$$$$$u.................U%$$$$$$$$$$$$$$$$$$$$&+",
  "                                                         ~0$$$ZZZZmZn||||\\]^^^^^^\"\"\"\"\"^^^^^^^^^jM$$$$$$$$$$ZZZZOOj1}",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^?|||``'''...",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
