/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `bang_up` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                            ^.",
  "                                                            [-",
  "                                                        0   rv",
  "                                                     l  C/  Ym",
  "                                                  _  u( }al Ub; ^c",
  "                                                  <O; wr *Z Uo- d(  ^\\",
  "                                                   ikY?oCO#vbM/\\8} }*^",
  "                                                    lpaw#qMdh&X$d:08}",
  "                                                   `ttm#aMaMk%0$*hMc",
  "                                                    ^Loh*MM%B$$$$a0uCh!",
  "                                                    fYph#&$$$$$$$dOQa&x",
  "                                                     ]O#8$$$$$$*Cnti1*bj",
  "                                                      r%$$$$$#Qvtj; 'mMq~",
  "                                                      @$$$$&Zzf/C~ ;\\zk#0",
  "                                                      Lq#&wYr/JW\\  `  \\k*x",
  "                                                      nQqZx{??[npU`  +vzkh+    ^",
  "                                                       0h^     tpZCYzvnrudJ   ,<:\"",
  "                                                       8$|}tt   LU/jjrrf//]  I_(\"\";'",
  "                                                       }Z*#m` .1Xzn<  \"-|/[ I])!,,\",,",
  "                                                        ^Xh#OULufr[     nj{i{}I,,^``\":",
  "                                                          }qkvUc/)[  '}?\\\\(:I:,^''^\"    `^^```'`",
  "                                                           !Jc\\\\1[{+\"(1[)jv?,\"''^\"    ,,,:;:\"`'`\",",
  "                                                           I\"(f-+_}[[}{|vYzv(\"^\"     I::i-?~;^''`^,^",
  "                                                               '\",<-|tuLQCYcx?;;ll>!Il:I~[}+;^`'''`\",",
  "                                                                   `1vzUCJcr/)~[?:!~~l:,Iii;\"^^`'''`^,`",
  "                                                     .```''.   I;li<+(vvur\\)\\<:;~;lr~l,^^^^``^^^``'''`\":.",
  "                                                   ^\",\"\"````^^\";iI~+I,}(1}}(xi:[0rI/]l,^'..''`^^^^``''`^,\"",
  "                                                 `\",;;\"^\",:;l!>~~;i{i\"i\\)\\Yr{`;:!I:]\"l:^'....''`^^^^`'''`^:'",
  "                                                \",I<l ;,,l+)\\][Zv~|c\\^l}}[dc_ ,::^,_^^:^''.....'``^^^``'''`\",",
  "                                              \"\";>]{{^'-Or'|v[I?~>:,,^;?\\mrzm `::^,~I^^^\"^''....''``^^^``''`^,'",
  "                                            ^\":i?{{?<: l?+```^^^^Il,:^,+h#u/O< ;:\"\">!^^'.`\"^''....''`^^^^`'''`\",",
  "                                          `\":i-{{]<I\"`  ;,^'`^^^^\">:,\"\">LbQ-Q\\ ,:,^!>^^'..`:,^'.....''`^^^^`''`^,`",
  "                                        `\",!_}{]<I\"`..   ;\"`'`^^^^lI,,^lfmO-nX `:,^l+^^'..^;~,^`'.....''`^^^``''`^\".",
  "                                       \",l+}{]<I\"`..     `:^``^^^^:i:,^;)LC|\\c! ;:^I<^^'..^;+^  ^`'.....'``^^^``'``^`",
  "                                     ^,I+}{]~I\"`..     '^ \",`'`^^^`>;,^,_YYj}u} ,:^;]\"^'..^I+^    ^`'.....'``\"\"\"\"\"^`'^'",
  "                                   ^\";~[{[~I\"`..     '\",`  :\"`'`^^^;!,\"\">xcu-jf `:\",-\"^'..^I+\"      ^`'....'^I:I~~I^'`:!",
  "                                 `\";<]{[~I\"`..    .`,:'    .:^``^^^`>;,^!\\nx[(/: ;\",~l^'..^I_\"        ^`'...;I:>[]i\"'',i;",
  "                               .^\"l]{[+l\"`..    .`,,        `,`'`^^`Il,^;}jf1[(i ,,\">i^'..^I_.          ^`'.>I,:lI\"`.'\"!<",
  "                             '^^^`',<l\"`..    .^:'           ,\"```^`'<:\":_\\|(){{ `:\"il\"'.'\"l-             ^`iI,^,,^'.'\"!!",
  "                            ::!+i\"'`:l..    '^,`              :^``^^'lI,\"<mMWW&&> :\"l_\"'.'\"l-               Il,^\",^'.'\"!!",
  "                           :;;+[<,'',>:   '\":.                ',`'`^``>:\"!JBBB%%u ,\"I<\"`.'\"l?                i:\"(cwOn?\"!!",
  "                           <;,:;,`.',>~.`,,                    ^\"````'>;\"lnoooaaw `:;-^`.'\"!]                !;ckMMpLXj!i",
  "                           :;\",:\"'.',<l:'                       \"^``^'\"!,I[kkkkkk! l:-^^.'\"!]                ;?qb#omYuj[i",
  "                           ;I\",:\"'.':~l                          \"`'``.>;I?Okkkkkt l;~:`.',![                .{OOmZCcxt(i",
  "                           ^l,_cQv\\l:+                           '^```.;l;?XkkkkkZ ,l>!^.',i[                 i0OmZLzxf(>",
  "                           .lchW#mUv_-                            ^^``'.iI]fdpqmOQ: >il^.',i!                 IJOZmLzxf|",
  "                            !wdabLcr|+                             \"`'`.ll-?Yzvxjt~ li+^.',ii                  rOZmQXnf}",
  "                            iZmwOYnf1!                              ^``'^>_+((((++\" `><^'`:>i                  >OZm0Xnf?",
  "                            !ZmwOYnf)>                              `^''.!++<        >-^'`:>>                  ,OOm0Ynj?",
  "                            `OZwOYnt|.                             ^ ^`'.,+-i        ,-^``:>>                   0OmOUuj?",
  "                             vZwOYnt]                               ` ^`''<++        `>:``:<>                   uOmZUuj?",
  "                             fZwZYnt+                               ` .`''l~_         ;I``:<<                   tOZZJvj|",
  "                             fZwZYxt:                                , ``'^l<^        ,,^`;<^                   >OZmCvrf",
  "                             fZwZYxt:                                 , ^``!>i        `:^^;~^                   ,000Uutf",
  "                             ?ZwZYxt;                                 `  ``,!+         ;\"^;~^                   ~qdaJXYv[",
  "                             >ZwZYxt;                                  I '`\"l_         ,,,:I\".                  jwmUUxtff",
  "                             >ZwZYxt                                    : `^;~^       ^;;;;:,,\":,               }UvYXt1)|",
  "                             :QQJvt/                                    \"` ^:>i      llI!>>l;,\",;i.              +rnx|}?",
  "                             xh#LXXv+                                    i  ,!-^.   l!li_[?<I,\"\":l~               '1[-+",
  "                             Z0JLn\\/f                                  ;IlI  ,_,;; .<!li+?_i;,^\":l<I                .",
  "                             )vzzt11~                                 il!+<.  ^,^,)/>lIIl!l;,^^^,I><",
  "                              [xr|[!                                 !il!:Il>+?[fYqw>l;:::::,\"^^\";i-",
  "                               _?+>                                  +!II>|](pn}OcXn~!;:,:::,\"^^\":!+^",
  "                                                                     +!II^\"`,?< ^^i~<iI:,:::,\"^^^:l~,",
  "                                                                     !iII'        `^^>l;:::::\"^^^,I>!",
  "                                                                     IiI;:`.'`'^\"I<> ~!;:,:::,\"^^\";i?",
  "                                                                     IiI;;I;,\"^^,I<< ,iI:,:::,\"^^\":!_",
  "                                                                     l>I;;I;,\"^^,I~`  <l;::::,\"^^^:l~`",
  "                                                                     \">I;;I;,\"^^,I~`  >!I:,:::,^^^,I<i",
  "                                                                     '>l;;I;,\"^^,I~^  ^>I:,:::,\"^^\";i>",
  "                                                                     '<l;;I;,\"^^,I~^   <l;::::,\"^^\":!-",
  "                                                                     '<l;;I;,\"^^,I+^   !iI:,:::\"^^^:l+^",
  "                                                                      <l;;I;,\"^^,l+^   '>l:,:::,\"^^,I<,",
  "                                                                      ~!;;I;,\"^^,l+\"    ~!;::::,\"^^\";>!",
  "                                                                      ~!;;I;:\"^^,l_.    ,iI:,:::\"^^\":i?",
  "                                                                      >!;;I;:\"^^,l_      <l:,:::,^^^:l+",
  "                                                                      I!;;I;:\"^^,l_      >!;::::,\"^^,I~`",
  "                                                                      IiI;I;:\"^^,l-      ^iI:,::,\"^^\";>i",
  "                                                                      IiI;I;:\"^^,l-       <l:,:::\"^^\";i>",
  "                                                                      ^iI;;I:\"^^,!?       !!;::::,\"^^:!_",
  "                                                                      '>I;;I:\"^^,!?       '>I:,::,,\"\",l~",
  "                                                                      '>I;;I:\"^^,!]        ~l;lIIl;:\",I<,",
  "                                                                      '<I;;I:\"^^,!_        ,iili-?<;\"\":i!",
  "                                                                       <l;;:,,\"\":!l         ~ili__i:\"^:!~",
  "                                                                       ~!Ili!:\",Ii!         <!I;II:\"^^,l_",
  "                                                                       +!!+[+I\"\";>!         :iI::;:\"^^,l+",
  "                                                                       <l!<~!:^^:ii         '>I::;:\"^^\"I+^",
  "                                                                      ^il><!:^``,iI          <l::;:,^^\"I~^",
  "                                                                      !l!<>;\"``^;+           !!;:;;,^^\";<`",
  "                                                                     ^il><l,^``,>,           :i;:;;,\"^^;>`",
  "                                                                     !l!<i;\"``\"l>            '>I:;;:\"^^:>i",
  "                                                                    ^!l><l,^`^;+.             <l::;:\"^^:i!",
  "                                                                    !li<i:^``,iI              >l;:;:\"^^,!!",
  "                                                                   `!l>>I\"``\"l+               I!;:;:,^^,!l",
  "                                                                   !li<!,^`^:~                'i;:\"`''.^l?",
  "                                                                  `!!<>;\"``,iI                 <:''`'.  `>",
  "                                                                  ;^^\"^\"^`^I~                  !^\"i+!\". ',,",
  "                                                                 ''``. .^,:~                  ':\";-}~,. .\"!\"",
  "                                                                ,^!?~,. `;>I                  ,:^^;I,'  .\"ll",
  "                                                               :\",>?<\"  ':~                   ,:^''`'.   ^I_",
  "                                                              \",\";iI^   ':~                   :;^''``.   `;~",
  "                                                              ;\",!!,.   `;~                   \";^''``.   ',>,",
  "                                                             :\"\"Ii;`   .\"i,                    I^''``'   .\"!l",
  "                                                            \",\";il\".   `;<                    .I\"''``'   .^I-",
  "                                                            ;\",li:'   .\"i,                    .l\"''``'    ^;~",
  "                                                           :\"\"IiI^    `;<                     .l\"`'``'.   `:>,",
  "                                                          \",\":!!,'   .\"i,                      !,`'```.   ',!!",
  "                                                          l\"^;!;`    `;<                      .\":`''''    ',;`....",
  "                                                         .:\"`'`'.   .,I^                     \"\"I]?>iii;\"\",;!ii!!!I..,",
  "                                                        `\"l?<ii,,\"\",I!lllII\"'\"               l^\"i-----------------, ::",
  "                                                        !^,-----------------!l               I^.'<------------<iii. ;,",
  "                                                        :^.i--------------ii;i0CCCCCCCCCCCCCCY\".                   `^",
  "                                                         ^                  `",
  "",
  "",
  "",
  "",
];
