/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `bang_down` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                                                              l",
  "                                                                                                                                             L+",
  "                                                                                                                                            }d    ^",
  "                                                                                                                                        C  ]$\\  ^C?",
  "                                                                                                                                    )  lo``8w: t&1   ^+",
  "                                                                                                                                    cJ no;W%u^h#}  }wz",
  "                                                                                                                                 tOcLW#$am$ZU$h[[OBJi>}c~",
  "                                                                                                   ```'.              '        t8$Bup$$$wX*m$qq$Bpwq80]",
  "                                                                                                ^\"\",\"^`'`\",      ``Iii~      t8$M01 ^M@8pQUhd%%aM%qt!",
  "                                                                                              ^\",;>+>;^`'^;!  `Ii]}}?:!:   t8*qc])z  whMowCJqWWdbka*C[",
  "                                                                                            `\"\";>-{1?!\"`'`:!>  I:,;:,^:< 'hZJcf|  -^ QqaMkZUJmo**wc(}[",
  "                                                                                           \"\":i-}1}->;^'.`,!_.  I,,,,\"\"~ ?zUc/{[_    xQpo#d0XzkkpOY/}l",
  "                                                                                         \"\":!_}1}->;\"`'..`,!-I  .l\",,\"^!>r\\1]_\\bWcnJ/Yz0d**qLuQkhO?",
  "                                                                                       ^\":!_}1}->;\"`'..  `,!?,l\" \";\"^'',j0zzxubbpZJJf ljOb*hmJri",
  "                                                                                     ^\",l+[1}->;\"`'.     `:<iIil,,i,']cmmOOj  `nCj/)    {ZbZYvu`",
  "                                                                                   `\",l~[1}->;\"`'.      .\"l}{i[~,\":nbaM8wCC(   I{/xI  I  ILt/(:",
  "                                                                                 '\",I~[1{->;\"`'.      .`\"I;+>fc!^`jbW%&omYX\\!  >jt\\{  \\Z1~Cj~",
  "                                                                                \"\";<]1{->;\"`'.      '^,I:^:!]ut>',Zmpp0Ucnn/)?_|)1}|ZB$@oZu+",
  "                                                                              ^\";>]{{->;\"`..     .'^:I,^^:!?};``:_nYXcnf|11){}}[[CM$#mz/?l'",
  "                                                                            `^\"l?{{?>;^'..     .`\"Iil\"^^:!-};``I+_]x\\(1}}?~^`;;i{mr)],",
  "                                                                          `^^``':~>;^'..     .`,I>~!,^`:i-{;'^!UJX0Jux]~}>\",:       >",
  "                                                                        \"::i>;^'`:l'..     '^:IIi~>;^`,i_{;'\"-d*m/vz->i[{l\"^^;,",
  "                                                                       `I:>[[>\"'',!!    .'\",^`:l<<I\"``i+{;',)aom}/zl :}tZr'`lI\"\".",
  "                                                                       :I:Iii:`.'\"!_  .`,\"'  :I>~!,``!~}:`;tokL}xX! ;{}!_>\"1i''^\":^'`",
  "                                                                       :I,:;:^'.'\"!?.^:^    ^;i~>:'`!~}\"`lvpwz[rz! ;1]:'`;1C\\`''`^,,`^;.",
  "                                                                       :;,:;,`..`:<~,`      :l<<I``!<[\"^icO0u[vr! l1?^'^l;^;^]v-''`^:,^:^",
  "                                                                       i;,|cuj?\"^I_\"       ,I<~!``!>[\"\"_UCJ({nf. i)+`',l,^^^`<?I.+.'\";,^,:",
  "                                                                       <>ZaMhOUx~!<       `;i~i^.l>-\":{XYX)1nt. >)<'`Il^^^`'.   jU{:I^''`\";.",
  "                                                                       <cd*&hQzn/>:       :!~<^ ;>~`;\\OJcj)r\\. <)l'\"i;^^`'.    .\"i;,^``''`^:^",
  "                                                                       <Qwpp0Xxtf_     . \"I<~\" Iii^!JbqZLut)  ~{\"`;>,^`'..    `,;,'`^^^`'''`\":",
  "                                                                       >mwdqLcr\\\\<      .;>~I Ii;:?Jkkkdw0) ._[\"^li,^`..    '\"I,...''`^^``''`\":`",
  "                                                                       IwqdwJvj\\}:    ' ,!~l Il:!]wkkkkkbx '-?',>!,`'.    '^;\":^`'..''`^^^`'''^,,",
  "                                                                        wqdmUnf/>    . ^l<l ;lI>/kkkkkkkv .+l`I~!\"'.    .^::   `\"`'...''`^^``''`\":",
  "                                                                       >wqdOYxtf     ^ I>l \"l!>tqbkkkkkv .<I\"i+l`.    .`,,       ,\"`'..''`^^^`''`^:`",
  "                                                                       <wpp0zr/?    : :!l \"!!>\\XCZqbkk1 :>I:++;'.    `,;'          ,^''..''`^^``''^,,",
  "                                                                       <wppQcj\\i   ^ `l>'\">l! '{nYLZp_ ;l\"!-~,.    '\"I'             `\"`'...'`^^^`''`\",",
  "                                                                       (wpqCvf/    \" I!',!Il    '1uY< Il:<?<`    '^;`                 ,^`'..''`^^`'''^:`",
  "                                                                       jwdwJnt(   ; ,l'^IlI       'I ,!l_?!    .^::                     ,^'...'``^^`''`\"\"",
  "                                                                       rwdmYx/]  ,  I'`,i^          ;!i?_,   .`,,                        `\"`'..''`^\"^^^`'`.",
  "                                                                       fZwQzj\\i.', ;'`:!'          :i<?~'   `,;'                           \"^`'..`;:!+!\"'`:;",
  "                                                                      \\k*aOuxr~,l `\"^;i           :>~?I   '\"I'                               ,^'.!;;_[<,'',>",
  "                                                                      wwLUufjj{l' \"\"l;           ,<~_^  '^;`                                  `\"`<;\":;,`.'\"!!",
  "                                                                      cXXCn|1|], .,!<           ,!~>  .^::                                      ^i;\"`^^`'.^I<",
  "                                                                      ljvv/}{{,'^\"!>_          :I~, .`,,                                         '!,^`^^'.':<",
  "                                                                      '_({??l+X}''\"I_.        :li' `,;'                                           \"I\"`|OpZc]!,",
  "                                                                      '>!lI` ?f{+_'':   ''''':l; '\"I'                                              l:jk&WqJv{I",
  "                                                                      '<l;;,`  .0YzXj;;:::,,\",:\"^;`                                                `IZwbpQznj-",
  "                                                                      '<l;;I;\"' !maq!Ilii!;:\"\":I!                                                   IuCQ0LXur{^",
  "                                                                       ~!;;II:\"^'vx>l!<?]+!:\"\",:;I                                                   -CL00Jcx/.",
  "                                                                       ~!;;II:\"^^:+il!~??~l:\"\"\"\",;l                                                  ^nCQ0LXuj",
  "                                                                       +!;;II:\"^`^+iIIl!!I:,,\"\"\"\",:I,                                                 :CL0QUvx!",
  "                                                                       >!I;;I:\"^`^+!I:,,,,,,,,,\"\"\"\":;I                                                 |CQ0Czn1",
  "                                                                       IiI;;I:\"^`^!!;,\"^^\"\",,,,,\"\"\"\",;l                                                 CL0QYur`",
  "                                                                       IiI;;I:\"^`\";i;,^^^^^\"\",,,,,\"\"\",:I,                                               }CQ0Jcx+",
  "                                                                       IiI;;I:\"^`\";il:\"^^^^^\"\",,,,,\"\"\"\",;I                                               JL0LXn\\",
  "                                                                       :iI;;I:,^`\";>i ;,\"^^^^^\"\",,,,,\"\"\",:l                                              }CQ0Uvr`",
  "                                                                       '>I;;I:,^`\";>i  ^:\"\"^^^^\"\",,,,,\"\"\",:I,                                             JL0Juf+",
  "                                                                       '>I;;I;,^`\";>>    ,,\"^^^^^\"\",,,,\"\"\"\",;I                                            }LQL0Jz}",
  "                                                                       '<l;;I;,^`\";<>     ':,\"^^^^\"\",,,,,\"\"\",:l                                           jqqLYr/t;",
  "                                                                        <l;;I;,^`\";<`       \":\"^^^^^\"\",,,,\"\"\"\":I\"                                         [UcUXf(\\",
  "                                                                        <l;;I;,^`\";<`        .,,\"^^^^\"\",,,,,\"\"\",;I                                         ~trx/1<",
  "                                                                        ~l;;I;,^`\";<^          ':,\"^^^^\"\",,,,\"\"\",:l                                          }}?-",
  "                                                                        ~!;;I;,^`\"I~^            \",\"^^^^\"\",,,,,\"\"\":I\"                                         ..",
  "                                                                        !!;;I;,^`\"I~^             .;,\"^^^^\"\",,,,\"\"\",:;",
  "                                                                        ;!;;;:,^^\"I~^               ^:\"^^^^\"\",:;;;::,\";",
  "                                                                        I!I;;;:,\":l+\"                 ,,\"^^^^,!l!~<l,\",l;",
  "                                                                        I>l!++!,\":!_                    :,^^^i!!+[-i:\"\";<",
  "                                                                        ^il<?_!,^,l_                     \",\":>l!<<!;\"^\";>i",
  "                                                                        !l!~<l,^`\"I_                       ,>!l><i;\"``^:>l",
  "                                                                       `!!<~!:^``\"l+                        >l!<>I,^``\"I+.",
  "                                                                       >li~>;\"``^;~                        l!l><!:\"``^:>I",
  "                                                                      :!!~<l,^``,>,                        >l!<>I,^``,!+",
  "                                                                      il>~!:^``\"!l                        l!l><!:^``\"I+.",
  "                                                                     !li~>;\"``\"I<                         >li<i;\"^`^:>I",
  "                                                                    ,!!<<I\"^`^;~                         \"!l><l,^``,!+",
  "                                                                    il>~!,^``,>`                         >li<i;\"``^;+",
  "                                                                   l!i~>;\"``\"!!                         \"!IIll,^`^:>I",
  "                                                                   ;\"\";:\"``^Ii                          ,...  `^`\"l+",
  "                                                                  '''.  `\"^;>                         '``,:^. .^;;~",
  "                                                                ,^:<<,. ':!>`                        `,\"!]]!`  `;<I",
  "                                                               ^,\"i]-;. .,>I                         ;\",!_~;'  `:~",
  "                                                              .:\";>i,'  .,>`                        ;,\";il,'   ':~^",
  "                                                              :\":i>;'   .,<                        `:\",li;`    `;_",
  "                                                             :\",!<l^    `I>                        ;\"\"Iil\".   .\"!;",
  "                                                            ,,\"I>!\".   ':<                        ;,\":!!:'    `;+",
  "                                                           `,\";>>:'   .^!;                       \":\",liI^.   .\"!;",
  "                                                           :\":i>I`    `;>                        ;\"\";i!,'    `;~",
  "                                                          ;\",l<!\".   .,>`                       ;,\":!i;`    .\"!<",
  "                                                         \";^,!i:'    ^li                        I\"^:!l\".    `;~",
  "                                                         \":^''`'    ':;.                       `,,`'``.    .\",`...",
  "                                                        ,\"~_>il,,\"\":lllllI;',                 ,\"i}+iil,,\"\",I!!!!!!: `\"",
  "                                                        :^<-----------------,:                ;^,~----------------- 'l",
  "                                                        ;',+-------------<il\"fCCCCCCCCCCCCCCCX;` ,--------------<il 'i",
  "                                                        ^`                  '                 ^^                    ,.",
  "",
  "",
  "",
  "",
];
