/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `beer_swig` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                         `|",
  "                                                      !   8`",
  "                                                      m?  an  `",
  "                                                      !8? J8! J?  n",
  "                                                   ?J` m8?n8m 8| |m",
  "                                                !!  |8|`8oJQpn8J!8J",
  "                                                `Jm|`J8amQoa}8Xaaq?`?",
  "                                                  ?a8mapQ8]o,b]8v*J8|",
  "                                                   `noXq0[\\~~!+qJ1b8|",
  "                                                  `nJJ8n]]` !mn` \"+m8mJ!",
  "                                                    |aoz( |mn`  _fYo$f~a`",
  "                                                   |JJamjan`  +/Xb#$$h<uJ",
  "                                                    !|8a|   l|uqhJ%$UYo<p?",
  "                                                      mJI^I)xQWfi8$B$$8o[a`  JZW?",
  "                                                      |8n<jL#MJJ~XO$$@UUkQJ  aqOW?",
  "                                                       a8Z8$$$$%+?)CXrnvUM8! `&qOo|",
  "                                                       Jv|&*0B$$Y(cXccczY08  caWOLoJ?!",
  "                                                       ?*{~o*$$ofjrCObwZCJ8'zkQkWOLoWkk?",
  "                                                        `mY~oLvrzvvm@$$$0X8dpQa&8WOLhoZW?`]]]]]",
  "                                                          |o|n//zCJ$$$WpUQ8*a#&88ZWO0*pZ#%%%%BB%Zl",
  "                                                           `WwYYCOOwadzOmWLCW8%@%dpM##O00o&M&%BB8Mt",
  "                                                           t#8*qpdmmmpkMhvjxCWBWjap00Oqppph#*8BB%Wo}",
  "                                                           ?LL@BW*W%kbmu(|/jn0#MM#8pZppppppdM8B@B8Mh;",
  "                                                                ][Lqanjt|(tuXYomm*W&bpppppppd&B@@%&#Z",
  "                                                     !uJCCC\\` i(XkM#ownrruXCLLWMW%Wqhppppppppd&@@B%Won",
  "                                                   'Z888%BBB%%%%a#kmqWdJL0ZOYOMW(jkwC*ppppppppd&@@B8Ma~",
  "                                                  I#&W8%%%88&M#ok*&ok%MmC0(XvWW&o*8a*#*ppppppppo%@@B&#m.",
  "                                                  qMMB#W&#akbdpU\\wW{uh&dQZn}L$@WW8%ok%M*pppppppZ8B@@%&*u",
  "                                                 f#W#&$#Zvop[uqwLq###88aqU[z-m$W&&%#k%%M*dppppdbM8B@B%Wo}",
  "                                                I*WMabB@UUbB**8%%&hW&8%*j;lp|n$%&W%Mp%%8*8akka#*cXMB@B8Mh.",
  "                                                qMMobkM$&W%BB%%%%%*#&&%MO~+YX|B$WW%Wp%%%%*W8adCt|tuMB@B&#J",
  "                                               f#W*kbo&@$M&%BB%%%%8aW&%&b{[u0/m$W&8&k#%%@B*WMut|(|tuMB@%Wo/",
  "                                              I*W#hbaW%@$$M8BBB%%%%aM&88ar(tpxc$%&&8ao%%@@%*WMut|(|tjb88%Wa;",
  "                                              QMMabhM%@@$$@W%BB%%%%&o&&%#CtfOJu8$W&%*k%%@@B&*Wbj/|(|tjb&*&#m.",
  "                                             1#W*kk*8B@$@B$8&%BB%%%%aM&%WwrxJOzb$&&%#k8%@@B&o*&bj/|(|tjw&##*u",
  "                                            '*W#hbo&B@$$B&M$W8BBB%%%&o&8&kcvXpYQ$BW8Mp8%@@B&od*Mbj/|(|tjO&*#o~",
  "                                            QMMabaW%@$$B&oQt$W8BB%%%BhM&8oJXYm0Q&$M&Wp8%@@B&om_a&wj/|(fuX88#aw.",
  "                                           1#Wobk#%@$$@8*0. 0$&%BB%%B#*&8#ZJCQ0Zh$&&&k#%@@B&om _#8CjrnzCq%B8MaU",
  "                                          '*W#kk*8B@$@%#d.  ^&%8%BB%%@aW8WpoWLLLL$@&8a*8@@B&oL  fM8dOQqk8B@B%Wa}",
  "                                          LMMabo&B@$@%Mk<    >$&8BB%%BM*&8h>'''``m$M8*k8@@B&or   cM8%%%%%%B@B%Wo+",
  "                                         1#WobhW%@$$BWh<      t$&%BB%B@hW8afl!!ii|$&&#k8B@B&or    cW%B@B%%%B@B%Mb",
  "                                        '*W*kk#%@$$B&ar        0$8%BB%@##&oU~~~~~~%BMMp%B@B&or     zW%B@B%%%@@%Mk>",
  "                                        LMMhb*8B@$@8ox         ^&%8BB%B%hW*Z~~~~~~0$*Mp%%@B&ar      Q&%B@BB@$$%Mb>",
  "                                       _W%%%BB8B$@8*Q           >$8%BBB@###q|~~~~~\\$W#k#%@B&ar      'd&%@@$$$$%#0",
  "                                      'b&#oW%B8MB%#O.            v$8%BB@%a#qn+_?]})@@ha*%@B&ar       'b%@$$$$$&w;",
  "                                      qW*qma8B%MhMb.              *$8BBB@a#wZ/fxucYa$aak%@BWaj        'n*$$$$%r'",
  "                                     ;oWW**&B@BWhp<               !$B%BB@8opdOpaomJu$%ak%BBWaj           `[[i",
  "                                     .aW%%8%B@@&o|                 x$8%BB@abkt?`    b$ap%@BWaj",
  "                                      tM8%%8%@@%#n                  h$8BB@&bpr      t$&p%BBWhj",
  "                                      .o&%%88%%%Md                  IB$%B@Bkb0      ^$Ba#BBWhj",
  "                                       t#8%Y<</m8h:                  j$B%B@*hb:      0$M#%BWhf",
  "                                       .q&b<I-\\xk#~                   O$%B@%dh]      }$W&%BWhf",
  "                                        {Mk)1)tx0&x                   '&$%BBMor       $@W8%Whf",
  "                                         q8f)1\\rv8x                    1@$%B8*p       0$M8%Whf",
  "                                         +WO)1(fnk)                     Q$@B%Mb>      >$8&&W&&UU?",
  "                                          -8t11/xmJ                     'M$B%Wh(       BWMMMWW&8&b_",
  "                                           nO)1|jX8                      {8$%&oX      c*#*hhoM&88W*v",
  "                                           `8t1)tno!                     lq@$8#pU(   /o*obwwb*W88&#h[",
  "                                            nC)1\\xpn                    z##*$$%koWpI]ko#okpph#&88&MaQ",
  "                                            `#(1(jJa                   v**hb8$$BW%88Wko#M#*#M&8%%8Mod",
  "                                             JC11tnM!                 ~a***WW#abq008]k*MW&WWW&8%%8W*k<",
  "                                             !#)1\\xk|                 na#*M00m}fp{c8uwo#W&WWW&8%%8&#hr",
  "                                              mLtxn0a!                /a##8W&BOpW8&%BMh*M&&WWW&8%%&MaQ",
  "                                              nZ!]\\uJ8                ~h##8$$$$$$$$@8JkoMW&WWW&8%%8Mod",
  "                                              JJt)/XL#!               .k*MW%@@@BB%&*b>/a#W&WWW&8%%8W*b<",
  "                                              !qvuvJ0v                 ZoMWWMW&8%%&#k<;h*MW&WW&88%%&#h|",
  "                                               `1YUOw>                 uo#WWMW&8%%&#k< ZoMW&WWW&8%%&MaX",
  "                                                 [nu[                  }a#WWMM&8%%8Mhj }a#W&WWW&8%%8Wop",
  "                                                                       ;h*WWMMW8%%8Mhr .k*MW&WW&8%%8W*b:",
  "                                                                        k*MWMMW8%%8Mar  uo#W&WWW&8%%&#k]",
  "                                                                        UoMWWMW&%%8Wox  ~h#W&WWW&8%%&Max",
  "                                                                        /a#WWMW&8%8Woq   Z*MW&WW&8%%8Woq",
  "                                                                        ~a#WWMW&8%%W*p   /a#W&WWW&8%8W*b.",
  "                                                                        .h*WWMM&8%%&*d   .h*W&WWW&8%%&#k<",
  "                                                                         Z*MWMMW8%%&*d    UoMW&WW&8%%8Mar",
  "                                                                         uoMWWMW8%%&#b>   ~a#W&WWW8%%8WoQ",
  "                                                                         }a#WWMW8%%8#k<    k*M&WWW&8%%W*d",
  "                                                                         ~h#WWMW&%%8Mh<    /oMW&WW&8%%&#k<",
  "                                                                          k*WWMW&8%8Mh(    ;h#W&WWW8%%8Mh|",
  "                                                                          J*MWMM&8%8War     J*M&WWW&&88MoX",
  "                                                                          noMWMM&8%%Wor     }a#*##**M&8W*d",
  "                                                                          ~a#WWMW8%%Wox     .hao*kwpoW8&#k:",
  "                                                                          .h#WWWW&88W*Q      uk**hdk#&%8Mh]",
  "                                                                           k**#oo#&8Wop      Ih*MM#M&8%8Maj",
  "                                                                           ua*aqqaW8&*d       k*MMMM&%%8Mhj",
  "                                                                           J**kbaM8%8#b       b*MMMM&8%8Mhf",
  "                                                                          +o*hbaM8%B8#d       uoMMMM&8%8Mh<",
  "                                                                         .w*abk#&%B%&or       uoMMMM&8%8Mh<",
  "                                                                         v*okk*&%BB8*Y        /oMWMM&8%8Mh<",
  "                                                                        +o*hboW8BB8#O.        ~a#WMM&8%8Mh<",
  "                                                                       'q*abhM8%B%Mm.         ~a#WMM&8%8Mh<",
  "                                                                       v*obk#8%B%Wh<          .h#MMM&8%8Mk<",
  "                                                                      +o*kk*&%B%&a~            k#MMMW8%8Mk>",
  "                                                                     'q*hboW%BB&or             k*W8%B@@%Mk>",
  "                                                                     LWM*oM8BB8*n              JWBBBB@$$%o>",
  "                                                                   !q@@@$$B8B8#0              'k%&ab*%$$BWc",
  "                                                                  -88*aW@$@&#MZ.              jW8#qZh8$$@&o~",
  "                                                                 -W8#wmoB$$8*d.               q&%8WM8@$$@8or",
  "                                                                _W8Wak#%$$$%*x                a&%B%%B$$$@8*x",
  "                                                               'k8&ak*%$$$$8o|                o&%B%%B$$$@8*Q",
  "                                                              'b8&oko8@$$$@Wk.                o&%B%%B$$$$%#p",
  "                                                              088*ka&@$$$@8o~                 o&%B%%B$$$$%Mb",
  "                                                             X&8#hhMB$$$$%#n                  o&%B%%B$$$$%Mk>",
  "                                                            j&8Mhk#%$$$$BWm.                  *&%B%%B@$$$BWh<",
  "                                                           _W8Wak*8@$$$@8o~                   *&%B%%B@$$$BWa]",
  "                                                           zW%Wao&@$$$$%#n                    *&%B%%B@$$$B&ar",
  "                                                          !W&%BBB@$$$$B&MwLLL]              'm8WB@BB@$$$$B&WB@@$$pu'",
  "                                                         l&&dbaaM&&8&W***###W$k.            08#mdaa*&&&8&Moooo**M@@d.",
  "                                                         c&8kppppppppppppppppb&\\            #%8appppppppppppppppp%$M~",
  "                                                         1&@Mppppppppppppppho*W}            *%@Bbpppppppppppppboo$$#<",
  "                                                          Z@$$$$$$$$$$$$$$$$$B/.............}8$$$$$$$$$$$$$$$$$$$$%f",
  "                                                           fO$$$Zmmmmm||\\\\\\\\i^^^^\"\"\"\"\"^^^^^^^)#$$$$$$$$$$hZZZZOr1{,",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"i|||^```'''...",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
