/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `beer_hold` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                   !`  !",
  "                                                                               !   J?  a",
  "                                                                           |`  J|  8? nm",
  "                                                                           !a` ?a !8n`8J",
  "                                                                            ma`?8n?8Jm8| n",
  "                                                                            !8a|o8mLaap|JJ  !",
  "                                                                          !| mXa8X8}8?8a8!!m?",
  "                                                                           JaJp|8>*:J{apam8J",
  "                                                                         !` ao8r/`<;;(i*vqJ",
  "                                                                         `m8m8Xu}?]})|jzO8ma`",
  "                                                                           JoJJ|]]]??????Qa",
  "                                                                           aL        ''`+Y8|",
  "                                                                          ?8L ~{1)|\\/tjrxz8J",
  "                                                                         `a$bC0OpkhhaWB$$%m0J",
  "                                                                         ?*$$$$$bl<Q*$$$*%<{a",
  "                                                                         `a\"wo*$w[f*$$dcuk}xJ",
  "                                                                          a-%$$$X<_m$$$@ch{Z?",
  "                                                                          nYz*hX})uxX0ZJYa)*!",
  "                                                                          rz1rJj\\tcJuvXUCaQ8l.",
  "                                                                         zhnfc0JrxX0XYCQQw8&oq.",
  "                                                                       'qdLJJ0qU&$@#kLOOQa*Zd&q.",
  "                                                                      IpwQohqbpU0ha$#bZOdWLkW8&q.",
  "                                                                     `OWBB%8M#&kzvc0LZq#&oW&&8%&q.",
  "                                                                ]]`    `noBB%8%qaapd*W*k&&8%B@@@aj",
  "                                                            'na%%BBBJ!    !uBBBv}(uzJYYO&@@@BC|`  `]]]]]",
  "                                                           -W&W8%BBBB%wC\\tYUU8%v}[])jvY0%on?    !m%%%%BBBm!",
  "                                                          I#W#B*&%%%%%%%%**#***c111/xzJOWWWWWwCO&&WMM&%BBB%m!",
  "                                                          qMWo$&M&&MMMMMMo*Mo#8kxnvzC0Ldoha&oa#MW#dwpo&BBBBB%h(",
  "                                                         f#W#h&$O]Q&u/wd\\YhZtb%*QLOZmLq##aM8khoMWoqZpo&%%BBBBB%h|",
  "                                                        I*WMab*$kqo%pq#o0mkqJp%o0OZ/rxo#p[vhcjoM&W*o#&888%%BBBBB%a|",
  "                                                        LMWobk#$WM8%88%%%#aM#%8aqpf]JM$###WMdhoW8%%%BB%%8888%BBBBB%8x'",
  "                                                       1#W*kbo&$B#8%888%%WaM#%8k\\\"1U(*$M#&%*dWaM8B@@@@BB%%8888%%BBBB%8n`",
  "                                                      '*WMhbaW%$$*&%%88%%%hM#%&d:lXJ)a$M#88ao%MM8B@$$@@@@BB%%888%%BBBBB8n`",
  "                                                      LMMobhM%@@$&W8%88%%%kM#%&q<+YC\\a@M#%&bW%%&&B@$$$$$@@@BB%%888%%BBBBB%m!",
  "                                                     1#W*kk*8B@$$@M8%88%%BkM#%Wm][JUf@@M#%Ww%%%@B%B@@$$$$$@@@@BB%8888%%BBBB%m!",
  "                                                    'pW#hbo&B@$$$$#8%888%BbM#%MJ)(Lzx$@MM%#b%%B@$@8#WB@@$$$$$@@@BB%%888%%BBBB%m!",
  "                                                    cMMabhW%@$$B&$W&%%88%BdMM%#U/tQYu$@MM%oh%%@@@BWh(`|wB@@$$$$@@@@B%%888%%%%%BBq|'",
  "                                                   _#W*kk#8@@$@8*BBW8%88%B*#M%*XjrpUz$@MM8ha%B@$@8#p    !no@@$$$$$@@@BB%8W&&MM&%B%b+",
  "                                                  'pW#hb*8B@$@%#d\\$M8%88%Bo#W8aznupYU$@M&&p&%B@$B&ac       !JB@@$$$$@@@@&#Wamqo8BBWa;",
  "                                                  cMMabaWB@$@%Mk<^$&&%88%Bo#&8hXczpJL$@M&Md&%@$@%Mb:          ?JB@@$$$$@oMMapbM%@B&or",
  "                                                 I#W*khM%@$$BWh<  bB&%%88@a#&&bZ0JLQO$@M8#p&B@$B&oL             `|wB@$$%*W#aoW%@@B&or",
  "                                                 pW#kk#8@$$B&ar   t$W8%88@a*&&p\\000M*$@M%aa&@@@%Wk]                `no@WMW*a#8B@$BWh)",
  "                                                fM&#o#8B@$@8ox    ^$&8%88@&*&Wm::::::$8M8bo8@$@8*q                    !oWWWW&%@$@8*Q",
  "                                               lM888%B%8@@%#0      bB&%88@&oW*Y<>ii!l$WWWqW%@$BWh(                    +#8Y~<{LM@%#d.",
  "                                              'dWophWBB&o&MO.      v$&%%8@Wo&hu~~~~~\\$WWMbWB$@%#d:                    L&cl\">)jJ8Wk<",
  "                                              t#WhwkWBB8okb:       ]$&8%8@WoWqc~~~~~n$MW*bW@$B&oz                    .*8~i+)jcU8or",
  "                                              vM8&W&%@@%#d<         $B8%8BWa#w|~~~~~n$#Mhh&$@%Mb?                    +MC>>[tvUdWQ",
  "                                              /#8%%8%B@BWb          q$&%8B%hom/?---_u$*#d&8$@8*Q                     .8[i+(xX08b.",
  "                                               wW%%8%B@B&a<         r$&%%B@hbqvrjjffC$**q&B@BWh(                     |C>>}fcJ##~",
  "                                               {*8%8oOmh8*\\         ~$%8%B@kqqaaaahhM$Mad&B@8#p                      a(i_|nYdhI",
  "                                                CW8O,,?/OWU          %$8%BBbpw     `v$#ko&$B&ac                     |8OOwzzQ8`",
  "                                                I*8f-?(ju8h          O$&%BBpdz      }$Wd*8@%Mb:                    ?MCXYZoa#|",
  "                                                 vWC)1(fnk*>         /$B%BBqaj      }$#m8%B&oL                    `MqpppqZom",
  "                                                 .*#(11/xQM:         ~B@8BBkhf      }$#q8B%Wk]                    rppppppphJ",
  "                                                  _&C)1|ju8`          M$8B%*k?      z$#o8B8*q                    `appppppp#!",
  "                                                   ?#(1)tnk|          J$%%%Mb>      0$#&8BWa(                    XppppppppZ",
  "                                                    mC)1\\rQm          {B$%%#d>      0$#&%%#d:                   !kpppppppa`",
  "                                                    !#(1(fu8`         I&$88#p       0$#&%&oz                    0ppppppppr",
  "                                                     mC)1/xk?        `?MB88#w       0$#&%Mk?                   !#pppppppq`",
  "                                                     !#(1|rQJ      lOWWWW&&8&r'     0$#&8*q                    mJLpppppd|",
  "                                                      mC1)tu8     1*##oo#W&8&Mp+   '#$M&Whk&r'                ?or[Ywqpbm",
  "                                                      !#))tvh|   +o**kqqk#W88W#k. _*M*&$&pW8Wp+               aJYwhdqq&!",
  "                                                       mL)[juM?  ko*odwqk#&88&#ahC&888$$$M%8&#k.             !8U#)Q8paJ",
  "                                                       8x)\\jXO8 ~k*##oao#W8%%&Maq0#Waoo**M@8MMon              aaYYkWb&`",
  "                                                       m0r/nJ0m ~k*MWWMMW&8%%8MoprU8vq_xd*@%bW#k;             |#/Z&Wh?",
  "                                                       `0UczCZ~  koMWWMMW&8%%8MopZ#8M%ba8$$%b8MoU             nUJoJ?",
  "                                                         !Ompz   Uo#WWWMW&8%%8WodM$$$$$$$$$W88&#h~           `8upa`",
  "                                                          .+I    /a#MWWMW&8%%8W*b>v*M&BB%%888%8W*Z           n0LM?",
  "                                                                 ~h*MWWMW&8%%8W*b< w*W&8&&&&8%%&Ma}          8Xhm",
  "                                                                  k*MWWMMW8%%%&#k] Ia#W&8&&&&8%8W*b.         m*a`",
  "                                                                  Zo#WWMMW&8%%&#hj  {oM&8&&&&88%8Mo/",
  "                                                                  na#WWMMW&8%%&#hr   C*W&8&&&&8%8&#k.",
  "                                                                  ~h*MWWMW&8%%&Mar   .w#W&8&&&88%8WoY",
  "                                                                  .k*MWWMW&8%%8MaL    +oM&8&&&&8%%&#h;",
  "                                                                   ZoMWWMW&8%%8Moq     v*M&8&&&&8%8W*O",
  "                                                                   na#WWMMW8%%8Wop      w#W&8&&&88%&Ma[",
  "                                                                   ~a#WWMMW8%%8W*d      'aM&8&&&&8%8&*Z",
  "                                                                   ;h*MWWMW&8%%W*d>      {oM&8&&&&8%8Mo\\",
  "                                                                    b*MWWMW&8%%&*b>       v*W&8&&&8%%&#k.",
  "                                                                    uoMWWMW&8%%&#k<       .w#W8&&&&8%8Wo/",
  "                                                                    }a#WWMM&8%%&#k<        +oM&8&&&88%&Mh;",
  "                                                                    ;h#WWMMW8%%8Mhj         t*W&8&&&8%8W*U",
  "                                                                     k*MWWMW8%%8Mar          w#W&&&&&888Ma~",
  "                                                                     UoMWWMW&8%8Wax          'aM&8&WWWW&&MZ",
  "                                                                     /a#MMWWW&8&MoX           {*WM*#ah*W8&*}",
  "                                                                     ~h**#ahoW&8Maq            v#h*aqwaW8&#Z",
  "                                                                      ka*aqwkM&8W*p            .ma#*aoM8%8Mk>",
  "                                                                      Zo*akh*&8%&*d             no#*o#&%B8Md",
  "                                                                     Ia*ohh#&%B%&*p             J*#ooM8%%&oz",
  "                                                                     J**akoW8%B%&oz             h**o*W%B%Wk>",
  "                                                                    Ia*oha#&%B%8#O.            ~a#*o#&%B8#0",
  "                                                                    J**hh*W8%B8Mk<             /o#ooM8%%&a(",
  "                                                                   Ia*ohaM8%B%&or              J*#o*W%B8Md",
  "                                                                   C**hh*&%BB8#O               h#*o#&%%&*z",
  "                                                                  Ia*akoM8%B%Mk<              ~a#*oM8%%Wk:",
  "                                                                  C**hh#&%B%&ar               uo#o*W%B8#0",
  "                                                                 Io*#hoW8BB8#0                m*MM&8%%&a]",
  "                                                                `ZB@$$$B%B%Mk:               `M@@@$$@8Md",
  "                                                               ?%B8&%@$$%MWa|               lh%MoMB$@8*r",
  "                                                              _W8#qma%$$BWh0                d8WpZh%$$%#/",
  "                                                             'b88*dd#B$$@&a<               _M88#*&@$$BM0",
  "                                                             Q&8WooWB$$$@&a<               Q&%&M&@$$$%#X",
  "                                                            )W8&*a#%$$$$BWk:              '#88WM8@$$$8o|",
  "                                                           'M88Mo*&@$$$$%#Y               fW%8MWB$$$@&h>",
  "                                                           d&8WooMB$$$$BWh;               *&%&M&@$$$BMd",
  "                                                          jW8&#a#8@$$$@8*Y               1M88WM8@$$$%*X",
  "                                                         lM88MooWB$$$$BWh;               Q&%&MWB$$$@8a(",
  "                                                         d&8W*oM%$$$$@8*Y               I#8%WM&@$$$BWk: [[",
  "                                                        +#8%W**&@$$$$BWh;               fW%8WW%@$$$%MMB%8@@r",
  "                                                       'a&&BBBB@$$$$@8W8@@$$L\\          XW%@@@@$$$$#hkbdpp*&}",
  "                                                       b8oZkaa*&&&8&Moooo**W$BQ        Y%#aW&MoobpppppppppbW|",
  "                                                      +M%&kppppppppppppppppp@@#<      IW8hppppppppppphoW8$$p.",
  "                                                      IM%$&bpppppppppppppho#$@o`      _MB#ppppphoW8$$$$$0c?",
  "                                                       Y%$$$$$$$$$$$$$$$$$$$$8[........bB$B88$$$$$$OX1,",
  "                                                        t#$$$$$$$$$$mmmmmmn\\|\"\"\"\"\"^^^^^!z$$$$$kZ(-'...",
  "                                                      ...'l(||`^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"|\\?^^^```'''...",
  "                                                         ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                       .................",
];
