/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `beer_swig` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                         '[",
  "                                                      l   k",
  "                                                      J>  d1  '",
  "                                                      :hi zd^ Y;  t",
  "                                                   +u  zhi/Mf &~ tc",
  "                                                l;  ?h[ hdf&Z(%1iB{",
  "                                                 xL1 |aOc#q#oZ%n&d:^~",
  "                                                  lQ*CYhobMa&k%k$*rW>",
  "                                                    }pMahM*#B%@$$BOU+",
  "                                                  'tYnObWMB$$$$$$8bm0wz\"",
  "                                                    <YaM&$$$$$$$pYr}<O#Y",
  "                                                   }YLbMB$$$$$bUxt/  1Mb\\",
  "                                                    '>p$$$$$*Cutrz` /CdMq!",
  "                                                      xqM%#Qcf/wa\" `  -p#C",
  "                                                      ?Lwhzj({f/kf{  '/cq*t",
  "                                                       cbj\"    ^bq0|fcuxxqd^  'i,,",
  "                                                       U$L_?)`  fLxfxrxjttj  ,>)I\":`",
  "                                                       >0aMq1  iYXc|{+]}\\\\j \"~(+:,\",:  ''..",
  "                                                         xbMp(xcjxx[.   1ff~-)>,,\"^`^iI-[;\":!",
  "                                                          +m#vJJj|/   :-/\\fl>I,\"`'`,;>iJC!^,>~'``",
  "                                                            zOtt|{{]>_j{{|n|:\"^'`\"' `>mqwZZZ>-`'^;\"",
  "                                                           ,I{X?-_[[[}{{tzXc|:':^   \">$$$$$$>?`'^:!^",
  "                                                              ^;:!<~(\\jXQLUzu)I;;lI~l>xxxxxx<?''`\"I>",
  "                                                                    iuzYCLYuffi[[l;-~<jjjjjj<]'''`,l>",
  "                                                                ^,;li[uccuj|((:;:^:[r<jjjjjj<1`'.'^:!I",
  "                                                    ^\"\"\"^`````^^>l~[?:_\\(1}{f1;:Qz~]t<jjjjjj~r)'''`\";>'",
  "                                                   I,:\"`^^^\",;I!~l,i<^;[|1Ljn::,!l\">_~jjjjjj~nc),''`\"Ii",
  "                                                  I;;'I:,l>~+_-tJ]:On<,_)}vZ( .::\"^!_~jjjjjj+cXcj,''^,l;",
  "                                                 ^I:l, l}ni-wn?]|?Ill^\">?tmjp[ ::,^I_~1{{{}{+XCYcj,.'^:i^",
  "                                                 l:I>+`'tt+'l!^^^\">:,\"^lzM*-Cu ^,:^;]~;^`'',?XLCYzr>'`\";<",
  "                                                I;;i+~; ,:^```^^^^lI,,^;{kbtfL' ::^:-\";`  '!rUCQCYzu>'`,ll",
  "                                               ^I:l~~!,. ;,^'`^^^^\"i:,^,+Omn1U[ :,\",~l^^..;_uzULQCYzv>'^:!:",
  "                                               l:I<+>:`.  ;\"`'`^^^^>I,\"\"icLY-vr ^:,\">!^`'.`l_uzULQCYzv)\"^;>",
  "                                              :;;i+<I^'.  .:^```^^^,i,,^I\\UX{/n\" :,^!~^`'.',!_vzULQCYzv(!,Ii",
  "                                             'I:!~~l\"'. .' \",^'`^^^`i;,^:]cv\\{r+ ,,^I~^`'.',!l)vzULQCUzc|>IlI",
  "                                             l:I<+i,`. .`,I :\"`'`^^`,!,\",~rnj-t) ':\";-\"`'.',!_l\\vXULQCUzu1lIi'",
  "                                            :;;>+>:`.  '\"!+  :^`'`^^'>;,^!\\jf[1(, ;\":-\"^'.',![ >(vXULLYnjf\"Ii!",
  "                                           'I:!~<I^'. '\"l~   .,^'`^^`I!,^I}\\|)1{< ,,,~l^'.',![  I(vzzuj\\(1'\";i!",
  "                                           l:I<~l\"'. .^I_     ^\"`'`^`'>:\":-waMWW& .:\">!\"'.',i-  \"!(/|){{1,''^:i^",
  "                                          ;;;>+i,`. .`;~^      ,^`'`^';l,\"<aBBBBB[ ;\"!~\"..',i!   :;I>~~!^`'''^:!.",
  "                                         'I;i+>;`. .`:<`        ,^'`^`.<:\"iY**ooaL ,,I~^'.',i!    ,:^'''`^`'''^;+",
  "                                         l:l~~I^'. ',>i          \"`'`^'ll,!tkkkkkk^`I;-^'.',ii     \":^'''`^`'.`;~^",
  "                                        ;;I<~!\"'. '\"!!           `^`'`'`>:l}kkkkkk1 l;-^`.',ii      :,`''''...`;+^",
  "                                        ;^^`'`^' .\"l+             \"^'``.III?LkkkkkJ :I~I`.`,ii       ;,`..    `I~",
  "                                       ,,I!:^'^;`^I<               \"`'`'`iI?ubdqwZ0'.>>l^.`,ii        ,^.    .,!",
  "                                      l;l]}>\"'`;<;+                 \"`'`.>l]}UXcnrf~ ii<^.`:>i               ^'",
  "                                      i::l!,`.`:<-`                 `^``.\"i-_||((?+I ^>~`'`:>>",
  "                                      i:^^^^`.'\"iI                 . ^`''.i+<!\"       i-`'`:>>",
  "                                      \"I\"`^^`'.^ll                  ^ \"`'.,+-i        ,-^``:>>",
  "                                       i:^^[unf+;_                   ' ^`''~++        `>I``:>>",
  "                                       \"I\"caWh0Y/<.                  ` '`''l<+.        ;I``:<>",
  "                                        l}qh#pJvr[`                   \" ^`'^_<,        :,^`:<>",
  "                                        `}QQOQUvx|!                    , ^'`;i!        .:^^:<>",
  "                                         lXL00Cznj!                    `' ``\"l-         I\"^:<<",
  "                                         .)LQOQXur!                     : '`^I+^        \",,:,\"..",
  "                                           CL00Uvx]                      I `^:>I       `:;;;::,\",:",
  "                                           }LQOCznj                      `\" ^,!<      ,lI!><iI,\"\":l;",
  "                                            CL0QYuj`                      l. \"l-'    ,il!+]]+!:\"\",I>\"",
  "                                            }L00Jcx~                    \"IIl  ^~!:;  ~il!~-_<I,^^,;i+",
  "                                             CQOLzn\\                   :!l>+\"  `:^\"+\\~!I;Ill;,\"^^\";!_",
  "                                             \\L00Uuj`                 '>l!l::l>+?1xwW~!;:,:::,\"^^\":l~`",
  "                                             ,CQOCcr!                 I>llI11[ZY-OUYc]iI:,:::,\"^^^,I<i",
  "                                              jUUvvnr`                :>Il\":,`{-:\",I+<>l;:::::\"^^^,I>_",
  "                                              |dowJunr                '>lI\"        .\" ~!;:,:::,\"^^\";!_",
  "                                              tQYQJj(\\^                <l;:`..'`'^,l+^,iI:,:::,\"^^\":l+^",
  "                                              ^txnx/1+                 >!;::;:,\"^^,l~^ <l;:,:::\"^^^,I<I",
  "                                                <t/1]^                 IiI::;;,\"^^,I<` >!I:,:::,\"^^,I><",
  "                                                 ,I;,                  ^>I::;;,\"^^\"I<> ^>l:,:::,\"^^\";i-",
  "                                                                        <l;:;;:\"^^\";>i  ~!;:,::,\"^^\":l+",
  "                                                                        ~!;:;;:\"^`\";>!  IiI:,:::,^^^,I<,",
  "                                                                        !!;:;;:,^`\":i!  '>l:,:::,\"^^\";>!",
  "                                                                        :iI::;:,^^^:!]   >!;:,::,\"^^\";i?",
  "                                                                        '>I::;;,\"^^:!-   :iI:,:::\"^^^:l+",
  "                                                                         <l;:;;,\"^^,l_    <l;,:::,\"^^,I<`",
  "                                                                         >!;:;;:\"^^,l+    !!;:,::,\"^^\";>!",
  "                                                                         I!;:;;:\"^^,I+^   '>I:,:::\"^^\":i+",
  "                                                                         ^iI::;:\"^^\"I~^    ~l;,:::,\"^^:l_",
  "                                                                         '>I::;:,^^\";<`    ,iI:,::,\"^^,I~`",
  "                                                                          ~l;:;;,^^\";>l     >l:,:::\"^^\";>I",
  "                                                                          !!;:;;,\"^^:>i     l!;,:::,,\"\";i>",
  "                                                                          Ii;:;;,\"^^:i!     ^iIlII!l;,\":!_",
  "                                                                          '>I:;;:\"^^:!l      <>!l~]-!:\",I~",
  "                                                                           <I:;::,\"\":!+      I<!l<_~I,^\";>,",
  "                                                                           ~!lI!iI,\":i-       <l;;I;,^`\";>>",
  "                                                                           I>l>?]>:\",l_       ~l;;I;,^`\";>>",
  "                                                                           l!!~+>;\"^\"I+       +!;;I;,^`\";>>",
  "                                                                          .il<+>;\"``\"I_       ;!;;I;,^`\";<`",
  "                                                                          !li+<I,^``,!!       I!;;I;,^`\";<`",
  "                                                                         :!!~~!,^``\"li        :iI;;;,^`^;<`",
  "                                                                        .!!<+i:^``^I<         'iI;;;,^`^;<`",
  "                                                                        ll>+>;\"``^;i          '>I;;;,\"`^;<^",
  "                                                                       :!i+<I\"``^:<`           <I;;;,\"`^;<^",
  "                                                                      .!!~~!,^``,>'            <l;;;:\"`^;~^",
  "                                                                      ll<+i:^``\"!!             ~l:\"``'.`;~^",
  "                                                                     ;:;!i;\"``\"ll              l:''`'.  ^i^",
  "                                                                     ...  `\"`^I~               ,^,>+!^. '::",
  "                                                                   \"^li:' .,I;>               ^:\"I?}<\". ',i`",
  "                                                                  :\"I][!` .^!_                l:^^;;\".  .\"!i",
  "                                                                 :\":><I^   ^l!                i,`'^^'   .\"!!",
  "                                                                ,\",i~l^    ^!I                i,`'^^'   .\"l+",
  "                                                               :\",!~i\".   ':~                 i,`'^^`    ^I-",
  "                                                              \"\"\"l~>,'   .\"i'                 !,`'^^`.   ^I+",
  "                                                             ^,\"I<<;'    `II                  !,`'^^`.   `;~^",
  "                                                            `,\";><I`    ':i                   !,`'^^`.   `:<`",
  "                                                            :\":i~!\".   .\"i'                   !,`'`^`.   `:>,",
  "                                                           \":^:ii,.    ^lI                    !,`'`^`.   ',ii",
  "                                                           :,`'``.    `,;.                   `\":`''''    ',:`...",
  "                                                          ,,_+>i;,,\",:!lllII:.,             ,\"l[_>il,,\"\",;!!!!!!;..:",
  "                                                         ,,^~----------------+,;            I^\"i-----------------^.;'",
  "                                                         ',.;--------------<il:cCCCCCCCCCCCCl^.'+-------------+ii. I`",
  "                                                          \"'                 ''              \"                    `\"",
  "                                                                                              .",
  "",
  "",
  "",
];
