/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `fists_up` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "                                                  rfrf()v;                                                    00z)?_-(|",
  "                                                  z|(}-)j|                                                   .OkhQ\\}1(:",
  "                                                  u/}]/JXz;                                                  YkodJn/{'",
  "                                                   <)zdwCXv;                                                [dah0vt|i",
  "                                                    \"zYCLJzv;                                              .dhowYr|(",
  "                                                     >cYLLJzv;                                             YbobLut|i",
  "                                                      }zULLUzv>                                           \\daaZXj|(",
  "                                                       |zULLUzv[                                         IdhopJn/|i",
  "                                                        jXJLLUzv}                     '                 `Obok0zj|(",
  "                                                        ^vXJLLUzv),                   X^  )  't        ,xdaowUn/|i",
  "                                                         IcYJLLUzv(:                  J} \\x  Q]   r   '1dhobLcf(\\l",
  "                                                          \\zYCQLUcn?!                 CX d\\ td  ^m+  .lUphhZYx\\|{:",
  "                                                          ;tzYCCzxt{:l              I Ww?@1]$\\ }%1   I;vLLCXnt(\\_",
  "                                                           lrvur/)|i`:l             hi&km8f8qi0B\\   l;;]nxjt(1(?;",
  "                                                            !]1}[}i''`,i.         Z,zpM*Woh%Y&%r  [:I:l>~-}[[]i~.",
  "                                                            ^:`''`^`''`:>         |h0W*W8d$m8&c[Xo{l:I>>;^' .^l>",
  "                                                             I,`''`^`.',il       '}ao$%%8#W&WJ&%z:;I,;!l\"'. ',<:",
  "                                                              I\"`'''. ',>!       U@%&#%&BWooq$mU(0(I\"^``'. .^I-",
  "                                                              >;^..   ':+^      U%$$$$$$$@%WMhh$dv~l\"'..   .\"ii",
  "                                                             '!I\".    ^l_^     \\W$$Wa*&%@$$$$$bur+il,'     ';~i",
  "                                                             .l,,^'  .\":~^    q$m{+jvcXUJLQOpmcjQ/!:,^    .\"I>i",
  "                                                             ;l,,;,`'.`:~^    8$X\"  ;)zv//tfjrrxi;l:,:;`...`:>>",
  "                                                             lI,,;,`..`;~\"    %$LJ(\"  ?dj>il  ,@YlI,,;:\"'..`:>>",
  "                                                             <;,:;,`..`;+\"    @8z.   ]Jw>  lI}hdn>;,,;:\"'..`:<<",
  "                                                             i:,::\"`..`;+\"    $oX\\;__0mL{   +$@U{i;,,;:^'..`;<<",
  "                                                            '!:,::\"`..^;+\"    $COv|XOQY/v<I ]$ht^!:,:;,^'..^;~!",
  "                                                            ,l:,::\"'..^I_\",I' ocz/}uUj1)tf/(Z$J:;l:,:;,^'..^;~^",
  "                                                            ;l,,::^'..^I+<+<\";Yt|][x'   -|)1*#t iI,,:;,`'..^I~^",
  "                                                            iI,,::^'..^Ii_1!,\":?_+t<     }{)$CI!>;,,:;\"`'.'^I+^",
  "                                                            >;,,;:^'..\"!-{l,,:,,}/t~>i\" l{1|{!\"Ii;,,;:\"`..'\"I+^",
  "                                                            i;,,;,^'..,\"'``^\",,`-f1{\\\\}-1)1i^'.I!:,,;:\"`..'\"I_\"",
  "                                                           .!:,:;,`'.'\"l> ''``^^rqLr}}[[[+\"..`.Il:,:;:^'..'\"l_\"",
  "                                                           Il:,:;,`'.'\"l?    '':0pbpLcj\\}.`.   <I,,:;:^'..'\"l-\"",
  "                                                           ;l,,:,\"`'.'^\"; ,''',+wqdmJut\\~:''':`>I,,:;,^'..',l-\"",
  "                                                           <I,`::^^^^^^^^^~;><<iJJUznf|/i<<>;?;i;,,:;,^'..`,!-,",
  "                                                           >;,' !:,;IIIIIl~;;I\"\"]jt\\){)-;l;`;?>!:,,;;,`'..`,!?",
  "                                                          'i;,, Ixx~~Lr+(0(IcL<\"~\\1(/fn>;{w)Iv/l:,,::\"`'..`,!?",
  "                                                          'i;\"` '1]>;}?l<]-l??,,+{]nUr'`;>?~l1+l:^```''. .`:i]",
  "                                                           !;^'  I:^^^\"^^^;!:;^,+}XOCn .;I^^ilI!:^'...   .`:<+",
  "                                                            :\"'  \";\"`^\"^^^Ii:;^,_8Wj/0 .;I^\"<i^I:^'      .^l<",
  "                                                             `'   I,^^\"^^^\">;;^,-*af\\L:';I^\"+:^^:\"'      ':!",
  "                                                                  ::^^^\"^^`~;;^:?dp/|Ui';I`,-^^`''`.    '`.",
  "                                                                  .;\"`^\"^^`<;;^:]Z0\\(X! ;I`:-^^`..'\"I>",
  "                                                                   ;,^^\"^^`!I;^:[CJ()vl II`I~^^'..',>i",
  "                                                                   ^:^^^\"^`il;^;[YX)1xI II^l-^`'..^;+^",
  "                                                                    ;\"`^\"^`:!;\";)cv1{j; I:^ii^`..'\"l?",
  "                                                                    ,,^^\"^`;i:\";)nx{}/: I:\">>\"'..',>i",
  "                                                                    .:^^^\"`,>;\"I1jf1{(, I:\"+!^'..^;+^",
  "                                                                     ,\"`^\"`.<;\"ItOCvnr[ I:,-,^..'\"l?",
  "                                                                     `,^^\"^.+;\"lu&WWMMY ;,:[,`..',>i",
  "                                                                      :^^^^.!I\"!uMMWW&U \",;~,`..^;+^",
  "                                                                      \"\"`^^.il,<ukkkkhc ,,l_,'.'\"l?",
  "                                                                      ',^^\".;!:_vkkkkkv ::!<,..`,>i",
  "                                                                       :^^^.:i;]Ckkkkkv ;;>i,..^;+^",
  "                                                                       '\"`^',>l]Lkkkkkv lI~!\".'\"l?",
  "                                                                        ,^^'.<i]XOOOOOu I!-\"\".`,>i",
  "                                                                        ^^^`.+<[tjjjjjj Ii]\"`.^;+^",
  "                                                                       `.\"``.!_+-~~~~~~ `<~\"''\"l?",
  "                                                                       ^ ,^`.i?_\"       .~_\"'`,>i",
  "                                                                       . '^^.l-_\"       .<>\".^;+^",
  "                                                                        : \"`.I_-        .>i\"'\"l?",
  "                                                                        , `^';+-        .il^`,>i",
  "                                                                        . .^'\"l?        ';\"^^;+^",
  "                                                                         ; \"`\"l?        ';\"`\"l?",
  "                                                                         ; .`\"!]        ';\"^,>i",
  "                                                                         .^ ^\"!]         I\"^;+^",
  "                                                                          i ^,!]         ;,\":I",
  "                                                                         ^i  ,![      .:::::,,\",,",
  "                                                                       ;;Ii: 'i~;,   ,lIliil;,\",;!.",
  "                                                                      il!+i:  .!\";^ ,ili+]?~l,\"\":l<",
  "                                                                     >!ll,l:::::::+t~!li+?-<I,^\",I>!",
  "                                                                     ~!l;_(+/C|]CUpp<!IIli!;,\"^^,;i-",
  "                                                                    '<l!:^^']f{+jcUr<l;:,:::,\"^^\":!+",
  "                                                                    '>lI;.       '~[~!;:,:::,\"^^^:l<I",
  "                                                                    IilIlI`     .`' :>I:,,::,\"^^^,I>>",
  "                                                                    !iIIll;,^``\"I<l  <!;:,:::,\"^^\";!_",
  "                                                                    ~!II!l;\"^`^,l_\"  IiI:,:::,\"^^\":l~`",
  "                                                                    <!Il!l:\"^`^:!]    <l;,,:::\"^^^,I>!",
  "                                                                   '<lIl!I:\"``\";>i    !!I:,:::,\"^^\";i+",
  "                                                                   ^>lIl!I,^``,I+^    ^>l:,,::,\"^^\":!+",
  "                                                                   IiII!l;,^`^,!?      i!;:,:::\"^^^,l<,",
  "                                                                   !!II!l:\"^`^:>~      ,iI:,:::,\"^^,;>!",
  "                                                                   ~!Il!I:\"``\"I~:       <l;,,::,\"^^\":!-",
  "                                                                   <lIl!I,^``,l_        IiI:,:::,^^^:l~^",
  "                                                                  '>lIl!;,^`^:i-         >l:,:::,\"^^,I>I",
  "                                                                  ^iII!l;\"^`\";<l         l!;:,::,\"^^\";i>",
  "                                                                  IiIl!l:\"``\"I+.         ^>I:,:::,^^^:!_",
  "                                                                  !!Il!I,^`^,!+           il;,,::,\"^^,I<`",
  "                                                                  ~!Il!I,^`^:>>           ,iI:,::,\"^^\";>!",
  "                                                                  <lIll;\"^`\"I~^            <l:,:::,^^\":!~",
  "                                                                 '>lI!l:\"``,l?             ;!;:,::,\"^^,l+.",
  "                                                                 ^iIll;,^`^:ii              >I:,:::,,\",I<,",
  "                                                                 I!I:::,\",\";<^              l!IIII!l:,\":il",
  "                                                                 !!l><!:\",li_               ^ii!!+]+l,\",l_",
  "                                                                 <li-]>:\"\"I+~                >>l!~_<I\"^,I~^",
  "                                                                 >ll>i;\"^\";~:                :>I;;I;,^^\";<`",
  "                                                                ,il!iI,^`^;+.                 <l::;:,^^\";>i",
  "                                                                l!li!;\"``,!<                  !!;::;,\"^^:i!",
  "                                                                >llil,^`^;~                   :i;::;:\"^^,!+",
  "                                                               ^il!iI\"^`\"l+                    >I::;:\"^^,l_",
  "                                                               ;!li!:\"`^:<:                    ~l::;:,^^\"I+",
  "                                                               <llil,^`\"I~                     I!;:;:,^^\"I~^",
  "                                                              'il!i;\"``,il                     'iI::;,\"^^;>`",
  "                                                              ;!li!:^`^;_                       <I::;:\"^^:iI",
  "                                                              illiI,^`,!;                       !l::;:\"^^,!!",
  "                                                              >;;;\"^`^:+                        ^i;,^`  .`I>",
  "                                                             ^`...  `,l<                         >,``^`.  'l",
  "                                                            `^,ii\". ':<                          l\"\">-<,. .\"I",
  "                                                           ':\"![?;' .,>                         ';\":+[~,. .\"l:",
  "                                                           ;,^:l:`  .,>`                        :;^`,:\"'   ^I<",
  "                                                          ';^\";;^   .,<^                        \";^''``.   `;<",
  "                                                          :,^:I,'   `;_                          I^''``.   ',iI",
  "                                                          ;\"\";;\".   ^l!                         .I\"''``'   .\"li",
  "                                                         :,^,I:`   .,>`                          l,`''`'    ^;+",
  "                                                         I\"^:I,'   ';+                           !,`''`'.   `:>,",
  "                                                        ^:^\";;^.   ^l>                           i:`''``.   ',!l",
  "                                                        l\"^:I:'   .\"iI                           ,:^''``'   .^I_",
  "                                                        ;\"^,;\".   ':~.                           :;^''``'    `;~`",
  "                                                       `:;'..     ^;\"....                        ^:I'...     `:\"'''..",
  "                                                      :\"<]--iiiiii<~~~~<<;`:                    :\"<}_iiiiiiii<~~~>ii; `;",
  "                                                      ;`;-----------------I<                    :`\"<----------------- 'i",
  "                                                      ;` liiiiiiiiiiiiii:\"^,                    ;` ,<---<iiiiiiiiiii\" `i",
  "                                                       `                 }XUUUUUUUUUUUUUUUUUUUUU\\`                    ^",
  "",
  "",
  "",
  "",
  "",
];
