/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `fists_up` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "                                                  JXzYLmM?                                                    8cj0qdppa",
  "                                                  kCLZpQOa                                                   `a)<)CZZW?",
  "                                                  apZwJ\\x#?                                                  mv!_\\uZa!",
  "                                                  `n*Z+]\\nM?                                                |Zi<1xY#|",
  "                                                    !#x|(\\ub?                                              `*?i]tcZa",
  "                                                     |dt|(/jb?                                             mj!+(nU#|",
  "                                                      Jmt|(/jb|                                           nZi>}jzZa",
  "                                                       mJ/((/jbJ                                         ?*]!-\\uU#|",
  "                                                       `az/((/jbm!                    `                'Y8|!<1rX0a",
  "                                                        !#n\\((/jb&c                   J!  |  `n        c&C>i]tvJh|",
  "                                                         ?af\\(|tjbWc                  Jn |J  Jn   n   1M*<!+(xX0&(",
  "                                                          Mdt\\(|trkWw.                Ja mJ |8` `m|  +*&x<<}fcJh*?",
  "                                                          L&Jt||jcZ8Wq.             ! 8o|8J?8m ?8J  'pW8z(|fuY0&d",
  "                                                          'd8CncUOWB%WqI            8?8zaqmmp|J8m   qMM#MXzUQmW#|",
  "                                                           _M8#o*8%B@%&o+         a!J88[8r8j8aQa` ?c#W*h*8#*M8Wk:",
  "                                                            jW%BB%%BB@%Wh.        n8aX8:nt\\va(*|n80*W#aaM%@$@%*X",
  "                                                             p&BBB%%B@B&a(       `|8X/_`\"_:r:k8oa?v#&Mo#8B@$B&h]",
  "                                                             '#8BBBB@$@&a)       JCCLaJJ}(_!\\)n8|Jq#&%%BB@$@%#p",
  "                                                              aM%@$$$$@Wb>      J8`    ,[}CLqk8Joak#8B@@$$$@&aj",
  "                                                             ~oM8@$$$$%*d>     |8m :>!,`'     }8J1a*&B$$$$$BMkr",
  "                                                             +*&&8@$$@8Wk>    mnYbbLXrft\\|){-}v8a0oW&%$$$$@&#aj",
  "                                                             u#&&W&%@@BWk>    8 n$$$$*0Z*kkbZLq8|u*&&WW%@@@BWaj",
  "                                                             JM&&W&%@@BWb>    8 QJQ8$$q_zhaW$$$vaJ#&&WW8B@@BWhf",
  "                                                             hM&&W&B@@%Mb>    8^#$$$$w\\[h$$*#$/[#hM&&MW8B@@%Whf",
  "                                                            .aW&WW8B@@%Mbi    8+uJMdd1[(O$$$b8.QdoM&&MW%B@@%Wkf",
  "                                                            +oW&WW8B@@%Mdi '  8\\1nCf{)fUxhM$&m{a{*W&WM&%B@@%Mk)",
  "                                                            /*&&WW8B@@%MdicMr'bxjUZn/X00UYJLhcd?u*W&WM&%@@@%Mk<",
  "                                                            v#&&WW8B@@%#bhbh8WhYLwmv@$$$pL00#qW.m#&&WM&%@@@%Mb>",
  "                                                            m#&&WW%B@@%#od0o&&WqdbUh$$$$$ZOQ8o&waM&&WW&B@@@8#b>",
  "                                                            hM&&WW%B@@8*pO*&&W&&MmUkaa8$#ZmW&88#oM&&MW8B@@@8#b>",
  "                                                           ;aW&&W&%@@@&8BB%88&&%bb#dJJmp0b88%B@#*W&&MW8B@@@8#d>",
  "                                                           +oW&WW&%@@@8#hCBBB%%%z?rZ8o**8%B@@BJC*W&WMW8B@@B8#d>",
  "                                                           u*W&WW&%@@@8*q  ]CBBW1-~-(xXCZ@%J?  h#&&WMW%B@@B&*pi",
  "                                                           v#&&W&8BB@B%8MCzYYY&b[?_[/uYJkWYYYvYaM&&WM&%B@@B&*pi",
  "                                                           h#&BWW%%%%%%%%%kMahho\\/tjuYCUahhaWqMoM&&WM&%B@@B&*pi",
  "                                                          .aM&@$*W&MM#####bMM#88wXYC0ZQpM#M%Wqa*W&&WW&%@@@B&oq",
  "                                                          ~oM&&$#vcbk(cbQ1L#x(k8kJOQUXuaMO]Q#nU*W&&WW8%@@@B&oq",
  "                                                          ~aW8%$B0whMZq*hwp#qq&&bOwutc@%Maqk*0b*W8%%BB@@$@%Wow",
  "                                                           wM8B$$#W%%88%%%M*WM%&bZf{\\v$@M#8%o*#*W%B@@@$$$$%Whc",
  "                                                           'd8B$$8M8%%8%%%#oWM%&d\":zU1$@M#%8ho%#W%@$$$$$$@8#O.",
  "                                                            'ZB$$$#&%%88%%8aWM%&p!iXJ(W@M#%&bW%%&8@$$$$$$BWw.",
  "                                                              `\\Q$WW%%88%%%kMM%Wq_-UC/o@M#%&p%%%@BB@$$$$@m)",
  "                                                                 z@M8%%8%%%hMM%Ww}1CLjo$M#%Wp%%B@$@8#a[i",
  "                                                                 >$W&%%88%%o#M%Ww|\\LQx*$M#%Mb8%B@$B&aj",
  "                                                                  b%W%%88%Ba#W%WmtjQ0v#$M#%*p8%@@@%Mb>",
  "                                                                  t$M8%%8%BW*W8MQxn0OXM$#W%oo8B@$@8*q",
  "                                                                   $&&%%88BWoW8M0vcOZJW$#W8ha8B@$B&aj",
  "                                                                   0@W%%88B&aW8#0XY0OQ&$#W8bo8@@@%Mb>",
  "                                                                   >$&8%%8%@kM8#phkqpd#$#&&p&%@$@8*q",
  "                                                                    &%&%%8%@bM8#n,(|||b$M&Wm&%@$B&aj",
  "                                                                    t$W%%8%@*#8on;;::,/$8&Mk&B@@%Mb>",
  "                                                                    ^$88%%%@o#&hu~~~<<x$&&#d&B$@8*q",
  "                                                                     0@&%%8@M*Wdx~~~~~n$WWoh&@$B&aj",
  "                                                                     ]$W%%8@WoMw|~~~~~n$MMha&@@%Mb>",
  "                                                                      $B8%%B&a#w|~~~~~n$*#k*8$@8*q",
  "                                                                      J$&%%B@howj11111n$#*p88$B&aj",
  "                                                                      -$%%%B@bhmUzzzzzz$#aw8%@%Mb>",
  "                                                                       B@8%B@opbCJJJJJJ$Bhk8B@8*q",
  "                                                                       X$&%B@aqd>      $@kd8BB&aj",
  "                                                                       +$@%%@#pd>      $@hh8@%Mb>",
  "                                                                        W$8%@#dp       $@ao8@8*q",
  "                                                                        c$%%BMdp       $@a*%B&aj",
  "                                                                        +$$%B8*q       $@M8%%Mb>",
  "                                                                         M$8B8*q       b@M8%8*q",
  "                                                                         v$@%8*w       0@M&%&aj",
  "                                                                         +%$%&*w       0$M&%Mb>",
  "                                                                          o$%&ow       0$M&&W#?`",
  "                                                                        (Zo$$&oml     )bWWWW&&8&0'",
  "                                                                      _dM#oW$@okMc   c##*aa*M&8&Mo+",
  "                                                                     Io*oboW$$@*8MX]co*obwqk#&88W*k;",
  "                                                                     Zo**&#WWWWWWW88ko*obqph#&88&#hx",
  "                                                                     k**MpQbJ|Lw|dpfh*##*o*M&8%%&Map",
  "                                                                    ~h**W%%BwXObzapzh*MW&WWW&8%%8W*b:",
  "                                                                    ~a*#M@$$$$$$$$@WkoMW&WWW&8%%8W#h|",
  "                                                                    na##*M%$$$$$@Bo0Qa#W&&WW&&8%%&MaX",
  "                                                                    Uo##**M&8%%8Mk( .k*MW&WWW&8%%8Mod",
  "                                                                    bo##**M&%%%&#d>  uo#W&&WW&8%%8W*k<",
  "                                                                   .k*##*#W8%B%Wow   Ih*M&&WWW&8%%&#hr",
  "                                                                   ~h*#**#W8%%8Mhj    JoMW&WWW&8%%8Mo0",
  "                                                                   }a##**M&8%%&#b>    }a#W&&WW&8%%8W*b.",
  "                                                                   na##**M&%B%&*q      m*MW&WWW&8%%&#k]",
  "                                                                   Uo##**W8%B8Waz      /a#W&WWW&8%%&Max",
  "                                                                   k*##*#W8%%8Mk]      .h*M&&WW&8%%8Wop",
  "                                                                  .h*#**#&8%%&*p        uoMW&WWW&8%8&*b<",
  "                                                                  ~h##**M&%B%WoL        Ih#W&&WW&8%%&#h|",
  "                                                                  }a##**W8%B8Mh(         JoMW&WW&8%%8MoY",
  "                                                                  uo##*#W8%%8#d:         }a#W&WWW&8%8W*d",
  "                                                                  Jo##*#&8%%&*Q           m*M&&WW&8%%&#k<",
  "                                                                  k*#**M&%B%Waj           /oMW&WW&8%%8Mar",
  "                                                                 .h*#**M8%%8Mb>           .h*W&WWW&8%8Wo0",
  "                                                                 ~a##**W8%%&*q             uoM&&WW&8%%&#b:",
  "                                                                 }a##*M&8%%Wor             Ia#W&WWW&&8&Mh[",
  "                                                                 uoMWWW&8&8Mk<              J*M###*#W&8Wox",
  "                                                                 J*#ak*W8&*od               }aa**bwd*&8&*d",
  "                                                                 k*opwhW88#bz                Zh**kdhM8%&#k<",
  "                                                                ;a#*aoM8%8Mk?                \\a#WMMW&%%8Mh<",
  "                                                                /o#oo#&%B8Mb:                .h#WWWW&8%8Mar",
  "                                                                J*#ooM8%%&oz                  J*MWWW&8%%Wox",
  "                                                               .h**o*&%B%Wk:                  /oMWWMW8%%&*Q",
  "                                                               }o#ooM8%B8*Q                   ;h#WWMW8%%&*p",
  "                                                               u*#o*W8%%Wh]                    k*WWWW&%%8#b",
  "                                                               h**o#&%B8#0                     uoMWWW&8%8Mk>",
  "                                                              ~a#ooM8%%&a(                     ~aMWWW&8%8Mh<",
  "                                                              u*#o*W%B%Md                       h#WWMW8%%Wa|",
  "                                                              m**o#&%B&o|                       J*WWMW8%%&ox",
  "                                                             IaMWM&%%%Wb.                       }oM&%B$$@B#Y",
  "                                                             X%@@@$$%&*z                        ;a&BB%%@$$B#'",
  "                                                            Y%&oo&@$BWh:                         *88aph&@$@8q.",
  "                                                           1W8omqM@$@&h.                        1M8Wbmk&@$@8*\\",
  "                                                           p&8W*WB$$@&a<                        cW%%&W8@$$$%#O",
  "                                                          1M88MM%$$$@&h>                        fM%@@BB@$$$BWk:",
  "                                                          Q&%&M&B$$$BMd                         _M8B@BB@$$$B&a|",
  "                                                         lM88MM8@$$$%*x                         +#8B@BB@$$$@8*Y",
  "                                                         Q&%&MWB$$$@&a<                         .*&B@BBB$$$$%Mb.",
  "                                                        I#88WM&@$$$BWb                           o&B@BBB@$$$BWa]",
  "                                                        jW%&MM%$$$$%#X                           aW%@BBB@$$$@&ox",
  "                                                       '#8%W#WB$$$@8a(                           cW%@@BB@$$$@8#d",
  "                                                       _M8%&W8@$$$BWk:                           cM%B@BB@$$$$%Mkr[i",
  "                                                      -aWM@@@$$$$$%W8@@@@p|                     ?%W#B@@@$$$$$%W8B@@@@$n'",
  "                                                      b8kwppaooooahkkkkkhM%v                   lW8kZdaaaooooahkkkhaaM$%L",
  "                                                     .M%MpppppppppppppppppMh                   _W%8kppppppppppppppppp$Ba",
  "                                                      dB$#ooooooooooooooW8%t                   IWB$&hppphooooooooooo8$%m",
  "                                                      'a$$$$$$$$$$$$$$$$$Q|                     Y%$$$$$$$$$$$$$$$$$$$$O'",
  "                                                        [zOOX11111+            .........         ~d$$$$$$OOOOOOf}}}}[",
  "                                                               ...''''``````^^^^^^^^^^^^^^^``````''''...",
  "                                                            ...'''````^^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^^^^````'''...",
  "                                                               ....''''``````^^^^^^^^^^^^^``````'''''...",
  "",
];
