/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `fist_up` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "                                                                                                         XkCvct}[+",
  "                                                                                                         OZU){?_)?",
  "                                                                                                        ~kokz({{|+",
  "                                                                                                       ~bo*wYr)[l",
  "                                                                                                      .da#pUx|/",
  "                                                                                                     .Oa#bCu/(!",
  "                                                                                                     0h#h0cf(}",
  "                                                                                                    nk#oZXj(\\",
  "                                                                                                   ub**qUx\\(!",
  "                                                                                       !         \"\\bo#dCut(}",
  "                                                                               m  'f  \\t   j    ,1ba#kQcf(\\",
  "                                                                               Y} ?X  *I  Q{   ,?dh#aZXr|()",
  "                                                                               zw UZ /a: OL   ,IfmpbmUn/(\\_",
  "                                                                               {#]wq!$L 0oi  'I;)JUYcx/(\\-",
  "                                                                             1j+&LBpZ@c0Bj `-I:!~|f/|1}(_>",
  "                                                                           ^. aCWb&d8aq$J:zwI:l~~lI><<~I~",
  "                                                                            Z/L*oM&b$q$qQ&w~;;>~!,'. .\"!;",
  "                                                                            !ka&&B@#%Mom@Jr>;\",:\"`. .`;_",
  "                                                                            O8&@@B%88#h&Z$%<;^''..  ',>i",
  "                                                                           Y8$$$$$$$$$$$@Wz~I^'     `I_]",
  "                                                                          IMB$@#&8%BBBB@*Xr~I\".    .,l!_",
  "                                                                         ]&8#xfzzzXXXYYYUzr_I\"^'. .``^;+^",
  "                                                                         U$o/   <rcuxrj\\)?/|I,\"\",^'..`;<l",
  "                                                                         X$buCr[  !Qu>:    <I,\"\",\"`..`:>i",
  "                                                                         f$dYZ?   /J/' l[O#1I,\"\",\"`'.',!]",
  "                                                                         -$qcu,  IJCX.   jd}I,\"\",\"`'.'\"l-",
  "                                                                         _$mXCx/0LJz/t+;1WL]l,\"\",\"`'.'\"I+^",
  "                                                                       `..@0UJt{UXcn/\\\\(d%n;l,\"\",\"`'..^;<!",
  "                                                                      ,<\",BYrt{[v?. '+1)ka}<l,\"\",\"^'..`:>i",
  "                                                                     ,<{;,>11[+()     ](Cv;il,\"\",,^'..`:i[",
  "                                                                    ,<{<:::I??[\\| !l .t\\{,\"il:\"\",,^'..`,!-",
  "                                                                   ,l<I\",,,,,(1{}(j)][1\\>`.!l:\"\",,^`..'\"l_^",
  "                                                                     '''`^^^^vUr[[}}[}-;.`'!!:\"\",,^`'.'\"I~!",
  "                                                                         ''',mwpwCvj\\_'`.  I!:\"\",,\"`'.'^;<i",
  "                                                            `^``'`'       .^,mwpmJuf\\+::::i_!:\"\",,\"`'..^:i[",
  "                                                          :,:^^````````~;!!iILCCYvj\\/+~+~:_i!:\"\"\",\"`'..`:!?",
  "                                                         I:,^I\"^\"\"\"\",,:>Il<!^}xjt({)1;;;^,-<!:\"\"\",\"`'..`,l_\"",
  "                                                        I:Ii ;;\":ii]><(}liri^!(1}{\\X+;-Zxlrj!:\"^\"\"^`'..',l_^",
  "                                                       ;:;<-: jwf\"CY[]Qj<(x[^!){}0r? I;_i:[>i;\"`''...  ',!-.",
  "                                                      ;:;>--! i_I`,l\"\",,<:;\"^![-YQX_ I;:`;?^i;\"'..     `:>i",
  "                                                     ::;>-->: ^I\"``^^^^^<;;,^lj8M-wf \";:^;<^\"I\"'       ^I<",
  "                                                    \";;i-->:`  I,^`^^^^^iI:,^ln*h-c/ \";:^I~^^^^`      `;\"",
  "                                                   `;:i_-<:`'. `;\"`^^^^^l!::^Irdq-uU ^;:^I+^^`..''``",
  "                                                   ;:!_-<;^'.   ;,^`^^^^:i::^ItZ0[xz .;:^l_^^'..`:>>",
  "                                                  I:!_-<;^'. .` `:^`^^^^`~;;^I\\LJ(jv .;:^!-^^'..^;+^",
  "                                                 I:l+?<;^'. .`:I :\"``^^^`>I:^I|YX)txI ;:^!!^`'..\"l-",
  "                                                ;:l+?~;^'. .`:>' ':^`^^^`ll:^;)cv1)j; I,^ii^`..',!-",
  "                                               ;:I~?~;^'. .`:<'   ;\"`^^^`:!:\";1nx(}/! I,\">i\"'..`:>>",
  "                                              ^:I~?~;^'. .`;~`    ^,^`^^`^>:\";[jf|}(~ ,;\"<>\"'..^;+^",
  "                                             \";;<?~I^'. .^;i       :^`^^^'<;,:[zcvnr[ \";\"~<^'..\"l-",
  "                                            `;;<-+I^'. .^I>        `,^`^^'!I,:]&WWWMb ,:,+I^..',i-",
  "                                            :\",;;;^'  .^I<          :^`^^'Il,:[&&&&&8 .:,_,^..`:<>",
  "                                           :\":,^'^:^ .\"lI           `\"``^':i,;[kkhhhh ';,-,^..^;+^",
  "                                         .I:<[+:``,>^\"lI             ,^`^`.<:l{kkkkkk!.l;?,^.'\"l-",
  "                                         :;:>+i\"''\"!>!l              '\"`^`.i;!{kkkkkk_ i;[\"`.',i-",
  "                                         l;\"^\"^`'.^I+\"                ,^`^.il>[kkkkkk_ ~I?\"`.`:<>",
  "                                         `I\"``^^'.',>                 \"^`^.:!<}wmmZZOf >l<\"'.^;+^",
  "                                          I;^`^~]\\+Il:                 \"``'^>+_unnxrr[ Ii~\"''\"l?",
  "                                           !,`vh*dQX{>                 ^^`'.~?_))~~~~I :<+\"'',i~",
  "                                           `I(p*&bCcx_                ` \"``.i?_\"       `~_\".`:<l",
  "                                            It00OQUvn):               ^ ^^`.l_+\"       .>~\".^;+^",
  "                                             ~UCQ0Czuri                \" ^`'I-+^       'i!\"'\"l?",
  "                                             `|JL0QUvx?                ; ``'^<+^        Il^',i~",
  "                                              'cCQ0Czu\\                 ^ ^`^!~^        I,^`:<l",
  "                                               lJC0QYvx:                l ^`^;~^        l,^^I+^",
  "                                                jCL0Czn1                `  ^^;~^        \",^\"l?",
  "                                                 JCQQYvr`                l ^^;~^        ,:^,i~",
  "                                                 [JL0Ccn+                \"  ^;<:        ,:,,\";",
  "                                                  vCQQYur                `I ^:<>      `;;;;:,,\",:",
  "                                                  +JL0Ccr!             `;;i  :<_:    llI!<<!;,\",;!.",
  "                                                   fUYvvcxI           lll>+:  :_;!. ;ili_[]~l,\"\":l<",
  "                                                   -0hqLcxr`         ,ilil;```^^^\"~}<!l!~-_>;,^^,I>!",
  "                                                   1QYCQx|(;         ~!l;~)_[\\{}tXpq<!I;IlI;,\"^^,;i?",
  "                                                    trxxf(-          ~!l:Ii:jQj-JXJx<l;:::::,\"^^\";!_",
  "                                                     \"(\\)]>          ~!I;.   ,' ^,?)+!I:,:::,\"^^\":l~`",
  "                                                       :;:           ~!I;^       '^ :>I:::::,\"^^^,l<i",
  "                                                                     ~!I;II;,^`^,l_\" <l;:::::\"^^^,I><",
  "                                                                     +!I;II:,^`^:!-  >!I:::::,\"^^\";i-",
  "                                                                     +!I;II:\"^`^:!-  :>I:::::,\"^^\":!_.",
  "                                                                     +!I;II:\"^`^:!?   <l;::::,\"^^^:l~`",
  "                                                                     <!I;II:\"^`^:i_   !iI:::::,^^^,I<i",
  "                                                                     ;!I;II:\"^`\";i!   ^>l:::::,\"^^\";><",
  "                                                                     IiI;II:\"^`\";>i    <!;::::,\"^^\";!-",
  "                                                                     IiI;II:\"^`\";<>    !iI:::::\"^^^:l+.",
  "                                                                     IiI;II:\"^`\";<:    '>l:::::,\"^^,l~`",
  "                                                                     IiI;II:\"^`\"I~^     ~!;::::,\"^^,I>i",
  "                                                                     IiI;II:\"^`\"I+^     IiI::::,\"^^\";i>",
  "                                                                     IiI;II:\"^`,l_.     '>l:::::\"^^^:!-",
  "                                                                     liI;II:\"^^,l_       ~!;::::,\"^^,l+.",
  "                                                                     :iI;II:\"^^,l-       ,iI::::,\"^^,I<`",
  "                                                                     'iI;II:\"^^,!]        >l:::::\"^^\";>!",
  "                                                                     '>I;II:\"`^:!<        >!;::::,^^\":i>",
  "                                                                     '>I;II:\"`^:i!        :iI::::,,\"\":!_",
  "                                                                     '>I;;;,\"^^:ii         <lIIIll;,\",l~^",
  "                                                                     '>l;;;:,\":I>l         liil<?-i:\",;<,",
  "                                                                     '<!!+-i:\",l+`         ^~!l<-+!,^\";i!",
  "                                                                     '>li__i,^\"I+^          ~!;;I;,\"^^:i!",
  "                                                                     ^ili>l,^`\";~\"          !!;:;;,\"^^:!_",
  "                                                                     i!l>i;\"``\"I~           :i;:;;:\"^^,!?",
  "                                                                     >l!>l,^`^:>,           '>I:;;:\"^^,l-",
  "                                                                    ;!lii;\"``\"l~             <l::;:\"^^,l_",
  "                                                                    <l!>!:^`^:<:             >l;:;:,^^\"I+",
  "                                                                   ^iliiI\"``\"l+              I!;:;;,^^\"I+.",
  "                                                                   ll!>!:^`^:<               ^i;:;;,^^\"I~^",
  "                                                                   >li>I,^`\"l<                >I:;;,\"^\";<^",
  "                                                                  ,!l>i:^`^:~                 <l::;:\"^^;<`",
  "                                                                  !l!>l,^`\"!<                 !l;,``'.',>`",
  "                                                                  :`. .``^:+                  ,l^'``'  .,:",
  "                                                                 ^`,\"'  ^;!;                  ',^;~~;' .^I.",
  "                                                                ,\"i[_:. ':+                   ;\"\">}?l`  `;>",
  "                                                               ;\"\"!+i^  ':~                  .I\"`,I:`   `:~",
  "                                                              ':^,l;`   ':~.                 .l\"''``'   ',>,",
  "                                                              I\"\";l,'   `I~                   l\"`'``'   .\"!!",
  "                                                             `:^:l;^   .\"i,                   !,`'``'   .^l~",
  "                                                             I\"\";l,'   ':~                    !,`'``'.   ^;+",
  "                                                            \",^:lI^.   ^l>                    i,`'```.   `:<`",
  "                                                            ;\"\";l:'   .,>`                    i:`''``.   ',ii",
  "                                                           :,^:lI^.   `;_                     l:^''``.   .\"!>",
  "                                                           I\"^;l:'   .\"!;                     ,:^''``'   .^I_",
  "                                                          ',\"''`'    ':;'                     ^:,''''.   .^;\"....",
  "                                                         '\"!?>ii,,\"\",I!lllII^``              ,,_[<iiil,\"\":!ii!!!!` \"",
  "                                                         I^I-----------------li             ,,^;-----------------i ^i",
  "                                                         ;^'<-------------+ii^?CCCCCCCCCCCCC/,' l------------+iii\" \"!",
  "                                                          \"                  `               ,'                    \"",
  "",
  "",
  "",
  "",
];
