/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `fist_up` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "                                                                                                         mJ|xxUmpn",
  "                                                                                                         8}/QZqddJ",
  "                                                                                                        ?o_~rQOO#n",
  "                                                                                                       ?*_l]fzbk|",
  "                                                                                                      `*-I-/c08`",
  "                                                                                                     `atI+|uJ#|",
  "                                                                                                     afI>1xYdm",
  "                                                                                                    Jvl!}jz0W`",
  "                                                                                                  !mOll?/vJo|",
  "                                                                                       !         z&Z!I_|nUqm",
  "                                                                               a  `n  |J   n    cW*iI<)rX0W`",
  "                                                                               Jn ?m  a?  Jn   cM*?I>{fcCoh",
  "                                                                               J8`J8 |8? Ja`  cM&Q-+[/uUp&L",
  "                                                                               |8nm8?88 J8|  1#WMhtfrvUOWa;",
  "                                                                             |J?qo8QaQ8Joa `r#W*kMkQC0dW#X",
  "                                                                           ```8aqnana(8Qd?nW#W*kk*8%%%%Wk.",
  "                                                                           `anaQ8;ct/zCu8a8oMWabo&B@$@8o|",
  "                                                                            ?8pc?''I`[ipcaJaM8&W&B@$@%Md",
  "                                                                            mCaJJJJu)\\j)wJXhM%B@@@$$B&ar",
  "                                                                           J8      ?]]]\\J08kM8@$$$$$B#dw",
  "                                                                          !8C .I,^^`''''lj8k#8@$$$$@&#*p",
  "                                                                         ?mwcvXrjjjffftttu8h#&%B@$$B%%Mb>",
  "                                                                         J]iB$$$@pOmqpd8%BB*#&8&&8B@@%Wh)",
  "                                                                         J[]8\\cm$$o)naW$$$$h#&88&8B@@BWar",
  "                                                                         nCfm}q$$$U/J@$*WqIw#&88&8B@@B&ow",
  "                                                                         ?Cvqn&$$#/|f@$$$0(o#&88&8B@@B8*p",
  "                                                                         ?CCx|cU1(/jJYdMBcdo#&88&8%@@@8#b>",
  "                                                                       j)`8Lt\\YOtfxuUJJLor&u#&88&8%B@@%Mk)",
  "                                                                      ch&k80cYOmnq@$Bb00ao&h*&88&8%B@@%War",
  "                                                                     chOM&8o0wdQQ$$$$$wOW88o*&88&&%B@@BWom",
  "                                                                    chOhWWW&ohmJC$o#$$Yp8&8o*W88&&%B@@B&*p",
  "                                                                   c#hM8&&&&%*#dmQXQwmwW%B@**W88&&%B@@B8#d>",
  "                                                                  `]CB@BB%8%%nnm88oo*M%B@Bmm*W88&&8B@@@8#k)",
  "                                                             `]]i     !uq@@B&[]-]|xzJd@ax' u*W88&&8B@@@%Mhj",
  "                                                          'na%%BBBm!   ???J%&[]-[\\nXJbWWWWod*W88&&8B@@@%Wam",
  "                                                         -W&&%%%BB%BB%%kM*oo#||\\txzJJbkbkWdaoW88&&8%@@@%Woq",
  "                                                        _#W&8#888888&&&aM*ho%mczULO00MMM%&pkoW888&8%B@@B&*d>",
  "                                                       l#WMa$MW8WoawhhLZ*aca%oL0ZOJfbMp}v*cXoW8%88%B@@@B&*d>",
  "                                                      'dWMhpW$X]X8|tmw)XhLvm%*0OZ1cq$MMdaWwhoW8BB@@@$$$B&*p,",
  "                                                     'dWMappo$ad#%&*88&&hWM8%*mpt(jd$#MW%Mq%oM8B@$$$$$$BWar",
  "                                                     QWMappaW$%M8%%8%%%%hMW&%*z\";p]Y$8MW%Mh%8M8B$$$$$$$%#O.",
  "                                                    zMWapphW%$$M&%%%8%%%a#W&%#ul>pxU$8WW%#k%%%8%$$$$$$BMf",
  "                                                   jMWodphW%@$$%M8%%8%%%#*WW%#z_?put$%WW%#b%%B@$BB%aQu?",
  "                                                  _MWodphW%@$$$$M&%%%8%%WaWW%#Y}1mcj$@WW%*d%%B@@BWhj",
  "                                                 _MW*dphM%@$$$B$BW8%%8%%BkMM%#J|\\Lzn$@MW%*p%%B@@%Mb>",
  "                                                '#W*bqkM%@$$@BW#$W8%%88%BaMW%MLtjQYv#$MW%oo%%@$@8#p",
  "                                               'dW#bqkM%@$$@BWa~bBW%%%8%B*#W%MQxn0QXM$M&8ao8B@$B&oL",
  "                                              'dW#bqkM%@$$@%Wh~ >$M8%%8%BWoW8M0vcLZU*$#&8aa8B@@BWhj",
  "                                              XW#kqkM%@$$@%Mk<   b%&%%%8%%hW8MmXYCZLk$&M8ha8B@@%Mb>",
  "                                             zWMkqbM%@$$@%Mm.    t$W8%%8%@hM&Wwmwqpd#$8M8kh8@$@8#p",
  "                                            jMMhpb#%@$$@%#Z.      &%&%%%%@o#&Ww((((z0$&W&bM8@$B&oL",
  "                                           _W8&MMM%@$$@%#O.       t$W%%%8@M*&Wm:,,,\"\"$@W&d&8@@BWhj",
  "                                          -W&W&%B%W%$@8#u          &B8%%8BWa&Mm<<<<<>$BM&p&8@@%Mb>",
  "                                         +#WkmbWBB&h%8*n           t$&%%%B@kW#Z~~~~~~*@#Wq&%$@8#p",
  "                                         vMWado8@B8oaox             $B8%%%@aMoO~~~~~~p$oMw&B$B&oC",
  "                                         CM8%88%@@%Mb}              v$&%%%@o#am~~~~~~p$k#q8B@BWhf",
  "                                         {#8%%%%B@B&h;              I$88%%@WokZ][[}}{X$a*k8B@%Mb>",
  "                                          CW%B%%%%B8*\\               q$8%%B%abduuvvczm$#ok8B@8*q",
  "                                          'o&%%p\\jca&Z               -$%%%B@bqdh8JJJJC$Whb8BB&oz",
  "                                           {#8b!,+\\xoo;               a$8%B@oqd>      $Bkd8@BWh(",
  "                                            L&01{)txZW\\               f$%%%@#dd>      $@ab8@%Mb>",
  "                                            '*8j(1|ju8u               .8$8%@#pb>      &@a*8@8*q",
  "                                             1WZ|))txqY                L$%%B%kb>      0$M*8B&oz",
  "                                              r8u(1|jza                I%$%B%ob>      0$#&8BWh(",
  "                                               ?h|))tno?                q$%B%Mk>      t$#&%%Mb>",
  "                                                mC(1\\rQm                {$$%%Mk<      }$8&%8*q",
  "                                                `#f))tnM!               .#$%%Mk<      }$&W%&oz",
  "                                                 nZ(1\\rZn                t$$%Wh]       $&W&&8dn!",
  "                                                 `af))tc8               'j#$%Whf      jMMMMW&&8&d_",
  "                                                  |h(1\\xk|            'jMMa$$&hddl  'q##ohhoM&8&W*+",
  "                                                   mYtxx0d?          .q#*abW$$WdWo+`uo*odmwk#&88W#h;",
  "                                                   |b<?(rYM!         to*o*WBB%%%88%Wko#obpdaM&88&#hx",
  "                                                   nqf\\(vCb?         ko*MkQdmJZZYhofh*MM#*#M&8%%&Maq",
  "                                                   `aYcvXLz          k**W#aWz(zp\\hZch*MWWWWW&8%%8Mod",
  "                                                     +vJ0wj          k*#W@$$$&@$%BB*hoMW&WWW&8%%8W*b<",
  "                                                      .\\u\\           k*MM8$$$$$$$@%qQa#W&WWW&8%%8&#hj",
  "                                                                     boMM##W&%%%&*d>;h*MWWWWW&8%%&MaX",
  "                                                                     boMM##W&%%%W*p  ZoMW&WWW&8%%8Mop",
  "                                                                     boMM##W&%%%Wop  /a#W&WWW&8%%8W*d:",
  "                                                                     boMM##W&%%8Woq  .h*MWWWW&8%%8W*k<",
  "                                                                     OoMM##W8%%8WoL   UoMW&WWW&8%%&#hr",
  "                                                                     uoMM##W8%%8War   }a#W&WWW&8%%8MaX",
  "                                                                     uoMM##W8%%8Mar   .k*MWWWW&8%%8Wop",
  "                                                                     uoMM##W8%%8Mhj    UoMW&WWW88%8W*b:",
  "                                                                     uo#M##W8%%8Mk]    ~a#W&WWW&8%%&#k<",
  "                                                                     no#M##W8%%8#k<     k*MWWWW&8%%&Mhr",
  "                                                                     no#M##W8%%8#b>     uoMWWWW&8%%8MaX",
  "                                                                     no#M##W8%%&#d:     ~h#W&WWW&8%8Wop",
  "                                                                     na#M##W8%%&*p       k*MWWWW&8%%&*b:",
  "                                                                     \\a#M#MW8%%&*p       /oMWWWW&8%%&#h<",
  "                                                                     +a#M#MW8%%&*w       ;h#W&WWW8%%8Mar",
  "                                                                     ~a#M#MW8%%&oz        Z*MWWWW&8%8WoX",
  "                                                                     ~a#M#MW8%%Wor        /oMWWWW&&88W*d",
  "                                                                     ~a#MMW&8%%Waj        ;h#M#M**M&8&*b>",
  "                                                                     ~a*MMMW&8W#a(         Jao*hqpaW8&Mh]",
  "                                                                     ~h**bpaW8&*b<         }ko*hpb*&88War",
  "                                                                     ~h*oddo&88#b>         .k*MM#M&8%%Wox",
  "                                                                     {o*oa*&%%8Mb>          U*MWMM&8%%WoQ",
  "                                                                     m**aoM8%B8#0           /oMWMMW8%%&*q",
  "                                                                    Ia*oa*&%B%Wh]           ~a#WWMW8%%&*p",
  "                                                                    uo*aaM8%B8#0            .h#WWMW8%%&#d",
  "                                                                    h**a*W%B%Wh]             Z*WWMW&%%8#d",
  "                                                                   }o*oa#8%B8*Q              uoMWMW&8%8#b:",
  "                                                                   J**aoW8B%Wk;              }aMWMM&8%8Mk>",
  "                                                                  ;a*oa#&%B8*X               ;h#WMM&8%8Mk<",
  "                                                                  to*aoW8B%Wk:                k#WWMW8%8Mh<",
  "                                                                  m*oa#&%B8*z                 J*W&%BB@B&a<",
  "                                                                 _WB$$@B%%Wb.                 /*%BBB@$$@&/",
  "                                                                (%%&8B$$%W*|                  1&%MkkMB$$%#+",
  "                                                               _&8amdW@$BWb                   d88amq*B$$BMZ",
  "                                                               d88*bo%$$@Wk                  +#8%&MW%$$$BWk:",
  "                                                              )W8&#M%$$$@Wk,                 +#8BB%%@$$$B&a]",
  "                                                             '#88M#&@$$$BM0                   *&BBB%@$$$@8ox",
  "                                                             jW8&#M%$$$$8o[                   *&B@B%B$$$@8#0",
  "                                                            '#88M*&@$$$BWb.                   o&B@B%B$$$$%Mb",
  "                                                            z&8W#M%$$$$%*X                    o&%@B%B@$$$BWh<",
  "                                                           lM88M*WB$$$@&h<                    aW%@B%B@$$$B&or",
  "                                                           Q&8W#M8@$$$BMd                     wW%BB%B@$$$@8*Y",
  "                                                          I#88M*WB$$$@8o|                     cW%BB%%@$$$@8#d",
  "                                                          U&8BBBB$$$$BWMwLLLv!               (8W&B@B@@$$$$%M8@@@@$L!",
  "                                                         r8oqaaa&&&8&#***###8Bj             _&&dmhaaa*&8&Wooooo**%$8_",
  "                                                         #%#ppppppppppppppppp#o             c&%Wpppppppppppppppppa$%m",
  "                                                         d%Bhpppppppppppppboo%w             j&@$*ppppppppppppbooo8$8U",
  "                                                         ?8$$$$$$$$$$$$$$$$$$w;.............;kB$$$$$$$$$$$$$$$$$$$$O'",
  "                                                          ;zW$$hZmmmmU||\\\\\\|^^^^^\"\"\"\"\"^^^^^^^!X$$$$$$$$$$hZZZZOj11<",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^]||^```'''...",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
