/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `hairspray` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                            .'''.        ...",
  "                                                                           .'`^``.    .'`^^^`.",
  "                                                                            '```'.    '^\"\"\"\"^`.",
  "                                                                             ...  ,   '`^\"\"\"^'",
  "                                                                             {]  //    .'``''",
  "                                                                         '[  |f  ql               '^\"\"^'",
  "                                                                      C.  h\" YZ !W:              '\",::,^.",
  "                                                                      <w! XJ Ud`pb: ?            .^\",,\"`",
  "                                                                       xki\\*[Jaj$Q;}J  `           .''.",
  "                                                                        bktMma#Z$XtWi fX",
  "                                                                      v[?oka*aW*&Q$X_WJ",
  "                                                                       Owq#h&o8%h%d*$J:",
  "                                                                     j)]C#*&B@$$W&k$kjQt",
  "                                                                      /hMW$$$$$$$$$$dz|                 '",
  "                                                                       o$$$$$$$$$$$*0c/                +-+;\"",
  "                                                                      _a&$$@B#apQJXuxnQn               I---r\\",
  "                                                                      +hW%0Uzurft\\[! t$ox              )\\---rf",
  "                                                                      Lq][?\\jULm1I  :c@dv              \"c)-\\zvf",
  "                                                                     +%t     <a]  ;[rQ@kv               IvzXXcv}",
  "                                                                      m8dvl  (ob}    c8o1                _vzXXcv}",
  "                                                                      [M*`   xwCz(!-/fo#)                 }vzXXcv}",
  "                                                                       mMv([cLCx/rnjt/Z&) ,                }vzYXcvv_",
  "                                                                       +dJQj|Xzr()f/|(v#/>iI                }vzYXcux`",
  "                                                                       IXuv\\{r|->?[)1)/\\1\\l\"l.              ivczYXcuf",
  "                                                                     .i](\\(}?/^   ._1(tt[I,\"\"I               [nczYXcuf",
  "                                                                    .i]?;!_~?)1uYr|()\\[i:,\"^``:,              ;uczYznjj:",
  "                                                                    ^^''`^,I?}[|{]}1|{,,^`'.`'                 _uunt(tcu;",
  "                                                                        '''``/utttrrj(,'.'^     .^^```''        [t}]/YYcu;",
  "                                                              .``          .'-Q0Z0UvrfI^\".    ',\",::\"`'''`.      fzYCQCYcu;",
  "                                                           ^\"\"^^```^\"   l,:::?Q0O0Uujt_III;+`I;:I~?+l\"``'''``     jzUCQCYcu;",
  "                                                          ;:,;,``^^^^^^^<I<+~;vXcur\\)ti<+l,-;!;;>]{-!,\"^^``'''`'   uzULQCYcu;",
  "                                                         ;;:, !:\";IIIll!<I:;\"^<\\()}}\\_;I[i:}?!;,;i>l,\",,\"\"^```'''``ivXULQCYcu!",
  "                                                        'I:I< \"{z+Icx-}ZrlfO[^i|){vnc!;-Qf;j|!:\"^^^^`^^\"\",,\"\"^```'''<vXULLCYcu+,",
  "                                                        !;;i+: 1/~`}?Il]?i>_l^i}?|m/; ;;l,;<;i:\"`'...''`^^\"\",,\"\"^```'1cXJLLJYcu[:",
  "                                                       ;;;!~~l ,:^`^\"^^^,>:;\"^itXZj0! I;,^I~^l;\"'.  ....''`^^\"\",,\"\"^``/cXJLLJYcu]!",
  "                                                      `I:I<+i:  I\"`^^^^^^~;;\"^imWQ-Z1 I;,^l_^\";\"'      ....''``^\"\",\"\"^!jzYJLLUcxf:l",
  "                                                      I;;>+>;^. ::^`^\"^^^!I:\"^iQhJ-Q\\ ,;,^!+^^`^`.         ...''``^\"\",:irzYUXnf|f^:l'",
  "                                                     ,;;!~<I\"'. ';\"`^\"^^^!l:\"^iUqm-J( \";,^i!^^'..`\",.         ...''``^\":<xxj/){(i'^:!.",
  "                                                     I:l<~!,'.   ;,^`^^^^;!::^iz0L-X) \";\"\">i^`'..^;+^  ..        ...''``;I~][[_I`''`,!.",
  "                                                    I;;>+i:`.  ' `:^`^\"^^\">::^iuJY-vn ^;\"\"~>^`..'\"l?       '        ....'l,`''`^``''`,l,",
  "                                                   ^;;i~<;^'. '\": :\"`^^^^'~;,^!xzc-fr .;\",+;^`..',i~           .        .';\"`''`^``''^;~",
  "                                                   l:l~~l\"'. .^I_ ^,^`^\"^'>I:^!jun-|t .;\",_,^'..`;~:               .      ^;\"`''`^`'.`;~^",
  "                                                  I;I<+!,'. .^;~^  ;\"`^\"^'il:^!trj[)|`';\":?,^'..^I_.                  .    ,;^''''.  `;+\"",
  "                                                 ^;;i+>:`. .`:<`   `,^`^^':!:^!\\t/))1, ;\":[,`..'\"!_                      .. ::`.     ^l_",
  "                                                 l:l~<I^'. ',>i     :^`^\"`,>:\"!QqZO0L< I\";~,`..`:>>                          :^.    .,I",
  "                                                I;I<~l\"'. '\"!l      \"\"`^^`.~;\"!Q888&&] I\"I+,`..^;+^                                 .",
  "                                               'I;i+i,'. .^l~        ,^`^^.i;,>v*##MMY ;,l_,'.'\"l?",
  "                                               I\"^``'^` .^I<         \"\"`^^.iI,~ukkkkkv ,,!+,..',i~",
  "                                              ,,Iil\"'`:l`;+          ',^`^.,!:_xkkkkkv ;:i!,..`:<l",
  "                                             \"I;+}+:'',>l<`           \"^`^':i;]xkkkkkJ lI>i,..^I_.",
  "                                             i;,Il:`''\"!-I            .\"`^'.<I?xbbbbbd ,l<>\".'\"!]",
  "                                             l;\"`^^`'.^I-            ' ,^``.<![tCCJJJU ^i+;^.`:>>",
  "                                              !,^^^^'.`:~              '^``.i>_)///\\\\\\ .~_\"^.^;~^",
  "                                              l;^`+vur/>i`            ` \"`^.I~?_\"\"\"\"\"\"  <?\"`.\"l-",
  "                                               !,[kW#wJv-!            ^ `^`';_+>        >]\"'',i-",
  "                                               \"IwpokQznt<             \" \"`'`]<>        i_\"'`:<l",
  "                                                lYLQ0Cznj?             ^ ^^'`?>>        l+\"`^I+\"",
  "                                                `)CQ0QYvr('             ^ ^``i>>        :i\"'\"l]",
  "                                                 IXL00Jcnf              ; ^``l>>        \",\"',>i",
  "                                                  ?CQ0LXuj`             ^  ^`:>>        ,:\"`;~:",
  "                                                   zL00Uvx+              l ^`:>>        ,:\"^I-",
  "                                                   }LQ0Czn1              ; .^:>>        .:^\"l_",
  "                                                    JL0QYuj               , ^:>>       '\"::,,\"^.",
  "                                                    }LQ0Jvx!            ',> .:>+      ;;;II;:,\",;^",
  "                                                     CL0Lzn1           lIl>\" '>+;,   ill>++>I,\"\":l;",
  "                                                     }L00Uuf         .ili~>:  .!\"\"^ i!li_[]~l,\"\":I<\"",
  "                                                      YYcXzz\\        >!ll:iIlll!!+jU<!I!<+~!;\"^^,Ii~",
  "                                                      QkdOvxx1       ~!l;+1~\\m\\{m0wZ<!;;;;;:,\"^^\":!~",
  "                                                      LUY0c/){       ~!!:``.<[~\"]\\vt<l;,,,::,\"^^^,I>;",
  "                                                      Ijrxr|{`       !iI;.        ^<<iI:,,::,,\"^^\";i_",
  "                                                        ?\\)]_        IiI:,\"^^''.'^;, <l;,,,::,\"^^\":l~,",
  "                                                         \";,         '>l;:;;:\"^`\";i] ,iI:,,::,\"\"^^,I>>",
  "                                                                      <l;:;;:\"^`\":!?  <l;,,,::,\"^^\":!+",
  "                                                                      ~!;:;;:,^`^:!-  ,iI:,,::,\"^^^,I<I",
  "                                                                      IiI::;:,^^^:l_   <l;,,,::,\"^^\";i~",
  "                                                                      ^>I::;;,\"^^,l+\"  ^iI:,,::,\"^^\":l~",
  "                                                                      '>l;:;;,\"^^,l+^   i!;,,,::,\"^^,I>!",
  "                                                                       ~l;:;;:\"^^,I~`   ^iI:,,::,\"^^\":!_",
  "                                                                       >!;:;;:\"^^\"I<`    i!;,,,::,\"^^,I<,",
  "                                                                       IiI:;;:\"^`\";>>    '>I:,,::,\"^^\";i>",
  "                                                                       '>I::;:,^`\";>i     l!;,,,::,\"^^:l+",
  "                                                                        <l::;;,^^^:i!      >I:,,::,\"^^,I>;",
  "                                                                        ~l;:;;,\"^^:il      !!;,,,:,\"^^\":!<",
  "                                                                        ;!;:;;,\"^^:!]       >I:,,::,\"^^,I<",
  "                                                                        :iI:;;:\"^^,!-       ,!;,,,:,\"^^\";il",
  "                                                                        '>I::;:\"^^,l_        <l:,,::,\"^^:l+",
  "                                                                         <l::;:\"^^\"I+        ,!;,,:::,,\",;>,",
  "                                                                         >l;:;:,^^\"I~^        <l:;IIll;,\":!i",
  "                                                                         I!;;:::,\",I~^        ^i!!l<?-i:\",I<",
  "                                                                         ^>!I!<!;\",I~`         i<!l<-+l,^\";>I",
  "                                                                          <!!_[+I\"\";>`         ^~lIIlI,^`^:ii",
  "                                                                          >l!<>I,^^:>>          <lIIl;,^`\";<l",
  "                                                                         ,!l>>l,^`^:>:          <lIll;\"^`\"I+^",
  "                                                                         <l!<i;\"``\"I~          '>lIll:\"^`,l-",
  "                                                                        `!l>>l,^`^:<`          '>IIlI:\"`^,!_",
  "                                                                        !l!<i:\"``,!!           '>IIlI:^`^:ii",
  "                                                                       ^il>>I,^`^;_            'iIIlI,^`^;<`",
  "                                                                       il!<!:^``,>,            :iIIlI,^`\"I+.",
  "                                                                      ^il>>I\"``\"l>             IiIIl;,^`\"l?",
  "                                                                      Il!<!:^`^:~              I!IIl;\"^`,!!",
  "                                                                      il>>I\"``,i;              ;!,^^`''^:>l",
  "                                                                     :^^\"^`^`^I<               ,^'`'.  ':<^",
  "                                                                    `'^^'  `,:<^              '\"^I~>,. .\"i",
  "                                                                   ,^I--I' .,>!               I\",+}-;' .^II",
  "                                                                  \",\"l_~:. .\"i`              ';^^:l:`   ^I_",
  "                                                                  ;\",!l\".  .\"i`              ,:^`\",`.   ^I-",
  "                                                                 ;\"\"I!;`   .,<               i,^^,\"`    ^l?",
  "                                                                `:\":!l\".   `l>               l,`^,\"'   .\"l>",
  "                                                                ;\",l!:'   .,<                I\"`^,\"'   .\"!!",
  "                                                               ;,\";!I^    `Ii               :;^`\",^'   .\"!!",
  "                                                              .:\",l!,'   .,>`               l:^`\",^.   ',ii",
  "                                                              I\"\"I!I^    `I~                !,^^\",^.   ',>i",
  "                                                             ^:^,ll,.   .,>,               .I\"`^,,`.   ':>>",
  "                                                             \":^''`'    `::                `,,`'``.    `:;....",
  "                                                            ,\"+_>il,,\"\":lllllI;',         ,\"i}+iil,,\"\",Ii!!!!!: '\"",
  "                                                            :^<-----------------,;        ;^,~-----------------''l^",
  "                                                            :',--------------<il\"fCCCCCCCX;` ,--------------<il 'i",
  "                                                            ^`                  '         ^^                    \"",
  "",
  "",
  "",
  "",
];
