/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `hairspray` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                            .'''.        ...",
  "                                                                           .'`^``.    .'`^^^`.",
  "                                                                            '```'.    '^\"\"\"\"^`.",
  "                                                                             ...  \"   '`^\"\"\"^'",
  "                                                                             [/  \\J    .'``''",
  "                                                                         `|  |J  m?               '^\"\"^'",
  "                                                                      m`  8! J8 !8?              '\",::,^.",
  "                                                                      ?a? Ja J8!m8? ?            .^\",,\"`",
  "                                                                       J8?n8nJomao??a  `           .''.",
  "                                                                       `8oJqo8j8j8|8| |m`",
  "                                                                      J||QQ8[8:8,8Q8?aa`",
  "                                                                      `aa8|Y(J\")<Jx8L8?",
  "                                                                     n||aXQ,'.  :>ZvbmJJ",
  "                                                                     `J88q}nJJaJJJ??v8m                `?`",
  "                                                                       8v???       !1ha`               a*k|!",
  "                                                                      ?8(  .`I>-)/jnUd8J`              |Md&Mm`",
  "                                                                      ?8(^1/jnJ0dh&$$@[va              n#*d8qa`",
  "                                                                      JBhmkakLz/q#$$&&{[8              !#a8mrLa`",
  "                                                                     ?wY$$$$$h>w$$WmcZv/8               ?arffrLJ",
  "                                                                      a-fk*$$Qi+Z$$$$Ca|J                nbrffrLJ",
  "                                                                      |ql$$$$c]|rL*pUXWjJ                 JbrffrqJ`",
  "                                                                       a{XLmr(|cUcvzYJaqJlc.               Jbjffrb8n",
  "                                                                       (d\\)zCjrcLQXUCQw8&hop'               JOjffrb8!",
  "                                                                      IqpnnJOcCphqmQ0QpWmJ*8*+              ?8Cjffxba`",
  "                                                                     +owmJLZqU%$$$@dOO8Cm#&88#_              J8Cjfjxba`",
  "                                                                    +owqModkqQ0ntzCLp8aaW&8%BBWc              ?8CjfjvMa?",
  "                                                                   'O8@B%%&M8MhmOpb#*p&&8B@@Bm('  i]]]`        n8LvY08XM?",
  "                                                                     `]CB@BB%CJqwqQUzL&B@Ba|'  !U%%%BBBon`      JM#MkutuM?",
  "                                                            !nwBBqC?     !u*@p)1}1/ncY#%hx??  r&8&WW8%BBBBw|`    aJt|(|fuM?",
  "                                                          'Z888%%BB%kCCC*&WWWq)1{)tnzUdM##MbB#MW#bqb#8BBBBBB%J?  `aJt|(|fuM?",
  "                                                         'dW&M&%%%%%%%%%hMhbkMxfrnzJQUohb*&pWoMWawOp*&8%%BBBBBBon!`Mu/|(\\fuM?",
  "                                                         LMW&$oW8MM###**h#WM88hJL0ZZCdMMmaWZq*W&Moa*&&&&88%%BBBBBBomMn/|(\\fuMJ!",
  "                                                        1#W#h$8Orb#rvpZ}z*Y{w8aCQZnvr*Mp)XWXL*W8%88%B%888&&88%%BBBBB%df/((\\fua&c",
  "                                                       '*WMabW$0Uk%Zq#*wqoad#8amqL[UM$MM#&MkMoW8B@@@@@BB%888&&88%%BBB%df/((\\frbWc",
  "                                                       LMW*kk*$&W8%%8%%%&hWM88oUf}X1o$#M&%#b%*M8B@$$$@@@@BB%%88&&88%%BM0f\\((\\frbWw.",
  "                                                      1#W#hbo&$$#8%%88%%%bMM88o[:)p}0$#M&%*d%8M8B$$$$$$$@@@@BB%%88&&88o8Jf\\((/xY8Wq'",
  "                                                     'pWMabhM%@$WW%%%8%%%o#W&8o)>\\p)J$&M&%ob%%B%B@$$$$$$$$$@@@@BB%%88&WM8XftjuYQ8%Wq~",
  "                                                     cMWobk#8B@$@M8%%8%%%**W&%o/?}p\\L$8M&%ao%%B@@B8&@$$$$$$$$$@@@@BB%%8WWMJXUQmWB@%Wo+",
  "                                                    _#W#kk*&B@$$$M&%%88%%MoWW%oj1(pfQ$&M&8ho%%@@@%Mb>]u*@$$$$$$$$$@@@BB%MW8W*M8%B@@%&*+",
  "                                                   'pWMabaWB@$$B$BW8%%8%%8aWW%on/tpxu$%M88ka%B@$@8*q    `\\C@$$$$$$$$$@@@@#&%BBB%%B@@%&*/",
  "                                                   fMWobhM%@$$@8W$W8%%88%BkM&%ovjrpXz$@M8&bM%B@$B&ac        !uq@$$$$$$$$@BM8BBBB%%B@@%Mk.",
  "                                                  I#W*kk#8B@$@%#db%&%%%8%BaMW%oznupCY$@M8&p&%B@@%Wk]           `]C*$$$$$$$8M8B@B%%B@@%Mk>",
  "                                                  pWMhbo&B@$@%Mb<t$M8%%8%Ba#W%oYczmQC%@M8Wq&%@@@%#d:               !\\q@$$$$&W8B@B@@$$%Mb>",
  "                                                 fMMobaWB@$$BWh<  &%&%%88BWoW%oCYUQQ0&$M8Wm&%@$B8oL                    ]C*$$WW%@$$$$$%*Q",
  "                                                I#W*kkM%@$$B&ar   t$W%%%8B&aW8od*aoo*@$M8Mk&B@@BWhj                       `\\JW%@$$$$@&C.",
  "                                                qMMhk*8B@$@8ox    ^$&8%%8B@kM8o)\"\"\",,w$#8#b&B@@%Mb>                           ?C$$$$J_",
  "                                               1MMaba&B@$@8*0      z$&%%%%@aM&anllII;t$M&#d&B$@8*q",
  "                                              '#8%%BB%B$@%#O.      ^$88%%%@o#&ku~~~~~n$&&*b&@$B&oz",
  "                                              0&Ma#8B%W*BMb:        d@&%%8@&*Wpc~~~~~n$MWoo&@@BWh)",
  "                                             tMMdZbWBB&a#h<         ]$&%%%BWaMwc~~~~~\\$#Mao&@@%#d:",
  "                                             mM&M*W%@@8*p|           M@8%%B@h#qc++++++$&*ka8$@8*w",
  "                                             JM8%%8%@@%#p            r$&%%%@h*mU|\\\\\\//$%abW%$B&aj",
  "                                             I*&%%8%B@BWk            .$B8%%@oapZZZZZmm$@kd8%@%Mb>",
  "                                              JM8%88%%%&a<            m$8%%@#kqz??????b$hq8%@8#p",
  "                                              .o&%d<I]vM#x            {$B%%@Mdbf      0$hw8BB&oL",
  "                                               tM8{i~)jJ&O             8$8%@Bwhf      0$od8BBWh(",
  "                                               .q8t)1|juMh             j$%%BBqhj      z$#b8B%Md>",
  "                                                {MO(1)tnp*,            I8$8BBahj      }$Wa8B8*q",
  "                                                 p8f)1\\rJW              L$%%B*hj      }$8&8B&aj",
  "                                                 'UO(1(fuM!             {$$%BWhj      }$&W8%Mk?",
  "                                                   af11/xpn             .#$%%Whj       $&W88#p",
  "                                                   nO)1|rJm              v$@%Waj       $@W88*L",
  "                                                   `8f1)fnM`             I&$8Waj       @8WW&&8hxl",
  "                                                    nO)1\\xp|           'rka$@Wa0l    IpMM##MW&8&Mf",
  "                                                    `8t1(jJm          _#M#a8$BadMc. Io#*hbba#&88W*u",
  "                                                     nO)1tu8`        +o*okaW$$@o88hCmo*admwk#&88W#h[",
  "                                                     `8xrfrpm`       Zo**Wa##***o*&#h*#*hbkoW8%8&Ma0",
  "                                                      a(_{ncmm       k**Md0bJ[JO[dw}h*MWMMMW&8%%8W*b;",
  "                                                      8rf)rJZm       k**WBB@hmb8wM#Qh*M&&&WW&88%8&#h\\",
  "                                                      ?pcvzCO!       UoMM@$$$$$$$$$Bao#W&&WW&&8%%&Mod",
  "                                                       `(JQwL        na#W&88%B@@B8WQ(h*M&&&WW&8%%8W*k]",
  "                                                         }u/.        ~h#WWMMW8%%8Wow to#W&&WW&&8%%&MaX",
  "                                                                     .k*MWMMW8%%8Woq .h*M&&&WW&8%%8W*b.",
  "                                                                      b*MWWMW&8%8Wop  /o#W&&WW&88%8&#h|",
  "                                                                      uoMWWMW&8%%&*d  .k*M&&&WW&8%%8Mo0",
  "                                                                      }a#WWMW&8%%&*b>  {a#W&&WW&88%8W*k;",
  "                                                                      ~h#WWMM&8%%&#b>   m*M&&&WW&8%%&Max",
  "                                                                       k*MWMMW8%%&#k<   }a#W&&WW&8%%8W*d",
  "                                                                       ZoMWMMW8%%8Mh<    m*M&&&WW&8%%&#h[",
  "                                                                       noMWWMW&%%8Mhj    +a#W&&WW&8%%8MoY",
  "                                                                       ~a#WWMW&8%8Mar     J*M&&&W&&8%8W*b.",
  "                                                                       ;h#WWMW&8%8War     Ia#W&&WW&8%%&Ma|",
  "                                                                        k*MWMM&8%%Wox      JoM&&&W&&8%8WoO",
  "                                                                        uoMWMM&8%%Woq      Ih#W&&WW&8%%&#k;",
  "                                                                        /oMWWMW8%%&*p       toM&&&W&88%8Max",
  "                                                                        ~a#WWMW8%%&*d       .h#W&&WW&8%8W*b",
  "                                                                        .h#WWMW&%%&#b        /oM&&WWW&&8&Mh[",
  "                                                                         Z*MWMW&%%8#b>       .h#WM#M##M&8W*Y",
  "                                                                         uoMMWWW&8&#k>        {o*o*hqpoW8&Mk:",
  "                                                                         }ao#ohoW&&#k<         mk**hpb*&88Ma|",
  "                                                                         ;ko*dwbM88Mh<         }k*M#*#&8%8War",
  "                                                                         .h*oha#&%%Waj          h*M##M&%%8Mh(",
  "                                                                         to*ah*&%B%Wh]         ;h#M##W8%%8Mb>",
  "                                                                        .h*ohoM8%B8#0          ~h#M##W8%%&#p",
  "                                                                        {o*ah#&%B%Wh<          ~a#M##W8%%&oL",
  "                                                                        w*ohoW8BB&ox           ~a#M##W8%%Waj",
  "                                                                       {o*ah#&%B8Md.           +a##*#&%%8Mh<",
  "                                                                       m*ohoW8B%&a]            /o##*M&%%8Mb:",
  "                                                                      }o*ah#8%B8#Y             no##*M&%%8#q",
  "                                                                      C*ohoW%B%Wk:             uoM##M8%%&ox",
  "                                                                     Io*aaM8%B&o|              u*&%%B@B%Wa(",
  "                                                                     Q8%8%%%B%MO               Q%@BB@$$BWk>",
  "                                                                   'aB%%B$$B&Wh<              r8%#ba&@$@8o.",
  "                                                                  'k8MppM@$@&ax              IM8&bZpM@$$%#n",
  "                                                                  z&8*dbW@$@8o<              1M8%W#WB$$$%#p",
  "                                                                 _W8&**8@$$@8a<              cW%%8&%@$$$%#p",
  "                                                                 d88#oWB$$$@&k:              o&%%&&B$$$$%#q",
  "                                                                jW8Wo#8@$$$%#X              '*&%%&8B$$$@8*X",
  "                                                               lM8&#oWB$$$@&h;              _#8%8&8B$$$@8*x",
  "                                                               d&8Mo#%$$$$%#Y               cM8%8&8@$$$@&or",
  "                                                              )W8&**&@$$$@&a<               qW%%8&%@$$$@&or",
  "                                                             '#88#oM%$$$$%#0                *&%%8&%@$$$B&aj",
  "                                                             fW8&#*&@$$$@&a[               +#8%%&&%@$$$BWaj",
  "                                                            `h&%BBB@$$$$%WWLLLL/`         'a&&BBBB@$$$$BWM@@@$$L|",
  "                                                           'k8bdaa*&&88W***###MB&I        b8aZbaa*&&&8&#oooo**W$Bz",
  "                                                           _W%hppppppppppppppppp&v       _M%&kppppppppppppppppp@@*<",
  "                                                           IWB&ppppppppppppppho#8t       !MB$&ppppppppppppppho#$@a.",
  "                                                            YB$$$$$$$$$$$$$$$$$$u.........U%$$$$$$$$$$$$$$$$$$$$&_",
  "                                                             _O$$$mmmmmmn\\\\\\\\\\i^^\"\"\"\"\"^^^^^jM$$$$$$$$$$ZZZZZZr){",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"]\\\\|^^^```'''...",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
