/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `idle_a` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                          !?  ^+",
  "                                                                                  +   ]]  v|  w;",
  "                                                                                  ;0  _Q  o) tq",
  "                                                                                   Lr +oIlB1`$/",
  "                                                                                   [*\\+&fr%{bhi Y",
  "                                                                                 ^. hku8OpW0$U;#(  l",
  "                                                                                  Z}|MwWbMoW*J$J }Z?",
  "                                                                                  !hdh#*#8k$w@ZU&d;",
  "                                                                                }ZcuaoB8@$*&MbM%U:",
  "                                                                                 ;q8@@$@@@%W#o&pZdn",
  "                                                                                 !M$$$$$$$$$$$$Mx+",
  "                                                                                 0W$$88M#**oookCx/",
  "                                                                                /%hOJzzcvvuunnxxxJ",
  "                                                                               I$$i  ;-YXcux{<; rBX",
  "                                                                                WBJ|-^  ]h+   ._Zku",
  "                                                                                d@O(!  \"Lpf''!-d$w)",
  "                                                                                z@O{   }wQv:   Q$Qi",
  "                                                                                ?@LCut0QCn|u/]/p@X",
  "                                                                               ^}WXQx)nYzr\\/t\\(p&/^",
  "                                                                              :+|qxj([r\\{?(|(1)do{il",
  "                                                                             I](>)1{-]j\"   `]{(rx/\":;",
  "                                                                           .;li:,,l<_)|(/|_[1)\\(+;,\";;",
  "                                                                             .```^\";-{}{/([{{|_:,,\"^^II",
  "                                                                   .'``'.       ````;Cn\\[[[1|I,^`'....`",
  "                                                                 \"\"\",^^`'`\"`      .`?mmqZUuft:'..'",
  "                                                                I:;\"l:````````Ii::::[mwqOYnft,^'      .^^^``'``",
  "                                                               \"I:l`'l,,,,,,,\"!>Ii>l~CJUXnf|tII;;:~'^:\":;;,^`'^:,",
  "                                                               !;;!I +X{,]z_!]1>;-l`:\\jf\\){(_li!,I+;I:I~]-i,`'`,!I",
  "                                                              ^I:l<i i1_^1t]IYj_[0r`I1(}/|r1ll?-^>-i;:!-}?i,`'`\";>'",
  "                                                              !;;i<i \";\"^\"\"^^^^>;>I^!}][Qu(IIlYji)Xi;,:lil,^'.'`,l>",
  "                                                             ;;:!<>I 'I\"^\"\"^^^^>;I^^>tzqCf, Il,`;+ii;\"^^^^^``'.'^:!:",
  "                                                             l:I><!,. l,^^\"\"^^`<;I^\"~h&U/0> Il,^l~\">;\"`''`^^`''.`\";>",
  "                                                            l;;!<i:`. ::^^\"\"^^`<;I`,-#af\\C;'Il^\"<i^;l:^`'``^^`'''`,l>",
  "                                                           `I:l<<I\"'. \":\"^\"\"^^`<;I`;1bp/rU .Il`,-^^^II,^`'``^^`'.'^:!:",
  "                                                           I;;i<!,`.  ';\"^\"\"^^`<;;^IfZO)xz .I;`;-^^`.;I,^''``^``'.'\";>",
  "                                                          \"I:l<>;^...  I\"^\"\"^^'<;;^!xLJ-xu .I;^!<^^'. !;\"`''`^^`'''`,l>",
  "                                                          !:I><l\"'. '\" \",^^\"\"^'<;:\">uYX-ut ,I,\"~!^`...\"!;\"`''`^^`'''^:!:",
  "                                                         ,;;!<i,`. .^I'':^^\"\"`'<;:\"+ccr-r] ,I,:],^'. ',ii:\"`''`^^`'.'\";>",
  "                                                         l:l<>;^' .`:<\" :\"^\"\"`'<;\":?un/{t- \"l`I_\"`'..^;~!!:^`'``^``'.`\"l>",
  "                                                        ;;;i<l\"'. ',i!  ;\"^\"\"`.~;\";{rj\\1|+ :I^i>\"'. '\"!_  l,^`'`^^`'''`:!:",
  "                                                       .l:l<i:`. .^l~   ^,^\"\"`.~;\"IfOQvn(! l:,+l^'..`;~:   l,^''`^^`'.'^;>",
  "                                                       l;I><I^' .`;+.   ',^^\"`.~;\"!QMM#*o- I:;?:^. '\"!+    :I,`''`^^`'.`\"Il",
  "                                                      `;\"\"`^^^. ',<,     :^^\"`.~;\"+O*#MWW] I\"l+:'..`:<:     ,;\"`''`^``''`,!^",
  "                                                      :,:;,`'\";`\"!!      ,\"^\"`.~;;]qkkkha- I,><,. '\"l?       ;;\"`'``^``''`:<",
  "                                                     ,;I?[>\"'`;~I~       ^\"^\"`.~;!{kkkkkk!`l:-:\"..`:<l        l:\"`'\"\"\"\"\"^``,I",
  "                                                     i:;><;`.`:<-         ,^\"^.~;+tkkkkkk `l;-:` '\"l-          I:^:;:>-<:`'^II",
  "                                                     i:^^\"^'.',>,       ` ,^^^.+I?rbkkkkk ^!!<:..`:>I           !;i;I_[+;`'^;~.",
  "                                                     l;\"`^^`''\"!!         \"^^^.+i]nQ0OOZm ,!~!, .^I-            .i!:;l!:^'.`;<^",
  "                                                      !,^^~]-+;I>         `\"^^.++-\\fjrxn\\ Ii]:\".`,>I             ;l:;lI\"'..^;+\"",
  "                                                      I;^chopLz-_        ` \"^`'+--\"i~~~~I I>+:'.^I_.             :I:I<+`..'\"!~",
  "                                                       !jd#&dJvr_.       \" ,^`'__]        ;~i:.',i~              !;rddmCfI`;+.",
  "                                                       Ix0OZQXuj}`       ; ^^`'?<i        :-;\".^I_.              iCh&&dLzn;i~",
  "                                                        -LQO0Uvr(l       . '^``?<>        l],`',i~              .]qbokOXnf}_.",
  "                                                        ;XQ0OCcxj         \" \"`^~~^        I_,'^;+.              ,rpbkmYnt\\}I",
  "                                                         {LQOLXnj`        I \"`^!_\"        I!\"',i<               ,JpkdQzr\\t]",
  "                                                          CQO0Uur!        l `^\"l?         ;,^^;+:                qdkqJuf|{;",
  "                                                          {L0OCcx?        ; '^,![        ';,`\"!_                <qbkZXx//;",
  "                                                          \"LQOLXnj        .^ ^,>i        .;,`;~:                rpkdQcf|]",
  "                                                           xQ00Yuj;       \"I \":<l        .:\"\"I+                 QdkqUn/\\`",
  "                                                           !L0OCvr+    .;;;< ';+!       ,::,,\"\"`               .qbkOzr\\{",
  "                                                            zQOLzx1   ,lli<<. `_ii.   ;;Ill;:,\",;,             [pkdLvt\\`",
  "                                                            _LLJvfx  ,ilil:'   \"`,! 'il!<__>I,\"\":l>            xpkwYx\\|",
  "                                                            ,ZppLUXf ~!l;+)<ii!lI;)x>!li_[]~I,\"\":I<\"           wpb0cf\\i",
  "                                                            >m0JCx//:~!l:Ii:fmj)pLdp<!Il>~<l:\"^^,;i<         .YhkZzj|(",
  "                                                            \"zuccf)(`+!I;.  `>\"\"?uYj<l;::;::,\"^^\":l<\"        |pqmLvcnj",
  "                                                             '{rr\\{< IiI:^       '~?<l;,\",,:,\"\"^^,;i<        /LX0z/)\\t",
  "                                                               <]_~  :>I::;;:\"`'`\";,;!I:,,,::,\"^^\":l<\"        jzXt{[(~",
  "                                                                     '<l;:;;:\"^`\";i] !l;,,,,:,,\"^^,;i<        `t|{?-'",
  "                                                                      ~l;:;;:\"^`\":i? .iI:,\",::,\"^^\":l<,         I;",
  "                                                                      >!;:;;:,^`^:!-  ;!;:,,,:,,\"^^,;i<",
  "                                                                      IiI:;;:,^^^:!-   <l;,\",,:,\"^^\":l<,",
  "                                                                      ^>I::;;,\"^^,l_   ^iI:,,,:,,\"^^\";i~",
  "                                                                      '>l;:;;,\"^^,l+\"   l!;,,,,:,\"^^\":l<",
  "                                                                       <l;:;;,\"^^,I~^    >l:,\",::,\"^^\";ii",
  "                                                                       >!;:;;:\"^^\"I~^    ^iI:,,,:,\"\"^\",l<",
  "                                                                       Ii;:;;:\"^^\"I<`     l!;,\",,:,\"^^\";ii",
  "                                                                       ^iI:;;:\"^`\";<,      >I:,,,:,,\"^^,l<",
  "                                                                       '>I::;:,^`\";>>      `i;:,,,:,\"^^\";ii",
  "                                                                        <l;:;;,^`^;>i       il;,\",:,,\"^^,l<",
  "                                                                        >!;:;;,\"^^:i!        >I:,,,:,\"^^\";i>",
  "                                                                        I!;:;;,\"^^:i!        ,!;,\",::,\"^^,l~",
  "                                                                        ^iI:;;:\"^^,!_         il:,,,:,\"^^\";il",
  "                                                                        '>I:;;:\"^^,!?          iI:,,,:,\"\"\",I~",
  "                                                                         <l::;:\"^^,l-          ,!;,,;;;;:,\":!:",
  "                                                                         >lI;;;:,\":!_           !l;il!~+!:\",;<",
  "                                                                         I>!!+-i:\",l_           .i>il<]?>:\"\":i;",
  "                                                                         ^<li__i:^\"I~\"           ;~!I!>!;\"^^:!_",
  "                                                                         ^ili>l,^`\";~^            <lI!!I,^`^:i<",
  "                                                                         i!l>i;\"``\"I-            '>ll!!;\"^`\";<:",
  "                                                                         >l!>l,^`^:>,            :iIl!l:\"``,l-",
  "                                                                        ,!lii;\"``\"l~             ;!Il!I,^`^:ii",
  "                                                                        <l!>!:^`^:<:             ~lI!!;\"^`\";+",
  "                                                                       ^iliiI\"``\"l+              >ll!l:\"``,!+",
  "                                                                       l!!>!:^`^:<              .iIl!I,^`^:>l",
  "                                                                       >li>I,^`\"l>              I!I!!I\"^`\"I_",
  "                                                                      ,!l>i:^`^:~               >lI!!;\"``,!<",
  "                                                                      !l!>l,^`\"!<               <;,^^```^:<^",
  "                                                                      :`. .``^:+                ^'''.  `,I-",
  "                                                                     ``,\"'  ^;!;               \"^;>!\". .\"!I",
  "                                                                    ,\"i[_:. ';+               I\":+{-;' .^l:",
  "                                                                   ;\"\"!+i^  ':~              ^;^\"I!;`   ^I-",
  "                                                                  ^:^:l;`   ':~              I,^\";:`    ^l+",
  "                                                                  I\"\"Il,'   `I~              I\"^,;,'   .\"!!",
  "                                                                 `:^:l;^   .\"i,             ;:^\":;\".   ',>,",
  "                                                                 I\"\"Il,'   ':+              l,^\";:^.   `;~^",
  "                                                                :,^:lI^    ^l>             ';\"^,;,`    ^I_",
  "                                                                ;\"\"Il,'   .,>`             I:^\":;\"'   .\"!>",
  "                                                               :,^:lI^.   `;-              I\"^\";:^.   ',ii",
  "                                                               I\"^;l:'   .\"!;             ,;^^,;,`    `:<`",
  "                                                              ',\"''`'    ':;'             ^,\"''`'.    ^;;....",
  "                                                             ^\"!?>ii,,\"\",I!lllII^`^      ,,+[<ii;,,\"\":li!!!!l^ \"",
  "                                                             I^I-----------------li     ,,^;-----------------< ^~",
  "                                                             ;^'+-------------+ii^?CCCCC/,' i--------------ii\" ^!",
  "                                                              \"                  `       ,'                    :",
  "",
  "",
  "",
  "",
];
