/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `idle_a` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                          !|  `?",
  "                                                                                  ?`  ?|  nJ  m?",
  "                                                                                  !a` ?a  aJ |8",
  "                                                                                   mJ ?8?!8J`8m",
  "                                                                                   |8J?8mnaJmo| J`",
  "                                                                                 `` 8pmLoaz8Lo!aJ  !",
  "                                                                                 `a|nroCna(a|888`?m|",
  "                                                                                  ?8oo<*In1}zCpma8?",
  "                                                                                |aJmqX+i..l,[)aXa?",
  "                                                                                 ?a88CJJJJCQOmL*aaJ",
  "                                                                                 !8<         `?f8n",
  "                                                                                 m8  \"\";ll!!ii~\\aa",
  "                                                                                |8%{\\jrrxnnuYCLCa8`",
  "                                                                               !a o$$$BLQOmqW@$$dfa`",
  "                                                                                8'Yhp8$$w<b$$$@Bt~8`",
  "                                                                                a_Zh*$$8|-YB@oqk[rm",
  "                                                                                JfZd$$$Z])nW$$$&{Z|",
  "                                                                                (Lf|nY1)|uCnUwUa)8`",
  "                                                                               jobj(vQufjcCJYCLoLhf.",
  "                                                                             'QbLkczLmzJOqQCL0Qao*oC",
  "                                                                            _pwLa&0OpwX8$$$%wOOWpQ8Wv",
  "                                                                           )M#oW&&*haQCLUCdmOOWpbM&8Mu",
  "                                                                            !J%B%%8&%WkmULmOqWMW&&8%%Mn",
  "                                                                  !Jo%BBon!   '|aBB%MjQb8MM*b&&8%B@@@*Y",
  "                                                                'O&8&8%BBB8Y]`.???JBq}[?}tuXUW@@@BC|`   ]]]]]",
  "                                                                pWM8*W%%%%BBBB#oWWWWm}]?{tuXU&%mx?   !U%%%%BBBml",
  "                                                               f#W#BB#&&&&&&&&*a#ah#b|\\/juYCYMMMMWbBXW&WMM&%BB%Wc",
  "                                                              'oMMoM$bjO&wrd*w0aMp*%WJzYJQOLd*ao&#bM#W#bwpo&BB%&*n",
  "                                                              f#W#ha$a0d%0YwMtzdm1z%#OLZUCz0#*qp8apaMW*pZqo&B@B8Mh~",
  "                                                             I*WMako$8M8%88%%%%hMh#%*Zwm)nL##*fXaQjoM&W*o*&%B@@%&#Z.",
  "                                                             LMW*hhM$B#&%888%%%hM#%8aYj?|X&$#*&%MbaoM8%%%%%%B@@B%Wo/",
  "                                                            I*W#ah*&@$*&%888%%%hM#%8k>:tU1h$#*&%*k8aM8%BBB%%%B@@B8Mh;",
  "                                                            qMMokaW%@$WW8888%%%hM#%&pliXJ|W@#*%8ho%M#&8BBB%%%BB@@%&#Z",
  "                                                           1#W#hh#8B@$8W8%88%%BhM#%W0+-Uzt$@#*%&p%%%##&%BBB%%%BB@B%Wo/",
  "                                                           pMMako&B@$$@M8%88%%BhMW%#X}10cr$@#M%Mp%%B@MM&%BBB%%%B@@B8Mh;",
  "                                                          f#W*haM%@$$$$#&%888%BhMW%*c|\\pcn$@#M%oh%%B@$oM8%BBB%%%B@@B&#Z",
  "                                                         '*WMah#8B@$@8$8&%888%BhMW8antjpuU$&#&8k*%%@$@8oM8%BB%%%BB@@%Wo/",
  "                                                         cMWoko&B@$@%MBBW8888%@kMW8bxxzpcw$&#&Ww&%B@$B&ooW8BBB%%%BB@B8Mh;",
  "                                                        I*W#hhM%@$$BWhO$W8%88%@kM8&quvJZYp$8#%#d8%@$@%Mbx*W8BBB%%%B@@B&#Z",
  "                                                        LMMak*8B@$B&or>$M8%88%@kM8MOzXCOLb$W#%aa8B@$B8oL _*&%BBB%%%B@@%Wo\\",
  "                                                       +#W*haWB@$@8*0  $8&%88%@kM&#qhhwqm*$#W&b#8@$@%Mk]  _#&%BBB%%BB@B8Mh.",
  "                                                       qMMhhM%@$@%Mb:  0B&%88B@kM8o(;~\\\\0&$#WWqW%@$@8*Q    v#&%BB%%%BB@B8#J",
  "                                                      1M88B8%%@$B&h]   t$W888B@kM8b{lI;;:w$#8*bWB$@%Wk]     cM8%BB%%%B@@%&o}",
  "                                                     'd&WM&%B8W%8ox    >$&8%8B@kMMw?~~~<>p$#&hh&@$@8*q       LM8BBB%%%BBBBWh.",
  "                                                     cM#qma8B%Mk#0      $%8%8B@kWoO~~~~~~*B#WpW8@@BWh(       'qW8BB88888%BB&C",
  "                                                    .oWMhhM%@BWkp:      d$&%8%@bMbU~~~~~~$%*MpW%$@8#p         'pW%WMWapkW%B8#u",
  "                                                    .aW%%8%B@B&a[       Y$&%8%@b#qc~~~~~~$%*ohW@$BWh(          '*MoW#dmbMB@%Mk:",
  "                                                     CM8%88B@@8*r       -$&88%@bowv))1{}[$&oko&$@8#p            +a*WW**W%@@%Wk<",
  "                                                     I*&%%8%BB%#Y       ;$%8%%@bbp00UzcvJ$#oqW8$B&a|             v#WM*M8B@@%Mb>",
  "                                                      CM88p\\rJ#Wd        %$8%%@bpp?nJJJJq$#abWB@%#d:             vMW##W%@$@8oz",
  "                                                      I*&Zl,_\\cMh:       O$&%%Bddw      }$MkoW$B&ac              wM&dOmq%@%Mb:",
  "                                                       C&U{}(fuk#<       u$%%%Bqkr      }$WpM8@%Md:              o&f,,_(uM8oc",
  "                                                       I#h){)tn0M(       +$@8%Bqhf      z$#w&%B&oz              +#*+i<1fuwWd:",
  "                                                        L8n11\\rX8:       ;8$8%%kk>      0$#d&@%Mb:              tWL+~}tvUk#|",
  "                                                        'kq){(juM!        #$8%%*d>      0$#*8B&oz               /&x~_)rzQ8b",
  "                                                          8t11tnk|        J$%%8*q       0$M&8%Mb?               '8_<?\\nYkM|",
  "                                                          nJ1{\\xQJ        u$@%&om       &@M&%8oL                ?m+~}fcJWf",
  "                                                          !#){(jv8        +%$%&aj       $@M&%Mk?                Jz~_(xXpJ",
  "                                                           mz11tno?      ?z#$8Wh(       $@W88#Q                 a\\<]/uUW!",
  "                                                           ?h){\\xpn    )MWMh$BMbU'    '(&WW&&88Yl              `*+~{jzwm",
  "                                                            ax{(jQm   c##akk@$%doo+  _dMM##MW&8&Mc.            |m~_|nY#!",
  "                                                            |O(\\xJ8` to*o#W@$$$8B&o]1o#*hdda#&88W*Z            Jr~]tcOa",
  "                                                            !81-|/Ja`ko*Mb0hao**#M8%ao*apmwk#&88W#h[           8{+1rX*|",
  "                                                            ?w1\\|vUa?k**W#aWX[zQ-kO1h*#*akh*W8%%&MoO         `mY~}jX0a",
  "                                                            !8nrrYQd!bo#M@$$%h88q&pXh*MWWMWW&8%%8W#h[        nC?}(nrX8",
  "                                                             !uzcJZf uo#W%$$$$$$$$@Wh*M&&&&W&&8%%&MoO        JCf1jUQL8",
  "                                                               fwd0. \\a#WWMMW8B@B8W0LoMW&&&W&&88%8W#h[       `0jjYOm#n",
  "                                                                     ~h#MWMMW8%%8Wow.w*M&&&&W&&8%%&MoO        \"UCZqU!",
  "                                                                     .k*MWMMW8%%8Woq +a#W&&&&W&88%8W#h[        ;uu;",
  "                                                                      ZoMWWMW&8%8Wop  voMW&&&W&&8%%&MoO",
  "                                                                      uoMWWMW&8%%W*p  .h*W&&&&W&88%8W#h[",
  "                                                                      }a#WWMW&8%%&*d   {a#W&&&W&&8%%&Mo0",
  "                                                                      ~h#WWMM&8%%&#b>   J*M&&&&W&88%8W#h;",
  "                                                                       k*MWMM&8%%&#b>   .h#W&&&W&&8%%8MoY",
  "                                                                       Z*MWMMW8%%&#k<    {oMW&&&W&&8%8&#k;",
  "                                                                       uoMWMMW8%%8Mk<     J*M&&&&W&8%%8MoY",
  "                                                                       }a#WWMW&%%8Mh]     .a#W&&&W&&8%8&#k;",
  "                                                                       ~h#WWMW&8%8Maj      {oM&&&&W&88%8MoY",
  "                                                                        k*WWMW&8%8War       m*W&&&W&&8%8&#k;",
  "                                                                        Z*MWMM&8%%Wor       Ia#W&&&W&88%8MoY",
  "                                                                        uoMWMM&8%%Wox        toM&&&&&&8%8&#k;",
  "                                                                        }aMWMMW8%%&oQ         m*W&&&W&88%8Mon",
  "                                                                        ~h#WWMW8%%&*q         Ia#W&&&W&&88&#k.",
  "                                                                         k#WWWW&88&*p          t*M&&MMMMW&8Wo/",
  "                                                                         Z*#MMMW&8W*d           w#Mo#okboW8&Mh.",
  "                                                                         ua**bpaW8&*d           +aao*hwqaW88Wo\\",
  "                                                                         }h*odpo&88#b>           uk*#*aoM8%%WoQ",
  "                                                                         {o*oa*&8%8Mb>           .h*#*oM&%B%Woz",
  "                                                                         m**aoM8%B8#p            ~a##o*M8%B8Mk]",
  "                                                                        Ia*oa*&%B%Wh]            /o#*o*W8%%&*p",
  "                                                                        to*aaM8%B8#0             uo#*o#&%B%War",
  "                                                                        h**a*W%B%Wh]             k*#**M8%B8Mb:",
  "                                                                       }o*oa#8%B8*Q             ;h##o*W8%%&*Q",
  "                                                                       J**aoW8B%Wk;             +a#*o#&%B%Wh(",
  "                                                                      ;a*oa#&%B8*X              uo#*oM&%B8#d",
  "                                                                      to*aoW8B%Wk:              Z*#o*W8%%&oz",
  "                                                                      w*oa#&%B8*z               hM&%%B%B%Wk<",
  "                                                                     _WB$$@B%%Wb.              (%@@@@$$B&#p",
  "                                                                    (%%&8B$$%M*|              -8%Mao8@$@8o|",
  "                                                                   _&8amdW@$BWb              'M8WbOpM@$@%#/",
  "                                                                   d88obo%$$@Wk              fW88#oM%$$$%#p",
  "                                                                  fW8&*M%$$$@Wk              p&%8WW%$$$$%#0",
  "                                                                 '#88M#&@$$$BM0             _M8%&M&B$$$@8or",
  "                                                                 jW8W*M%$$$$8o[             LW%8WW8@$$$@&a]",
  "                                                                '#88M*&@$$$BWb.            '*&%8WW%$$$$BWk>",
  "                                                                Q&8W*M%$$$$%*X             1M8%&M&B$$$$%#d",
  "                                                               lM88M*&B$$$@&h<             p&%8WW8@$$$@8*X",
  "                                                               Q&8W*M%@$$$BMp             I#8%&WW%@$$$@&ar",
  "                                                              I#88M*WB$$$@8o|             cM8%&M&B$$$$BWh<",
  "                                                              U&8BBBB$$$$BWMwLLLv!       ?8&8BBBB@$$$$%WM@@@$#L!",
  "                                                             X8oqaaa&&&8&#***##M8Bj     l&&dmhaaM&&8&W*ooo***%$8_",
  "                                                             #%#ppppppppppppppppp#o     c&%Mpppppppppppppppppk$%k",
  "                                                             d%Bbpppppppppppppboo%w     j&@$appppppppppppppoo8$8U",
  "                                                             ]8$$$$$$$$$$$$$$$$$$w;.....;kB$$$$$$$$$$$$$$$$$$$$b`",
  "                                                             .IXW$$hmmmmmU\\\\\\\\\\]^\"\"\"\"\"^^^!X$$$$$$$$$$&ZZZZZZ))~",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"|\\\\]^^^^```'''...",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
