/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `idle_b` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                      l   U:  [^",
  "                                                                                  t<  Yl  M; ik",
  "                                                                                  ;k\" Ux |a;'M)",
  "                                                                                   qC Uw pq;0k:",
  "                                                                                   \\#\\Ya[$0Y$c }z",
  "                                                                                 t\\:*bbWm$C$b+0d`  l",
  "                                                                                  ZOdWb%k@b@L$ki^zJ\"",
  "                                                                               `Ut1ha#a8*&&d#hQh&u",
  "                                                                                 O#o&$$$$B&a*k$O]",
  "                                                                                 0@$$$$$$$@@BB%mQm>",
  "                                                                                )W$$$$$$$$$$$$dn\\",
  "                                                                                zM$8qmZZOO0QQLJnr",
  "                                                                               0$J??/jffftttt(?/k(",
  "                                                                               &$/   ^+cOc\\>'  ,8J;",
  "                                                                               d$mYf? \"^k`  .{n8hu",
  "                                                                               z$w-    kwQ'  .L$q(",
  "                                                                               _@wn];[zOUu/lI;O$0i",
  "                                                                               +BU0c\\XCUu\\jjt\\m$X`",
  "                                                                              I-8vXj1xzvj{(/|)m%j!'",
  "                                                                             i[1Jf/1?f~lIi[1{)Cpj\"!'",
  "                                                                           ^i1[II_?+]f}l   ~{(/1!\"\"!'",
  "                                                                          .,II^\",,!}))1vv/\\((|>:,,\"\"!'",
  "                                                                             ''``^\",/}[{]]}{{l,\"^'..`;",
  "                                                                   '```.        `'`^Z0Ux\\f//+^'..'.",
  "                                                                ',\",^^`'`\"^      `^<mmqZUuj/~.'.      '^```'`.",
  "                                                               ,;:,;:`````````<;III}OZm0Ynf/+:,,^;  ,\"\"::,^`'`,\"",
  "                                                               !;;,.!,\":::::::~;!>I\"vzcnj|)|l><!;]^I::i-->:^'`\"I>",
  "                                                              :I:;l lY/I~U(i(v?;)?^,?/(1}}|>II,`I+iI:I+}}~;^''\";>\"",
  "                                                              i;:li \"(]:>\\-;/t}Ictl:]({trvv!IrQ[!O<I::l>iI\"'.'`,l<",
  "                                                             `l:;!i` I,^^\"^^^^>II,`;?-)wx] \"I~_:<)<I,^^\"\"^`''.'\";>\"",
  "                                                             !;:Ii!\" !,^^\"\"^^^!II,^IfmWjX} \"I;`,-^>I,^```^^`'.'`,l>",
  "                                                             !:;!iI\" ,:\"^\"\"^^^iI;,^lvWo-O/ \"I;`;+^;!;\"```^^^`'.'^;>;",
  "                                                            :I:Ii!:` ';\"^\"\"^^^il;,^i0hw-L\\ \"I:^l_^^Il:^```^^`''.`,l+",
  "                                                            i;;!iI\"'  I,^^\"\"^^>l;,\">Cqz-U( \"I,^i!^^'iI,^``^^^`'.'^:i;",
  "                                                           `l:Ii!:`.. ,,^^\"\"^`!l;\"\"~J0u-z1 ;I,\"+l^`''i;\"```^^`''.`\"l+",
  "                                                           l;:lil\"'.  .:\"^\"\"^`:!;\",_CJx)v} lI`:]\"^`. ,!:^```^^`'.'^:i;",
  "                                                           l:;i!:`.... ;\"^\"\"^`:!;\":?Xzf1x> II`I+\"^'..`!I,^``^^^`'.'\"I~",
  "                                                          :I:lil\"'. ', ,,^^\"\"`;i;\";}vu\\{f; II^!+\"`...^l>;\"```^^`'.'`:i:",
  "                                                          !;;!i;^...^I`':^^\"\"`;i;\"I)xr{{\\: I:\"<>\"'..',i+!:^```^^`'.'\"I~",
  "                                                         `I:Iil\"'..':>l :\"^\"\"`,>;,l(ft()), I:,_:^'..^;~:\"l,^``^^`''.`,!:",
  "                                                         l;;!i;^. .^l+  ,\"^^\"`.>;,!CohmQCI I,;?:`. '\"!+  II\"```^^`'.'\"I~",
  "                                                         l:Iil,'..`:~:  ',^^\"`.<;^>wWWWWM] I\"I_:'..`:<l   l;\"```^^`'.`,!:",
  "                                                        :;:!l;^. .\"!<    :^^\"`.~;,-0ao*#M] I,ii:...^I-    .l,^``^^`'.'^;<",
  "                                                        !,^^`'`^'`;+.    ,\"^\"^.+;;[kkkkkk- l,~i,..',>~     :I,```^^``'`\"l:",
  "                                                       \"::!i:`'\"I:ii     `\"^^^.+;!{kkkkkk_`l;?:^..^;+.      l;\"`\",\",,^`'\"i",
  "                                                       !:![]!^'^I~-       ,^^^.lI~{kkkkkk_^!I-:` '\"!_        !:;;:>?+;^'^;l",
  "                                                      .!::lI\"'.`;_,       \"^^^.!l?jddddbb^\"il+:..`:~:        `li;;~]+;`'`:<`",
  "                                                       !,^\"\"^'.`:~        '\"^`.i!]\\YUUJJC `>>>, '\"l?          ;i::Il:`'.`:<<",
  "                                                       i;\"^\"^'.':<^      ` \"^^.i<?1||\\\\// .~_;\".`:>I          .!::II\"'..`;+^",
  "                                                       `l\"^+unf~,>^      ^ ,^^.>_~^\"\"\"\"\"\" .~-,`.^I_.          .l::<[_'..\"!_",
  "                                                        i,caMh0Y/i`      . `^^.l-+\"       .>+,'',i~           ,I{ZbpOU}':<:",
  "                                                        l{qh#dCvr[`       ` \"^.;--        .<<,.`;~:           ;?d*%#ZUv1I?",
  "                                                        .{0OZ0Yuj)i       : \"^'I<?        .il\"'\"!]            :cqkaqJvrt>l",
  "                                                         >Q0ZOUvr)>       ; `^`i!]        .>\"^`:<l            !0qbpQzr\\t_",
  "                                                         \"c0OOJcrf        .'.^`,i~        ,l\"`^I-             !wpbqCvf\\(i",
  "                                                          [0OZLzxf         ; \"`:>>        ,:\"`,i~             +qpbmUnt\\}",
  "                                                           Q0ZQXnf;        i `^:<<        ,:\"^;+^             <qddOXr\\('",
  "                                                           n0Z0Ynj:        ;' ^;~^        ,:^\"!_              rqbpLcj\\+",
  "                                                           {0OOJuj+        :, \"I+^        ,:,,;:              zqbqJut/^",
  "                                                           ,QOZCvr?     `;;I! `I_!     .:;;;:,,\",\"            wpbZYx/|",
  "                                                            Y0ZQzx{    lll>+<  `?:!.  ,lI!>>!;,\",:!.         .qdd0cj\\i",
  "                                                            /0Z0Xxf   ,iliI^`'''^^\", :ili+]]~l:\"\":l<         <qdpCut/",
  "                                                            iLLJvfj   ~!l;+|+~)_<]?vm~!l!+?->I,^^,I><        (qdwUx/{",
  "                                                            ;ZpZCYzt  ~!!::l,rOj[wQm0<!IIl!l;,\"^^,;i-       ;OdwUn/|i",
  "                                                            fZLLUj\\/; ~!l;.  ',\"`;1u/<!;:,:::,\"^^\":!+^      QbpOUccx~",
  "                                                            \"vuzu\\11  ~!I;\".       ^!>!I:,:::,\"^^\":l<,      QJU0u\\|\\?",
  "                                                             '\\rj([\"  <!IIlI:\"^`^:!- \">l;,:::,\"^^^,I>!      -vzc/{{\\`",
  "                                                               ??+!  '<lIIlI:\"^`^:i]  <!;:,:::,\"^^\";i-       +f/{]i",
  "                                                                     '<l;IlI:\"^`\";>i  !iI:,:::,\"^^\":!+.       ;I;`",
  "                                                                     '<l;IlI:\"^`\";<>  '>l;,:::,\"^^^:l~,",
  "                                                                     '<l;IlI,\"``\"I~^   >!;:,:::,\"^^,I>!",
  "                                                                     '>l;Il;,^`^,l_\"   :iI:,:::,\"^^\";i+",
  "                                                                     '>l;Il;,^`^,!-     <l;::::,\"^^\":!_",
  "                                                                     '>l;Il;,^`^:!]     !!I:,:::\"^^^,l~`",
  "                                                                     '>I;II;,^`^:ii     ^>I:,:::,\"^^,I>i",
  "                                                                     ^iI;II:\"^`\";<>      ~!;::::,\"^^\";i>",
  "                                                                     liI;II:\"^`\"I~^      IiI:,:::\"^^\":!_",
  "                                                                     IiI;II:\"^`\"I+\"       >l:,:::,\"^^,l~^",
  "                                                                     IiIIlI:\"`^,l-        >!;::::,\"^^,I<I",
  "                                                                     IiIIlI:\"`^,!_        ^iI:,:::\"^^\";i<",
  "                                                                     IiIIlI,^`^:ii         <l;,:::,^^^:!-",
  "                                                                     I!IIl;,^`^;>l         ;!;::::,\"^^,l~",
  "                                                                     ;!IIl;,^`\";~^         '>I:,::,\"^^\"I<,",
  "                                                                     ;!I;;:\"^^\"I+.          il;,:::,,\"\";i!",
  "                                                                     !!I;I;,\",Il-           ,iIlIIll;,\":!-",
  "                                                                     +!l~?~;\"\"I<_            <i!!~]_!,\",I~",
  "                                                                     ~!l~_>:\"\";>i            !<ll~-~I,^\"I<`",
  "                                                                     <lI!l:\"`^:>l            \"<l;Il;,^`\";<l",
  "                                                                     >lI!I,^`^;~^            '<l;II;\"^`\"I~^",
  "                                                                    '>Il!I,^`\"l?             '>l;II:\"^`\"I_.",
  "                                                                    :iIl!;\"^`,ii             '>I;II:\"^`,l?",
  "                                                                    ;!Ill:\"`^:<^             '>I;II:\"`^,!<",
  "                                                                    >lI!l:^`\"I_              '>IIlI:\"`^:>i",
  "                                                                    <lI!I,^`,!<              '>IIlI,^`^;<`",
  "                                                                    >Il!;\"`^:>:              'iIIlI,^`\";~^",
  "                                                                   'iIll;\"`^;+               'iIIl;,^`\"I_",
  "                                                                   ^!Ill:^`\"l>               .iIIl;,^`,l+",
  "                                                                   ;!,\"````,il               :i:^^`'.`,!!",
  "                                                                   ^'''.  `:~.               ;,''`'. .\"il",
  "                                                                  \"^,<~:' ',+                ,^:<~I`  `;^",
  "                                                                 ':\"l]?I' .\"i               :,\"i[]!`  `:<",
  "                                                                 ;,^\";,'  .\"i`              l\"^,I;^.  ':<`",
  "                                                                 l\"^,:^.  .,>`             .I\"`^,^'   ':<^",
  "                                                                 ;^^,,`   ':~.             `;^`^,^.   `:~^",
  "                                                                ,:^\":,'   `;_              ,:^`\"\"^.   `:~^",
  "                                                                l,^\":\".   `I+              l:^`\"\"`.   `;~^",
  "                                                                I\"^,:^.   ^l!              !,``\"\"`.   `;~^",
  "                                                               ,:^^:,`   .\"ii             .l\"`^\"\"`    `;+\"",
  "                                                               !,^\":,'   ',>`              I\"`^\"\"'    ^;+\"",
  "                                                               l\"`\",\"'   ':~^             :;^`^\"\"'    ^I+",
  "                                                              ^,;'..     `:\"'...          ^,\"''`'.   .^;,....",
  "                                                             ,\"i]--+iiiii<~~~~~<!^l      ,,+[<ii;,,\"\":li!!!!l^ \"",
  "                                                             l^,-----------------!!     ,,^;-----------------< ^~",
  "                                                             ~^ ;iiiiiiiiiiiiii\"\"'(CCCCC/,' i--------------ii\" ^!",
  "                                                              `                          ,'                    :",
  "",
  "",
  "",
  "",
];
