/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `idle_b` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                      !   J?  ?!",
  "                                                                                  n?  J?  8? !8",
  "                                                                                  !8! Jm |8?`aJ",
  "                                                                                   aa`J8`m8?J8?",
  "                                                                                   n8JJonaOmq8 ?m",
  "                                                                                 nn!o08X8cmaYnJ8!  !",
  "                                                                                  aa8[o(b-w-b88|`nm!",
  "                                                                               `mnnoQz_1{,<[wx8m8a`",
  "                                                                                `a88r,   '\"[!OrpJ",
  "                                                                                 mCJJJJJJJJJJJJMaa?",
  "                                                                                |8}           _ba",
  "                                                                                J8 \"?[}}{11)((\\d8",
  "                                                                               JJ#qq000Owkkkkho&8n",
  "                                                                               8 0$$$$MYtYLaB$$&\"k?",
  "                                                                               a+xZYq$88<%$$@O#u<8`",
  "                                                                               Jtr@$$$$~])B$$@&Cjm",
  "                                                                               ?CJXwMmr{/nU*#M#LZ|",
  "                                                                              'Xa/1rJf|/nJzzYJa08_",
  "                                                                             'pp8xfz0crxXOLJLQo8&*+",
  "                                                                            _om08YJ0qXk*#am0OQa8q8*~",
  "                                                                           fa0mM&kqbwYZ#$$$kOqWmo88*~",
  "                                                                          )&#M%8&&#MbQ0nxJJLq8*W&&88*~",
  "                                                                           !noBB%88%kW*pkkbM8W&8%B@@%d.",
  "                                                                 `no%BB*J!    !JBBB%}(nQpLO0b8B@@Bw|!   ]]]i",
  "                                                                r&8&8%BBB8O]]]-??m%k}[?}/nXUk@oJ?    |w%%%BBBJ!",
  "                                                               cMW&MW%%%%%%%%%hM##Mm{{}1fuYUbW&&ZvC|b&8WW&%BB%&z.",
  "                                                              I*WM&$*&8WWWWWWWkM*a#&xjxuXCQC*hh*Mw8#WWoppaW%BB8#Z",
  "                                                              v#WM#$*fU#ktLoLxqMQq%&qJQ0ZZCaM#&%#bo#W#bZmkM%BB8Ma[",
  "                                                             .oMW#a$8QwWaJpMJYZMrU*WwLZYzxn*#c)mo{h#WW*haM8B@@%&*Z",
  "                                                             {*WMooB$#&%%88%%%aMM&%Mqp0]vw$8#kdWhQh#&8%88%%B@@B8Ma[",
  "                                                             wMW#a*8$*&%%88%%%o#M&%#Y[:XfZ$8#M%&p%h#&%BB%%%BB@@%&*Z.",
  "                                                            I*WM*a#8$&W8%88%%%o#M&%*x:!p{U$8#M%Mb%WoW8%BB%%%B@@B8Ma\\",
  "                                                            v#W#ooW%$@M8%88%%%a#M&%o)>]p(C$8#W%#d%%#*W8BB%%%%B@@B&#b.",
  "                                                           .oMW*a#8B$$#&%%88%%a*M&8h\\?jp/L$8#&%ao%%Bo#&%BB%%%BB@B%Wa\\",
  "                                                           {#WMooW%@$$&&%%88%%o*M&8k\\)npj0$M#&8b*%%@BoM8%BB%%%B@@B&#b.",
  "                                                           wMW*a#8B@$$@W8%88%%W*M8&d\\/cQnZ$##%Ww8%B@$&*W8BB%%%BB@@%Wo\\",
  "                                                          I*WMooW%@$@@$M8%88%%WoM8WqfjX0ch$##%Mb8%B@$B*#&%BB%%%B@@B8#b.",
  "                                                          vMW#a#8B@$B&$&&%%88BWoM8MZxnCOXM$#M%*b8B@$@%#aM8%BB%%%B@@%Wo\\",
  "                                                         .oWMooW%@$@%#BB&%%88BMaM&MQvcOOJW$#W8hh8B@$B&oQoW8BB%%%BB@B8#k.",
  "                                                         {#W#a*8B@$B&hw$W8%88B&aM&*LYULQ0&$#W&dW%@$@%Mb?t#&%BB%%%B@@%&o\\",
  "                                                         qMWooM%@$@8*0I$&8%88B@hM&oL0p#o*%$#&WqW%@$@8*Q  CM8%BB%%BB@B8Mk.",
  "                                                        I*W#o*&B@$BWk? b@&%%8B@hM8h]::::<h$M8#dWB@@BWh(  'qW8BB%%%B@@B&o/",
  "                                                        cMW*#M%@$@8*X  t$W%%8B@kM&p1iilIIw$#&oa&@$@8#p    +*&%BB%%%B@@%Mk.",
  "                                                       .*&%%%BB%@BMb:  ^$&8%8%@bMMm~~~~~~p$#&ko&@$B&ac     v#&%B%%%%BBB8*/",
  "                                                       fWWoaW%B8#Wor    MB8%8%@bMoZ~~~~~~p%*WqW8$@%Mb:      wM8B&&8&&%BB8o;",
  "                                                      .oWomw*%@%#kp     J$&%%%@*MkO~~~~~~p%o#pWB$B&oL       IoWMMWhqbM%B%MJ",
  "                                                      +*&W##8B@%Md]     ]$8%%%@o#qX___+++%8a*bW@@%Wk]        {#aMMkwbM%@%Wh<",
  "                                                      Io&%88%B@BWb      .$B8%%@oowJtt//\\\\$Bhha&$@8*q          voWW##W%@@BWhf",
  "                                                       mM8%8%B@BWk>      a$8%%@ahqphqmZZZ$@kdM8$BWa(          +*WW#M8B@@%Mb>",
  "                                                       {#8%88%%B&h<      X$&%%@apk>??????$@kp&%@%#d:          +*WW#W8@@@8*L",
  "                                                       .o&80<<\\m8a<      +$B%%@#pd>      $@hb&BB&oz           t#&8OrQhBBWh?",
  "                                                        JWb<I_\\xk#~      .B$8%@Mpp       $@kh&@%Mk?           vM*+`l}/O8#q",
  "                                                        +#q1})fuOMj       b$8%@#kq       $@a*8@8*q            v&x~>?\\xz8a(",
  "                                                         a81}1/n0Mj       u$B%Boow       $@a8%BWh(            w8/+-)rcL8d",
  "                                                         f&c{{\\xY8:       +B@8B&oz       $&#8B8#p             m8-+?|nXpMr",
  "                                                          Yq{}|rv8        .M$8%Waj       $&W8B&ac             (b-+[tuY*a:",
  "                                                          `81})jvo?        m$%%Whf      >$&W8%Mb>             ?m_+1jcLa~",
  "                                                           mx}1tuk?        u@$%Mk>      }$&W88oL              JX+-(xXbn",
  "                                                           n0{{/npn      '(Q&$8Mb>      }$&&&&MQ!             mx+]\\uYW!",
  "                                                           !#1}|x0J    'jMM#o$B#dw_    )bWMWW&&8&0l           8-+}fc0a",
  "                                                            a/}(r0m   .w#*hbk$$BqWo+  c*#*aa*M&8&W*+         `8__1rzb|",
  "                                                            JJ{1fv8   to*o#8BBB@%%8&CQo*obwwk*W88W#h;        ?m_-|nY8`",
  "                                                            ?k(\\xJ8`  bo*MbLbkQdhwh8kko#obqph#&88&#aX        nL_]/vmm",
  "                                                            !*[}\\fJa` ko*WW#&c1zm]bL1k*#M#**M&8%%&Mop       !a|]/vU*|",
  "                                                            Jw||/zCa? k*#M@$$B&8BM8#Zh*MW&WWW&8%%8W*b>      a|-{/xrpn",
  "                                                            !knjnJ0q` k*MM&@$$$$$$$$@hoMW&WWW&8%%8W*k]      8r/1nJCpJ",
  "                                                             !vczLm> .k*MM##W8%%%W*p fa#W&WWW&88%%&#hx      nCjxUZwW!",
  "                                                               Cqbr  ~h*MM##W8%%8Wow .k*MW&WWW&8%%8Mop       ]YJOwf`",
  "                                                                     ~h*M###W8%%8Mar  Uo#W&WWW&8%%8W*b:       |nu~",
  "                                                                     ~h*M##MW8%%8Mhj  ~h*W&WWW&8%%8&#k]",
  "                                                                     ~h*M##M&8%%&#k<   ZoMW&WWW&8%%&#hr",
  "                                                                     ~h#M##M&8%%&#d>   /a#W&WWW&8%%8MoQ",
  "                                                                     ~a#M##M&8%%&*p    ;h*M&WWW&8%%8W*d",
  "                                                                     ~a#M##M&%%%Wow     JoMW&WWW&8%%&#k<",
  "                                                                     +a#M##M&%%8War     }a#W&WWW&8%%&#hr",
  "                                                                     }a#M##W8%%8Mhj      k*MW&WW&8%%8MaX",
  "                                                                     na#M##W8%%8Mk<      uoMW&WWW88%8W*d",
  "                                                                     na#M##W8%%&#d>      ;h#W&WWW&8%%&#k<",
  "                                                                     no#M##W8%%&*p        Z*MW&WW&8%%&Mh|",
  "                                                                     uo#M##W8%%&oQ        }a#W&WW&8%%8MaX",
  "                                                                     uoMM#M&8%%War        .h*W&WWW&8%8W*p",
  "                                                                     uoMM#M&%%8Wh(         uoMW&WW&8%%&#b:",
  "                                                                     uoM##M&%%8Mk<         ~a#W&WW&8%%8Mh]",
  "                                                                     u*MMMW&8%8#b:          m*M&WWW&&8&Max",
  "                                                                     Jo#M#M&8&#*p           /oM###*#W&8Wop",
  "                                                                     bo*kqkM8&MhQ           .ha**bwd*&8&#b.",
  "                                                                     b**kdaW88War            Uh**kpk#&%8Mh<",
  "                                                                     k*#**W8%%Wa(            [h#M#*M&%%8Mh(",
  "                                                                    ;h##*#&%%8Mk>            ~h#M##W8%%8Mk>",
  "                                                                    ~a##*M&%%8#q             ~h#M##W8%%8#d,",
  "                                                                    /o#**M8%%&or             ~a#M##W8%%&*q",
  "                                                                    uo#**W8%%Wh<             ~a#M##W8%%&oz",
  "                                                                    Z*#*#&%%8#p              ~a#M##W8%%Waj",
  "                                                                    k##*#&%%&*z              ~a#M##&8%8Mh<",
  "                                                                   .h##*M8%%Wa]              +a#M#M&%%8Mb>",
  "                                                                   ~a#**W8%%Mb               +a#M#M&%%8#d",
  "                                                                   }o#**W%%8#X               +o#M#M&%%&*Q",
  "                                                                   u*&8%%B%&a(               /oW8%B@@B&or",
  "                                                                   OBBB@$$%Wk:               u&BBB@$$@8o(",
  "                                                                  O%&hkW@$@&b               l&%WhkMB$$%M{",
  "                                                                 1W8*wqM@$@8a;              Q&8omwo%$$BWk.",
  "                                                                 L&%8M&B$$$8o~              *&%&#M%$$$BWh<",
  "                                                                 *8%&W%@$$@&h<             +#8%%&%@$$$BWk<",
  "                                                                _M8%&&B$$$@Wk:             1M8%8&%@$$$BWk>",
  "                                                                cW%8W&B$$$BMd              cW%%8&%@$$$BWk>",
  "                                                                *&%8W8@$$$%#0              qW%%88%@$$$BMk>",
  "                                                               _M8%&W%@$$$%*x              *&%%88B$$$$%Mb>",
  "                                                               cW%8W&%$$$@8oj             +#&%%88B$$$$%Mb>",
  "                                                               o&%8W&B$$$@&h<             _M8%%88B$$$$%Mb>",
  "                                                              I#8%8&8@$$$BWk>             cM8B%&8B$$$$%Mb",
  "                                                             'a&MB@@$$$$$BW8@@@@#u'      ?8&8BBBB@$$$$%M&@@@$#L!",
  "                                                             08owppbooooahkkkkkh*%q     l&&dmhaaM&&8&W*ooo***%$8_",
  "                                                             *%&pppppppppppppppppoo     c&%Mpppppppppppppppppk$%k",
  "                                                             Q%$Moooooooooooooo88BC     j&@$appppppppppppppoo8$8U",
  "                                                             \"w$$$$$$$$$$$$$$$$$Zf......;kB$$$$$$$$$$$$$$$$$$$$b`",
  "                                                             .._YZZU|||||]^^^^^^^\"\"\"\"\"^^^!X$$$$$$$$$$&ZZZZZZ))~",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"|\\\\]^^^^```'''...",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
