/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file The ASCII Punk sprite sheet (SPEC D10): every frame, the loops that
 * sequence them, and the grid they share. Generated by `design/render.mjs`;
 * edit the design project, not this file.
 */

import { rows as idleA } from './idle_a.js';
import { rows as idleB } from './idle_b.js';
import { rows as swayL } from './sway_l.js';
import { rows as swayR } from './sway_r.js';
import { rows as stompL } from './stomp_l.js';
import { rows as stompR } from './stomp_r.js';
import { rows as fistUp } from './fist_up.js';
import { rows as fistsUp } from './fists_up.js';
import { rows as pogoCrouch } from './pogo_crouch.js';
import { rows as pogoAir } from './pogo_air.js';
import { rows as bangDown } from './bang_down.js';
import { rows as bangUp } from './bang_up.js';
import { rows as wind1 } from './wind_1.js';
import { rows as wind2 } from './wind_2.js';
import { rows as wind3 } from './wind_3.js';
import { rows as wind4 } from './wind_4.js';
import { rows as kick } from './kick.js';
import { rows as twist } from './twist.js';
import { rows as strut1 } from './strut_1.js';
import { rows as strut2 } from './strut_2.js';
import { rows as point } from './point.js';
import { rows as sing } from './sing.js';
import { rows as sneer } from './sneer.js';
import { rows as smokeDrag } from './smoke_drag.js';
import { rows as smokeExhale } from './smoke_exhale.js';
import { rows as beerSwig } from './beer_swig.js';
import { rows as beerHold } from './beer_hold.js';
import { rows as hairspray } from './hairspray.js';
import { rows as laceBoot } from './lace_boot.js';
import { rows as tuneUp } from './tune_up.js';
import { rows as n64 } from './n64.js';
import { rows as ampLean } from './amp_lean.js';

/**
 * The grid every frame shares. The cell shape is deliberately absent: the stage
 * measures the font it actually got rather than trusting a number from here.
 */
export const SHEET = Object.freeze({
  cols: 168,
  rows: 128,
});

/**
 * Every frame's art, by frame name.
 *
 * @type {Readonly<Record<string, string[]>>}
 */
export const FRAMES = Object.freeze({
  idle_a: idleA,
  idle_b: idleB,
  sway_l: swayL,
  sway_r: swayR,
  stomp_l: stompL,
  stomp_r: stompR,
  fist_up: fistUp,
  fists_up: fistsUp,
  pogo_crouch: pogoCrouch,
  pogo_air: pogoAir,
  bang_down: bangDown,
  bang_up: bangUp,
  wind_1: wind1,
  wind_2: wind2,
  wind_3: wind3,
  wind_4: wind4,
  kick: kick,
  twist: twist,
  strut_1: strut1,
  strut_2: strut2,
  point: point,
  sing: sing,
  sneer: sneer,
  smoke_drag: smokeDrag,
  smoke_exhale: smokeExhale,
  beer_swig: beerSwig,
  beer_hold: beerHold,
  hairspray: hairspray,
  lace_boot: laceBoot,
  tune_up: tuneUp,
  n64: n64,
  amp_lean: ampLean,
});

/**
 * What each frame is: its group, how much energy it carries, and where it falls in the bar.
 *
 * @type {Readonly<Record<string, FrameMeta>>}
 */
export const FRAME_META = Object.freeze({
  idle_a: { group: "dance", energy: 1, beat: "down" },
  idle_b: { group: "dance", energy: 1, beat: "up" },
  sway_l: { group: "dance", energy: 1, beat: "down" },
  sway_r: { group: "dance", energy: 1, beat: "down" },
  stomp_l: { group: "dance", energy: 2, beat: "down" },
  stomp_r: { group: "dance", energy: 2, beat: "down" },
  fist_up: { group: "dance", energy: 3, beat: "down" },
  fists_up: { group: "dance", energy: 3, beat: "down" },
  pogo_crouch: { group: "dance", energy: 3, beat: "up" },
  pogo_air: { group: "dance", energy: 3, beat: "down" },
  bang_down: { group: "dance", energy: 3, beat: "down" },
  bang_up: { group: "dance", energy: 3, beat: "up" },
  wind_1: { group: "dance", energy: 3, beat: "down" },
  wind_2: { group: "dance", energy: 3, beat: "and" },
  wind_3: { group: "dance", energy: 3, beat: "up" },
  wind_4: { group: "dance", energy: 3, beat: "and" },
  kick: { group: "dance", energy: 3, beat: "down" },
  twist: { group: "dance", energy: 2, beat: "and" },
  strut_1: { group: "dance", energy: 2, beat: "down" },
  strut_2: { group: "dance", energy: 2, beat: "up" },
  point: { group: "dance", energy: 2, beat: "down" },
  sing: { group: "dance", energy: 2, beat: "down" },
  sneer: { group: "dance", energy: 1, beat: "up" },
  smoke_drag: { group: "break", energy: 0, beat: null },
  smoke_exhale: { group: "break", energy: 0, beat: null },
  beer_swig: { group: "break", energy: 0, beat: null },
  beer_hold: { group: "break", energy: 0, beat: null },
  hairspray: { group: "break", energy: 0, beat: null },
  lace_boot: { group: "break", energy: 0, beat: null },
  tune_up: { group: "break", energy: 0, beat: null },
  n64: { group: "break", energy: 0, beat: null },
  amp_lean: { group: "break", energy: 0, beat: null },
});

/**
 * The frame sequences, by loop name.
 *
 * @type {Readonly<Record<string, string[]>>}
 */
export const LOOPS = Object.freeze({
  idle: ["idle_a","idle_b"],
  sway: ["sway_l","idle_a","sway_r","idle_b"],
  strut: ["strut_1","strut_2"],
  stomp: ["stomp_l","idle_a","stomp_r","idle_b"],
  twist: ["twist","sway_r","sneer","sway_l"],
  headbang: ["bang_down","bang_up"],
  pogo: ["pogo_crouch","pogo_air"],
  windmill: ["wind_1","wind_2","wind_3","wind_4"],
  chorus: ["fists_up","bang_down","fist_up","bang_up"],
  climax: ["pogo_crouch","pogo_air","fists_up","kick"],
  front: ["sing","point","sneer","sing"],
  smoke: ["smoke_drag","smoke_exhale"],
  beer: ["beer_hold","beer_swig"],
  n64: ["n64"],
  backstage: ["amp_lean","hairspray","lace_boot","tune_up"],
});
