/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `kick` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                                         ?JJ1;l",
  "                                                                                                                       ?ann\\)(cX",
  "                                                                                                                    `|mpjInfrX0w:",
  "                                                                                                                 `|mpr!^~)JQOpkC",
  "                                                                                                               ?Jpri`,<}/uzOdk&?",
  "                                                                     m   n?                              `|JJJpxi`\"!?(jvUOh*an`",
  "                                                                 |`  8! `8?                           ?na88dx>`^;+{/nzCwMm!",
  "                                                             `m` ?m  8n |8                        `?J888on<^`:>]|jvYQkMn`",
  "                                                              |a``8n 8m a8  ?                   (m88W*b&],\"!-1tnzJZkk|`",
  "                                                               aa!m8?88|p8 ?a                  X&WobwZp8}[}\\rvYLqam|",
  "                                                               !8oaQ8w08[8?8| !m!             t#WhZOwb*8JxnzJ0pMWt",
  "                                                              m|nQoLYC/a(8Q8!n8?              mMW#haM8B@%bqdhW%k{",
  "                                                              `a88~O:ri\\jJxaqo?              IhM8%%%B@$$$$@B%h(",
  "                                                             |J|oX0;I.' +(m8pJ?|             ta#8B@@$$$$$$Bh(",
  "                                                              n8pt<?|JmJJ|?,C8a!            .aMM8@$$$$$$BW(",
  "                                                              !aaJJ??     ^-)8a             t*WWM%$$$$@&*L",
  "                                                              ?8^   .`i-(fnJ0W8m?           wMWM*#8@$$B&aj",
  "                                                              J8[^?)/rX0daM$$$)fm          {*WW#*W%@@@%Mb>",
  "                                                              n8nCOwakL|rm$$W8f]8          C#WW##&%@$@8#p",
  "                                                             !a[%$$$$$mI%$$Wohwl8         IoMWM*M8B@$B&oL",
  "                                                             `ai(Bvd$$Q~]w$$$@M[8         v#WW#*W%@@@BWhj",
  "                                                              ?q;*o$$$m}/vYOLzdz8'_      .aMWM*#&%@$@%Mb>",
  "                                                               JjUOddz|/vXUcXUQ88p*z'    t*WW#*M8B@$@8*p",
  "                                                               `8}/1vJjrXqhLJLL*8Za8b_   w#WW#*W%B@$B&oL",
  "                                                               +#knjX0YZ$$$$a008QdW&8Wz'{oMWM*#&%@$@%Whj",
  "                                                              .qbMLC0wLo$$$$aJkMa&&8%B8dw#WW#*M8B@$@8Mb>",
  "                                                              Chw#*qbdOOa0nQQp8W&8%@B&r+oMWM*#W%B@$B8*p,",
  "                                                             vad#&&W#W*bbbhbMod8%@Bhj' v*WWM*#&%@@@B&om",
  "                                                            'hB@@BB%%%ZOqwqUccJ8Bk) ! laMWW#*M8B@$@%Mhj",
  "                                                               ]\\L*@@@p()11\\rvXbMkWMao#*WWM*#W%B@$@8#b?",
  "                                                       !]CC]]    `??J%8|())/xzUOdqpMaah#WW#*#&%@@@B&*p,",
  "                                                     |a%%%%BBaJJw*MahbkLjxuzJQJhW#88oQh#&8&W&%B@$@%Wam",
  "                                                   ?h8&88%%%%%88&*o&ah&WOL0ZZLX*WY[m*/k#&%BBB@@$$@%Mhj",
  "                                                 !m8&#&WW8WM#*ahkZkW0uo&bY0Xxvp8W*h##bM*&%@@$$$$$@8#d:",
  "                                               `Z8&#kmk$MoqahjvpL{Y#JUa8aOwC<Y8$MW&%#k%MW%@$$$$$$B&a[",
  "                                             `x8&MkwOZp@@z/mBmq#&*oaWW8%*wv+p-z$&WW%Mh%%&8@$$$$$$8d+",
  "                                            |88MhwOZpaM%$&o%BB%%%%%aM&&%#cIlpjt$%WW%Ww%%%@@@$$$LJ-",
  "                                          |h8MhwOZpaW8B@$$W&%B%%%%%#*&W%Ww~+YX|B$WW%Wp%%%@@@8*q",
  "                                        !h8WaqOOpaW%B@$$$$BW8BB%%%%8hWW%&b[}vLtd$MW8&d8%%@@B8*w",
  "                                      !m8WoqOOqaW%B@$$$$$$$W&%B%%%%%o#&88hj(rpj0$8W8&bW%B@@B&oL",
  "                                    `U8&opOOqaW%B@$$$$$$B8%$M8BB%%%%&o&&8octfpzv$@W&8ha%B@@B&ar",
  "                                  `x8&*dZOqaW%B@$$$$$@B&O1 bBW%BB%%%BaW&%#Lrx0JzM$M&8ao%B@@BWaj",
  "                                 |h&#dZOqaW%B@$$$$$@%WXl   ^$&8%B%%%B*#&8MmuvLZUk$WW8o*8B@@BWhf",
  "                               |a%B%MwqaW%B@$$$$$@8Mj'      t$W8BB%%%%aW8&dzXCqLq$%W%*k8B@@%Mk<",
  "                             'k&M#&BB&#%@@$$$$$B8b)          bB&%B%%%BaM&8kJJC0OZ$@W8*d8B@@%Mb>",
  "                             pWomw*%B%##$$$$@B&0l            ^$88BB%%B#*&8o0QQQQQW$M8#k8B@@%#d>",
  "                            +*W#ho&B@%Mp$$@%WrI               z$&%BB%B@hW8*x`````|$8&Mh8B@@8#p",
  "                            +*&WM&B@@%#q@8b)'                  &@8%B%%@o#8#X!!!ii?$%WWw8B@@8*q",
  "                            {#&WM&B@@8odO_                     >$&%BB%B8o&#Z~~~~~~*$#Wq8%@@8*w",
  "                            u#&WW8B@BWk]                        z$&%B%B@hM#w?~~~~~0$*Md%%@B&om",
  "                            vM8Y/xCM%#Q                          &B8BB%@*##q|~~~~~\\$##bW%@B&ar",
  "                            vWc;:?/c8o(                          ]$8%B%@%a#pn__-][{$%oho%@BWaj",
  "                            c&n_]\\nX8h:                           q$8BBB@a*dCtjrnvz#$hh*8@BWhf",
  "                            C8?_}tv0&Q                            I$@%BB@Wodqwbao#Jp$Mh*%@%Mk?",
  "                            f8-_{jcpM]                             r$8%B@@kpd??    ^$%kk%@%Mb>",
  "                            ?b--)xX*z                              .o$8BB@*mb>      &$ab%@%Md>",
  "                            ?m_?|nY8                                {$@%B@Wmh]      z$#h%B8#d:",
  "                            |m_]/vZm                                 Z$%BBBwar      }$8#%B8*q",
  "                            Jn_}fch|                                 IB$%BBhoQ       $B#8B8*w",
  "                            Jx_1rXW`                                  z$B%B&*p       b$M8%&om",
  "                            81_(nQa                                   'M$%B8#b>      t$M&%&or",
  "                            8--\\vqn                                    {@$%%Mk<      >$%W8&*J???????????????????????????????????",
  "                            8[{fz*?                                     p$@%Waj       $8WWWW&&&&&&&&WWWWWWWWWWWWWWWWWWWWWWWWWWW&8hr'",
  "                           mY>?nJ8`                                     IW$B&oz      _#M#**#MMMMM#########################*#*aoM&8Wp'",
  "                          ?b(/rYckn                                     (o@$8*qYl   {o#*kpdhaaahhhhhhhhhhhhhhhhhhhhhhhhhhh*odmd*&8&#Z",
  "                          !bj|nCO#?                                   _pM#*$$Wd*Mc..ko*apmqkhhhhhhhaaaaaaaaaaaaoooooooooah**hbaM8%8Mk<",
  "                           _nxYOC|                                   Ia*obb@$$888%%Mh*#*aha*###MMMMMMMMMWWWWWWWWWW&&&&&&#h#WMMW&%%8Mh<",
  "                            XOqp>                                    Uo*o&MM*hbp0d*fh*MWWWW&88888888888888%%%%%%%%%%%%%%%k*WWMW&8%8Mh(",
  "                             ++.                                     bo*#kCwY]c0]dZnh*W&88%%%%%%%%BBBBBBBBBBBBBBBBBBBB@@@h*MWMM&8%8Waj",
  "                                                                     b**M8&Bhmk$M8B***W8%BBBBBB@@@@@@@@@@@@@@@@$$$$$$$$$$*oMWMM&8%%War",
  "                                                                     toMMB$$$$$$$$$B80W8B@@@$$$$$$$$$$$$$$$$$$$$$$$$$$$$$WaMWMMW8%%Wor",
  "                                                                     .w*W8@$@%%B%8&#h;(aB$$$$$$$$$$$$$$$$$LLLLL/[[[[i    ~h#WWMW8%%Wox",
  "                                                                      +a#W&&&W&88%8MoY  !uLLLLL/[[[[i                     k#WWMW8%%&ox",
  "                                                                       J*M&&&W&&8%8&#k;                                   J*MWMW8%%&*X",
  "                                                                       .h#W&&&W&88%8MoY                                   uoMWMW&%%&*q",
  "                                                                        {oM&&&WW&8%8&#k;                                  +aMWMM&%%&*p",
  "                                                                         C*W&&&W&88%8MoY                                  ;h#&%$$$$BMp",
  "                                                                         Ia#W&&&W&8%%&#k;                                  h8B%8%@$$B*'",
  "                                                                          toM&&&W&&8%8Mo/                                 'M8Wkqh8@$@&w.",
  "                                                                           w#W&&&W&8%%&#k.                                fW8Mdwa8$$@8o[",
  "                                                                           +oM&&&W&&8%8Mo\\                                cW%%8&%@$$@8*x",
  "                                                                            v*W&&&W&8%%&#k.                               cW%BB%B$$$$%#p",
  "                                                                            .h#W&&W&&8%8Wo\\                               cW%BB%B@$$$%Mb",
  "                                                                             {oM&&&W&8%%&#b.                              cW%BB%B@$$$BWh<",
  "                                                                              C*W&&&W&8%8Wa\\                              vM%BB%B@$$$B&or",
  "                                                                              .aM&&&W&8%%&#b                              vM8BB%%@$$$@8*X",
  "                                                                               t*M&&&W&8%8Wa}                             tM8BB%%@$$$@8#d",
  "                                                                                w#W&&W&&88&#Z                             _M8BB%%B$$$$%MhLL*@$p(",
  "                                                                                IoM&WMMMW&8Wo[                            _#8BBB%B$$$$BWM#ohk%$8t",
  "                                                                                 v*#o*hphM8&MZ                            )W8B@@@$$$$&#dpppppk$%b",
  "                                                                                 .wa*obqhM88Wa<                          r8Wk*W&*ohppppppppph8$8U",
  "                                                                                  to*hkoW8%%Waj                         'M8#pppppppppppho8B$$$$0.",
  "                                                                                 .w*okhM8%B%Wk:                         IM%@#pppppo#8B$$$$$dQ[`",
  "                                                                                 t**hk*&%B%&ox                           d%$$%88$$$$$$$Q/[",
  "                                                                                Ia*akoW8BB8#0                            'h$$$$$$$MQ[i",
  "                                                                                C*okhM8%B%Mb.                              ]Q00v[`",
  "                                                                               {o*hk*&%B%Wh<",
  "                                                                              .w*akoW8BB&ox",
  "                                                                              t*okhM8%B8#0",
  "                                                                             Ia*hk*&%B%Mb.",
  "                                                                             QW%8M&%B%&h<",
  "                                                                           !o@B@@$@8%8o\\",
  "                                                                          -&8*bo%$$%#*Y",
  "                                                                         'M8Wbmh8$$BMd.",
  "                                                                         d8&*h#%$$$BMd",
  "                                                                        X&8#ho8@$$$B#X",
  "                                                                       -W8WaaWB$$$@&a;",
  "                                                                      lM8&oh#%$$$$%#n",
  "                                                                     'b88#h*8@$$$BWk.",
  "                                                                     X&8MaaW@$$$@8o\\",
  "                                                                    )W8WoaMB$$$$BMZ",
  "                                                                    p&%Mo*8@$$$@&a<",
  "                                                                   ?&&BBBB@$$$$%WMLLLL]",
  "                                                                  _&WqkaaM&&8&W***###W@0",
  "                                                                  z88pppppppppppppppppaM~",
  "                                                                  j8@appppppppppppppooW#I",
  "                                                                  'k@$$$$$$$$$$$$$$$$$*[    .....................",
  "                                                                    /b$$&OZZZZZ(((((('`````^^^^^^^^^\"\"\"\"\"^^^^^^^^^`````'''...",
  "                                                                             ..'''````^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^^^^```'''...",
  "                                                                                ...''''````^^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                                              .................",
];
