/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `kick` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                                         ~jf]l;",
  "                                                                                                                       <Oo0J0Lr{",
  "                                                                                                                    .[Ykk#vXcf1].",
  "                                                                                                                  [Yh#8%k0/){-_-",
  "                                                                                                               ~nk*8%&hZUuj{_?|;",
  "                                                                     J   u;                                 -nk*&%8*qLzx/)1[?!",
  "                                                                 (   o` 'M;                             `[cboW%%MbOUvj|{{-.",
  "                                                             'U  +X  W] /b                          .^\"}maW%B&awCznt){{!",
  "                                                              }O  *[ 8j MQ  -                    '^\":!+Zk&8*p0Yvj\\1}];",
  "                                                               OZ\"Qp!%Q{$X }C                  ^,:!+]{|OZmZCznt({}_I",
  "                                                               :apCMLBwa%v}Wi i0,             \"I:<}{]+!uzcur/1}{]l",
  "                                                              J[(#b#b8bMoC$X;Xa;              i;:l<i;\"`\"{(1}}1~;`",
  "                                                               OkpMaWMo%q8pU$w;               <;\"^^`'..  \":;l^",
  "                                                             {c}w##MB@@$#&b$d]})             \"iI\"'..      '^",
  "                                                              [pM8$$$$$$$$$$JOU^             i;;\"'      `;",
  "                                                              Id$$$$$$$$$$%pQc/             ,l::;`    .,l-",
  "                                                              +h%$$$@%apLYvrjjMQ!           !I:;lI^.  `,>>",
  "                                                              ukM%qQUcxf/\\|!  Qd/          ^!::Il;^'..`;~^",
  "                                                              f*d\\(t\\rUwC[  :/Bkc          II:;ll,`...^l-",
  "                                                             I$$^     }#^  :!t&*z          i;:IlI\"'..',!-",
  "                                                              Z&m(x_  )kw]   .h&Y         ;l::Il:^'..`:>>",
  "                                                              <*MQ_   [ZJxt{(jL%C         >;:;lI,`...^;+^",
  "                                                               n&pt__jCJnf/rf/f&Zil\"     ,l::Il;\"'..'\"l-",
  "                                                               .hbU0x\\zcf?<(\\(|CY/>\":    !I::ll:^'..`,i-",
  "                                                               .tpvXf)f}    >1|f/_:,\":\" ^!;:;lI,`'..`:<>",
  "                                                               l+Zr\\1]|i    i\\\\t>:,\"^`^:!I::Il;\"'..'^I+^",
  "                                                              I<]<[?+_{{i)u)()/l,\"`'','.i;:;ll:^'..'\"l-'",
  "                                                             ;i_l,,:!?[[[[?[{\\]\"`''^`  ;l::IlI,`'..`:i[",
  "                                                             ^'.''`^^^\\j/tfnnx/\"`\".    >I::Il;\"'...^;<>",
  "                                                                   ..'-LQO0Jcnj+I,;I>!l!;:;ll:^'..'\"I+;",
  "                                                                    .^^CQQQUvj/{+?-;>><I::IlI,`'..`,!-.",
  "                                                      ^^^^````  .!Ii<+~(zcuj\\)\\<:I\"^i)<I,\",:,^'...`:i[",
  "                                                    ^\",\"\"^`^^^^\",l!,>>,:{(1}}|f!:fm[!J~I,^`''..  .^;<>",
  "                                                  `\",l,::\":;l!i<~}~;1u!,~t)jcn-\":l<Il+Il,`'..    .^l_.",
  "                                                `\",I~[~ Ii?><Xx-(OfI\\/>\">{]|hf\" ;:,^I~^;:^.      ',i,",
  "                                               \",I<]1}-''rU}`}?I,lii::\"^!]nb-pj ,::^;<^^\"\".     .^;.",
  "                                             \"\";<]{{->;` ,i^``^^^^^i;,,^IxM*-XY ^::^:]^^`''.",
  "                                           ^\";>]{{->;^'.  ;,```^^^^ll,:^:]kbtfC' ::^:-^^`'.'\"l?",
  "                                         ^\":>?{{->;^'..   `;\"``^^^^\"<::^,+mmn|U+ I:\",_^^`'.'\"!]",
  "                                       `\":i?{{->;^'..      :,^``^^^^iI,\"\"<zLc-z1 \":\",~:^`..',i-",
  "                                     '\",!-{{?>:^'.     .`\"` ;\"``^^^^,!:,^!rYX-rn .:,\"<i^`..',ii",
  "                                    \",!_{{?>:^'.     .`,\"'  ':^``^^^`>;,^I|cv1/jI ;,\">i^`..`:>>",
  "                                  ^,l_}{?>:^'.     .^:^      ,\"```^^`ll,^;}nx|}t< ::^i!\"'..`:<<",
  "                                ```^I]?>:^'.     '^;`         :^``^^`^>:\",_jf|?|? ^:^!~\"'..`;~^",
  "                              ,,;I,`'\"l^'.     '\":.           ',^``^^'i;,\"<\\\\|11} .:\"l_\"`..^;+^",
  "                             I:![]l^'^ll    .`,,               \"\"``^^'I!,\"iO##MMM] ;\"I~\"`..^I_\"",
  "                            .l:I>i,'.^I-  .^:'                  ,^``^`.<:\"lcB%%%%C \"\";<\"`..^I-",
  "                            .l,:I,`..^I?'^,.                    .\"```^'!I\"lf*ooooq `::]\"`.'\"l?",
  "                            `I,;I,'..\"i+\"                        ,^``^'\"i,I}kkkkkk!.I:?^^.'\"!]",
  "                            ;I,-{]+.':~:                          ,````.>;I]qkkkkk1 !;_^^.',![",
  "                            ;<ChoqLn<I+                           '\"```.llI?LkkkkkJ lI+:^.',ii",
  "                            :rdMWqUvjil                            \"^``'`>I-uddpwmZ `i<i`.`:>>",
  "                            :UqdwJuf/[.                             \"```.>l_|UXcunrI <>!^.`:<>",
  "                            IwqdmYx/\\_                              '^``.:i_?||(((~, I<l^.`;~:",
  "                            \"wpdOXr\\(,                             . ^``''<-_\"\"      ^<~^.^;~^",
  "                            <wppQcj\\~                               ' ^`'.l[+^        i+^'^I+\"",
  "                            <wdqCutt                                ` .^`':[<:        I<^'^I_.",
  "                            ]wdwUn/{                                 ^ ^`'`]ii        \"I^`\"l-",
  "                            rqdZXr\\i                                  ' ^`'<!_        `l^`\"!]",
  "                            rqdOcj/                                   , '`':l-         ;\"`,![",
  "                            mppLvt(                                    ; ``^I+^        ;,^,ii",
  "                            wppJn/~                                    `' ^^;<^        ^:\",ll",
  "                            ZmOXr\\;                                     I '`:>i        \":::::::::::::::::::::::::::::::::::::::,\"^'",
  "                           Yaaqutr                                       : `,i<       lIIllIIIIIIIIIIIIIIIIIIIIIIIIIIIIlll!Ili!;,\":I",
  "                          <wLJctrf+                                      i. \"l?'    `il!~-_<>>>>>>>>>>>>><<<<<<<<<<<<<<<<<!!_[_!,\",l>",
  "                          ,YzCu|{|;                                    ;Ill  :_l;,  <!l>-[?~<>>>>>>>>>>>>>>iiiiiiiii!!!!><ll>~>;\"^\"I<`",
  "                           >vvt{?l                                    il!++.  \"\"^`<?<!Il><>lIIIIII;;;;;;;;::::::::,,,,,,l>I;;;:,^`\";<`",
  "                            {{?-^                                    !il!,;I!>+-1jpw<l;::::,\"\"\"\"\"\"\"\"\"\"^^^^^^^^^^^^^^^^```<l;:;;,^`\";>l",
  "                             ..                                      ~!lI<|]fwr)wJJu<l:,\"^^^`````````````````''''''''''''<!;:;;,^^^;>i",
  "                                                                     ~!l;^,`<[~ ;;])+l:\"^``''''''''''............        !!;:;;,\"^^:ii",
  "                                                                     ,!;;'         '^\":^`'...                            ;iI:;;:\"^^:i!",
  "                                                                      !l:\". .^``^^,I<  ^'.                               '>I:;;:\"^^:i!",
  "                                                                      .iI:,,,:,\"^^\";ii                                    <l::;:\"^^,!l",
  "                                                                       l!;,,,::,\"^^,I<                                    !l;:;:\"^^,!>",
  "                                                                        >l:,,,:,\"^^\";ii                                   I!;:;:,^^,l?",
  "                                                                        ^i;,,,::,\"^^,l~                                   'i;:;;,^^,l-",
  "                                                                         ll;,,,:,\"^^\";i>                                   >I,`.   `;-",
  "                                                                          >I:,,,:,\"^^,l~                                   <\"``\"^.  `l",
  "                                                                          ,!;,,,:,\"^^\";i:                                  I^:~?>\". ',l",
  "                                                                           !l:,,,:,\"^^,l~                                 ^:^;_]>\"  .\"!\"",
  "                                                                           .iI,,,:,,\"^\";i:                                ,:^`\",^.  .\"!l",
  "                                                                            ;!;,,,:,\"^^,l~                                ,:`'`^'.   ^I-",
  "                                                                             >I:,,::,\"^\";i:                               ,:^'`^`.   `;+",
  "                                                                             ^!;,,,:,\"^^,l~                               :;^''^`.   `:<`",
  "                                                                              ll:,,,:,\"^\";i;                              :;^''``.   ',ii",
  "                                                                               >I,,,:,\"^^,l+                              :;^''``'   .\"!>",
  "                                                                               ,!;,,,:,\"^\";i\"                             \";^''``'   .^I_",
  "                                                                                !I:,,:,,\"\",l>                              I\"''``'    ^;>   .",
  "                                                                                 i;,:;;;;,\":i\"                             I\"''``'.   `;;I!><^ \"\"",
  "                                                                                 ;lIil<_<;\",I>                            .;\"'...    ,l+-----< ^~",
  "                                                                                  !>!!+?<;\"\";>`                          '^:~!:,li<---------<\" \"i",
  "                                                                                  ,!l>~i:\"`^:>>                          I^l-----------<i\"'    ,",
  "                                                                                  !li~>I\"``^:<                           I`'I-----il\"'",
  "                                                                                 \"!!<<l,^``,!!                           ;^  `\"\"",
  "                                                                                 il>~i:^``\"I~                             ^",
  "                                                                                Ili~>I\"``^;+",
  "                                                                               `!!<~l,^``:>`",
  "                                                                               !l>~i:^``\"!!",
  "                                                                              \"!!~<I\"``\"I~",
  "                                                                              il<~l,^`^;+",
  "                                                                             ::^\"I,^``,>`",
  "                                                                            ''''. .\"^\"!;",
  "                                                                           ,^!+!^  ^Ili",
  "                                                                          ;\":+[<^  `;_",
  "                                                                         :\"\"l>l^.  `;_",
  "                                                                        ^,\"I>!\".   `I>",
  "                                                                        :\":i>:'   .,>",
  "                                                                       ;\",!>I`    ^ll",
  "                                                                      :\"\"l>!\".   ':~",
  "                                                                     ^,\";>i:'   .\"!;",
  "                                                                    .:\":i>;`    `;<",
  "                                                                    I,^;il\".   ',>`",
  "                                                                    ,,`'`'.    ^:;",
  "                                                                   ,;-~ii;,\"\",;!lllII:.,",
  "                                                                  \"\"\"----------------->;'",
  "                                                                  ^\".i--------------ii:IYCCCCCCCCCCCCCCCCCCCCCCCCCCCCC]]]]]]]",
  "                                                                   \".                 '",
  "",
  "",
  "",
  "",
];
