/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `lace_boot` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                                                                  ?",
  "                                                                                                                                                 ?m",
  "                                                                                                                                            `!  ?8!   !",
  "                                                                                                                                         |  nJ ?8m  |a?",
  "                                                                                                                                         8?`8J?oo!!m8?  `|!",
  "                                                                                                                                     !` ?8amqaa/ampa``|ma?",
  "                                                                                                      !nJoBCC?                     !aJp88J|U8Qibm\\*nmo8| !?J?",
  "                                                                                                    'O88&8%&B%bl          ??     `mJI]*#  .?wL_/]#CXq8ma8m|`",
  "                                                                                                   'dWMadBBMW8&o~  lYYkM#*o*<  `nm]fqk$$1i;>]kx?-~}Crdwn!",
  "                                                                                                   f#Woq&$M&8WW*O   wMkppbMMj |wU/p$o\\%$M1i;<(#c}ljb88JJn`",
  "                                                                                                  .oMW#M$dwhB%8Mk>  }#&W&&%Wxmc(fzL$$$%$d*{iI+|#n{\\Q*8?`",
  "                                                                                                  {*WM&$WtuQ&BB%&0'  wW&&&%&OxruJZw(a$#$pU*{il_vM)(Yd888J`",
  "                                                                                                  wMWW$8W#kZ/0BB%8Wc'}#&W&%8wLZqbu~l>-{|XwQ*{!!-0hq8m`",
  "                                                                                                 IoW&$%W#kpqJZWBB%**d_mW8B@B8xr/v)][1jxY@$@k*{i}|am??!",
  "                                                                                                 v#W$$W#kpb#8%0]m*bq8Wa#W0/j8))Y$BxfXQn$$$$$$q)L*a!",
  "                                                                                                 aM$$WMhpb*8%%owbmYh&8ou~!,`8Yf\\$$wJLzY$$$m@$$W8J`",
  "                                                                                                {*B$&Mhpb*8%%%MoZ}rhBB/<\"`:<QhcZm$aYJC0w&@k\\|<k|",
  "                                                                                                L8$&Mapdo&%%%Ma0Oo#B%#}]_?)fnhk0Y0QOZmd*w||Cpmn",
  "                                                                                               IM$%Maddo&%%%*kLw&BB&hqjtjxvUQOdWM****WowbJ|?",
  "                                                                                               j$%Moddo&%%&#dLb%B%#kqCxXCQOZObW@@BB%%88k",
  "                                                                                               $$WoddaW%B8owL*BBWY++}(tjv0bwm8M0]C*@@B&q",
  "                                                                                              0$WodpaW%BMoZ0WB%d{l+nmujp#omCk&8&pI `]Con",
  "                                                                                             0$W*bphWBBMa0qBBWvI>}QLrz@$oLn\\OB@%Mol",
  "                                                                                            }$&*bphWBB*kL*B8b1+-fpXjw$@dJqpZdBMW%8%BBqC?",
  "                                                                                           }$8*bpkW@8#dZ8BMY[}|JOxc*$&OCa%@BW/C&888%%BB%k_",
  "                                                                                          ?$%#kpk&@&owdB8q\\)(umUxO@$hCZ&BB8#&kW&#ah#&%BB&*+",
  "                                                                                         -$B#kpk8$MowMB##j/tLZvuh$BwJhB@%#&%##W#bZZkM%BB8#k;",
  "                                                                                        '#$#kpk%@#haB&m1c#ucCvU8$#QOW@%MM%%%h#WMhpdo&B@B8Mhj",
  "                                                                                       '#$MhpkB@#aW&b/~_]\\#0Xq$$bJh@BW*&%%%Bh#&&WMW8B@@@%Mhj",
  "                                                                                      'a$Whpo$%oM8*J]~~~+]\\#8$&ZO8B&*M8%BB@$h#&&&W&%B@@@8Mkf",
  "                                                                                     'h$Wap*$8*W#d/~~~~~~+fB$o0o@8*o&%B@@$$$h#&&&W&%B@@B8#b)",
  "                                                                                     0$8ad&$MMM*J-+~~~~~~Y$@kq8%#h#8B@@$$$$$h#&&&W&%B@@B8*d>",
  "                                                                                    X$8ok%@MMM*oj1]_~~~}*$&d#BMkhWB@$$$$$$@Bh#&&&W&%B@@B&*p,",
  "                                                                                   z$$oa@BMW#wW%8L(}-+n%$#h8Wkd*B@$$$$$$@%k(h#&&WW&%B@@B&ow",
  "                                                                                  z@$o*$%#WL'I*&bChj1Z$BoM8hqh&@$$$$$$B8O-  h#&&WW&%@@@%Wam",
  "                                                                            ??`  jB$#W$B&*{   tMk(x#B$W*WowqM@$$$$$@B&xl    h#&&WW&%@@@%Whj",
  "                                                                        'rkWW&&8X8$#8@%ML'     q8u0$$###pmaB$$$$$@%k('      h#&&WW&%@@@%Mkf",
  "                                                                       _#M#*#M&WW$8BB&p+       IW$$B##bmd8$$$$$B8O-         k#&&WW&%@@@8#b>",
  "                                                                      +o**W%@8MM$BB8Mc.        >&$8ohwwW$$$$@B&xl           k#&&WW8B@@@8#d>",
  "                                                                      Zo*MdQ#@%8B%W*u         z$$Wadm*$$$$@%k('             k#&&WW8B@@B8*p",
  "                                                                      k**WM*&M@B&M#Mo+      ^b$BWhqaB$$$B8O-                k#&&WW8B@@B&ow",
  "                                                                      k*MW@$p]vB@%&&#a+    }&$8MkbB$$@B&ma?!??????xUUUUYYk&&a#&&WW8B@@B&az",
  "                                                                      J*W&8@%o*vU8B&W#q???C$@&WMM%%8&&&&&&WWWWWWWWWWWM##M##Mo#&&WW8B@@BWaj",
  "                                                                      'qMW88%$&cmWk8WWWWWWWWWWWWWWWMMMMMM####***ooaaaa**hqpoo#&&WW8B@@%Wk)",
  "                                                                       'qMW888@Bk-X#M#######***oooaaahhhhkkkkkbbbbkkh**hqqb*o#&88%BBBB%Mb>",
  "                                                                        'qMW88&8#d*#abdkhkkkkkkbbbbbkkkkkhhhaaooo**o**kqqh#&*W88&W8%B%W*d,",
  "                                                                         'qMW888oa**kwmdkkkhhhaaaoo***##MMMWWW&&&8#**bqphM&%%8Maqqo8BB&aq",
  "                                                                          'LMW88ko##okka*##MMMWWW&&&&888888%%%%%%M*obqpaW88&#bwZmd*%@B&om",
  "                                                                            z#W8bo#WWMMW&888888%%%%%%%%BBBBBBBB@M*odqdo&88OZw#kk#&%@@@8*m",
  "                                                                             c#WhoM&888%%%%%BBBBBBBBB@@@@@@@$$@**odqb*&on<\"i{xb8B@@$$@&aj",
  "                                                                              c#MoM&8%BBBB@@@@@@@@$$$$$$$$$$$@**apqa&p}\"`\"!?\\xY8$$$$$@WZ.",
  "                                                                               c#MM&%B@@@$$$$$$$$$$$$$$$$$LLq#*adoaY>`^I+{\\rvYQ%$$$$@8Q.",
  "                                                                                c#W&%@$$$$$$$$$$$pLL/]]`  iv*$@#p|\"^;<[|juXJ0qW@$@%mx!",
  "                                                                                 c#W8%B@$BBBB%&o+       'mBB%*X>`,i](fuzJ0qa&%%aU?",
  "                                                                                  c#W888&&&&88&Mo+     -h88bx^\"l-)fnzJ0d*%BBU?'",
  "                                                                                   c#W888&&&888&Mq.   x88\\\"<-+1tnzJZk*m|`",
  "                                                                                    c#W888&&&888&#w.'Z88w-_{jnzJmkMWw+",
  "                                                                                     f#W888&&&&&&&Mph%8##nxvUOo&BB8o|",
  "                                                             [[[[[]]]vLLLLLLv] ???xUUY&&WWWWMMM#W&&8%WaqkWao*%$$$@Wk.",
  "                                                          !q@@@@@@@@@@@@BBB@$$8WWMMM##**oaahhhkko&88Mkwqa&B@$$$$@&o~",
  "                                                         Y%%WM&&WWMMM###***&@$BMhhkkkkkkhhhaaoooW%8*dwpo8@$$$$$@&o~",
  "                                                        )W8#wZkaaaaaaaooo**8$$BWb**##MMWWW&&&&8#&8#pwd*8@$$$$$B&q'",
  "                                                        q&%MhkMW&&888%%BBB@$$$@Wk88%%%%%%%%BBB&#&%WahM%$$$$$$BWq'",
  "                                                       ?W&BBBB@$$$$$$$$$$$$$$$BMkBB@@@@@@@@@@@%&WBBBB@$$$$$$B88@$$p\\",
  "                                                      l&WpkaaM&&&&&&888888$$$$%*&$$$$$$$$$$$$M8*mbaa*&&&8&&*ooo**W$Bp",
  "                                                      z88ppppppppppppppppph$$@kYL[[[[[[[]]]iIM%&hppppppppppppppppp%@#~",
  "                                                      f8@Mppppppppppppppoo&W/>              `#%$%bpppppppppppppboo$@*;",
  "                                                      `k@$$$$$$$$$$$$$$$$$*}.................n%$$$$$$$$$$$$$$$$$$$$8_",
  "                                                        fb$$&ZZZZmZ||||||i^^^^^^\"\"\"\"\"^^^^^^^^^j#$$$$$$$$$$kZZZOOj1}^",
  "                                                         ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^i|||``'''...",
  "                                                            ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                          .................",
];
