/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `lace_boot` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                                                                  ]",
  "                                                                                                                                                 }z",
  "                                                                                                                                            ';  }#`   !",
  "                                                                                                                                         }  v| [$/  fmI",
  "                                                                                                                                         *I'@1[$O`>bZ;  `\\;",
  "                                                                                                                                     l. ?&0J#z$oxk@c `fq0I",
  "                                                                                                         '`                        >&$aa$$$mU8%C$MYxh%0i >}z>",
  "                                                                                                     ^\"\"\"\"^,'^,                  ^b$$w~r$$@qQOd@bp$WZmq#*X~",
  "                                                                                                    ;:;>+'`;;\",!'   ``,;Ili!`  `z$%wu/  qaMawCZq@*#&%bv_'",
  "                                                                                                   \"I:!?, ;:^::l<   !I~-_+;I> fh*Uri~C^ uqaMkmUCZ#apkaCz/.",
  "                                                                                                   i;:l; _[>'`\";~\"  ^I,:,,^:ldZQYj(   ^ /Qpo#bOUXqM*qC:",
  "                                                                                                  `l:;, :Yu(,'`^,,   !:,,,^,{vcu\\}]L> l -YQpo*d0z0hhhhhbr^",
  "                                                                                                  !I:; \":l~}U1''`\";, \"l,:,^\"t(}?+nk*hpOCj]v0po*pQXMhz'",
  "                                                                                                  !;, `:I~-?\\}:''^!l: i:\"'.:ZJcUxQwm0zvt. .|0poZCz(;!,",
  "                                                                                                 :I:  :I<-+l\"^)w}l+?\":>I:1JqQ0Qt `vXf)u     ;vQf/|`",
  "                                                                                                 i; .:I<-+l\"^^!]+[t<,\"!nko&%UJYC  ]/(rf   [_ \"zt?",
  "                                                                                                `l` ,;>-+!\"^^^;!}Zc<`'Uh8%WhUYr}[ >t/|)]<z@$qhzi",
  "                                                                                                I\" ,;>-_!,^^`I>1{iI'`ImwdqQYujr|t1)1}[jk$%kUn{~",
  "                                                                                                ; ^;i__i,^^^l<(]:'',<?zYXcxt({{[[[[[j%&wc]l,",
  "                                                                                               ` ^;i__i,^`,l_|+^'^l~?|cf\\({}{+:.''\"I>(>_",
  "                                                                                                 ;i__i:^`\"!](!'':tbbmLUXx)+][\";,   .'',?",
  "                                                                                                :!_->:`'Ii}1:'^_O*bv[uz-I![\\<,\",I     'l",
  "                                                                                               :!+->:``;>)?'`:n#am((cr. !(uC{''^;!",
  "                                                                                              ,l+-<;''l~(!'\"+0bpX-fz] '_\\?-}_`;:^^^`'",
  "                                                                                             \"l~-<:.\"l_}\"`;tmZL\\{vx! ,{|i^'':J|\"^\"\"^``'^,",
  "                                                                                            ^l~-~,.,!]_'\"?JQLu[tc1. <|},''\"I,~:,I>>l,`'`,l.",
  "                                                                                           'I~-~\" ;i];`ItJJY(}nn< ']\\<''^I,^II:I+{}~;^'`\"I~",
  "                                                                                           I<-<`'I>>',[00Uzr|x/\" I){:'`;I^^^>I:I<-+!,`''^;<i",
  "                                                                                          I<-~'.l>:,+Ukdw0Jnf?  +\\<'`:l,^^`'>I,,:;:\"`'.'^;<i",
  "                                                                                       ` :>-i ^!I\"!\\wkkkdqOCI ,}1\"',!;^^`'..>I,\",:,^'..'\"I<>",
  "                                                                                      ^ :>-l \"l:l_UkkkkkkbX` i1i'\"!!,^`'.   >I,\",:,^'..'\"I+!",
  "                                                                                     \" \"i_, ;;I!/pbkkkkkkt .~?\"^l<I\"'..     <I,\",:,^'..'\"l_^",
  "                                                                                    ^ ^i~^.;II!jJ0wdkkkZ! ,_l`;~>:`..     .`<I,\"::,^'..`,!-.",
  "                                                                                   \" .i>'`I:l!:lvYLmpbv^ I>\":~_l`.      '^\" <I,\"::,^'..`,!]",
  "                                                                                  \". !! ^I;;  !}qUcJO{ `!;\">?<,.      '\"^   <I,\"::,^'..`:i}",
  "                                                                                 ^' l: ',l`   \"[LQJr' ;l:!]?I'     .`,.     <I,\"::,`'..^:>i",
  "                                                                         ',::,\"\"^\" I\".^;;      lcC)  III-[>'     '^\"        <I,\"::,`'..^;<<",
  "                                                                        lIIll;,:: \"'`,I.        +> 'Il+}_^     '\"^          <I,\"::\"`'.'^I+^",
  "                                                                      .ill:^'\";; ``^I,            \"!>]]:    .`,.            ~I,,::\"`'.'\"I_\"",
  "                                                                      >!l;_(I.^^'`:!;            :i_[l    '^\"               ~I,,::\"`..'\"l-",
  "                                                                      ~!l:;l,;'',;l;i.         `:<?i'   '\"^                 ~I,,::\"`..',!]",
  "                                                                      ~l;:. -wn`.^:,I>'       \"I~+'  .`,[\\:       .''''``\",,iI,,::\"`..`,i~",
  "                                                                      ll:,\"'^i!nt\"',:Il     .,:II^^^,,,,,:::::::::::;;IIIll;!I,,::\"`..`:>>",
  "                                                                       lI:\"\"`.,xUCO|::::::::::::::;;;;;;IIIlll!!!iii>ill<?-iiI,,::\"'..`;<!",
  "                                                                        lI:\"\"\"'{m*jI;IIIIIllll!!!ii>>><<<<~~~~~~~~~~>ll<??+!iI,\"\"^`''`^;+^",
  "                                                                         lI:\"\",-z+lli+_~<<~~~~~~~~~~~~~~<<<>>>ii!!lil!~??<I,l:^\",:\"`'^:!_.",
  "                                                                          lI:\"\"\"<il!~][_~~<<<>>>ii!!!llII;;:::,,,\"ll!~?->;\"^^\";>??i\"'`,i?",
  "                                                                           ;I:\"\"~illi~~illII;;;:::,,,\"\"\"\"^^^^^^``Il!+?_i:\"^,l~]{[_l^''\"![",
  "                                                                            ,I:\"+iI;:;;:,\"\"\"\"\"^^^^^^```````''''';li+?_!,[Jdq0c(<l,^'.'\"![",
  "                                                                             ,I:>iI,\"\"^^^````````''''''...... 'lli_?++rZaM8oOUv]'..  .\"ii",
  "                                                                              ,IIi;,^```'''''......          .ll>-?\\Ck*8B&oqJvrf     ':>",
  "                                                                               ,III,^''..                    ll>}cwaW%%#bOJznt||    .^:",
  "                                                                                ,I:,`.                      . >Uk#8%WkmCznj\\){|! '`'.",
  "                                                                                 ,I:\"`'..''``^,!.        ''`(Zo&%&awLXuj\\)}}[~I`'",
  "                                                                                  ,I:\"\"\",,,\"\"^,;i.      ljJq*%8*pQYuj\\1}}[>:.",
  "                                                                                   ,I:\"\"\",,,\"\"^,;l    .!Z*8hpb0Yvj\\1}{_;",
  "                                                                                    :I:\"\"\",,,\"\"^,I!  `^]mpdOXvr\\1}{?-`",
  "                                                                                     ^I:\"\"\",,,,,,,;I^^\"-Xzvx/(}]+I\"iI",
  "                                                                                  .''',:::::;;;I;,,\"^:>?{11}}?,  ':~",
  "                                                            ..........'''''. .^;;;;IIll!ii>><<<~!,^^;~]?>,'\"    '\"!'",
  "                                                         `^^:I,,::;;IIIll!!\". `;><<~~~<<<<>>ii!!:^\"l_]-i\".     ',i'",
  "                                                        ':^l]}<>>>>>iiii!!l\"  ':~!llII;;::,,,,\"l,\"l-]_l^.     ',l",
  "                                                        I,^;<<I:,,\"\"^^```''.  ':~^^^^^^^``````\"l,^:i<I`.     `:l",
  "                                                        :,`'``.               ';~'''''.......'^,:`'``'      `\"^..",
  "                                                       ,:-~ii;,,,,\"\"\"\"\"\"\"\"    ^!,            ;\"![+>il,,\"\"\",l!!!!!: ';",
  "                                                      \"\"\"-----------------<  .,`             ;^,<-----------------^.I`",
  "                                                      ^\".;--------------ii,:XLCCCCCCCCCCCCCCQI`.^+-------------+ii..!",
  "                                                       \".                 .                  `^                    ^",
  "",
  "",
  "",
  "",
];
