/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `lace_boot` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                                                                  ]",
  "                                                                                                                                                 }J",
  "                                                                                                                                            'I  }W\"   !",
  "                                                                                                                                         1  ct }$x  fp!",
  "                                                                                                                                         Wi`$\\[$q^>kdl  `/I",
  "                                                                                                                                     l' ?BmLWC$Mzk$J `fpm!",
  "                                                                                                       ,;i<;;'                     >&$##$$$d0%@Z$&Qnh@q~ >}X~",
  "                                                                                                     >++_+~-<+_.          ''     ^k$$d+r$$$kmqh$ah$8pdpMWJ-",
  "                                                                                                    --?1|,;??+-{,  .!l+?][}}:  `X$@dUr  k#8#bZpk$WW%BaU]^",
  "                                                                                                   !]-}tl ?-+-?})   [](/\\(?][ foM0z~+Q^ Xk#8*dOOpW#ko#LXf'",
  "                                                                                                   {?-[+ )/1<~_](I  l]_-__~?-kpw0zx.  \" jwkM&ap0Lk&WkZI",
  "                                                                                                  ;[-?< _QUn_<<+-~   [-___~-rJCUnt/m< ! [QwkMWhqLq*****an^",
  "                                                                                                  []-- i-[(j0j<<~_?< l[_-_~_vxf|)U#&#hpZu1JwkMWkwL8*J'",
  "                                                                                                 .}?+ l-](//ut-<<~[[_^}-+<>-dOC0vmkdqLJn' 'jwhMpZCfli:",
  "                                                                                                 ~]-'\"-])/([+~rbt[|t+-1]-jOkwwwr `UQcrU   . IXwcur^",
  "                                                                                                 {?^\"-])/|[_~~}\\(tz)_+}UoMB$OOQZ  {uxzv.  \\- \"Lv1",
  "                                                                                                ;[I +?1/|}_~~~?}jdC1<<O*@$B#OQXt( +vuxj|_X$$p*L~",
  "                                                                                                _> +?1\\\\}_~~~?{xx}]<~[dbakwQUzznvtrft/zo$@oOY\\?",
  "                                                                                               ._ !?{\\\\{_~~+[)uf-<<-)\\LQLJXvrff/t/t/cB%dC)>I",
  "                                                                                               ; !?{\\\\{-~~_]|v(~<+[)\\nCcnrftf(->><+]{r{\\",
  "                                                                                                ^?{\\\\1-~<+}tv}<<-z*odm0LYr)tf+?~.:!>><_f",
  "                                                                                               ^?}|\\1-~<]}rx-<+|d&oz[XL[l}jc)_+-?.  .:i-",
  "                                                                                               -}|/1?~~?{n/<~?J8Mp|\\Jc' ?uCZf<<+]{.",
  "                                                                                              +[|/)?<<[)u}<_|pohJ-xL{ \"(ct|t(~]-~+~<<l;'",
  "                                                                                             <[(/)->+]\\r_~]cbdZt1Uz> ixv{~<<-On_++++~<<++^",
  "                                                                                          . ![(/(->_}t\\<_/Ommz}rJ\\' {vj_<<_[-)-_]11[_~<~_}\"",
  "                                                                                         . I](/(+i?}t?~[cOO0\\1XY_ ,fc)<<+[-~][-]|rr(?~<<_](`",
  "                                                                                         '^])/)~<]11<-twwOCvfXn: +nr-<~?]+~~)]-])/|}_<><+])]",
  "                                                                                        ''])/(<>]{-_|OoabqOYc1 ')c)<~?[-~~~<1]-_-??_~>><+])]",
  "                                                                                       ; _1/{i+}]_}vkoooabqZ! ijx+<-}]+~~<>>1]__-?-+<>><+]([",
  "                                                                                      ! _1\\[i_[?[\\OooooooaJ` ]x{<_}{-~<<>>ii)]__-?-+<>><_[|-",
  "                                                                                     > i{\\-i??]}vhoooooooj \"1t_+[)[+<>>iiiii)]__-?-+<>><_}\\I",
  "                                                                                    l i{(+>]]]}zOqbaoooqi >\\[~](1-<>>iiiii>~)]__-?_~<>>~-}t^",
  "                                                                                   >'\"{1<~]?[[?[JQmdhoz^`?1_-(\\}~>>iiiii<++,)]__-?_~<>>~-{f",
  "                                                                                  >\"\"}}i+[?_ '}tkOCOq1 ;}?_)t)_>iiiii><_<`  )]__-?_~<>>~?1r",
  "                                                                            ''   l; ?->~-};   itmmOc` ~[-{ft]<iiiii>~-;     )]__-?_~<>>~?)]",
  "                                                                         ;~-__++!> ?_<+]-      ]LZ| ^?][/j1<iiiii<++,       )]__-?_~<>>+](}",
  "                                                                       ^]?][]-_-~ i<~-?\"       .)~ ;][|j\\+iiii><_<`         )]__--_~>><+[|;",
  "                                                                      \"}][?~<+?- !~_]<            <})ff?iiii>~-;            (]__--_~>><_[\\I",
  "                                                                      }}[?\\u[>+iI~-{+           ^-{\\j}iiii<++,              (]__--_~>><_}t",
  "                                                                      )[[-]}_?<<-][]{\"         !-)t1<ii><_<`                (]__--_<>><-{j",
  "                                                                      )[?->>|bY<>+--]1,      .~](|<ii>~-tul '''''':llllll~__{]__--+<>>~-11",
  "                                                                      ?[-__<~}[Yv_<-?]]'''`^,_-]?~~+_________---------?]?]]-}]__--+<>>~?)[",
  "                                                                       ]]-+_+>_X0Zqx--____----------?????]]]][[[}}{{{{[[1/\\}{]__--+<>>~?(_",
  "                                                                        ]]-++_<jdWz]?]]]]]]][[[}}}{{{111))))((((((((1[[)/t|[{]_++~<<<~+]|;",
  "                                                                         ]]-++_\\L([]{(\\))))))((((((((())))111{{}}[[}[[)//)]_[-++--+~<~?}/^",
  "                                                                          ]]-++_1{[[(tf\\))))111{{{}}[[]]]??---____][[(/\\1?_+++?1/t{+<~-1f",
  "                                                                           _]-++){]]{)){[]]]???---___++++++~~~~~~]]}(t\\{-++_[(frj\\[+<<_{j",
  "                                                                            >]-+|}]--??-_++++++~~~~~~~~<<<<<<<<<?]}|t|}_/OhbwCn)[_~<><_{j",
  "                                                                             >]-1{]-+++~~~~~<<<<<<<<<<>>>>>>>><[]{|t|(Xp#%$Mp0J/<>>ii<_1]",
  "                                                                              <]]{]_+~<<<<<<>>>>>>>>iiiiiiiii>[]{\\/uZoW@$@WkOJXziii!i<?{",
  "                                                                               <]]]_~<>>>>iiiiiiiiiiiiiiii,,l][1fCb#%$$8opOCYvnu!!ii>++",
  "                                                                                <]?_~>iiiiiiiiiii;,:`      \"ii}0o&@$%#dZLYcnjfn[><+i;",
  "                                                                                 <]-_~<>><<<~~-{\"        i<<rpMB$@MkmLUcnjft/)]<l`",
  "                                                                                  <]-+++____++_?{,     `?zOkW$$&hwQUznjff/{?l'",
  "                                                                                   <]-+++___+++_]]    ;[pW@#hoq0Uznjff1i",
  "                                                                                    <[-+++___+++_][  >+/dhoqLUznjff/|:",
  "                                                                                     ![-+++_______??~+_\\QLJXurt\\)]_1+",
  "                                                                     ^,,:::,^. ''':lll___----???-___+-1trjjtt\\_!i<?|",
  "                                                           l>>>>>>>>>><<<<<>i>+?-???]][}}{{111))}-++](ft)-<+!!!i<-{,",
  "                                                         !+~-]---??]]][[}}}_>i~]1))))))))111{{}}?+_[\\j/{_>i!!!i<-1,",
  "                                                        :-+[fr(1111111{{{}}_>i<?|[[]]???--____+[_+[/j\\}+>i!!!i~-]",
  "                                                        ]-+?)(]---__++~~<<<>ii<?|++~~~~~~~~~<<_[_+?1)]~>i!!!i~?[",
  "                                                       '-_~<~<>>iiiiiiiii!!!!!<]|<<<>>>>>>>>><+_?~<~~<ii!!!>~_+>>>;^",
  "                                                       _?\\[++~<<<<>>>>>>>>!lli+{-iiiiiiiiiiii?+}r{++~<<>>><-???---><?",
  "                                                      >__?----------------+ll<_!:           .]+_]----------------->>[:",
  "                                                      !_>~--------------++~?LkBBBBBBBBBBBBBBM[~>>_-------------_++i<{`",
  "                                                       +<!!llllllllllllllli^                 l+>!!!!!lllllllllllll!_^",
  "                                                        `;ll;\"\"\"\"\"\"                           \"!!lllllllll,\"\"\"\"\".",
  "",
  "",
  "",
];
