/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `n64` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                      ``",
  "                                                                  !!  ||",
  "                                                                  !a  JJ",
  "                                                               n`  8| ma  `",
  "                                                           ?!  !a` aa`88 !J  `",
  "                                                            JJ` m8?Jon8p?aJ ?a",
  "                                                             J8n!8oaQ*w0moJ?8|",
  "                                                              J8waXoLnCfaqaqa",
  "                                                            `? JqXo[p;1)tZCUJnJ",
  "                                                             |8m80[(<  '(YQm#a",
  "                                                              `m0r~:?nmJ|? ,c8J",
  "                                                            !m888wmJ|!   `<1|d8|`",
  "                                                              `8j`   'I-\\xYw*#J(8`",
  "                                                               8u,`<1tu0b%$$/QQ:m?",
  "                                                               8oitXOawp$$B0tjM-vn",
  "                                                              ^*BwWmv~m$$*zvfrLq\\m",
  "                                                              &$$$$$$~|Q$$$@rnvox8 '",
  "                                                              ^LZa$$m}[fwaZvnvzQopj#0l",
  "                                                               `*$$$O|xzvfxucXUCb8*m8Wr'",
  "                                                                `ZUzcjjUJJvzUCLLpM0p&&8M)",
  "                                                                 r)fUUvJkqwJQ00LWqbW&&8%8p'   `]]i",
  "                                                                .UczLZM$$$$oZZ0a8hW&%BB&j' `na%%BBBw|",
  "                                                                vk0OqqrLLCX0mmoMo88B@8Q'  r&8&W&8%BB8d+",
  "                                                               +odoakkkLCmqk*8wvL8@%0I   cMW#kpk#8BB%Wa~",
  "                                                              .d8@@BB%%%Mppzx\\jnckMdYk#o&oMWawOq*8B@%&o0",
  "                                                                i]vLp$$@W/\\(1(tncChdqk#ba*W&#ah*W%@@B&#k;",
  "                                                                    `?x88Q\\\\\\fuYCUMho%Wpw*W8%888%B@@B8Mar",
  "                                                        `no%%BBon]JO**bpmhzcXUQOLwWWuYa0YoW8%B%8%BB@@%&*p",
  "                                                       -W8&8%%%%%88&hMMaM%*O0mLUxm#&ZqMhka#&%B%%8%B@@B8#k<",
  "                                                      _#W#&88&WM*akbpo&uYWWqJQtfL$BWW88oaMoW8%B%8%BB@@%WoX",
  "                                                      wMW$8W8WapnXpv1LMQwW8hmqn))o$M&&%#k%o#&%B%%8%B@@B&*d.",
  "                                                     ;aM&8$WX{wMcLhM*#o&&88*0_>p}x$8&&%Mp%&aM8%B%8%B@@B8Mh[",
  "                                                     ;aM&&%$hp#BB%%%%%aM&&%MCi>Lu)B$WW%&d%%**&%B%%%%B@@%&oY",
  "                                                      aM&&W$$M8BBB%%%%Wo&&%&b[?n0\\d$W&88ho%8aM8%B%8%B@@B8#b:",
  "                                                      aM&&WW$BW%BB%%%%%aM&88on1/prv$B&&8o*%%#*W%B%%%%B@@%Wa|",
  "                                                      hM&&WW%$8&%BB%%%%&o&&%#C\\/OUn&$W&%#b%%@oM8%B%8%B@@B&*0",
  "                                                      hM&&WW8$$W8%BB%%%%oM&%WpjrXZvm$&&8Mb8%@W*W%B%%%%B@@8Mk;",
  "                                                      hM&&W&8B$$&8BBB%%%&*&88hzuvpYU$@W8Wp8%@@aM&%B%8%B@@%Wox",
  "                                                      hM&&W&%B@$@&%BB%%%BoM&%*LzXZ0C*$W&&k#%@@8oW8B%%%BB@B8#d",
  "                                                      kM&&W&%B@@$%&%BB%%BW*&8WwUJQZ0d$%&8a*8@@@o#&%B%8%B@@%Mh<",
  "                                                      kM&&W&%B@@%$%8BBB%%BhM8&kZqbo**$$W8*b8B@@WoW8B%8%B@@B&oX",
  "                                                      v#&&W&%B@@8&$&%BB%%B#*&8oc11l''x$&8Mb8B@@8o#&%B%%%%BB%Mb",
  "                                                      v#&&W&%@@@8o%$&%BB%%@aW8#X\",,:;_$BWWp%%@B%8%%%88&WM8BB8*[",
  "                                                      v#&&W&%@@B&orb$8%BB%BM*&Mw<~~~~~p$*WoW888bZmk&ohkkkM%B%MZ",
  "                                                      v#&&W&%@@B&aj^&%8BB%B@aWWq|~[jjJbBZZJft>i!l~)zMoo*#&B@%Mk>",
  "                                                      u#&&W&%@@BWh? >$%bqo%BWW8bM##&U1!l/Ydmbp)~_[tnw8%%BB@@BWk>",
  "                                                      u#&&W&%@@BWk>i]w0i}tfJdk0Oappp&upZu{i+xQ8fjrcUd%@$$$$$%Md",
  "                                                      u#&&W8%BB%%%%888mzYcnjttnammpmWY>+}tuYQw8UJC0d%$$$$$$$8o~",
  "                                                      u#&8%88&WMWo\\};<pobp0LJXubJ/cQ8jcJQZpk*&W***%@$$$$$$$Bb+",
  "                                                      /*WMhhbdpb*?,!~-}c$B8&*ap#0/cQ8bk#WB8aMB$$B8wQQQQLLv]!",
  "                                                      +#WhmqbhoMk))\\jnvXa$%BBBB&d/zQ8|?` $@ak%@8#d>",
  "                                                      u#&W#W8%B@%OcYCOda#8$8BB@8d/zqa    z$Wa%B8#d>",
  "                                                      {#8BB@@$$$$@%*&B@m_IB$%B@%d/zpJ    >$%h%B8#d>",
  "                                                       p8B$$$$$$$$$#C]    j$@%BBMULkn     &$M8B8#d>",
  "                                                       'UB$$$$$$L]`        O$BBB%&MY`     t$&&%8#d>",
  "                                                         `[QQ/i            'W$BB%Wa|      ^$BW%8#d>",
  "             Y%%%%%%%%%%%%%%%%%%%%%%%%%%%%W+                                _@$%B&oQ       0$M88#d>",
  "             z&#************************#8*>                                .k$$B8#d.      }$8&8#da8m(",
  "             z&&888888888888888888888888BB*>                                0Yp$@8Wo}       $$W%#da&8&&x'",
  "             z&#########################MB*>                               x0I0WWW&&8hx!   vM#&$$*#8888&&Z!",
  "             z&omvvvvvvvvvvvvvvvvvvvvvvJh%*>                              ~pu#MM##MW&88&hx-#W&%%W#o%BM&888&k(",
  "             z&&L''''''''''''''''''''''1%B*>                             ;pUo#*kdbaM&&&888&8MbmLzLp&@M*&&&88&&x'",
  "             z&&L''''''''''''''''''''''1%B*>                            .0Yh**apmqh#WW&&&&888&*Cfm@$$#aWWW&&888&Z!",
  "             z&omvvvvvvvvvvvvvvvvvvvvvvJh&*>                            X0}h*#*hkh*MMMMWW&&&&888&B$$B*&WWWWW&&888&k(",
  "             z&&L''''''''''''''''''''''1%B*>                           \\p.\\h*MWWMW&&WWMMMMWW&&&&8888&888&WWWWWW&&88&&x'",
  "             z&&L''''''''''''''''''''''1%B*>                          ~p~ ~h#W&88%888&&WWMMMMWW&&&888&8888&&WWWWW&&888&Z!",
  "             z&appppppppppppppppppppppppp%*>                         .p\\   m#W8%BB%%%%88&&WWMMMMWW&&&888&8888&&WWWWW&&88&k|",
  "             z&&L''''''''''''''''''''''1%B*>                        .0X    'pW8B@BBBB%%%%88&&WWMMMMWW&&&888&8888&WWWW&WWW&&&r'",
  "             z&&L''''''''''''''''''''''1%B*>                        x0.     'x8B@@@@@BBBB%%%888&WWMMMMWW&&&88&&88&WWM#ohh#&8Wq.",
  "             z&omvvvvvvvvvvvvvvvvvvvvvvJh%*>                       \\p;        `]JBB@@@@@BBBB%%%%88&&WWMWW&&&WWW&8W*hbpppd*&8&*n",
  "             z&&L''''''''''''''''''''''1%BaX~                     ~p[             !\\CB@@@@@@@@BB%88&&WWWWM##*o*W8&Mkbha*M&%%&*q",
  "             z&&L''''''''''''''''''''''1%Boz0px[.                .0x          i]]vLLL#$$@@@@@$$@&WMM#*oahkbbbbhM88Woh&88%%BB8*z",
  "             z&omvvvvvvvvvvvvvvvvvvvvvvJh%*> .[XpX\\;             00        `u@@@@@@@BB%%8&&W&@$$%#kbbbbbkkhao*#&%%WodBBB@@@B&h;",
  "             z&&888888888888888888888888BB*>     ~x00x~         xp.       -8B8WWWM#**oahkkkba%$$BWkao**#MWW&&88%B%&od@$$$$$%0I",
  "             z&&8%%%%%%%%%%%%%%%%%%%%%%%@B*>        ;[Xpx[.    [p~       lW8&kmpkbbbkkhao*#MWB$$BWh*888%%%%%BBBB@B&ao$@BqC]!",
  "             z&#ppppppppppppW%%%%%%%%%%%@B*>           .~xp0\\;~p\\        QW8Wkwb*#MWW&8%BB@@$$$$BWh#BBBBB@@@@@@$$%MC\\]`",
  "             z8%*oooooooooo*B$$$$$$$$$$$$@*~               >fUpU.....'''+WW%%8W8B@@@$$$$$$$$$$$$BMb%@$$$$$$$$$$$Bk1",
  "             U$$$$$$$$$$$$$$$$$$$$$$$$$$$$%['```^^^^\"\"\"\"\"\",,,,_,,,:::::)&&kaB$$$$$$$$$$$$$$$$$$$%*&$$$$$@d000j11~",
  "                                    ...''```^^^^\"\"\"\",,,,,:::::::;;;;;;;Z8Wbqpppppppppppppppo%$$@&%@$$$#vI'''..",
  "                                            ...''''`````^^^^^^\"\"\"\"\"\"\"\"\"o8@%ppppppppppppppppp#$&kpppbMo",
  "                                                                       r8@$%#o8888888888888B$$#pppppMa",
  "                                                                        Y@$$$$$$$$$$$$$$$$$$$$%88$$$%_",
  "                                                                         !/00000}/M$$$$$$$$$b00000t[`",
];
