/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `n64` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                      ^",
  "                                                                  iI  /_",
  "                                                                  ;0  C\\",
  "                                                               j.  *~ wz  '",
  "                                                           -I  ;w  pC %Q iu  `",
  "                                                            nv. Ydlc*]BZ;#) [O",
  "                                                             ra(,aqJ&Q@wY8}}&>",
  "                                                              foZC#pWkBpMdQ$x",
  "                                                            .- /aokMaW&b$m$O\\vr",
  "                                                             -b0qkMMM$$B88$$0x",
  "                                                               rhM$$$$$$$$$&Qc}",
  "                                                            lXh&@$$$$$$$$%h0LUJ{.",
  "                                                               hB$$$$@#pJcrt\\U$%C",
  "                                                               da&%h0Yuj/~  UQMWQ;",
  "                                                               wboYxt/cf  `1Uzd8q?",
  "                                                               uC/-vLo[  ljxYcYMot",
  "                                                                     kL)   'zuxw&C",
  "                                                               ~z>; [ZmY]>}xuxjnMqIl,",
  "                                                                |   1CcjxXcurf/\\Cd[[\":'",
  "                                                                 |/jrXz/\\/xjt\\((/\\1-,,\";.",
  "                                                                 cQY/tn\\~]]\\(11(t\\+:,,\"^\"I",
  "                                                                 /xj(}I    !}}1|\\>:,^'',`    `````'.",
  "                                                                ;~1{??c((|f)}{)/<\"\"`'\":   ',\",:,\"`'`\":",
  "                                                               'i_i>~]rf|[]}})fn(\"'^,    ,;:I~-~I\"`'^:i'",
  "                                                               :^.''``l+?\\/zYJzur~;:`,Ii,!;;>]{?!\"''`,!~",
  "                                                                     ...:UCL0LYvr|>+?~I+>!::I><!:`'.`,l~",
  "                                                                       \"\"(JJJXuf\\/;>i^;-]!:\"^\"\"\"^`'.'^;>!",
  "                                                          '```''   \"!l+-[<jxj/){|]::nt>1f!;\"``^^^`'..`,!_",
  "                                                        :\",\"^``^^^\",<;;>;^!{1[(/c[I,}?;<~>I,^``^^^''.'\"I<`",
  "                                                       I:I,^\"\":;li<+-i,nf::-\\)UX| '::\"^!i;i;\"``^^^`'.'^:i<",
  "                                                      !;: \";\":>-vf-x0(;)]:\"<[?v0Qi ;,,^I~^il,^``^^`''.`,l+",
  "                                                      >;,^ :fO];r(<IlI!,,\"^!)da-Zv \",,^;-^,i;\"``^^^`'.'^;<,",
  "                                                      >;,,` <-I'`^^^^^i;,,^;\\aa|uQ' ::^,_^^!l,^``^^`'..`,!>",
  "                                                      >;,,:  ;\"`'`^^^^:!,:^,+mqu)C_ :,\"\"<i^\">;\"``^^^`'.'\"I~",
  "                                                      >;,,:: `:^`'`^^^^i;,\"\"iv0J-zx ',,^il^`Il:^``^^`'.'^:>;",
  "                                                      >;,,::^ \",^'``^^^,!,,^I|JU{/u, ;,^l+^`'i;\"``^^^`'.`,l~",
  "                                                      <;,,::^  :\"`'`^^^`i;,^:-Xzf}x[ ,,^;+^`':!:^``^^`'.'^;~",
  "                                                      <;,,::^'  ,\"`'`^^^,!,\"\">run-tt .:\":-\"^'.iI\"``^^^`'.`:i!",
  "                                                      <I,,:,^'. .:^''`^^`!;,^l(rj}1|l :,\"~l^'.^!:^``^^`'.'\"l_",
  "                                                      <I,,:,^'.. `,`'`^^`:!,\";]t/)}1_ ^,\"il\"'.'iI,^`^^^'..^;<`",
  "                                                      ~I,,:,^'..^ ^\"`'`^^'>;\",~xcYOOZ> :\"l+\"'.':i:^``^^`'.`,!>",
  "                                                      :I,,:,^'.'\"\" ,^`'`^'I!,\"!0BBBBBv ,\";+^`.'\"!I\"```````'^;+",
  "                                                      :I,,:,^'.'\"!^ ,^'```'>;\"If8&&WMd `::-^`''^^`^^^\",:;\"`'\"!\"",
  "                                                      ;I,,:,^'.',ii  \"`'`^'Il,;]kkkkkk_ l:({(nuwqmL/~<~~~;`'^;>",
  "                                                      ;I,,:,^'.',>>  `^`'``.>;:?CkbpdpQXqpbkhao*#bQXn_i!l,'.`;~^",
  "                                                      ;I,,:,`'.':<:   )CYx{~+n00cjtxmao*pZCCuvwbdmYuj}^``'..`;~^",
  "                                                      ;I,,:,`'.`:~^  [CoZUXcnuUL/---)ZLLqhobc\\(YXcx/|}..    `I_",
  "                                                      ;l,,:\"`''`^I]nvcrrfrvXYUXcf[-[1OabZUnt([{/\\|11)`      \"i'",
  "                                                      Il,\"^^\",:I1k**Moj?]}1(/jnvcUr)1zr\\)}?_+-}[[[_>'      `:.",
  "                                                      ,!:;><+_-)pa&*kpZx`;i~-]}rcUr)1]-++Ii+>\"  '\".",
  "                                                      .l:>}?+<!}00QJzvxj> ^`'\",1cUr))^'   .><`.^I_\"",
  "                                                      ;I,:I:\"`''/nrf|1{}[\" ^`'._cUr)}      :>`'^I_\"",
  "                                                      ^l\"`''..   !_[?~;:  ' ^''~cUr1<      ^<^'^I_\"",
  "                                                       I\"'                ` .`'lrj([!       ;\"`^I_\"",
  "                                                        ''                 \" ``'l<~!        ,,^^I_\"",
  "                                                                            : `'`:>I        `:^^I_\"",
  "             `^```````````````````````````:'                                 ' ``,!+         ;\"^I_\"",
  "             \",I!!!!!!!!!!!!!!!!!!!!!!!!l\"!^                                 <  `\"I+         \",\"I_i\"`",
  "             \",,\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"''!^                                +>; .^:!\"         ;^I_>,\",,.",
  "             \",+fttttttttttttttttttttttt}'!^                               l+ ,:::,,\"^.    :;I,  ll^\"\"\"\",^",
  "             \",?nnnnnnnnnnnnnnnnnnnnnnnn\\^!^                              '-;l;III;:,\"\"\"\". l:\"^^:li^';,\"\"\",\"",
  "             \",|BBBBBBBBBBBBBBBBBBBBBBBBQ'!^                              -i!l!~_+i;,,\"\"\"\",\";+[(r(-,.I!,,\"\"\",,.",
  "             \",|BBBBBBBBBBBBBBBBBBBBBBBBQ'!^                             +><!l>-[?<I::,,,\"\"\"\",l|Y[.  Ii:::,,\"\"\",^",
  "             \",?nnnnnnnnnnnnnnnnnnnnnnnn\\,!^                            >+\">lI!<~>l;;;;::,,,\"\"\"\",`  'l:::;::,,\"\"\",\"",
  "             \",|BBBBBBBBBBBBBBBBBBBBBBBBQ'!^                           ;- :>l;:;;:,,::;;;;::,,,\"\"\"\"\",\"\"\",::;:::,,\"\"\",.",
  "             \",|BBBBBBBBBBBBBBBBBBBBBBBBQ'!^                          '-' '>l:,\"^^^\"\",,::;;;;::,,,\"\"\"\"\"\"\"\",,::;::,,\"\"\",^",
  "             \",>-------------------------^!^                          -;   il:\"^```^^^\"\",,::;;;;::,,,\"\"\",\"\"\"\",:::;::,,\"\",\"",
  "             \",|BBBBBBBBBBBBBBBBBBBBBBBBQ'!^                         +>     ;:^`'''````^^^\"\",::;;;;::,,,\"\"\",\"\"\"\",::::::::,\",'",
  "             \",|BBBBBBBBBBBBBBBBBBBBBBBBQ'!^                        l+       .\"'...''''```^^^\"\",::;;;;::,,,\"\",,\"\",::;I!><I,\":l",
  "             \",?nnnnnnnnnnnnnnnnnnnnnnnn\\^!^                       ;-            `''..''''```^^^\"\",,:;;::,,,:::,\":l<+---_!,\",!l",
  "             \",|BBBBBBBBBBBBBBBBBBBBBBBBQ'i<'                     '-\"                `'.....'''`^\"\",,:::;;Il!il:\",I~+<il;,^^,l?",
  "             \",|BBBBBBBBBBBBBBBBBBBBBBBBQ'!<+-l\"                  +l                  .......  ',;;Il!i><~~+++<;\"\":i>,\"^^```\"!<",
  "             \",?nnnnnnnnnnnnnnnnnnnnnnnn\\^!^  \">->;              ++          .....'''``^\",:;,'  `I<~++++~~<>i!I,^^:!_``''..',<",
  "             \",[000000000000000000000000j'!^     'l++l'         l-         \"`^:::;Il!i><<~~~i^  `:<>i!lI;::,,\"\"^`^,!_.     ^,",
  "             \",,^^^^^^^^^^^^^^^^^^^^^^^^''!^         \">-l\"     \"-'        :^,<[-~~~~~<<>i!lI:'  ':>!\"\"\"^^^`````''`,>i .'",
  "             \",I------------:```````````''!^            `!-+; '-;        ::^:~]+!lI;:,\"^`'..    ':<I``'''''.... .`II",
  "             \"\"^liiiiiiiiiil'            '!,               \"!~-~.....''''::^`\":\"`'..            ';+`.           '\"'",
  "             .                            ^:'```^^^^\"\"\"\"\"\",,,,I,,,:::::;\",<i'                   ^!,     ......",
  "                                    ...''```^^^^\"\"\"\",,,,,:::::::;;;;;;;l\":+?---------------!^  ',^.   '\"^'''..",
  "                                            ...''''`````^^^^^^\"\"\"\"\"\"\"\"\"!\"'^-----------------l ,~---+;i",
  "                                                                       \"\". `li\"\"\"\"\"\"\"\"\"\"\"\"\"`  l-----;i",
  "                                                                        `'                   .^\"\"   ^",
  "",
];
