/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `n64` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                      ^.",
  "                                                                  il  t?",
  "                                                                  Iw  Lf",
  "                                                               r.  W- pC  '",
  "                                                           ?l  Ip. kO @m ic  `",
  "                                                            cz. ChiXW{$plM/ [w",
  "                                                             u#/:#k0Bm$bCB(}%+",
  "                                                              xMqO&k%o$h&aZ$z",
  "                                                            '? j#Mo8#8Ba$d$qfcn",
  "                                                             [aZbo888$$$BB$$qX",
  "                                                               v#8$$$$$$$$$%wC|",
  "                                                            !J*%$$$$$$$$$@*wZ0Z).",
  "                                                               *$$$$$$WkOJzvu0$@Z",
  "                                                               a#%@*wQUcu? .0w&%wl",
  "                                                               baM0XvuCu. `|0Lh@k}",
  "                                                               vLj{JmM{  !ncQC0&Mn",
  "                                                                     *O|   `CUYb%Z",
  "                                                               +Y>I {pdL}~)zUXzU8k~]<.",
  "                                                                /   (ZCzYLCYzcvuZhtf+-I",
  "                                                                .frcXLCuuuXcvnxxvvn/__+?,",
  "                                                                 Cq0uvYx[11nrjjncc|-__+~_?     ..",
  "                                                                 vXzrf!    +tfrnv1-_~<<_I   ,>~~<<<!\"",
  "                                                                ~)jf\\\\Jttfcrtfxv1++<<_+   I_+_-_+~<<+_\"",
  "                                                               \"}\\}{1/zcnt/ffrzYn+<+~.   <?-](/(]+<<+?1:",
  "                                                               _+><<<~[)\\nuC0OCUX)]_l~]{_}??1fx/}_<<~-{)",
  "                                                                  \":I>>>-OZmqmQJXu1|/)[|1}?-]1)}-~<>~_[|`",
  "                                                                     ':++xOOOQUcnv?1}~?tt}?+++_+~<<><+]1?",
  "                                                         :>~~<<i,.;<[[(/f1zXcurfnt--Yv{rz{?+~~~++~<>>~-}/",
  "                                                       `-+_+~~~~~++_)??{?~}jj/xuC|]_f\\?))1[-+~~++~<>><_](:",
  "                                                      ^]-]-++_-?[{)|/}_Yc-?tnrOQx ;--++{1?{?+~~~++~<><+?1{",
  "                                                      []? !?_?1/Cz/Yqx?r/-_)t/JZw< ?__~[|~{[-+~~++~<>>~_}\\",
  "                                                     '1?_> +zq/?Xx)][]}__++}xo#-pY i__~?/~-{?_~~~++~<><+])!",
  "                                                     '1?__! {|]<<~~~~~{?__~?vMM|cw`'--~-\\+~}[-+~~++~<>>~-{}",
  "                                                      1?__-^`]_~<~~~~~-}_-~_|bkz(Z] __+_){~+1]_~~~+~<<><_[|`",
  "                                                      1?__-- ;?+<<~~~~~{?_++{Cq0-Jz :__+{}~~[}-+~~++~<>>+?1~",
  "                                                      1]__--< >-~<<~~~~-}__~]vO01rU: -_~[|+~<{]_~~~+~<>>~_})",
  "                                                      )]__--+I __~<<~~~~{?_~-/LCn{X) ~_+?|+~<?}-+~~++~<><+](`",
  "                                                      )]__--+<, ++<<~~~~_}_+_)XUY-uv \"-+-/+~<>1]_~~~+~<>>~-1?",
  "                                                      )]__--+<>'\"-+<<~~~<{?_+[nzc)\\x< +__([+<>+{-+~~++~<><_[\\",
  "                                                      (]__--+<>! l_~<<~~~?}_+?fvuf(j{ l_+{}+<><{]_~~~+~<>>+?):",
  "                                                      (]__--+<>>< i+~<~~~<1?+_(YJQqqp>'-+[|+<><?{?+~~++~<><-{}",
  "                                                      ~]__--~<><_< ++<<~~<]}_+{q@$$$$c ~+]|+<><+{[_~~~~~~<<~]|",
  "                                                      ~]__--~<><_{;'-~<<~~>1?+]XBB%%8h ;--/+~><~+~~~++_-?+<<_}!",
  "                                                      ~]__--~<><-1] ^_~<~~<][_?f*ooooo? [-nfrYUbkdZv)))((]~<+]{",
  "                                                      ~]__--~<><-1[  !+<<~<>1??tmoahhkmJbhao*#MW&omQU\\{}[_<>~?(;",
  "                                                      +[__-_~>><?)i   jZQXf1(YwwCnxzdMW&hpZZUJkoad0Uzj~~<<>>~?|;",
  "                                                      +[__-_~>>~?(; .(Z&bOQCUU0mf---rdwwhW&#CnxQLCXunf>>>iii~]/",
  "                                                      +[__-+~<<~+?/YJCXXcXJQOOQCu}-)jb&#bOUcrtrunxjjr~iii!!>_{:",
  "                                                      +[-+~++_-]roW&8Wz\\\\tjxuzUCCOXrrQXurt\\()|t///({<!!!!!!~-\"",
  "                                                      >}-?1)(\\/nh#@&*hdY,~}1|\\tXCOXrr\\())~[(1+i>~_!,,,,,,^",
  "                                                      \"[?1jt|)}fwwwOLJXc? <~<+_rCOXrx;\"   \"1(~>+[/I",
  "                                                      +[_-]?+~<<uYXvxjft/l +<<>(COXjt      _1~<+[/I",
  "                                                      I[_<<>>>iii[(/\\1?~^.,^~<<1COXj[      l)+<+[/I",
  "                                                       ?_<iii!!!!!i!:.    I ;~<]zzx/_      `?+~+[/I",
  "                                                        l<i!!!i>:.         i i~<]1)-        ~_~+[/I",
  "                                                           ,,`              ~ ><~?)+        ;-++[/I",
  "             !~~~~~~~~~~~~~~~~~~~~~~~~~~~~-,                                \",.~~-{(         ]_+[\\I",
  "             >_]}}}}}}}}}}}}}}}}}}}}}}}}[_};                                 } \"~+[\\         >-+[\\{+i\"",
  "             >_-_+++++++++++++++++++++++<<};                                +<_ I+?{l        '?~[\\1_+_-;",
  "             >_{xxxxxxxxxxxxxxxxxxxxxxxx|<};                               l+ ~--___+<:    ~+--!>}[++++__>",
  "             >_{nnnnnnnnnnnnnnnnnnnnnnnn/~};                              '-i]??]]?-_++_~:`[-_~+-[{+<]_+++_~\"",
  "             >_nBBBBBBBBBBBBBBBBBBBBBBBBm<};                              -~}][)\\|{?__++++__?|juYu/_>]}__+++__;",
  "             >_nBBBBBBBBBBBBBBBBBBBBBBBBm<};                             +<)}[1/jt1]--___++++_[nQt>i>[{---__+++_>",
  "             >_{nnnnnnnnnnnnnnnnnnnnnnnn/~};                            >+l1[][1(1[????--___++++_<il~}------__+++_~\"",
  "             >_nBBBBBBBBBBBBBBBBBBBBBBBBm<};                           ;- >1[?--?-__--????--___+++++_++__------__++__;",
  "             >_nBBBBBBBBBBBBBBBBBBBBBBBBm<};                          '-' ,1[-_++~+++__--????--___+++__+++__-----__+++_>",
  "             >_--------------------------~};                          -;   }[-+~~<~~~~++__--????--___+++_++++_------__++_~\"",
  "             >_nBBBBBBBBBBBBBBBBBBBBBBBBm<};                         +>     ?-+<<<<<<~~~~++__--????--___+++__+++_----__--_+_I",
  "             >_nBBBBBBBBBBBBBBBBBBBBBBBBm<};                        l+       ;+<>>>><<<<~~~~+++_--????--___++__++_--?]}11]_+?]",
  "             >_{nnnnnnnnnnnnnnnnnnnnnnnn/~};                       ;-          .;~<<>>><<<<<~~~~++__-??--____-__+-[1(\\/\\|[_+-}-",
  "             >_nBBBBBBBBBBBBBBBBBBBBBBBBm<]~'                     '-\"              ^;~<>>>>>><<~~++___---??][}[-+_](|){[?_~~_}t",
  "             >_nBBBBBBBBBBBBBBBBBBBBBBBBm<[_+-l\"                  +l             ^:::!>>>>>>>ii<_-??][}{1)((||1?++?{)_++~~<<_}{",
  "             >_{nnnnnnnnnnnnnnnnnnnnnnnn/~};  \">->;              ++         ,>>>>>><<~~++_-?_<i>~])((||(()1{}}]_~+-{\\<<<<>><-)`",
  "             >_/wmmmmmmmmmmmmmmmmmmmmmmmc<};     'l++l'         l-        `+~+---?][}{1)((||1+ii~?(1{}[]?--__++~<~-{/>iiii>+~'",
  "             >_-+~~~~~~~~~~~~~~~~~~~~~~~<<};         \">-l\"     \"-'        ?+-(j/||||(()1{}[]-<ii<?)}+++~~~~~<<<<>~-1{>><l;.",
  "             >_-------------+~~~~~~~~~~~<<};            `!-+; '-;        _-+?(f\\}[]?-_++~<<>>i!i<?([<<<<<<>>>>>i>~]-^.",
  "             >+<~++++++++++~>iiiiiiiiiiii<}l               \"!~-~.....'''\"?-~~_-_~<>>>iiiii!!!!!i~]\\~>>iiiiiiiiii<+;",
  "             Ii!!!!!!!!!!!!!!!!!!!!!!!!!!!+!'```^^^^\"\"\"\"\"\",,,,I,,,:::::i__(1<>iiii!!!!!!!!!!llli+}_iiii>>lIII,^^`",
  "                                    ...''```^^^^\"\"\"\",,,,,:::::::;;;;;;;?_-|[---------------~>!i<-+<i>!>i\"'''..",
  "                                            ...''''`````^^^^^^\"\"\"\"\"\"\"\"\"{+<<-----------------~i-1---_+1",
  "                                                                       i_>!>~+>>>>>>>>>>>>>il>}[----+1",
  "                                                                        !<!lllllllllllllllll!>>>>!l!+\"",
  "                                                                          '\"\"\"\"\" 'llllllllll,\"\"\"\"\".",
];
