/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `pogo_crouch` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                        !",
  "                                                                                                J!  |  !J   ?`",
  "                                                                                                |m !8  mn  ?m",
  "                                                                                                ?8!?8`|8? ?8!",
  "                                                                                                ?8mJ8?a8??8m",
  "                                                                                              `a`8p8paL8?*8` !`",
  "                                                                                             ? ma8]8(8]8a0n!mJ",
  "                                                                                             naJqo?0lntJ}8aoJ   `",
  "                                                                                              ao8>~\";;_`0unJ?nJa!",
  "                                                                                             |aoCJJ?]1\\frc88aa|",
  "                                                                                            ?8,  ^?????]]]\\8J`",
  "                                                                                            a8  ''''''''`I/88an",
  "                                                                                           |8LI(/tttfffjjjr88",
  "                                                                                          ?mI$$8##88*wqpB@$*wn",
  "                                                                                          ?w,qoo$$ht[mM$$$$z[8",
  "                                                                                           8\"wqpw$a|)M$$&Y8:XJ",
  "                                                                                           a?MW$$$U?1c$$$$8'k?",
  "                                                                                           J(n/cJ{1/uzXmwZ8ia",
  "                                                                                         'rMd/(X0/trvLzYJL8rn",
  "                                                                                        r*mm0vzQmxw*WaJL0Q8q!",
  "                                                                               ]]]i    -MohMaLOpOZ$$$$$Z008m-Yd|",
  "                                                                            |m%%%BB%x'  'Y8%8hkqJ0W&#$MQwWk*dO*k.",
  "                                                                          !h8&8MBBBB8#+   lk%%88hmCzQO0p8pQQq*%M\\",
  "                                                                        `Z8&#k$MM%BBBB&C]-? (&%UQ*Woo*Wo*k#W&&88a:",
  "                                                                      `x8&MhwO$WM&8%%%BBB##&hZ&u[??(rcU0MM88%%BB&Y",
  "                                                                     |&8MhqOOq$W{naWw#888o**#M&f[?](rcUQ&@@$$$$$LU`",
  "                                                                   (h8WaqOOqhM$Wpb#U|LMuzd*aM&%x((|fvYCm@B\\]]",
  "                                                                 !m8WopOOqhM8B$&W&&Wo88ULbO]XBWQuvzUQ0LoW&&&z(`!Jo%BB*J?",
  "                                                               `U8&*dZOwhM8B@@$&W&&W&%%%o*hqM%o0OOZm0wah*M&Mb%&88888%BB8bl",
  "                                                             `x8&#dZOwk#8B@@$$$&W&&W&%%%a*aWB&ddq\\/tXhopCo8k#MWWokh#8BB%8Wr",
  "                                                            |h&#bmOwk#8B@@$$$$$&W&WW&%%%h*a8%*/}+tvm$&aUnp#\\oMW*pOmhW%BBB%&bl",
  "                                                          ?h&MkmOmk#8B@$$$$$$B$8W&WW8%%Moo*%&pIIu0/8$*hWB&d0aMW#hdk#8%BBBB%8Wr",
  "                                                        !m8WhwOmk#8B@$$$$$@B&O$W&&WW8%%a*oW%*jl~Zjx$Boa%%ooMaM&8&&8%%%%%BBBB%&bl",
  "                                                      `U%%WbOmb#8B@$$$$$@%&0l $#&&WW8%Bh*a%&d-_fm/m$WhMBWd%WaM8%BBBBB%%%%BBBBB8Wr",
  "                                                    'Y888%BB#*8B@$$$$$@%Wr'   $#&&WW8%%h*#%#v[{0Xr&$*h%8ao%%oM8B@@@@BB%%%%%BBBB%&bl",
  "                                                    pW*pbM%B8o8$$$$$@8b)'     $#&&WW8B#oo&8b\\(rprC$8a#%Md%%%B#&B@@@@@@BB%%%%BBBBB8Wr",
  "                                                   {#WaqbWB@8*o$$$B8O1       ^$M&&WW8Bo*a%ML/tJLuh$#h%8kW%%B@$8&%B@@@@@@BB%%%%BBBB%&bl",
  "                                                   u#&&W&%@@8*p$B&0l         }$M&&WW%@k*M8knrxpzX@@o*%#k8%B@$@BW*8%B@@@@@BB%%%%%BBBB8Wr",
  "                                                   +*&&W&B@@8okWr'           }$M&&W&B8a*&M0nuCmYp$&a&&b#%B@$$B&ox'Y8%B@@@@@BB%%%%BBBB%8bl",
  "                                                   +*&&W&B@@8ar'             }$M&&W&@***8hqCzCCCW$*o%ok8B@$$@8*0   lZ8BB@@@@@BB%%%%BBBB%Wr",
  "                                                   ;o&88Zw8%&h>              }$W&&W8@a*WWJ)Udaqp$Bo&WpM%@$$@8#O.     !Z8B@@@@@@B%%%%%BBB%8bl",
  "                                                    a&O,:?/b&b,              }$W&&W%$h*8h\\!!!-fW$W*8ha&@@$@%Mk<        !Z%B@@@@@BB%%%%%BBB%8|",
  "                                                    a8)~_(xc8d               }$W&WW@WoW#Q~<>i!lo$*&MqM%@$@BWh~           -h%B@@@@@BB8&8&W8%B%k_",
  "                                                    C8[?}/uX8Q               \\$W&W&$o*Wpt~~~~~|$8#8bo&@$$B&ax              (h%B@@@@%#W*pqa8BB&o~",
  "                                                    v8u?}/uO&r               Y$&&W8$hMhQ~~~~~~0$#W*d#B$$B8*Y                 (h%B@@M#Wopqo8BB8*X",
  "                                                    IWu?}tuZ#:               Y$&&WBBh*wf~~~~~~%%*Wd*&$$@8#O.                   (&%B*#&&WW8B@@8*q",
  "                                                     Ju?}tvZJ                U$&&W$#odw1}]-++n$##od*@$@%Mb;                     'x8**&%8&8B@@8#q",
  "                                                     Ju]}tvdJ                O$&&&@ohpmJnjt|)k$k#d*8$@%Wh<                        'joW88&8%@@%#p",
  "                                                     Ju]}tvh?                #$&&%@bdp_JJ*k0Q$8aha#$$B&ar                           mM88oOxw#8#p",
  "                                                     Ju]}fvh?                #$&&B&bk(    `?p$#ad*%$B&oX                            /#&ZI^i{tbWd",
  "                                                     Jw]{fc*?                M$&&@*kp       b$kd*M$@8#O.                            ;o8n+<[/nY8d",
  "                                                     ?w]{fc8`               .B$&8Bbaj      >$%kb#@@%Mb;                              C&c{})tnz8d",
  "                                                     ?w]{jc8                ~B$&B%od:      z$WpM&@%Wh<                               {Mq{}1/nc8d",
  "                                                     ?k\\fv08                +B$&B&az       &@*aM@B&a|                                .d#1}{\\xc*f",
  "                                                     at>|jron               +B$8%Mb:      }$8*W8B&ox                                  l8/}}|rvh?",
  "                                                    !8\\(|cCpJ               {B$8&oz       0$MWW@8*0.                                   Jc{}(jvh?",
  "                                                     JnrnJOk?            -YYw@$8Mb>      ^$BWWB%#b.                                    |q{})fukn",
  "                                                      jzY0w,           )MMMMa@$&oq       t$&W&%Mk<                                     `#1}1tuOJ",
  "                                                       zdZ~           v*#abkh$$8kbv      p$W&%Wa|                                       ar}{/nOJ",
  "                                                                     }a**WW8@$$$oMa}  lOWWW&&8&*l                                       JU}}\\n0J",
  "                                                                     uo##hCk#M&%B@B&/c#M#**MW&8&WOl                                     ?q{}|xC8",
  "                                                                     uo##8&%Y?zkJb8%*o#obqdaM&888&&O-                                   `8|\\rzX8!",
  "                                                                     /oMMB$$%hob/MO>h**hqmpaM&&&888&&b(                                 |b!l{frLa",
  "                                                                     .q#W8@$$$$$@%dOa*#*aho#WWW&&&888&&k(                               Jw\\\\)uJL8!",
  "                                                                      'qMW8888%@$$@oa#MWWW&&&WWWWW&&888&&k(                             !#XnxY0dm",
  "                                                                       'oM&888&&&8%#a#W88%%88&&WWWWW&&888&&k(                            !zzXLmr",
  "                                                                        +oM&888&&&88a#W8%B%%%888&&WWWW&&&888&kr'                           (0b\\",
  "                                                                         +*M&88&&&&88#&%BBBB%%%%88&&WWWW&&&888&Wr'",
  "                                                                          _*M&88&&&&88&8%BBBBBB%%%88&&WWWWW&&888&Wr'",
  "                                                                           1*W&88&&&&8%8&&%%BBBBB%%%888&WWWWW&&888&Wr'",
  "                                                                            v*W&88&&&&8%8W**a%BBBBBB%%%88&&WWWW&&888&Wx'",
  "                                                                             c#W&88&&&88%&Mo}!U%%BBBBB%%%88&&WWWW&&888&WYl",
  "                                                                              c#W888&&&888&Mh. '|m%BBBBBB%%%88&WWWW&&&88&&Ol",
  "                                                                               c#W888&&&888&#m    !n8%BBBBB%%%88&&WWWMWWW&&8Ol",
  "                                                                               'q#&88&&&&8%8W*u      ?m%BBBBB%%%88&&*#*aa#&8&#+",
  "                                                                                'qM&88&&&&8%8Mo+       `na%BBBBB%%%#**bwqaW88Mh;",
  "                                                                                 'qM&88&&&888&Mh.         ?J%BBBBBM*obqph#&%8War",
  "                                                                                  'pM&88&&&888&#m           '|a%BM*obqdaM8%B%War",
  "                                                                                   +oM&88&&&&&&&#u             !#*obqdoW8%BB%Wk]",
  "                                                                                    +*W&8WMM#MW&&#+            z*obqboW8%BB%&*n",
  "                                                                                     _*MMMobqb#&8Mh.         'q*odqb*&8BBB%Wa}",
  "                                                                                     lbMobwmphM88Wo|        'q*odqb*&%BBB%Mw~",
  "                                                                                   lOMobwmph#&8%%&or       'q*adqk#&%BBB8#Z.",
  "                                                                                 lOMobwmpaM&%%B@B&h?      'q*apqh#8%BBB&*u",
  "                                                                               l0M*bwmpaM&%%B@@@%#n     !u#$$$8MM8%BB%Wo+",
  "                                                                             'XM*bwmdaM8%BB@@@%&0l     x%B88B$$@&&BB%Ww;",
  "                                                                         `/LLB&hwwdoW8%BB@@B%Wr'     'Z88oqdMB$$%#W8#J.",
  "                                                                       ]wBB%@$$B*oW8%B@@@B8b)       !h%&opmdM@$$%Mk*u",
  "                                                                    `\\oB8#bd#B$@&a%B@@@%&0l        (8%Whqqa&@$$$%Mb+",
  "                                                                  !uBB&opOOpM@$@8oW@@%kr'         Y88Mkqpo8@$$$$%#p",
  "                                                                ]qB%WawOZd*8@$$$8ok8O)          'k88#bwd*8@$$$$@8o[",
  "                                                              uoB%Mkm0mb#%@$$$$$8aJl           -h%8*dwb#%$$$$$@%#u",
  "                                                            'h%8*dZOwkM%@$$$$$$@Mu            -&%&opwkMB$$$$$@8#u",
  "                                                            d8&kOOwhW%@$$$$$$$@&f            'M8&aqqhWB$$$$$@8#u",
  "                                                           +M88*baWB$$$$$$$$@8x'             fM88#haWB$$$$$@8#u",
  "                                                           U&8BBBB$$$$$$$$@BBC!             ?8&&BBBB@$$$$$@%8%@$$L!",
  "                                                          X8aqaa*&&8888&####MB%_           lW8kmhaaM&&88&Moooo**8$%f",
  "                                                          M%*ppppppppppppppppp&h           f&%Wdppppppppppppppppb$Bh",
  "                                                          #BBbpppppppppppppboo8Z           )WB$Mppppppppppppppho#$%Z",
  "                                                          ]%$$$$$$$$$$$$$$$$$$m;............kB$$$$$$$$$$$$$$$$$$$$k'",
  "                                                           +0&$$hmmmmmn|\\\\\\\\]^^^^\"\"\"\"\"^^^^^^!z$$$$$$$$$$$ZZZZZO)1}",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"]\\|]^```'''...",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
