/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `pogo_air` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "                                                       f&bjt/xzm%%&pI      `aqJ8z8LZj88a?an 'dW#hdhW%&*&8#Y",
  "                                                        X&bYYLwWB@B8#1   nJ!|QQ8(d{YIaQ88m  v#WodhM%@$$BWb.",
  "                                                         08%8%%%%B@B8Mu   J8m8[t)1I!1>p|8nn kM&&WW%@$$@&a[",
  "                                                         'd8B@BB%%B@BWk:?? Jo8C)?[:`;?;boa` v#8BB@@$$@%#Y",
  "                                                          'b8B@BBB@@BWk>!m88/^]][\\JJCwbO8m! k#8B$$$$$@Wkm",
  "                                                           +M8B@@@$$BMd   J8i           iw| h#&B$$$$$%*hw",
  "                                                           t*M%$$$$$%*q  |8a^[())11{{-~-\\ba hM88B$$$B%8*q",
  "                                                           CM&&@$$$@&*w ?m $$#okkkkbm00QQo8 aM8&W&%B@@8#p",
  "                                                           aW&WM%@@@8*z ?J:po$$8J_}Ob$$$$dx#aW8&W&%B@@8#di",
  "                                                          +oW&MW8B@@8or ?mI80q8$axf$$&*#$;fMoW8&W&%B@@%#b>",
  "                                                          t#&&MW%@@@&aj `8~o@$$$\\?1q$$@m8\"kzoW8&W&%B@@%Mk>",
  "                                                          CM&WMW%@@B&af  8[txqC|}\\uv*$$Wm{a}*W8&W&%B@@%Mk)",
  "                                                          aM&WM&%@@BWhx  8\\1xCc|/nYYzYJqCd|u*W8&W&%B@@%Mhf",
  "                                                         +oW&WM&B@@BWh#k)auuJmzYW$$*JLQdp8+u*W8&W&%B@@%Whj",
  "                                                         /*W&MM8B@@%#om&&&CQwpv@$$$$kO0ao8Mw#&8&W&%B@@%War",
  "                                                         J#&&MW8B@@WowqWW&*bdLO$$$$$pOq8&&8h#&8&W&%B@@%WaC",
  "                                                         aM&WMW%@@&owqW&&WW88dQhxXk*Qo88%B@k#&8&W&%B@@BWow",
  "                                                        ~oW&WM&%@BW&BB%%8&8%LL8*bkbh#8B@@%Uh#&8&W&%B@@B&oq",
  "                                                        /*W&WM&%@@@8WM@@BB%8t]-nzCOmw@Bm(  hM&8&W&%B@@B&*q",
  "                                                        J#&&MM&B@@B&om ]uq@W[]_]|xXJp&kUYcnaM&8&W&%B@@B&*pi",
  "                                                        hM&&MW8B@@B8MkLWWWWW1{{)fvYJdhhkMboaM&8&W&%B@@B&*d>",
  "                                                       ~oM&#8%%%%%%%%%h#adb#XrnvYL0C**o8&boaM&8&W&%B@@B&#b>",
  "                                                       /*W%$o&&WMM##**k#WM8%*L0OmZYwMMnU#OroM&88&8%B@@B8#b>",
  "                                                       J#W&$%hma#JjZk)xhm[X%#0LOcnvM#MLm#qwaM8%BB@@@$$B8*d>",
  "                                                       Z#&8B$pfCBwJdMwpb*h#%#wqQ<nk$&WW%&p%aM8B@@$$$$$B&oL",
  "                                                       t#&%@$%M8%%8%%%%aMW&%M0(!p(X$8WW%Wq%8M&B$$$$$$$%Mm.",
  "                                                       .p&B@$$M&%B%8%%%o#WW%Mc;lZj($BWW%Ww%%%8%$$$$$$@&L.",
  "                                                        'O%$$$BW8%%8%%%MoWW%M0<+Ux\\$@WM%Wm%%%@@@@$$MLnl",
  "                                                          ?C$$$M&%%%8%%%hWW%Ww]}JLfW$MM%Mm%%B@$B&ow",
  "                                                              bBW8B%8%%%aMW%Wq)(UQr*$MM%Mh8%B@@BWaj",
  "                                                              >$W&%%%8%%a#W8&p/tz0uh$#M%Mk8%B@@%Mk?",
  "                                                               bBW%B%8%%WoW8&djrYZcw$8W%Mk8%@@@%#d:",
  "                                                               >$W8%%%%%%hW&&bnuYpYq$8W%#b8%@$@8*w",
  "                                                                bB&%B%8%BhM&8kXzXpCQ$BW8#b8B@$B&ac",
  "                                                                >$W8%%8%Bo#&8hJUCQ0Z$@W8#d&B@@BWh(",
  "                                                                 bB&%%%8BWoW8hQQQQp8$$M8*p&@@@%Mb>",
  "                                                                 >$&8%%8B%hW8a?\"\"\"\"\"m$M8*p&@@@8#q",
  "                                                                  b@&%%%%@hM&h{ii!!!z$*&*b&@$B&oL",
  "                                                                  >$&8B%%@o#&bj~~~~~n$&Wo*&@@BWhj",
  "                                                                   b@8%%%@WoWdc~~~~~\\$MMo*&@@%Mk>",
  "                                                                   >$&%B%B%aMqc~~~~~~$%#ao&@@8#p:",
  "                                                                    M@8%%B@h#mz__--??$%aao&$@8*w",
  "                                                                    1$8%B%@o*pCtfjjrx*$hho8$B&aj",
  "                                                                     a@8%%@Waqwwbaaaa@$hko%@%Wk]",
  "                                                                     f$8%%@%hwm??`   t$oba%@%Md>",
  "                                                                     .8$8%BBkdw      }$8pa%@8*q",
  "                                                                      j$%%BBabq      >$&b*%B&oz",
  "                                                                      I8$8B@*dq       $@o8%BWhf",
  "                                                                       L$%%BMkp       &@M8%%Mb>",
  "                                                                       I%$%B8#d       0$M8%8#p",
  "                                                                        q$BB8#d>      0$#&%&oL",
  "                                                                        {%$%%#b>      }$M&%Waj",
  "                                                                         q$B%Mb>      }$8&8&MQ?",
  "                                                                         t%$8Mk>      (WWWWW&&8Wr'",
  "                                                                       lXMo$BMkw)    c##*oo*W&8&Mp_",
  "                                                                      1##*aB$BakMq. to*obwqk#&88&W#f",
  "                                                                     +o*oka%$$BW%8hmko*odwph#&888&WMQ'",
  "                                                                     Zo**Mkoaahkbo8Qh*##*ooMW&&8888&Mp_",
  "                                                                     k**MkOkX-Xm?d0/h*MW&&&&&&&&&888&W#f",
  "                                                                     k*#WBB$apk%h&Mmk*W&8%88&&&&&&888&WMQ'",
  "                                                                     toMM@$$$$$$$$$$%*W8%%%%88&&&&&8888&Mp_",
  "                                                                      m*W&%%%%%B%8&#hUM&8%%%%88&&&&&&888&W#f",
  "                                                                      Ia#W&&&W&88%8WoO'0W&8%%%%88&&&&&8888WMQ'",
  "                                                                       u*M&&&&&&8%%&#h[ -b&88%%%88&&&&&&888&Mp_",
  "                                                                       .w#W&&&W&88%8WoO  'rW&8%%%%88&&&&&888&W#f",
  "                                                                        +oMW&&&W&8%%&#h[   lO&88%%%88&&&&&8888&MQ'",
  "                                                                         v*M&&&W&&8%8WoU     )M&8%%%%88&&&&&888&Wd_",
  "                                                                         .h#W&&&W&8%%&#h;     'XW&8%%%88&&&&&888&W#f",
  "                                                                          {oM&&&W&&8%8WoU       lb&8%%%%88&&&&&888&MQ'",
  "                                                                           J*W&&&W&8%%&#h;        rW&8%%%88&&&&&888&Wd_",
  "                                                                           .a#W&&&&&8%8W*U         'OW88%%%88&&&&&88&WMf",
  "                                                                            {oM&&&W&88%&Mh;          -b&8%%%%8&&WMWWW&8&0'",
  "                                                                             m#W&&&W&8%8W*U           'rW88%%%8M*#akoM&8Wq.",
  "                                                                             IaM&&&W&88%&Mh;            lO&8%%8a*aqmb#&8&*O",
  "                                                                              t*M&&&W&8%8W*U              )W&8ao*akh*&8%&#b:",
  "                                                                               w#W&&&&&8%8Mh;              'XMa*okh*&%%B8#d,",
  "                                                                               IoM&&&W&8%8W*U                C**hkoW8%B%&oX",
  "                                                                                t*W&&&W&&88Mh;              +a*akh#&%BB8#d.",
  "                                                                                .w#WW#M##W&&#U              m**hk*W8BB8Mk<",
  "                                                                                 +o##*kwd#&8Wa;            {o*akaM8%B%&ar",
  "                                                                                 'o#opwphM8%Wox            w*okh#&%B%&*0",
  "                                                                                _d*hqwb*&8%%&or           to*hkoW8BB8Mb:",
  "                                                                               z#odwqhM8%B@B&h]          .a*okaM8%B%Wh[",
  "                                                                             'p#hqwd*W8%B@B8#n           t*W###&%B%&ox",
  "                                                                            _#*bwqhM8%B@@%WqI           \\%@@$$$B8B8#O.",
  "                                                                          'z#apwd*W8BB@B8*1           'h%8MM%@$@8MWk<",
  "                                                                         ld*kwqhM8%B@B%Mc'            088hZw#B$$%Mk|",
  "                                                                      `vLB%8adoW%BB@B&p+             jW8Waba&@$$%Mb",
  "                                                                    `nBB8%@$@&W%B@B8#f              _W8&*a*8@$$$BMb",
  "                                                                   |a%Wkwa%$$%*8@%WL'              'b88Mao&@$$$$%#0",
  "                                                                 !m%8oqZp*B$$%Mh&p+                0&8WoaM%$$$$B&h<",
  "                                                               `n%%MbZmhW@$$$B#pf                 jW8&*a*8@$$$$%#Y",
  "                                                              |a%&awZp*%$$$$$%*\\                 lM88#aoWB$$$$BWh;",
  "                                                            !m%8#pZwh&@$$$$$@&m.                'd&8WoaM%$$$$@8*X",
  "                                                           -8%WkmZd#%$$$$$$B&z.                 XW8&*a*8@$$$$BMk:",
  "                                                          lW8MpZwa&@$$$$$$%M_                  Y%#M8M#WB$$$$@8o\\",
  "                                                         'k&%&ak#%$$$$$$@8p'                  _W8hwkao8$$$$$%Mb.",
  "                                                         O8hba*8@$$$$$$BWc                    fWBBkppppb#B$@&WOi",
  "                                                         M%#pppphM$$$@%#_                     IWB$&hppppppb*8@$$p/`",
  "                                                         d%Bhpppppph#%$$p/`                    -%$$$$8obpppppdo8$$$q!",
  "                                                         -8$$$8oppppppk#B$$L!                   `vd$$$$$BWopppppdoB$W+",
  "                                                          `vd$$$$B#hpppppb*B8+                      ]vp$$$$$8#bpppa$&u",
  "                                                              ]vQ$$$$8obpppp%v                          i/Q$$$$$8W$$W\\",
  "                                                                  i/Q$$$BWo#&\\                              i/Q$$$$@j",
  "                                                                      i/Q$$p)                                   i[[`",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];
