/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `point` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                      `|",
  "                                                                                               a  ?n  n?  ?m",
  "                                                                                               m| |m `8? `8!",
  "                                                                                               J8`J8`n8?`am",
  "                                                                                               ?8mJ8|88!a8!",
  "                                                                                             |J?opaQ8X8aXm |m`",
  "                                                                                           `` aa8~8]8~8{d|aa`",
  "                                                                                            mmJQo(J:t)\\(8L8!!nm?",
  "                                                                                            `aow!,'.`_,c(oaa8J`",
  "                                                                                            |aJJC8JJCQOOkmzq?",
  "                                                                                           `8v          ?{amJm",
  "                                                                                           n8[ liiiiiiiii)d8?",
  "                                                                                          nma-nQJcCCCCCCCCd8?",
  "                                                                                          8 j*h$$$$#mqpdbB$$$!",
  "                                                                                          a+xZ<1nm$$B(Z@$$$B$!",
  "                                                                                          J{zm+(8$$$Y/Y&$$Q(a",
  "                                                                                          nvOu1n8$Bq/ju8$$$Wn",
  "                                                                                          xCOX\\/Xv|trnCYZWx*`",
  "                                                                                        l0b8oX/jCQrnvcJQQoQm",
  "                                                                                      l0kLL88uzJmQvh@$$oQa8| -.                          `|JBBqC]i",
  "                                                                             `]]]]    -h%%8&8hOqdCU$$$$$Om8Ooon                       ?nZ&8WW8%%BBBqC]]",
  "                                                                           (a%%%BBBUl   r&%%88*pOQ0haaW$QpMQ08o;                  !|J%8WMWawp#W&&8%%%%%%on'",
  "                                                                         'd&&&M%BBB%M_   'Y8%%#WabmZJQmOk8##&8&O              `?Ja%8&#aaMWhqb#MM#Wd\\i?numwpJn?!",
  "                                                                        'dWWa$MM%BBBBBCCr(??k%0(XmkMoMM8&&&&&88#[          ?na%8&W*kpmZaM8&W&%%88*>\"I_____-?tnLwpJJ??",
  "                                                                        XWWop$WM&88%%%BB#*W&&Wu[??)jcU0M8BBB@@@Ba.     !|w%%8&#abqmZmpkaM8B@@@@@Bw{}1()1}[?--____-/xYhab",
  "                                                                       zWWopq$W1joaZh&&8a*o*#&u[]](rcUQB$$$pLL[]i  `?J%%8&W*hpwZZwdh*W8&M8@$$$$$$#uxvunxrjft\\|)1}[?-{/\":",
  "                                                                      zMWodqk$Wbo&OfCMvfq#wo%8X/tfnzCCw8aU?!    ?Ja%%8&#obqmZmqba#&8B@@$%8@$$$$$$$%bqqwLCJUXzcvunxjfxj_-",
  "                                                                     zMWodqk#$WM&&W&88wwhZ1z%WZXYJQOO0o#MW&a0JU%%8&W*hdwZZmqboM&%B@@$$$$$$$$$$#$$$$$$$@B%Jm#ooadqwm0mJrn",
  "                                                                    -MWodqk#8$WM&&W&%%%*oohM%oOmZYCYw*h#&%#k8W&&#okpmZZwpkoM&%B@@$$$$$$$$$@an`        [i      `????JnJ*a",
  "                                                                   _MW*dqk#%@$&W&&W&%%%o*oM%&pbC|/rwM*L1Q8bk#WMkwZZZwdh*W8%B@@$$$$$$$$$@%U!                            `",
  "                                                                  _MW*dqkM%@@$&W&&W&%%%b#a8%*/^~YfZ$&akwd#(q#W#bmwba*W8%B@@$$$$$$$$$@Bm(",
  "                                                                 _MW*dqkM%@@$$&W8&W&%%8a*o%&blIfQ(a$*hMB&poh#&&M*#W8%B@@$$$$$$$$$$Ba|'",
  "                                                                '#W*dqkM%@$$$$&W8&W&%%WooM%#v!~Lc/$@oh%%*a%h#&%%%BB@@$$$$$$$$$$@%n!",
  "                                                               'dW*dqkM%@$$$B$&W8&W&%Bo*o88k{-\\p/L$&a#BWd%%o#&%@@@$$$$$$$$$$@%m?",
  "                                                              'dW#bqkM%@$$@BW$&W8&W8%Bh#o%ML}1YJr*$*h8%ah%%%*&%@$$$$$$$$$@Ba|'",
  "                                                             'dW#bqkM%@$$@%Wh#8W8WW8%%h*M%an|/pcu$@ooBWb8%%@B&%@$$$$$$@Ban!",
  "                                                             0W#bqkM%@$$@%Mm.08&8WW8BWo*8WmtfzZvm$&aW8h*%%B@$@8%$$$$$BU?",
  "                                                            XW#bqkM%@$$@%#Z. 08&&WW8@o**%oXrxZLXM$*a%Mp8%B@$@BWh[[[[i",
  "                                                           Y8%%BB88@$$@8*u.  08&&WW%@h#M&puuzpYJ$BoM8ko8B@$$B&ox",
  "                                                          X&Ma*8BBW#$@8*n    08&&WWB%h*&#dpOYLLa$Wa%#k&%@$$@8*0",
  "                                                         t#MbZdWBB&a&&o}     p8&&WW@&oM8b~1vO#kB$*#&d*8@@$@%#d.",
  "                                                         vM&M*W%@@8*ka~      %8&&W&@o*W*Y!ll!iv$Bo8*dWB@$@%Wk<",
  "                                                         vM8%%8%@@%Mb;       %%&&W8$h#&p{~~<i!c$WW&bo8@$$B&a|",
  "                                                         Io&%%8%B@BWh:       %%&&WBBhMaL~~~~~~o$*&obM@$$B8oX",
  "                                                          tM8%%8%%%8o[       %%&&W$Wo#qt~~~~~}$%#Wp*8$$@8#O.",
  "                                                          .o&%o];?jaMn       B%&&&$o#d0+~~~~~Y$oWadM@$@%Mb<",
  "                                                           {#8{i<1jz8d      .B%&&%@hoqX({[?_+*BaMd*8$@BWh[",
  "                                                            q8n)1|juoo:     ~B%&&B%hqpqQvxj/v$Woha#$$B&ox",
  "                                                            +Mh(1)txm#>     ~B%&&@Wbb(?|Jmhd*$hop*8$@8*0.",
  "                                                             L8n)1\\rX8      +B%8&@abd:     !$$kb*M$@%Mb.",
  "                                                             'Uh(1(fno?     +B%88Bdhz      >$%bk#B@%Wh<",
  "                                                               an)1/xZJ     +B%8B%hb>      z$#q*M$B&ar",
  "                                                               |h(1(jz8     {BB8BWoL       &$ob#@B8*Q",
  "                                                                an1)tno?    u@B8%Wk]      >$%hW8@8#O.",
  "                                                                |h)1|rZJ    u@B88*q       z$##MB%Mk<",
  "                                                                 an1)fz8    u@B%Wh(       &@MW8BWa|",
  "                                                                 |h)1/no?(YZo@B8#p       }$8W&B&ox",
  "                                                                  aYrtxQ8WMMo@B&az       0$#W88*0.",
  "                                                                  mc+}nuO&boh$$&dhu     ?@8W&%Wb;",
  "                                                                  aYj)fUm8M8@$$$*Mh[  )bWWWW&88kj",
  "                                                                  ?qcvcJ#kCk*oW8%B@aJq##*ao#W&8&Mq.",
  "                                                                    /JLwM8&%U]Xkfw8oao*adwphM&8&W*Z",
  "                                                                    .bha#B$$Bh8buMc}h**apwdaM&88&Mou",
  "                                                                    ~h*###B@$$$$$Bdwa*M#oo*M&88%8W#a}",
  "                                                                    }a*#**#W8%@@@$$*a#W&&&&&&&8888W#hI",
  "                                                                    na##**M&8%%8Mhj_a#W888&&&&&888&W*m.",
  "                                                                    uo##**M&%%%&#b> v*M&888&&&&&8%8&M*J",
  "                                                                    bo##**W8%B%Woq   c#W&888&&&&88%8&Mou",
  "                                                                    k*##*#W8%B8Wac    c#W&888&&&&88%8&#a+",
  "                                                                   ~h*#**#&8%%8Mk]     c#W&888&&&&88%8W#h.",
  "                                                                   +a##**M&%%%&*p       c#W&888&&&&8888W*m.",
  "                                                                   na##**M8%B%WoL        c#W&888&&&&888&M*u",
  "                                                                   uo##*#W8%%8Mh(         c#W&888&&&&888&Mo/",
  "                                                                   b*##*#W8%%&#d:          c#W&888&&&&8%8&#a+",
  "                                                                   k*#**M&%%%&*w            c#W&888&&&88%8W#w.",
  "                                                                  ~h*#**M&%B%Waj            'w#W&88&&&&88%8W*m",
  "                                                                  +a##**W8%%8Mb>             'q#W&88&&&&888&Wou",
  "                                                                  no##*#W8%%&*p               'q#W&88&&&&888&Mo+",
  "                                                                  uo##*#&%%%Woz                'q#W888&&&&888&#aI",
  "                                                                  k*#**M&%B8Mh]                 'q#W888&&&&8%8&#m.",
  "                                                                  h*#**M8%%8#d                   'qMW888&&&&&&&&#J",
  "                                                                 ~h#MW&&88%&*L                    'qM&88&MMM#M&8&#t",
  "                                                                 +a##o*W&&##a(                     'qM&8a*obphM&8Wo~",
  "                                                                 no*bwd#&8Wad:                      'qMoa*apqhM88&*O",
  "                                                                 J**akoW8%Wom                        'qho#*o*M8%%&*d",
  "                                                                 h**o*W8%%&or                         'k*#*o#&8%%&*q",
  "                                                                +a#*o#&%B%Mk:                         .h*#*oM&%B%Wa|",
  "                                                                uo#ooM8%%&*X                          ~a##o*W8%%8#b:",
  "                                                                k**o*W8B%Wh]                          /o#*o#W8%%&oL",
  "                                                               ;a#*o#&%B8#0                           uo#*o#&%B%Wh]",
  "                                                               /o#ooM8%%&a]                           k*#**M8%%8#p",
  "                                                               J**o*&%B8Md                           ;h##o*W8%%&or",
  "                                                              .h#*o#&%%&o|                           +a#*o#&%B8Mk>",
  "                                                              }o#ooW8B%Wb.                           uo#*oM8%%8#0",
  "                                                              u**o*&%B8*z                            ZM%%%B@B%Wa(",
  "                                                              #%@$$$B%Wh:                           ?8BBB@$$@8#b:",
  "                                                            'h%8M8@$@8*Q                           -&%MkkMB$$%#Y",
  "                                                            d8WdZh%$$%#|                           d&8amq*B$$BMm",
  "                                                           lM8&oaW@$$%#n                          _M8%W#M%$$$BWk>",
  "                                                           Q&%&M&@$$$%#n                          LW%8WW%@$$$BMb",
  "                                                          IM88MM8@$$$8o|                         '*&%&MWB$$$$%#p",
  "                                                          zW%&MWB$$$@&k:                         1M8%&M&B$$$@8ox",
  "                                                         '#88WM&@$$$BMp                          p&%8WW8@$$$@&a(",
  "                                                         fW88MM%$$$$8*r                         I#8%&MW%$$$$BWk>",
  "                                                         *&%WM&B$$$@&h<                         cW8%&M&B$$$$%#d",
  "                                                        1M88MM8@$$$BMd                         '*&%8WW8@$$$@8*Q",
  "                                                        q&%&MW%$$$$%*X                         _#8%8WW%@$$$@&oC[`",
  "                                                       ?W&BBBB@$$$@&#hLLLL]                   -%&M%@@@@$$$$B&&@@@@@$n'",
  "                                                      l&Wpbaa*&&8&W***###W@b.                'M8aZdaaaaoooahkkaaaoM$Bp",
  "                                                      z88pppppppppppppppppkW~                _W%8kppppppppppppppppp$@*<",
  "                                                      f&@Mpppppppppppppboo&Ml                lMB$@hppppbooooooooooW$Bq",
  "                                                      `k@$$$$$$$$$$$$$$$$$*}..................n%$$$$$$$$$$$$$$$$$$$$mI",
  "                                                        fb$$&ZZZZZU||||||^^^^^^^^\"\"\"\"^^^^^^^^^^-d$$$$$$&ZZZZZO)111{\"",
  "                                                         ...'''````^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^^^^````'''..",
  "                                                             ...'''`````^^^^^^^^^^^^^^^^^^^^^^`````'''...",
  "                                                                          ..................",
];
