/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `point` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                      `]",
  "                                                                                               0  ?)  c!  [X",
  "                                                                                               0_ (z `&: ^#`",
  "                                                                                               cp Uw ck:`Wt",
  "                                                                                               +MfJk+$Q;&w`",
  "                                                                                             [u>Mqpow$X&W( fz",
  "                                                                                           `` Z0a#o#WWb$U[WU",
  "                                                                                            XJj*h8oW8b$p0$U`>zL>",
  "                                                                                             C*M8$B@%#&q8Cw$h)",
  "                                                                                            )8B%8&$$B&M#h@Wr,",
  "                                                                                           'M@$$$$$$$$$$$$JYcU",
  "                                                                                           jW$$*aoooooooaQur:",
  "                                                                                          c$8pu(/nnnnnnnnnxz;",
  "                                                                                          8$qn[   !1uxrjf}_{~`",
  "                                                                                          d$mYhOu[  `L{'   `!`",
  "                                                                                          X$mXbL\"   tUt, iYdt",
  "                                                                                          f$ZC0v\" `?JXn\"   {+",
  "                                                                                          [$OXJJfnCYzu|f}nqX",
  "                                                                                         ,[@0cJz\\(zvnr\\)(dW|",
  "                                                                                       ,~|(8Cnj\\[(x<.  i)kki                                ``",
  "                                                                                       \"^^\">1t{?_|t     {ux\"i!l                         `,\"::\"`````",
  "                                                                            `^^``'`'    ',^^;([-{(1<>i; )|j(1\"i                      ^^:I:>]-l:,,\"l)nr}_!",
  "                                                                          :,,\";``''^I     `\"^^]{}[[}\\)[{1\\?l,^:<                .`^\",Iii;;<?+IIII1k*aqwmZOYt1i,",
  "                                                                         ;:;> ;;````''  `   \"^10zj|{)[[?-I,,,\"^l\"            `^^,;!<-[}>;\",:\"^^\"+pa8MdddddpqwmZOUt/>!",
  "                                                                        ^:;i- ;I,\"^^^```I!:,\":nmqqQzx/1;\"``''..'i        '^^\",Ii+?}}[-~>;^''....-OZZ0LQOZmqppddddpqwZU0q",
  "                                                                       \";:i_? :0Xii}<,,\"il!lI,nmwwLzr/)`              ^^^,;l<_]}}]_<l:\",I^'     \"zzvnnuvczXUJCQ0ZmqpOU8W",
  "                                                                      \";:i_?~ :~!,{X\\;xX?l]!^^fJUXvj\\|]^^.       .`^^\":Ii+?[}}?+>I:^`'..`\".      ,1)11)(\\/tfjrxnvczYvzdp",
  "                                                                     \";:!_?~I :;,,:,\"\"[]<}0r`:}ft\\){11iI;:,i, '^^\",;l<_]}}[?~iI,^`'..              ^,,!<~i~}}}{1)(|\\)xcv",
  "                                                                     ;:!_?~I^ :;\",:,^^^l!!<;^i1}}t|t]l<l:`I~\":,:Ii~-[}}[-~!;,^`'..        '`                   ^```il_)1",
  "                                                                    ;:!_?~I^' ,;\",:,^^^ili;`,-+\\CUz];!(O)\"+~l:;<]}}}]_<!;\"^''..        .^.",
  "                                                                   ;:!_?~I^'. ,:\",:,^^`~li\"^lJ8ktX} ,i~]_lL?I:I+[]+>l:\"`''..        .`'",
  "                                                                  I:l_?~I^'.  ,:\",:,^^\">l!`\"+*#X)L> l<;`,-!>I,,I!l:\"`''..        .'`",
  "                                                                 I:l_?~;^'.   ,:\",:,^^:!!;`Ixok(rU .!>^^!i^<I,^```''..         '^",
  "                                                                ::l+?~;^'. .` ,:\",:,^`ili\"\"<OpJ-U( ,>l`:_^^iI,`'...         .``",
  "                                                               ::l+?~;^'. .`: ,:\",:\"^'<l!`;(Z0f\\z! l<\"^i>^^^l,`.         .`^",
  "                                                              ;:l+?~;^.. .`;< \":\"::\"`^>l;^>uCJ-ru .!i`:+^^`'`,^.      .'`",
  "                                                             ,:I+?~;`.  .^;i  \",\"::\"':!!\":[UXj}n[ ,>:^>l^^'. .^^     `.",
  "                                                            ^:I+?~;`.  .^I>   \",\"::\"'il!^!jcv}|j; l>`;-\"^'. .`:<,",
  "                                                           `\"^``'\"^.  .\"lI    \",\"::^.<l;,-nnj-t\\ `!;\"~!^`.  ',i!",
  "                                                          ^,;il\"``:I '\"!l     \",,::``>l,lxCct(|> :>`I~,`'. '\"l~",
  "                                                         \"I;+}+:`',i,,i\"      \",,::.,iI\"~kakdQu' lI,+!\"'. .^I+",
  "                                                         :;,;!;^''\"!~>'      ^^,,:,.!l:lto***ow `i\"l_;`. .`;<`",
  "                                                         :I\"`^^`'.^I+        ^^,,:^.<I,-Okkhaor :;,+i\". .`,>;",
  "                                                          !,^`^^'.':<.       `^,,:``<;>(kkkkkk! l,!+I'  '\"!>",
  "                                                          \"I\"`~vur/>i,       `^,,:.:iI?YkkkkkZ ^l:-l\". '^l<",
  "                                                           i,[kMMqJc-l       `^,,, il+1bkkkkkt i;i_I' .^;~`",
  "                                                           `IQpoh0Xnj+       `^\",^.<i?fQOmqpb!'>I_l\" .`:>,",
  "                                                            lYLQ0LXur[.     '`^\",`^<?-/jnvXUn :!<>I  ',i!",
  "                                                            .)CL0QUvx|\"     '``\",.;++I\"I+]|/> <!-l\" '\"l~",
  "                                                             ;zLQ0Cznj      ''`\",.i+_.     '  <+!; .^I+",
  "                                                              ?CL0QYur:     .'`\"^'_<~        ^+~l`.`:<`",
  "                                                               cL00Jcx]     .'`\"`^<+^        I?l;.`,i!",
  "                                                               +CQ0Lznj     ^'`\"`:!_         i~I.'\"!+",
  "                                                                cL00Uvr:    I'`\"`;~:        ^>:\".^I<",
  "                                                                +CQ0Ccx]    ;'`^\"l?         II;'^;~`",
  "                                                                 cL0QXuj    ;'`^:<l        .;:\"`:>I",
  "                                                                 +CQ0Uuj\" '^i'`\"I-         \"::',!l",
  "                                                                  uYzYczn!;;i.`,><         I:\"\"l~",
  "                                                                  XbbZunxt+!>  ,_>;      .\":,^:+",
  "                                                                  XCXQXt}!;\"'.  l;<,  .,::::,\"\",`",
  "                                                                  ;/rxr\\I<|~li:\"`'.` lII!iiI:,\",Il",
  "                                                                    _\\(];^,^twj~X)vp-!li_]->I,\"\";!>",
  "                                                                     +>iI'  `>\"+uZpZ>!l>-]_i;\"^\",;i;",
  "                                                                    '<lIlI`.     \\v{>lII!il;,\"^^\":Ii^",
  "                                                                    ^>lIl!I:\"`''. ;<>l;,,,,,,,\"^^\":l>",
  "                                                                    IilIl!I,^``\";<> >I:\"\"\"\",,,,\"^^\":li",
  "                                                                    ;iII!l;,^`^,I+^ :l;,\"\"\",,,,\"\"^\",;!l",
  "                                                                    ~!II!l;\"^`^:!?   ,l;,\"\"\",,,,\"\"^\",;iI",
  "                                                                    <!Il!l:\"^`\";>~    ,l;,\"\"\",,,,\"\"^\",I>.",
  "                                                                   '<lIl!I,^``\"I~:     ,l:,\"\"\",,,,\"^^\":l<",
  "                                                                   '>lIl!;,^`^,l-       ,l:,\"\"\",,,,\"^^\":li",
  "                                                                   IiII!l;\"^`^:i-        ,l:,\"\"\",,,,\"^^,;!;",
  "                                                                   ;!II!l:\"^`\";<l         ,I:,\"\"\",,,,\"^\",;i,",
  "                                                                   ~!Il!I:\"``\"I+.          ,I:,\"\"\",,,\"\"^\",I>'",
  "                                                                   <lIl!I,^`^,!]            ,I:,\"\"\",,,\"\"^\":I!",
  "                                                                  '>lIll;,^`^:>i             lI:,\"\"\",,,\"\"^\":li",
  "                                                                  '>lI!l:\"^`\"I~^              lI:\"\"\"\",,,\"^^\";!;",
  "                                                                  IiII!l:\"``,l-                lI:\"\"\",,,,\"^^,;i.",
  "                                                                  ;!Il!I,^`^:i~                 lI:\"\"\",,,,\"^\",I>",
  "                                                                  ~!Il!;,^`^;<:                  lI:\"\"\",,,,\"^\":I!",
  "                                                                  <lIll;\"^`\"I_                    lI:\"\"\",,,,,,,,Il",
  "                                                                 '>l;:,,\"\"^,!_                     lI:\"\",I;;I;,\",I\"",
  "                                                                 '>II!l:,,II>l                      lI,\"il!+-<;,\":i'",
  "                                                                 Iil+]_I,\";>_.                       l;!ili-?<;\"^,l<",
  "                                                                 !!l>~!:^^:i[                         l<iIli!;\"^^,l_",
  "                                                                 <lli!:\"``,ii                          ~!Il!I,^``,!?",
  "                                                                'il!il,^`^;~                           <lI!!;,^`^:>I",
  "                                                                ;!l!!;\"``\"l>                          '>ll!l:\"``\"I+.",
  "                                                                ~lli!:^`^:<:                          :iIl!l:^`^,!_",
  "                                                                >l!iI,^`\"I~                           ;!I!!I,^`^;<:",
  "                                                               ,!l!!;\"``,>,                           ~lI!!;\"^`\"I_",
  "                                                               lllil:^`^I_                            >ll!l:\"`^,ii",
  "                                                               >l!iI\"^`,!I                           .iIl!I,^`^;~^",
  "                                                              ^il!!;\"`^;+                            I!I!!;\"^`\"l+",
  "                                                              ;!lil,^`\"l<                            >;^^^`'`^:>I",
  "                                                              I`..  `^:<                             \"'``'. .\"I+.",
  "                                                             ^`\";\"' .\"l+                            ,^;~~;'  ^Ii",
  "                                                            ;\":_}<^  ^l;                           ;\"\">[]l`  `;>",
  "                                                            ;^,i>:'  `II                           I\"^:l;`   `:~^",
  "                                                           :,^,I,'   `Il                          ;:^\"::^.   `;+",
  "                                                           I\"\";;^.   \"iI                          l,^,;:`    ^I-",
  "                                                          ,:^,I:`   ',<                          ';\"^,;,'   .\"!!",
  "                                                          I\"^:I\"'   `;-                          I,^\"::^.   ',>l",
  "                                                         ^:^\";;^.   ^!!                          I\"^,;:`.   `:~^",
  "                                                         l,^:I,'   .,>`                         ,:^^,;,'    ^I_",
  "                                                        ';^\";;\".   `;+                          l,^\"::\".   .\"l+",
  "                                                        I,^,I:`    ^l>                          I\"^\"::^.   ',il",
  "                                                        :,`'`'.   .,l\"                         ^,I^.''.    `:,''...",
  "                                                       ,:-+iil,,\",;!llllI:.:                  ;\">}_iiiiiiii>~~iiiiI 'I",
  "                                                      \"\"\"-----------------~:'                 ;`\"<----------------- 'l^",
  "                                                      ^\".;-------------+ii,IYCCCCCCCCCCCCCCCCX;` '<----+iiiiiiiiii: 'l",
  "                                                       \".                 .                   `^                    `",
  "",
  "",
  "",
  "",
];
