/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `sing` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                          ^.  [~  ^[",
  "                                                                                      !x  ?(  q!  qI",
  "                                                                                       w_ -q '%l cm",
  "                                                                                       /b\"_*I|W}]@{",
  "                                                                                       :#J}&tpot8w:`U,",
  "                                                                                     lv Z*O%L$doBv>*)",
  "                                                                                      \\kCWpBq$m$wU$n >Jr",
  "                                                                                    {j>0*aM#h$o8p$YzWb>",
  "                                                                                     \\aa8@$$$$&oMZ$Mn:",
  "                                                                                     _&$@@@@@BBBB%%MYYf",
  "                                                                                     b8$$$$$$$$$$$Mzx:",
  "                                                                                    _*B$*kkbbpZO0QLXji",
  "                                                                                   ?k%k/1xrrjffttt/{xL",
  "                                                                                   X$#/   ;{JQU/?i   Q}",
  "                                                                                   1B*zZzi   0~ '!<LqL]\"^`",
  "                                                                                   I8Mz0^   UZC_   z8(~\\(i;!",
  "                                                                                    M&XC~;~|OJv/l.^0k+?n/i:!+",
  "                                                                                    U8JQX/cCUvj/j/\\@q~ll;\"\"l?",
  "                                                                                   In%cJu(/z)' `)((@q_;^`'^<~l",
  "                                                                                 `i1j%jf(]\\|     1(aY,i,,^;!:ll",
  "                                                                                :l]_;-1[-_/;    ./\\\\?|+,<!:l!:l.",
  "                                                                                 `^`^\";?-1)-!|[>_(\\t]!,^;~!:l!:!'",
  "                                                                       `^``'`.     .^`^\"]{[[[[-[}(-;,,,\"\"I!!:ll:!'",
  "                                                                   `^^\",I```'`,^      ^`?ZYnt\\))\\I:^^`'..'I\"l:!l:ix]",
  "                                                              .^^\",:I!<.;:^```````Il,``,]Zwq0Ynff:'. .      .l;!l:>nf",
  "                                                          '^^\",;l>~_-??^^I,\",\"\"\"^^IiI!lI/ZZmQXxtf``         -cl;!l:~/+",
  "                                                      `^^\":Ii<+-??-_~>!''\\m[:f/iI_~!Il;^+YXcuj|((;;:::< ',^\"lUjl;~<;|j",
  "                                                  `^\",;l>+_??-_~>!I:\"^`  +?l\"r(>}0r!\\0-^!\\\\(1}{1ii!I\"i>;:,I><?\\};,++nzu;",
  "                                             .``^:Ii~_-?-_~>!I:\"^`''...  !:\"\",\"^^l+l_]i\"~)}tcnz>l+}!,-Il:I~}}+I_u\\f[|Yzu;",
  "                                          \",::^``;+-_~>!I:\"^`''...       ;:\"\",\"^^^ill;`:?_1Qvf';l/z)l0-I:;>__i,^[cYY[|Yzu;",
  "                                         I:<[_;`',i!:\"^`''...            ,:\"\",\"^^^!Il,^IjbMfC] ,!I`\"<~<I,\",::\"^^^)cYY[nYzu;",
  "                                        :;l~_i\"''\"!<...                  \";\"\",,^^`+Il\"^>wML-0{ ;!;`:-^>l,^`'''`^^^\\zYY[nYzv;",
  "                                       ';;<+!\"'..\"!<             .       ';\"\",,^^`~Il`,_khc\\Ci l!,^!>^Il,^'..''``^:jzYY[nYzv[",
  "                                       ;:i+i,'. ',<:       .              ;\"\",,^^`<Il`;|pw/jY''l!`,_:^^;:^'....''`^:rzUY[nYzv}",
  "                                      `>xOZu]. '\"i<                       I,\",,^^^>I;^!nOQ-nc `lI`;-^^`.^\"^`'....'``<uzUYrCYzv):",
  "                                      ?b#&bLz|.\"ii                        I,\"\",^`;iI:\"<XJz-v{ ,l:^>i^^'. `,,^`'...''`<vXULQCYzv(l",
  "                                     IZhMoZXnf~!!                         \",\"\",\"`:iI,:?YXj}x[ :!^:?\"^`. .^;~^\"^''...'']vXULQCYzv(I.",
  "                                    .nk#oZXr|/_!                          \",\"\",\"':!I^I|cv1)f; l!^l~\"`'. ',i~  ^\"`'...';|cXULQCznf+!.",
  "                                    !b*#wYx|([!                           .:\"\",\"'!!l^ifnr[(\\^ I;\"~!^'. .^I_     \"^`'..`I(cXUYvj\\/<,l,",
  "                                    Oa#dJn\\(1l                            .:\"\",\"'il:\"+zut)|1 .l,;_:^'..`:<I      ',^''.'ifnrf|1)['`\"I:",
  "                                   nk#hLu/(['                              :\"\",^.!l::)oakZC1 ,l^!~,'. '\"l+         .\"`'.\"l+[[[-<`''`\"II",
  "                                  ~b#oOct(}                                ;\"\",^.lI,!XMMM#*z \":,_l\". .`;~:           ^\"`';:^''``^`''`\"I!",
  "                                 .Oo#mXj()                                 \"\"\",^.+I,_Qhao*#| l,I_;`. ',i<              \"^`I,`''``^`'.^;~^",
  "                                 nh#pYr(1                                  ^\"\",`.~;l}kkkkkk- l,><:. .^I_.                ^\"I,`''``'..`;~^",
  "                                ~k#kCx|\\                                  ^'\"\",`.<;~tkkkkkk `l:_;\"..`:>I                  .;I\"`'..   `;_.",
  "                                QkaQu\\|:                                    ,\"\"``>l[YkkkkkZ :Il+;' '\"l~                     ::^.     ^!;",
  "                              .nbOXn\\(:                                   ' ,\"\"';><]Cqppdbv II~i: .`:<:                       `.    ',`",
  "                              O*%dJj},                                    ` ,\"\".:i-]vcXYJC) il_;^ '\"!_",
  "                             ]qbpJnt?                                     ^ \"\"\".:<?]?(|\\/tI >>~; .^;+",
  "                             /CUcj(\\                                      . `\"\".!_+^    \"\" .<-l, ',ii",
  "                             Irt(}[,                                      ' '\"\"'>+-        `_+:'.^l-",
  "                              .>i:                                        '` \"`'+<~        ,-l:.`:<,",
  "                                                                           : \"``!<l        ;?,^'\"!+",
  "                                                                           I \"^^l_\"        I~:'^;~^",
  "                                                                           > \"^\"!]         ;;\"',i<",
  "                                                                           l '^,>i        .;,`^I_",
  "                                                                           ; `^;~:        ,:,`:>I",
  "                                                                          .!' \"I-         ::^\"l+",
  "                                                                       .:;;i^ ,!?         ;,\",>:",
  "                                                                      ,lli<<: .>-!.    \"::::,\"\"\"`",
  "                                                                     ,il!l,'.  ,I:<  ,lIl!!I:,\",;l",
  "                                                                     >!l;+(>!I;:\"^`_<!li+?-<I,\"\":l>",
  "                                                                     ~!!:;!,fwj+Jndh<!li_]-<I,^\",Ii:",
  "                                                                     +!l;.  ;+;~f00Y<!II!>!I,\"^^\":l<",
  "                                                                     +!I;\"       if1<l;:,::,,\"\"^^,;!<",
  "                                                                     IiI;;I;,`''.'^;<l:,\"\",,,,\"^^\",I>:",
  "                                                                     IiI;;I;,^`^,l~^\"!;:\"\"\",,,,\"^^\":l~",
  "                                                                     IiI;;I;,^`^,l+^ :l;,\"\",,,,\"\"^^,;i!",
  "                                                                     IiI;;I;,^`^,l+^  !l;,\"\",,,,\"^^\":I>\"",
  "                                                                     :>I;;I;,^`^,l_\"   >I:,\"\",,,,\"^^\":!>",
  "                                                                     '>I;;I;,^`^,l_    .iI:,\"\",,,,\"^^,;iI",
  "                                                                     '>l;;I;,^`^,!-     \"!;,\"\",,,,\"\"^\":I<",
  "                                                                     '>l;;I;,^`^:!?      :l;,\"\",,,,\"^^\":!>",
  "                                                                     '<l;;I;,^`^:!?       !l:,\"\",,,,\"^^,;i:",
  "                                                                      <l;;I;,^`^:!]        lI:,\"\",,,\"\"^\":l<",
  "                                                                      <l;;I;,^`^:i<        .iI:\"\",,,,\"^^\";!!",
  "                                                                      ~l;;I;,^`^:i!         `!;,\"\",,,,\"^^,I>\"",
  "                                                                      ~!;;I;,^`^:ii          :l;,\"\",,,\"\"^\":l~",
  "                                                                      +!;;I;,^`^:>i           Il:,\"\",,,\"^^\";!I",
  "                                                                      !!;;I;,^`^;>>            lI:\"\",,,,\"^^,I>'",
  "                                                                      ;!;;I;,^`^;>l             iI:\"\",,,,\"^\":l>",
  "                                                                      I!;;I;,^`^;<`             .!;,\"\",,,,,\"\":i:",
  "                                                                      IiI;;;,\"^\";<`              :l;,\":I;;;:,\":>",
  "                                                                      liI;;;:,\";I~^               Il:I!l>_+l:\",Il",
  "                                                                      '>l!++!:\",!+^                lI<!!+]_!,^\";>,",
  "                                                                      '>li--i,^,I+\"                 ><lI!il:\"^\";>i",
  "                                                                      ,!li>l,^`\"I+                  ^>lI!l;\"^`^;<l",
  "                                                                      il!>i;\"``\"l~                  :iIl!l:\"``\"I_",
  "                                                                     ^ili>l,^`^:<:                  I!Il!I,^`^,!<",
  "                                                                     l!l>i;\"``\"l+                   >!Il!I,^`^;<:",
  "                                                                     >li>l,^`^:~                    <lI!l;\"^`\"I_",
  "                                                                    ,!l>i;\"``\"!<                   '>ll!l:\"`^,!<",
  "                                                                    <l!>l,^`^;+                    .iIl!I,^`^;<:",
  "                                                                   ^ilii;\"``,i;                    I!Il!;\"^`\"I_",
  "                                                                   ll!>!,^`^;_                     l!I!!;\"``,!~",
  "                                                                   ili>I\"``,i,                     <;,^^'``^:<:",
  "                                                                  ,\"`  ```^I~                      ,'''.  '\"I-",
  "                                                                 .`^\"^. .\";>^                     ,^:>>:' .^l!",
  "                                                                ,\",+[>^  ^l>                     ;\"\">}]l`  `;>",
  "                                                                ;\":<+I'  `Il                    .I\"^;!I^.  `;~.",
  "                                                               ;\"\";l:'   `Il                    ,:^^::^.   `;+",
  "                                                              ':^,lI^    \"iI                    !,^\":,`    ^I-",
  "                                                              I\"\"Il:'   ':~                     I\"^,:,'   .\"!<",
  "                                                             `:^:lI^.   ^ll                    ,:^^,:\"'   ',ii",
  "                                                             I\"\"Il:'   ',<                     l,^\"::^.   ':<`",
  "                                                            :,^:lI^.   `I~                    `I\"^\":,`    `;~^",
  "                                                            ;\"\"Il:'   .\"i,                    ;:^^,:\"'    ^I_",
  "                                                           \":^,lI^.   `;+                     l,^\"::^.   .\"l+",
  "                                                           :,`'``.   .\";,                    `\":`'``'    ',:`...",
  "                                                          ,,_+>i;,,\",:!lllII:.,             ,\"l[_>il,,\"\",;!!!!!!;..:",
  "                                                         ,,^~----------------+,;            I^\"i-----------------^.;'",
  "                                                         ',.;--------------<il:cCCCCCCCCCCCCl^.'+-------------+ii. I`",
  "                                                          \"'                 ''              \"                    `\"",
  "                                                                                              .",
  "",
  "",
  "",
];
