/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `sing` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                          ``  ??  `|",
  "                                                                                      !J  ?n  m?  m?",
  "                                                                                       a| ?8 `8? n8",
  "                                                                                       n8!?8?|8J?8J",
  "                                                                                       !8a|8mmamao?`J!",
  "                                                                                     !J`aX8Q*aY8j8!aJ",
  "                                                                                      n8az0LUurJuaoa !JJ",
  "                                                                                    |n?aQo;r-~\\^kroJa8|",
  "                                                                                     J8oc~    \"iizwXw?",
  "                                                                                     ?aJJJJJJJJJJJJwaJJ",
  "                                                                                     aL           ;J8?",
  "                                                                                    ?8v !<~~+-}{1)(U8|",
  "                                                                                   ?mmuJ0LQQ00Opkkk#Ba`",
  "                                                                                   J[IB$$$$bnrvmho$$$CJ",
  "                                                                                   |Cl8{ra$$$1k$@*hB?QZXXY('",
  "                                                                                   !a;81%$$$/}|d$$$@\"pbJLoMw;",
  "                                                                                    8<M|bMkL1/nJ#@8B~bquUoWoc",
  "                                                                                    Z|0(fUr\\txXUXUC8/k*#M88*C",
  "                                                                                  lpo0x/uLJr0@$BQLQ8QwM%BB8hkn",
  "                                                                                 ja0moXYLwCL$$$$$0L880o&&%MoW#x",
  "                                                                               'b*wdW&bmpdJM$$$$@UbWqCb&h*W**W*+",
  "                                                                        `]]i    !m%%%8&#omQp*Lmad0Wdwo&8Mb*W**W*~",
  "                                                                    i\\J%%%BBBUl   !U%B%8#8*bbdppkWWM&&&88#U*W**Wo~",
  "                                                                ]uJ%%%8&#%BBB%&X    `n%Bq}uLqdkhZWW8%BB@$@Mt*W**Wo#n`",
  "                                                           `]uw%%8&W#oh@MW%%BBBBBBM#&ZZ&w}[?1fvYYW@$$@qC]!  +*W**WaOa`",
  "                                                       `]Jo%%8&M*akdpqq%8#&8&8888%#o#**#U{}[)jvYY%%J|     |JaM*W*#Wkan",
  "                                                   i\\J%%8&W#ohdpqqpdka*@BJ}mWXUa#dko#*W8btfruXCLLMMWWWkCU&8888J*WkkMqd`",
  "                                               ]uJ%%8&M*abpqqpdka*MW8%%$$dq#8cLhm)z*J1p%oCJL0ZO0oooM8ahMW&Mah#MhM&bbuuM?",
  "                                           |JwBB%W#okdpqpdka*MW8%BB@@@@$$*W88&8%%#b*dqa8kQZUxvrh#bZo&p#*WMkZZbM88CXmLtuM?",
  "                                         -k&WW%B%Mdpdbh*MW8%BB@@@$$$$$$$$MW88&8%%%o#*W%Wqd0(xXBM*UjQ#1p#WMaddo&%%dffmLtuM?",
  "                                        I#WhmdMBB&aoW8%BB@@@$$$$$$$$$$$$$&W88&&%%%o#*&%#X~IX|w$&*#%8kkh#&8&WW8%%%%dffmutuM?",
  "                                        QW#bdo8B@8*h@@@$$$$$$$$$$$$$$$$$$8W88&&%%%b#*88a];(p)O$MoW%Wp%h#&%BBBBB%%%8Jttmutua?",
  "                                       1MMhb*8@$@8oh$$$$$$$$$$$$$$pLu]! 0@M88&&%%%k#*%&d~<rC\\a$#o&%oa%M*&%@@@@BB%%%8JttmutrbJ",
  "                                      'dWoba&B@$B&hW$$$$$$$@LC]]`       }$M88&&%%Bh##%MC-]Jzf@@#o%&dW%%MW%B@@@@@BB%%8uttmutrbm?",
  "                                      jW&&b8%@$@&ah$$*Lu]!              }$#&8&&8%8h#M%*v{)pux$B##%Mp%%%@%&8BB@@@@BB%%Muttc|tjb8Q.",
  "                                     lM*},~(0%@8or]`                    ^$#&8&&8%Ma#W8kf\\jpxO$&*W8ao%%B@$B&&%B@@@@@BB%Mj/|(|tjb&q'",
  "                                     p8f;i}fv*8or                        $8&88&8BWo#&WqtjXZvm$Wo%&q8%B@$@%MkO8%B@@@@@BWdj/|(|tjb&p+",
  "                                    +MOI!}jzCW*x                         b8&88&8BWo#8#Cxn00XM$#*%#b8%@@$B&az lZ8%B@@@@MWdf/((\\ju*&*+",
  "                                    -*!l]tcCo#x                          0@W88&8B**#%oYvcmLJ%$#M8ko8B@$@8#d.   (k8B@@@B#8Cf/txzJ*%&*t",
  "                                    a1I_\\uJoWn                           z@W88&8@o*W&bOLY0L0$@#&WdW%@$$BWh(      r&%B@@B#8OzYCOo%@B8#v",
  "                                   JUI<(nUhh1                            }$W88&8@o#WW0/0O#oa$&*%ok&B@$@8*Q        'x8%B@8M8W**8%BB@B8MC.",
  "                                  ?oli1xYqm                              >$W88&8@*#&*fI;II+J$8W&d*8@$@%Mk]          lZ8B@MW%BBB%%BB@B8#U",
  "                                 `a_l[jXqa`                               $888&8@b#&d)<>i!lL$#&MdM%@$B&oz             -k%BM&%BBB%%BB@%Mk>",
  "                                 JuI-tcZa`                                $%88&%$kM#m~~~~~~p$#&hkW@$@%#d:               (h8M&%BBB%B@@%Mk>",
  "                                ?dI~\\vQW`                                 %@&8&B$kMbU~~~~~~$B#WdM8$$B&a|                 'xMM8B@@@$$$%Md,",
  "                                a]>)nLW?                                  0$&8&B%h#wt~~~~~}$W#*bM@$@8*0                    'QW%@$$$$$8o|",
  "                              `Jp\\jvJW?                                   Y$&88BWahw|?-__+n$##kaW$@%Wk]                      -a@$$$$Bb{",
  "                              a\\^+/Qk?                                    Y$&88$Wapwnrjt/|Q$a*dM%$B&oQ                         ]vQQC?",
  "                             |m+-\\uwJ                                     {$888@Whq0mahhZO&$hakM$@%Mb:",
  "                             Jptxz0W`                                     +$%88@opb>   `??$@hp#&$B&ar",
  "                             ?8wwha?                                      ~$B88@abp       $BddWB@8#p",
  "                              !JJ|                                        ~B$8%Bbhz      }$&p*W@BWh]",
  "                                                                           W$8%Boh(      t$Mq&%@8*Q",
  "                                                                           #$8%%*d>      0$#kW@%Mb<",
  "                                                                           a$&%8*w       b$MM&B&oz",
  "                                                                           J$B%&aj       $@W&%%#d.",
  "                                                                           v$B%Mk?      >$&W&BWh(",
  "                                                                         ?xw@$8#p       }$WW88*0",
  "                                                                       )bWMa%$&oql      Q$W&8&a]",
  "                                                                      c*#okhW$@hpo+   lOWWWW&&8kj",
  "                                                                     /o*o#&B$$$&MWh. c###oo#W&8&Mq'",
  "                                                                     Zo*MbLh*#MW&%%B#o*obqph#&88W*Z.",
  "                                                                     ko*WM*&X]zb\\wanho*adwph#&88&#a/",
  "                                                                     bo#M@$$MdMkX8cth*##oao#&8%%8W*h;",
  "                                                                     boMM8$$$$$$$$Mbh*MW&W&&&88%8&MoZ",
  "                                                                     uo#MM#M&%@@@@%8h*W&88&&&&88%8&#a\\",
  "                                                                     uo#MM#M&8%%&#b<toMW&8&&&&&8%%8W*k.",
  "                                                                     na#MM#M&8%%&#b> v*M&88&&&&&8%8&MoU",
  "                                                                     na#MM#M&8%%&*b> .w*W&88&&&&88%8&#h}",
  "                                                                     \\a#MM#M&8%%&*di  'a#W&88&&&&88%8W*Z.",
  "                                                                     ~a#MM#M&8%%&*d    +o#W&8&&&&&8%8&Mon",
  "                                                                     ~h#MM#M&8%%&*p     toM&88&&&&88%8W#h;",
  "                                                                     ~h#MM#M&8%%W*q      v*M&88&&&&88%8W*Z",
  "                                                                     ~h#MM#M&8%%Woq       w#W&88&&&&8%8&Ma/",
  "                                                                     .h*MM#M&8%%Wow       'q#W&8&&&&88%8W#h.",
  "                                                                      k*MM#M&8%%Woz        +oMW&8&&&&88%8WoU",
  "                                                                      k*MM#M&8%%Wox         {oM&88&&&&8%8&Ma}",
  "                                                                      k*MM#M&8%%War          v*M&88&&&&8%8W*k.",
  "                                                                      b*MM#M&8%8War           C#W&8&&&&88%8Mou",
  "                                                                      U*MM#M&8%8Waj           'w#W&8&&&&8%8&#h~",
  "                                                                      uoMM#M&8%8Mh(            IoM&88&&&&8%8W*Z",
  "                                                                      uoMM#M&8%8Mh<             +oM&88&&&&&88Wo/",
  "                                                                      noMMMW&8%8Mh<              v*W&8WMMMMW&8Wa;",
  "                                                                      no#MMMW&8W#k<               C#WMo#adb*W8&#J",
  "                                                                      +h**bboW8&*b>               .w#h**bwd*&88Mh]",
  "                                                                      ~a*appo&8&#b>                'ah*#*o#W8%8Maj",
  "                                                                      /o*aa*&8%8#b                  }a##**M8%B8Mh(",
  "                                                                      m**aoM8%B8#0                  /a##**W8%%8#d",
  "                                                                     }o*oa*&%B%Wh]                  uo#*o#&8%%&oX",
  "                                                                     J**aoM8%B8*Q                   Z*#**M&%B8Mh]",
  "                                                                    Ia*oa*&%B%Wk:                   h*#**M8%%8#d",
  "                                                                    to*aaM8%B&*z                   ~h##**W8%%&oz",
  "                                                                    h*oa*&%B%Mb.                   +a##o#&%B%Wh]",
  "                                                                   {o*aaM8%B&o|                    uo#**M&%B8#d",
  "                                                                   C**a*&%B%Md                     J*#**W8%%&oz",
  "                                                                  Ia*aaM8%%&a]                     kM&%%BBB%Wh?",
  "                                                                  z8B$$B%%8#0                     l&@BB@$$@8#p",
  "                                                                'UB%8%@$@8Mh<                    -&%WaaW@$$%#x",
  "                                                                08&bma%$$%*X                     d8&hZw*B$$%MZ",
  "                                                               _W8Whb#B$$%#n                    +#8%W*#%$$$BWk:",
  "                                                               d&8M*WB$$$%#n                    cW%8WW%@$$$BMb",
  "                                                              )W8&*#%$$$$8o|                    *&%8W&%$$$$%#p",
  "                                                             '#88M*WB$$$BWb.                   _M8%&W&B$$$@8*X",
  "                                                             jW8W*#%$$$$%*x                    cW%%&W8@$$$@&ar",
  "                                                            IM88#*WB$$$@&h;                   .*&%8WW%@$$$BWh<",
  "                                                            Q&8W*#%$$$$%#0                    1M8%&W&B$$$$%Mb>",
  "                                                           _M88#*WB$$$@8a[                    LW%%&W8B$$$$%#d",
  "                                                           zW%&##8@$$$BMb                     *&%8WW8@$$$@8*Q",
  "                                                          !W&%BBB@$$$@8MkLLLL]              'm8WBBBB@$$$$@&WB@@$$pu'",
  "                                                         l&&dbaaM&&8&W***###W$k.            08#mdaa*&&&8&Moooo**M@@d.",
  "                                                         c&8kppppppppppppppppb&\\            #%8appppppppppppppppp%$M~",
  "                                                         1&@Mppppppppppppppho*W}            *%@Bbpppppppppppppboo$$#<",
  "                                                          Z@$$$$$$$$$$$$$$$$$B/.............}8$$$$$$$$$$$$$$$$$$$$%f",
  "                                                           fO$$$Zmmmmm||\\\\\\\\i^^^^\"\"\"\"\"^^^^^^^)#$$$$$$$$$$hZZZZOr1{,",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"i|||^```'''...",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
