/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `smoke_exhale` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                              -",
  "                                                          I   X\"",
  "                                                          1f  U/",
  "                                                       l  .ai Ym  (",
  "                                                       <O. Jd^Xo< #; ]u",
  "                                                    X{  (h-<#UJ&n|o:^a;",
  "                                                     fw/ cojb*q%Qdd+&L",
  "                                                      idoxq#dMdBq8m&M(iv",
  "                                                       ^Y*okMaWM*$k$Bqa>",
  "                                                      nCCCdM#&$$$$$$$mJt",
  "                                                       `rkM&@$$$$$$$MZLUdj",
  "                                                      1zCdMB$$$$$$hJut->O*v",
  "                                                        {#$$$$$&mYx/fi  zMZ<",
  "                                                         Zb8@aQcj/vX_ ;vO#ar",
  "                                                         Zwhmuf/Yo%i    'mMw\"",
  "                                                         )kcI;    Xmx   ~vp#r",
  "                                                         U$Cl<~I -YmLcXvnrnad^  ^;",
  "                                                         im#o0?   xCjfjrrf/nY` :+i:\"",
  "                                                          \"C#ati[fczv/_-?\\|// I](l\"\":",
  "                                                            J*mU0n/r/.    /t{i1{I,,\"\":\"                                           ..'..",
  "                                                             xdnvr()-   !?/\\{?_:,\"`''\"'                                           .'''..",
  "                                                             ivu(1[]{++t|{)t],\"\"`'',`    ^^^^```''                                 ....",
  "                                                            l::-~+~][[[}}(rvn_\"''\".    ,,,;I;\"^^``````''                             .'''.",
  "                                                                ..\"I~|\\jzLJzvxl:,.'^\".!:;>?]~I::,\"\"^^^``````''                      .'```'.",
  "                                                                     }XUCQLXuj(i>~!i!!l:I~[[~IIIII;;::,,\"\"^^^`````'.                 '```'.",
  "                                                      .```''    ^\":;IlnXYYvr\\|}l+>^!-<l:,;!l:\",,::;;IIIII;;::,,\"\"^^``````'             ....",
  "                                                    ,\"\"\"^`````^^I!!_?ilff/({1/>:>z+lU~l,^```''```^^\"\",,::;;;IIII;;::,:\",,\"`'`\"         '`^^`'",
  "                                                   l:;;\"^\"\",:;I!i<::?^,~|{(trn!:]f]I[<l,^'........''''```^^\"\",,::;;Il:I+?>,`'\"!'       '^^^^'",
  "                                                  l;;` l,:!~{(_[C\\IxL{\"i(1{q\\: ;:,^;<\"l:^'         ........'''```^^Il:!-?>\"''\"l~        ''''",
  "                                                 'I:l< \"}q)^Uv->1]iI!;^l]-UUQ) ,::^;[^\":^.                  .......!l,,;;\"`..^I-         '```.",
  "                                                 l;;>+l i]!`\";^^^^<;:,^I/oW-YU ^::^:?^^^^'                         :l,\",,^'..\"l?        '^\",\"`",
  "                                                ;;;!~~l. I\"```^^^^ll,:^:?ahfjQ' ::^,_^^`'..`,i^                    \"!:\",,^'.'\"!-        .`^^^'",
  "                                               'I:l<~!,` ^:^``^^^^\">::^,+mqu1J_ I:\",+:^`'.'\"l-                      >:!cdpOJ{I!i         .''",
  "                                               !;;>+>:`'  ;,```^^^^>I,\"\">X0z-Y) \":\"\"<i^`'.'\"l?                      i>Za8MwJcfi>        '\",,^.",
  "                                              ;;;i~<I^'.   ;\"``^^^^;!,,^!jJU-xu .:,\">i^`'.',![                      ;\\wdadQzxf[`        `\",,^.",
  "                                              I:l~~l\"'. .' ^,^``^^^`>:,^I|Xz)\\r\" ;,^i!^`..',i~                      ,{ZmwOUujt}^         .''",
  "                                             I;I>+i:`. .`,: :\"``^^^`lI,^;[vu|{f~ ::^!~\"`..`,>i                      .1ZmwOUujt{.       '^`.",
  "                                            ,;;i+>;^'. '\"!+  :^``^^`,i:\",_xr/]\\] ^:^l_\"`..`:>>                       }ZZwZUujt[       ',;:\"",
  "                                            I:l~~I^'. '\"l<   \",```^^'i;,\"</t\\[){ .:\"I~\"`..`:<l                        ZZwZUujt         `\"^'",
  "                                           I;I<~!,'. .^I+     ,^``^^'Il,^i/cO000< ;\";<\"`..^;~^                        OZwZJujt",
  "                                          ^;;i+>:`. .`;~`     .,^``^`^<:\"lu%%%%%C \"\";[\"`..^I+^                        OZwZJujt      ,;,",
  "                                          l:!~<;^.  `:>,       ^\"``^^'!I\"It&&WWWb `::?\"^..^I_\"                        fZwZJujf      ,:,",
  "                                         I;I<~l\"'. ',i!         \"^``^':!,;]kkkkkk! I:_^^.'\"l-                         fZwmJujf",
  "                                        ^;,I!l,'. '\"!>           \"````.>;;?Zkkkkk1 l:+:^.'\"l?                         )ZmmJujj",
  "                                        ;^^^`'^\" .^I~            `^```.ll;-LkkkkkJ II<i^.'\"!]                         >ZmmJuf-  :l,",
  "                                       ;:l+>,``:i`;>              \"```'\"iI[rkkbbdd `!>!\".',i~                         iQQLXr/?",
  "                                      \"I;~[+:'',i>~^               \"``'.iI[/O0LJUXi <il^.`,ii                         [d#dOJvXJu",
  "                                      :;,,;,`''^l_`                ^^``.I!]?rft\\||> !>~^.`:>>                         /00QOk88m?",
  "                                      \"I\"`^^`'.`;+                ' \"``''<]_?++\"\"\"  ^<_^.`:<<                          jxw8*J{",
  "                                       i:^`^^'.',>                 ..^`'.i?~^        >~^'`;~^                           !>{>\"",
  "                                       `I\"`(JpOc]!\"                ` ```.,?<l        l~^'^;+^",
  "                                        l:jk&WqJc{I                 ^ \"`'`-ii        \"<^'^I_\"",
  "                                        ^lmwbpQznj+                 `  ^''<!+        `l^`\"l-",
  "                                         IuLQOLXur[^                 : ``',l-         ;\"`\"l?",
  "                                          -CL00Uvx|.                  , ^`^I+^        ;,^\"!]",
  "                                          ,nLQ0Cznj                   \"  `^;<:        ^:^,i-",
  "                                           ICL0QYur:                   : '`:>i        .:,,,,^'",
  "                                            rL00Jcx]                   `` ^,!<       ^;;;;::,\",:",
  "                                            ,CQ0LXnj                    i .\"l-      llli<<i;,\"\":!;",
  "                                             rL00Uvr:                 .:I; 'I+l:   lili_[]~l:\"\":l<`",
  "                                             +CQ0Ccx]                :lli<`  ;;\";.`<!l!~-+i;,^^,I><",
  "                                              cL0QXuj               ^ili>;``\",;!+UC<!I;IlI;,\"^^,;i-",
  "                                              +CQ0Unf;              !illl{][j\\1OQO0<!;:::;:,\"^^\";!_.",
  "                                               zQ0CCYv;             +!III+l]Lf!|\\nj+iI:::;:,\"^^\":l~`",
  "                                               wdmYcjj|             IiIl`   ^.   .,!>l;::::,\"^^^,l<I",
  "                                               cYzCv/1{             ^>I;\"       ^:i <l;:::::\"^^^,I>!",
  "                                                (jxr|{,              <l;::;:,^^^:l+.>!I:::;:,\"^^\";i?",
  "                                                 l({-_               >!;::;:,\"^^,l~^:>I:::;:,\"^^\":!_",
  "                                                   ..                IiI::;;,\"^^,I<` <l;::::,\"^^^:l+^",
  "                                                                     '>I::;;,\"^^\"I>i >!I:::;:\"^^^,l<,",
  "                                                                      <l;::;:\"^^\";>! :>I:::;:,\"^^,I>!",
  "                                                                      >!;::;:,^^\":i>  <l;::;:,\"^^\";i+",
  "                                                                      :iI::;:,^^^:!-  >!;::::,\"^^\":!-",
  "                                                                      '>I::;;,\"^^,l_  :iI:::;:\"^^^:l+.",
  "                                                                       <l;:;;,\"^^,l+^  <l;::;:,\"^^,I~`",
  "                                                                       !!;::;:\"^^\"I~`  >!;::::,\"^^\"I>i",
  "                                                                       :iI::;:\"^^\";<,  :iI:::::\"^^\";i<",
  "                                                                       '>I::;:,^^\";>i   <l;::;:,^^^:!-",
  "                                                                        ~l;:;;,\"^^:i!   !!;::;:,\"^^,l+",
  "                                                                        !!;:;;,\"^^:!+   ^iI::::,\"^^,I~`",
  "                                                                        ^iI::;:\"^^,l-    <l:::::\"^^\";>I",
  "                                                                         >I::;:\"^^,l+    !!;::::,,\",;i!",
  "                                                                         ~l::;:,^^\"I~^   ^iIIIIlI:,\":i?",
  "                                                                         I!;:;:,\"\"\";<`    <>!!+]+l,\",l_",
  "                                                                         ^iII;II:,,I>I    !>l!~-<I\"^,I~^",
  "                                                                          <il<?_l,\":i!    \">I;;I;,^^\"I<`",
  "                                                                          >!!<_<;\"^,!l     <l::;:,^`\";<`",
  "                                                                          ili~i;\"``,!<     ~l;:;;,^`\";>,",
  "                                                                         l!!<<l,^``,>l     !!;:;;,^^^;>>",
  "                                                                         il>~!:^``\"l>      :i;:;;,\"^^:>i",
  "                                                                        il!<>;\"``^;+       '>I:;;:\"^^:ii",
  "                                                                       `!l><l,^`^:>`        <I:;;:\"^^:i!",
  "                                                                       !li~i:^``\"!!         ~l;:;:\"^^,!!",
  "                                                                      ,!!<<I\"``^I<          ;!;:;:\"^^,!l",
  "                                                                      >l><!,^`^:~           :i;:;;,^^,l+",
  "                                                                     \"!!<>;\"``,iI           '>I,\"`''.^l?",
  "                                                                     I^\"\",\"``\"l>             >,''`'. .^>",
  "                                                                    `'`'. ',\";>              ;^,>+!^. '::",
  "                                                                  ^\",<_l` .\"!<`             ^:\"I?}<\"  ',i",
  "                                                                  :\"I_?!`  ^l>              l,^^;;\".  .\"!i",
  "                                                                 ;\",!i;`   ^ll              ;:`'`^'   .\"l>",
  "                                                                ,\"\"I>l^    ^!I              ,:`'`^`.   ^I_",
  "                                                               `,\";i!,.   ':>               ,:^'`^`.   `;~",
  "                                                               ;\",!i;`   .\"!\"               ,:^''^`.   ':>,",
  "                                                              :\"\"l>l^    `;<                ,;^''``.   ',i!",
  "                                                             ^,\";i!,'   .,i,                :;^''``'   .\"l+",
  "                                                            ':\":!i;`    `Ii                 :;^''``'   .^I_",
  "                                                            I,^:il\".   ',>                  :;\"''``'    `;~^",
  "                                                            ,,`'`'.    ^:;                  `,,''''.    `::....",
  "                                                           ,:-~ii;,,\",:!lllII:.:           ;\"<}~iiil,\"\",lii!!!!, `,",
  "                                                          \"\"\"-----------------~:'          :^:~----------------+ 'i",
  "                                                          ^\".i--------------ii:IYCCCCCCCCCx:` ,-------------<iil `!",
  "                                                           \".                 .            ^`                    \".",
  "",
  "",
  "",
  "",
];
