/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `smoke_drag` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "                                                                                       .'''.",
  "                                                                                        ...",
  "                                                                                           ...",
  "                                                                                          '```'.",
  "                                                                                         .'````.",
  "                                                                                          .'''.",
  "                                                                                              ...",
  "                                                                                            .`^^^'",
  "                                                                                            '^\"\"^`.",
  "                                                                                             ''`'.",
  "                                                                               '~              ..",
  "                                                                            u  /|            '^\"\"^.",
  "                                                                        f   k  q)            `\",,\"'",
  "                                                                    (   c1 .M<'B1             '``'",
  "                                                                    >m: ~a!<8j|8{ J^",
  "                                                                     )a1 aw]%0Z#}cm  C:     '\",\"'",
  "                                                                      r*vzMQ%d#hz@1>#|      ^::,`",
  "                                                                    lI L#q*hMoWp%pQ$v        '`'",
  "                                                                     nwrpMhW*W&p@d$C+/<",
  "                                                                      (h*#&@$$$&W&WMq)   '\"\".",
  "                                                                   'fhOb8$$$$$$$$$$ac}   \";;^",
  "                                                                      QB$$$$$$$$B%*OUxi",
  "                                                                      h#@$B&ad0JXurfjqp)",
  "                                                                     ;k*&QYcxjt/\\-^ \\$WU;",
  "                                                                     vb?]?[uYbLf`  in8MU;",
  "                                                                     *v      w|` 'i/1]hJ;",
  "                                                                     }M#z]l -abx   ./[wL;",
  "                                                                      m8-   rmLuj){O8oBQ;",
  "                                                                      [W0\\}zCJuf/nrM8x8Z>l:",
  "                                                                       CYOu|uzn(}jQ8O(OU]],:",
  "                                                                      ,[nut1\\(lII~88/|f|(!\",;.",
  "                                                                     :<{)({-(!   ,\\r)\\t?;,,\"\"I`        ~xj/~",
  "                                                                    :>{i;+~_1{nzj)(1(}l,,^`'.`,       naWa0Yf",
  "                                                                   '\"\"'`^\":l-})[?}{|ti,^'.'^      '``>wdaqUuj:",
  "                                                                        '''``Jczzvvnj-`.^'     \"\"\"\"\"^;UUXvXYXu",
  "                                                                           .'rQOZQXur|\":''', :;,;><!:^>/cwpQXvt",
  "                                                           .\"^\"^```\"   `,::::/QQ0Czrtfi><>I<,!;;<[{_l\"'!YUCQJXvt",
  "                                                          :,;;^````^^^^;>I~_><cvur/)([:il^I_>l::i+_>:^''}XULQJzv[",
  "                                                         l;;.^I\",:;IIl!!~;:;^,-|1}[)ti:{X{Iv~l:\"\"::\"^^``'xYJQLUzu[",
  "                                                        ^I:ll l_?liXt_|O(IQC[\"~\\)|Xu1:;?1-l1+l:^`''``^^``lzYCQLYcui",
  "                                                        l:I>+.^fu?;/)!!]-li>:\"<}?uO\\' ;;\"^l_,!:^'..''``^^`-XUCQCYcn;",
  "                                                       I;;i+~: I:^`^^^^^:i:;^\">twO}m< ;;,^l_^,;^`'..''``^^`tXULQJXvn:",
  "                                                      ^I:!~+!, `;\"``^^^^^~;:\"^iZMQ-O? I;,^!-^^\":\"^''..''`^^:cYJLLJzvt",
  "                                                      l:I<+>:`  I,^`^^^^^!I:\"^iLkm-Q\\ \";,^!l^^`'\",^`'..''``^~zYCQLUzvf;",
  "                                                     I;;>+<;^'. `;\"``^^^^Il:,^!umZ-Jf \"::^i!^^'..^:\"^''..''`^|XUCQLYcuf!",
  "                                                    ,;;!+~l\"'.   ;,^`^^^^:i:,^lfQC-jv `::^i!^`'..^Ii:^`'..''`:uYJLQCYcu(i",
  "                                                    I:l~+!,'. .`.`:^`^^^^`~;:^l/UY{fn .;:^>i^`'.'\"l? \"\"^''..'`[zYJLQJXcn}i",
  "                                                   I;I<+i:`.  ',l ;,``^^^`!I:^I|zc1/jI ;,\">i^`..',i~   :^`'..'I)XUCQCzxf}I>",
  "                                                  ,;;i+<;^'. '\"!~ .:^`^^^`!l:^I)un{(t; I,\"<>^'..`:<>    \",^''.`IxXXcnf||?\"I;",
  "                                                  I:!+~I^'. '\"l<   ,\"``^^`;i:\";{rj)[|> ;,\"<>^'..^;+^     .:\"`'.:i\\\\(1}1]''\"l;",
  "                                                 ;:I~+!\"'. .^I>     :^`^^`'<;\";[/\\()1< \":\"~>^'..\"l-        `,^'.I:l>~iI`''`,l;",
  "                                                ,;;>+i,`. .`;~^     \"\"``^^'>I,:]#**ooQ ,:\"~<^..'\"![          \"\"``l,`'`^^`''`,!I",
  "                                                I;i+<;`. .`:<`       ,^`^^'ll,:?888888 .:,+,^..`:>>           ^,^;;\"`'`^``''`:<",
  "                                               l:l~~I^'  ',>'        \"\"``^':i,;]oooo** ';,+\"^..`;~:             ,\"!:^''`^`'.`:><",
  "                                              :,^^`'^^. ',ii          ,^`^`.<:;]kkkkkk_ l:_\"^..^I_.              ';l,`'''.  `:<:",
  "                                             `::!!,``,;'\"!!           \"^`^`.i;I[qkkkkk_ i:-\"^.'\"l]                 I;^'.    `I~",
  "                                             l:>}?I`'\"lil>             \"``^.lll{Lkkkkkt >;?\"^.',i~                  ^^.     \"l",
  "                                            ;I,;!I\"'.^I+~              ^^`^.:i!?Cddppqx ll?\"^.`:<l                         .",
  "                                            ^l\"`^^^'.`:<^               \"``'.<>]uYXzzcj Ii]\"'.^;+^",
  "                                             l:^`^^`''\"!\"             ' ^^``.><](||(((( .<[^''\"l?",
  "                                             .l\"`I|vzf]Ii              ` \"``.!++!\"\"     '<?^'',!-",
  "                                              I;lZo&kQXj~              . ^^`.;-<l        i>^'`:>>",
  "                                               !fqkowUvr}`              \" \"`'`[<>        !~^'^;~^",
  "                                               \")LL0QUvx\\!              ^ ^^'`_>>        :>^`^I-.",
  "                                                lzCQ0Cznj>               ^ ^``!>i        \";^`\"!]",
  "                                                .1CL0QYvx!               ; ```,ii        ^:\"`,>i",
  "                                                  cCQ0Jcn1                ^ ^`,i!        .:\"`:<:",
  "                                                  +CL0QXur`               ; ``,![        ';\"^I_\"",
  "                                                   rCQ0Jcx+               ^\" ^,!]         ;,,:l",
  "                                                   ,CL0LXn\\                ! `\"!?       `;::::,\",,.",
  "                                                    jCQ0Uvr`             .\"l\" \"l?`     III!i!I:,\",I:",
  "                                                    \"CL0Czn]            ;IIi>  :-,I\"  !!l>-]_i;,\",;iI",
  "                                                     jC0QXnf           l!l<~!   \"`^,`~>ll<-]_i:\"^\":!~",
  "                                                     \"XzXJXXj         '>ll:i>i>><~+nkjilIl!il;,^^^,I>>",
  "                                                      qbwJujj?        :>ll;[?~QL[0ZOm/iI:,,::,,\"^^\";!+",
  "                                                      CYXQv\\)?        '>l!\"'. -+::~1f}>I:,,,::,\"^^^,I>:",
  "                                                      ;frxr|{          <l;,          \">!;:,,,:,,\"^^\";!+",
  "                                                        -|1?-          >!;:,\"^`''',I<l >l;,,,::,\"^^^,I>;",
  "                                                         ';'           IiI::;;,\"^^\";>i ,iI:,,,:,,\"^^\";!_",
  "                                                                       '>l::;;:\"^^\";i!  il;,,,::,\"^^\",I<\"",
  "                                                                        <l;::;:\"^^\":i+  .iI:,,,::,\"^^\";!<",
  "                                                                        >!;::;:,^^^:!-   l!;:,,,:,\"^^\",l<,",
  "                                                                        IiI::;:,\"^^,l_    >l:,,,::,\"^^\";ii",
  "                                                                        '>I::;;,\"^^,l+^   ^iI:,,,:,\"^^\":l<",
  "                                                                         <l;:;;:\"^^,I~^    i!;,,,::,\"^^\";ii",
  "                                                                         >!;::;:\"^^\"I<:     >I:,,,:,\"\"^\":l~",
  "                                                                         IiI::;:,^^\";>i     ,!;,,,::,\"^^\";il",
  "                                                                         '>I::;:,^^^:i!      !l:,,,:,,\"^\":l~",
  "                                                                          <l::;;,\"^^:!>      .iI:,,,:,\"^^\";>:",
  "                                                                          >!;:;;,\"^^,!-       l!;,,,:,,\"^\":l+",
  "                                                                          Ii;::;:\"^^,l_        >I:,,,:,\"^^,;>\"",
  "                                                                          '>I::;:\"^^,I+.       `i;,,,::,\"^\":!<",
  "                                                                           <l::;:,^^\"I~^        il:,,,:,,\"\"\";>\"",
  "                                                                           !!;:;;,^^\";<`         iI:,I;II;,\",l<",
  "                                                                           ,i;:;;,\"^^:>I         ,!Iili_->;\"\";>`",
  "                                                                           '>I;;:::,,;i!          !>il>-->:\"\":!>",
  "                                                                            <il!~~l,\":il          .~!Ilil:\"^^,!?",
  "                                                                            !il<?-!,^,l?           <lI!!I,^`^:i<",
  "                                                                            !li~<l,^`\"l-          '>ll!!;\"^`\";<:",
  "                                                                           \"!!<~!:^``\"l_          ^iIl!l:\"``,l-",
  "                                                                           il>~>;\"``^:<`          I!Il!I,^`^:ii",
  "                                                                          I!i~<I,^``,>,           >!I!!;\"^`\";~^",
  "                                                                         `!!<~!,^``\"!l            <lI!l:\"``,l+",
  "                                                                         ll>~>;\"``\"I~            '>ll!l:^`^:>I",
  "                                                                        :!!~<I\"``^;>             :iIl!I,^`\";+.",
  "                                                                        i!<~!,^``:<`             ;!I!!;\"``,!_",
  "                                                                       !l>~i:^``,i\"              ~;^^^`'`^:>:",
  "                                                                      ^;;ll;\"``\"ll               \"'``'. .\"l_",
  "                                                                     .'''. .\"`^I<               ,^I+~;' .^I>",
  "                                                                    \"^I~!^  `II~               l\"\">[?l'  `;>",
  "                                                                   :\",~}~\"  ';+`              `;\"^:I:`   `;~.",
  "                                                                  ^\"\"l<!\".  ':+               ;:^\"::^.   `;+",
  "                                                                 \",\"I<i,.   ';~               l\"^,;,`    ^l+",
  "                                                                 :\":>>;'   .\"!\"              ^;\"^,;\"'   .\"!!",
  "                                                                ;\",i<l^    `I!               I,^\"::^.   ',>,",
  "                                                               :\"\"l<!\".   ',<                I\"^,;:`.   `;~^",
  "                                                              ,,\"I<i:'    ^!:               ,:^^,;,'    ^I_",
  "                                                             `,\";>>;`    `;>                !,^\"::\".   .\"l_",
  "                                                             !,^;il^.   .,>`                I\"^\"::^.   ',;^`^\"' `",
  "                                                             ,\"`'`'.    ^:;                ':\"`.''.    ^i<~+__I `l",
  "                                                           .\";?<ii,,\"\",;!lllII\".^         ^^I-i:,lii<---------- `>",
  "                                                           \"\"\"-----------------!I`        ;^I-------------<iI\"  \";",
  "                                                           \"\".i--------------ii:!QCCCCCCCX;`.I-----<il\"\"",
  "                                                            ^.                 '          ;^  `\"\"",
  "                                                                                           `",
  "",
  "",
  "",
];
