/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `smoke_exhale` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                              ?",
  "                                                          !   J!",
  "                                                          |J  JJ",
  "                                                       !  `8? J8` |",
  "                                                       ?a` m8!Jo| 8? ?J",
  "                                                    m|  n8|?8amza|8?`a?",
  "                                                     Jan`m8J8x8)dao|a8",
  "                                                      ?8oJ8xorU1vw080m!J",
  "                                                       !aXqo[0;\\+~xmo88|",
  "                                                      JmmaY<[,  ]Cm|\"u8m`",
  "                                                       !mozr'!nmn`  ;}X8an`",
  "                                                      |JJa8ran!   <\\uwW$f\\a",
  "                                                       `n8J?   ,[fXqa$$$b;d|",
  "                                                         8(\".i)rCbqUd$Mndr{m",
  "                                                         8*>[nO*Q_^a$$$$@M|p!",
  "                                                         n8h#B$$$$f[c$$$kzMXm",
  "                                                         Jt|8#k#$pf[(rjxucLo8!  jd_",
  "                                                         ?o~{#k$$$v\\XXXczYUp8!'QbaWz'",
  "                                                          !q|n&amXrrxUdpqCLwa_pwL*8&b_",
  "                                                           `a|j/1uJcU@$$$$Jqha0Z#&&88Wz'                                          ..'..",
  "                                                            `ZQvxzLQp$$$oqUaWqdW&8%@B&r'  ]]CC]]                                  .'''..",
  "                                                            'a#qQ0mwZbbULZbMd&&8B@B&j' 'x8%%%BBBBBCC]]                             ....",
  "                                                           .qWW%obkpbbbd*omxud8@Bh)   _b&&M#W8%%%%BBBBBBCC]]                         .'''.",
  "                                                            ]\\L*@@8B%bdZz(/jxv#W0xYXzU*WWaqwkMW&&&88%%%%BBBBBBCC]i                  .'```'.",
  "                                                                 ]\\L*mjt|)|fuXQohkoo**#WMkmmk####MMMWW&&88%%%%BBBBBoCu]i             '```'.",
  "                                                     |w%%BBon']]fOWM#*uftfxzJCZ*ba%*pk#W&M**W&&&WWMMMM#MMMMWW&&88%%%%B%BBoCC?          ....",
  "                                                   -k8888%BB%%%%M*odqo#YXULOOUhWajb*/k#&%%%%BBBB%%%88&&WWMMMMMMMMMWW&W8&&8%B%k_        '`^^`'",
  "                                                  I#WMM8%88&WM#*okWWq%&kLOLUcu*WwXw#mk*&%B@@@@@@@@@@BBBB%%%88&&WWMMM*W#dqa&BB&*~       '^^^^'",
  "                                                  qMWB$#&W*kOQdm\\J#c(O8aQ0Z]JW$MW&%Mh8*W%@$$$$$$$$$$$@@@@@@@BBBB%%%#*W*pqa&B@8#0        ''''",
  "                                                 1#W#h$8Z?Q8/xph0woMoW%*wpt/)Q$&WW%Ww%8W%@$$$$$$$$$$$$$$$$$$$$@@@@@*#&&WM8B@@8#p         '```.",
  "                                                '*WMab*$aw*B8W%%%%hM&&%MJi;pf/$%WW%Wq%%%%B$$$$$$$$$$$$$$$$$$$$$$$$$W*&8&&8B@@8*q        '^\",\"`",
  "                                                LMWokk*@$M8%B%%%%%#*&W%Wqi>Yz(B$WW%&d%%%@@@B&oXQQQd$$$$$$$$$$$$$$$$8oW8&&8B@@8*L        .`^^^'",
  "                                               1#W#kbo&B$8W%BB%%%%8hWW%&b[?n0\\d$MW8&bW%%@@@8#p        `[[[/QQQd$$$$$aW88dZwh%8or         .''",
  "                                              '*WMabaW%@$$M&%B%%%%%aM&88af1jpfQ$8W88ka%%@@@8*q                    `[mM8t\";]\\C8aj        '\",,^.",
  "                                              LMWobh#8@@$$$M8BB%%%%Mo&&%oz\\tpcu$@W&8ao%B@@B&ow                      vWm_i_(rv*o<        `\",,^.",
  "                                             _#W*kk*8B@$@B$%&%B%%%%BaW&%#Ljr0Cc8$M&8o*%B@@B&oz                      /Mw[]{/nzha>         .''",
  "                                            'pWMhbo&B@$$B&W$W8BB%%%%*#&8WmnuCOXk$WW%*b8B@@B&aj                      +#w}]{/nz*h,       '^`.",
  "                                            cMMobhM%@$$B8*Q0$W%BB%%%&aW8&dczJqJw$%W8*d8B@@BWhj                       dk}]{/nz8O       ',;:\"",
  "                                           _#W*kk#8@@$@8#O.^&8&%B%%%BoM&8hUUJmQO$@W8#b8B@@%Wh)                       '8}]}/nz8.        `\"^'",
  "                                           pW#hbo&B@$@%Mb:  }$&8BB%%BM*&8oOwao**@$M8Mh8B@@%Mk>                        8}]}/nz8",
  "                                          fMMabaWB@$@%Wk<    0$&%B%%B%hW8#U)))!^|$88Wm8B@@%Mb>                        8j]}/nX8      ,;,",
  "                                         I#W*khM%@$$BWh[     ^&%8BB%%@*M8MY,,:::~$BWWq8%@@%#d>                        Jv]}\\nX8      ,:,",
  "                                         pW#hk*8@$$B&or       }$8%BB%BWo&Mw~~~~~~*$#Wd8%@@8#p                         Jv][\\nX8",
  "                                        fM&#o#&B@$@8*X         0$8%B%B@aWMq{~~~~~0$*WbW%@@8*q                         nQ[[\\nO8",
  "                                       lM88%%B%8$@%#0          ^$%8BB%@##Mp|~~~~~\\$#Mko%@B&ow                         ?w[[\\nOJ  :l,",
  "                                      'dW*ba&BBWa%MZ.           t$8%B%@8aMmc~~~++_$Boho8@B&oz                         ?k)(jcmJ ^)-",
  "                                      t#MkmbWBB&oak<             M$8BBB@a#mU{)(\\tfo$ka*8@B&ar                         |dI_{\\YaJ@$z",
  "                                      vM&&M&%@@8*d~              -$%%BB@#owqzXQZmp%$*ak%@BWhj                         J01)vb88m?",
  "                                      t#8%%8%B@%Md                m$8%B@@hwdOJJ???^$%hd%@%Whf                         `aOp888J",
  "                                      .aW%%8%B@B&h:               '$@%BB@oqk>      &$hk%B%Mk<                          `nJJJ?",
  "                                       {#8%88Zw88o[                j$%%B@&qh(      0$*k%B%Mb>",
  "                                        wW8O,:?\\bWn                 h$8BBBpar      }$8h%B%#d>",
  "                                        {#8)+-(ju8b                 {$$%BBhoQ       $B#8B8#p",
  "                                         C&C)1(fuko>                 Q$BBB&#p       b$M8%8*q",
  "                                         I#h(1)/xQ#:                 I&$%B%Mb>      t$M&%8*w",
  "                                          c8n)1|ru8                   t$$%%Mh]      >$%W%&oL",
  "                                           (h(1)fno?                  .b$B%Waj       $@W&&&&hU?",
  "                                            mn)1\\xZJ                   {%$%&oX      'ZMMMMW&&8&b_",
  "                                            !h(1(jz8                    a$@8*p?    'q##okkoM&8&W*u",
  "                                             mn1)tno?                 )b#M$B#b*b_  Jo*odmwk*&88W#h<",
  "                                             |h)1|rZJ                c*#akB$$MM8MwYko#okpdaM&88&#aX",
  "                                              an1)fz8               {a*oaM%%8&M*o8dh*MM###W&8%%&Maq",
  "                                              |h)1tu*?              Uo##*OwmXJ01dw1h*MWWWWW&8%%8Wod:",
  "                                               aX1\\|LM?             boM#Mb*w(XoLb#Zko#WWWWW&8%%8W*b<",
  "                                               8\\[txXZa             uo##B$$$%@$$$$$#a#WWWWW&8%%8&#k(",
  "                                               aUj|xJ0m             }a#M8$$$$$$$%Wo;h*MWWWWW&8%%&#hx",
  "                                               `qzccCO~             .h*MWWMW&8%%W*d:ZoMWWWWW&8%%8Maq",
  "                                                 _QOpL               ZoMWWMW&8%%&#b</a#WWWWW&8%%8Wod",
  "                                                  I++                no#WWMW&8%%&#k<;h*MWWWW&8%%8W*b<",
  "                                                                     ~a#WWWM&8%%8Mhj ZoMWWWWW&8%%&#k]",
  "                                                                     .k*MWWMW8%%8Mar /a#WWWWW&8%%&Mhr",
  "                                                                      ZoMWWMW&8%8WoX ;h*MWWWW&8%%8MaQ",
  "                                                                      /oMWWMW&8%%Wop  ZoMWWWW&8%%8Wop",
  "                                                                      ~a#WWMW&8%%&*d  /a#WWWWW&8%8W*b:",
  "                                                                       k*WWWM&8%%&#b> ;h*MWWWW&8%%&#k<",
  "                                                                       UoMWWMW8%%8#k<  ZoMWWWW&8%%&Mhr",
  "                                                                       /aMWWMW&%%8Mh]  /a#WWWWW8%%8MaX",
  "                                                                       ~h#WWMW&8%8Mar  ;h*WWWWW&8%8Wop",
  "                                                                        k*WWMW&8%8Wox   JoMWWWW&8%%&*b",
  "                                                                        UoMWWM&8%%WoQ   }a#WWWW&8%%&#k<",
  "                                                                        }aMWWMW8%%&*p   .h#WWWWW8%%8Mh|",
  "                                                                        ;h#WWMW&%%&#b    J*MWWWW&&8&Max",
  "                                                                         k*WWMW&8%8#k>   }a####*#W&8Woq",
  "                                                                         uoMWWW&888Mh<   .ha**bwb*&8&*d",
  "                                                                         }a##M##W&&Mh(    Uh**kphM8%&#k>",
  "                                                                         ;ho*hqd*&8War    }a#MM#M&%%8Mk<",
  "                                                                          m**kdhM8%&ox    ;h#WWMW&%%8Mh<",
  "                                                                         Ia*akaM8%%&*X     k*MWMW&8%8Mh]",
  "                                                                         C*ohh#&%B%&a(     UoMWMM&8%8Waj",
  "                                                                        Io*akoW8BB8*Y      /oMWMM&8%%War",
  "                                                                        m*okaM8%B8Mb.      ~a#WMMW8%%War",
  "                                                                       {o*hh*&%B%Wh<       .h#WWMW8%%Wox",
  "                                                                       w*akoW8BB&ox         k*WWMW8%%&ox",
  "                                                                      to*hh#8%B8#O          u*MWMW&%%&*x",
  "                                                                     .a*ak*&%B%Wk;          /oMWMW&%%&*Q",
  "                                                                     t*okaM8BB&o|           ~aM&8BB@@%#q",
  "                                                                    I#%88&8%B8#Y            .a&BBBB@$$%h",
  "                                                                   nBBB@$$B&8WZ.            'M%&ab*%$$BWv",
  "                                                                  X8&hd*B$@8*h<             jW8#qmh8$$@&a;",
  "                                                                 -W8Mdq*B$$%*X              q&%8MM8@$$@&or",
  "                                                                'M8&oaWB$$$%*x              LW%BB%B$$$@8*X",
  "                                                                0&8#a#%$$$$8o|              cW%BB%B$$$$%#d",
  "                                                               j&8Mao&@$$$BWZ.              cW%BB%B@$$$%Mk:",
  "                                                              _W8&oaMB$$$$8o[               cW%BB%B@$$$BWa]",
  "                                                             'b88#a#%$$$$BMO                cW%BB%B@$$$@&or",
  "                                                             X&8Mao&@$$$@&a]                cM%BB%%@$$$@8*Q",
  "                                                            )W8WoaMB$$$$%#U                 vM8BB%%@$$$@%#d",
  "                                                            q&%Wo#8@$$$@&h;                 vM8BB%%B$$$$%Mk<",
  "                                                           ?&&BBBB@$$$$%WMLLLL]            -a&&B@BB@$$$$%WW@@@@$L|",
  "                                                          l&WpkaaM&&8&W***###W@d          'W8hmkaaa*&88&*oooo**&$%c",
  "                                                          z88pppppppppppppppppkW~         _W%Wkppppppppppppppppd$Bo",
  "                                                          f8@appppppppppppppooW#l         -WB$&ppppppppppppphoo#$Bw",
  "                                                          ^h@$$$$$$$$$$$$$$$$$*}...........J%$$$$$$$$$$$$$$$$$$$$h+",
  "                                                            fb$$&mmmmmm|\\\\\\\\\\i^^^\"\"\"\"\"^^^^^^zM$$$$$$$$$&ZZZZZY)1{",
  "                                                          ..'''````^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"i\\\\i^^```'''...",
  "                                                             ...''''````^^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
