/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `smoke_drag` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "                                                                                       .'''.",
  "                                                                                        ...",
  "                                                                                           ...",
  "                                                                                          '```'.",
  "                                                                                         .'````.",
  "                                                                                          .'''.",
  "                                                                                              ...",
  "                                                                                            .`^^^'",
  "                                                                                            '^\"\"^`.",
  "                                                                                             ''`'.",
  "                                                                               `?              ..",
  "                                                                            J  |J            '^\"\"^.",
  "                                                                        n   8` mJ            `\",,\"'",
  "                                                                    |`  Jn `8|`8J             '``'",
  "                                                                    ?a! ?8??8m|8J J!",
  "                                                                     n8n 88|8om0Jn8  J!     '\",\"'",
  "                                                                      Jommq88Y8|a8J!aJ      ^::,`",
  "                                                                    !!`aXoq/C}Jfa0aaa`       '`'",
  "                                                                    `JaJo[p>|:!rlbfp||?",
  "                                                                      JoQO,:   (\\\\p88J   '\"\".",
  "                                                                   `n8m8Q/JJmJJn??`ihJ   \";;^",
  "                                                                     `av??      '^l{C8|",
  "                                                                      8X. ',i_1\\jnJOq8an",
  "                                                                     !80,)txX0wh*B$$$/:k?",
  "                                                                     nB&wooqL1xX%$$opC;w?",
  "                                                                     8Y$$$$$$]C%$BaUO$<k?",
  "                                                                     |zI#d*$pi+c$$$@M$|8?",
  "                                                                      a?p$$$z[|nzQOm8WL8?",
  "                                                                      |q)CZj|\\uXUuzM8Z88Y*c",
  "                                                                       pf1uCuruLZXq8hL*8bw&Q'",
  "                                                                      ckvnYOJL*#Mk88Z080Lo8&d+",
  "                                                                     chOQLOpQo$$$&hqOWpqM&&88M1        ?JJJ|",
  "                                                                    chOaMbkbwOvjz0LqW8*&&8B@@%0.      J0>>\\Qa`",
  "                                                                   188BB%8W&8MdbhhMoZa&%B@Bh('  ?JoBBB*_i?/uk?",
  "                                                                     ]uq@@BB%fcvvXuvXp%@%Ul   -h8888%B8rfnftzM`",
  "                                                            `]CCCC]     `]C*@z)1}(fuzL8WUYYcCQM&MakoW%%M0]-(fYa`",
  "                                                          'x888%%BB8n]CYbWWWWJ)))\\rcUXohha#k&*WMhmOd#8BB#/|(\\jCa`",
  "                                                         'd&WW%%%%%%%%%MaMkdakrxuzUQLmWo*%#da*WWoddaW%BB%m/((/jOJ",
  "                                                         qMW@%#&&WMM##*okMWM%&pC0ZmQYoWOfZ#xb*W8&WW8%%%BB8U\\((/rbJ",
  "                                                        f#W#*$#dq*afYdC{L#)|w8kJQLjn0WWq0p#Od*W%BBBB%%%%BB#x\\(|trb|",
  "                                                       I*WMhb@%XuqMJQ**wp*oaW8hZqn{JB$MM&%*d&oW%B@@@BB%%%%%dt|)|fxM?",
  "                                                       pMMobkW$#W%B%8%%%WaWM%8aY]{Z[k$MM&%*d%&M8BB@@@BB%%%%8U/((\\fvM?",
  "                                                      fMW*kbo&$%M8%%%%%%%kMW88a}I(p{q$#M&%*p%%8W8%B@@@@BB%%%8x\\((/jcd`",
  "                                                     I#W#hbaW%$$M&%B%8%%%oMW88o(~}p(C$8W&%o*%%BB8&8B@@@@BB%%%at\\((/rL8O'",
  "                                                     pMMabhM%@@$%M8%%8%%%#*W&%on[{p/Y$&WW%o*%%B@@8W8%B@@@@B%%8Q/|)|trL8w.",
  "                                                    cMWobk#8B@$$$M&%%%8%%WaW&%*X(|pzx$BWW8ao%%@@@%MoW8B@@@@BB%&c/()|frq&m.",
  "                                                   _#W*kbo&B@$$B$BW8%%8%%BkWW%#U/fOYv$@WW8ao%%@$@8*qlO&%B@@@BB*#t\\((\\fxkWm.",
  "                                                  'pWMhbaWB@$$B&#$W&%%%8%B*MW%#Crx0JzM$M&8aa%B@$B&oz  (W8B@@@@#&mt\\(|jvZ8#Z",
  "                                                  cMMabhM%@$$@8*0C@W%B%8%B**W%MQuvOQUM$M&8ha8B@@BWhf   'O&%B@@B#8JjrvYLh%8#v",
  "                                                 _#W*bk#8@$$@8#O.^$&8%%%%BMoW8MOzXQmLa$W&8ha8B@@%Mb>     )W8B@@WM8dO0d*%@B8#u",
  "                                                'pW#kb*8B@$@%#Z.  z$&%B%8%@kW8MmUJL0Oh$8W8kh8@@@8#p       'Y&%B@#W%%%%%BB@B&*u",
  "                                                zMMhba&B@$@%Mb<   ^$88%%%%@aM&WwQQQQoB$&W8kh8@$B&ow         -k8B%*&BBB%%B@@B&*u",
  "                                               _#WobhW%@$$BWk<     z$&%B%%@**&Wq\"\"\"\"\"\"$@W&b&8@@BWaj          'X&%MM8BBB%%B@@%Wh;",
  "                                              '*W*bk#%@$$B&h~      ^$88%%8BWo&Wwii!!!!$BM&d&8@@%Mk?            -k8*W%BB%%B@@BWhf",
  "                                              Q&%%BB%8$$B&ar        z$&%%%B@hWMw~~~~~~p$#Wd88@@%#d:              rM#&%BB@@$$BWk?",
  "                                             jWWo*&BB&M@8ox         ^$88%%%@aM#m?~~~~~p$oWp8%$@8*w                lpW%@$$$$$BMO",
  "                                            I*WhZq#%B8*a*X           L$&%%%@*#*Z(~~~~~Y$aMq8%$B&ac                  X8@$$$$$8q.",
  "                                            u#&M*M8B@%Mb0            !$8%B%@Wooq|__--?v$**q8%@BWh(                   !C$$$$w(",
  "                                            {#8%%8%B@BWh<             q$8%%B@haqutfjrrz$#ow8B@%Mb>",
  "                                            .qW%%%%B@@8o[             1$%%BB@ahwmwhaaao$@km8B@8#q",
  "                                             +*&%%8%%%8#Y              a$8%B@*bdt??    &@hq8BB&oL",
  "                                              CM88x,~)08k              )$%%B@Mph(      0$oh8BBWhj",
  "                                              'o&L<i]/no#<             .8$8%@Bmhj      0$*k8B%Mk>",
  "                                               tWq(1)/xQ&x              j$%%BBdaj      }$Wa8B8#p:",
  "                                                q8f)1|ju8n              .8$8BBoaj      }$&M8B8*w",
  "                                                +Wh(1)tnp|               L$%%B&ar      ^$8W8%&aj",
  "                                                 -an)1\\rJm               I%$%B&or       $@W8%Wk]",
  "                                                  |h(1(fnM!               L$B%&ow       &@M8%Md>",
  "                                                   mn)1/xqn               {8$%&*w       0$M&&W#|!",
  "                                                   !h(1(jUa                w$B8*q      'ZMWWWW&8&k)",
  "                                                    mX))/no!             )O*8$8*qYl   'p##*ao#W&8&#c",
  "                                                    !#(1|rZJ           'L##oa$$&p&#t .w**apwdaM&8&Mon",
  "                                                     mC))fX8           C**hko$$$8%8&m*a**hpwdoW888W*k;",
  "                                                     !#nf\\fZa`        ~h**WoaoahkkbMawa#M#oo*W&8%8&#aX",
  "                                                     `8[]\\uzwJ        \\a#*Mmqk)(m)j8(Ua#W&&WW&&8%%8W*b.",
  "                                                     `8xf(nJZJ        ~h#*8B@$pdWWkBoqa#W&&&WW&88%8&#a\\",
  "                                                      ?dzczCO`        .k*M&$$$$$$$$$$$a*MW&&&W&&8%%8Wob.",
  "                                                       `|L0qL          ZoMW&8%%B@B&#h(Ia#W&&&WW&88%8&#h\\",
  "                                                         +v+           na#WWMW&8%%8Mhr toMW&&&W&&8%%8Mod",
  "                                                                       ~a#WWWMW8%%8Max .m*M&&&&W&88%8&#h[",
  "                                                                       .k*MWWMW8%%8WoQ  +a#W&&&W&&8%%8MoO",
  "                                                                        ZoMWWMW&8%8Wop   JoM&&&&W&88%8&#h[",
  "                                                                        noMWWMW&8%%&*d   .h#W&&&WW&8%%8MoY",
  "                                                                        ~a#WWMW&8%%&#b>   {o#W&&&W&88%8&#k;",
  "                                                                        .k*WWWM&8%%&#k<    m*M&&&WW&8%%8MoY",
  "                                                                         Z*MWWMW8%%8Mh]    Ia#W&&&W&&8%8W*k;",
  "                                                                         noMWWMW&%%8Maj     toM&&&WW&8%%&Max",
  "                                                                         ~a#WWMW&8%8Wax     .w*W&&&W&&8%8W*b.",
  "                                                                         .h*WWMW&8%%WoX      +a#W&&&W&8%%&Ma\\",
  "                                                                          Z*MWWM&8%%&*p       J*M&&&W&&8%8W*b.",
  "                                                                          noMWWMW8%%&*d       .h#W&&&W&8%%&Ma}",
  "                                                                          ~a#WWMW8%%&#b:       {oM&&&W&&8%8W*Z",
  "                                                                           h#WWMW&%%8Mk<        m*W&&&W&&&8&Mh[",
  "                                                                           J*MWMW&8%8Mh<        Ia#W&#MM#M&8&#O",
  "                                                                           /oMWWW&8%8Wa|         t*#o*odpaM88Ma~",
  "                                                                           ~a#MMWW&&&Mar         .who*hppaW88WoX",
  "                                                                            ha**kk*&8Wox          +ko#*o*W8%%&*q",
  "                                                                            Jo*hqpo&8&*q           k*#*oM&%B%Woz",
  "                                                                            w*okk*&8%8#p          ~h##o*M8%B8Mk]",
  "                                                                           to*hkoW8BB8*Q          }a##o*W8%%&#p",
  "                                                                          'a*abaM8%B%Wk<          uo#*o#&%B%War",
  "                                                                          C*okh#&%B%&a[           Z*#**M&%B8Mk>",
  "                                                                         {o*hk*&%BB&*x            h*#o*W8%%&*0",
  "                                                                        .w*abaW8BB8#0            ~a##o#W8%%Wa(",
  "                                                                        v*okh#8%B%MZ.            /o#*o#&%B8Mb:",
  "                                                                       Io*hk*&%B%Wh<             u*#**M8%%&*L",
  "                                                                       w*abaW%BB&o[              kW%%%B@%%Wh]",
  "                                                                      fMW*#W8%B8*n              ?8BBB@$$@8#d",
  "                                                                    `w@B@@$@8%%MO              -&%MbkMB$$%#X",
  "                                                                   'h%Mko%$$%##b.              #8&hmq#B$$BMZ",
  "                                                                  'b8&kmb&$$BWb<              1M8%W#W%$$$BMk:",
  "                                                                  X&8*h*8@$$BWb               LW%8WW%@$$$BMd",
  "                                                                 z&8Mha&@$$$BMO              '#&%&W&B$$$$%#0",
  "                                                                -W8WahMB$$$$8o[              fM8%&W8B$$$@8or",
  "                                                               lM8&oh#%$$$$BMU               p&%8WW8@$$$B&a]",
  "                                                              'b8&*ho8@$$$@&h;              I#8%&WW%$$$$BWk>",
  "                                                              0&8#haW@$$$$8*\\               cW8%&M&B$$$$%#d",
  "                                                             j&8MahMB$$$$BMZ                *&%8WW8@$$$@8*d[]][i",
  "                                                             *&8Ma*8$$$$@&a<               +#8%8WW%@$$$@&M8%%8B$a'",
  "                                                            |&8BBBB@$$$$%WMLLLL]           UW8B@@@@$$$$%akkbdd#$Bq",
  "                                                           )8Mqkaa&&&8&M***###8@X         X8#paW&*aohpppppppppp$Ba",
  "                                                           z88pppppppppppppppppoM<       IM8#pppppppppppppho#8$$8u",
  "                                                           z8@appppppppppppppooW*`       !M%@#pppppho#88$$$$$$$L(",
  "                                                           \"h@$$$$$$$$$$$$$$$$$o}.........d%$$B88$$$$$$$$kOj{\"",
  "                                                            ;zk$$&mmmmmU\\\\\\\\\\\\^^^\"\"\"\"\"^^^^!q$$$$$$$&ZY(-..",
  "                                                          ..'''````^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"]nmZ||^^```'''...",
  "                                                             ...''''````^^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
