/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `sneer` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                        iI",
  "                                                                     \\  ]f",
  "                                                                     L! ]L",
  "                                                                 _(  vQ Xb` t",
  "                                                             .l   Jr +#}Yo<!p  U",
  "                                                              (C; ,ar,MwmW/dL 0Y",
  "                                                               >kJ:(*Jk#d8X$XQMi",
  "                                                                lq*Cp#d&k%k%0$Y;n",
  "                                                               ! ^J#ah##*@*M8dZM]",
  "                                                               \"YpLZhM&@$$$@$$$Q{",
  "                                                                 >J*MB$$$$$$$$W0zf",
  "                                                               |dM8$$$$$$$$%hOXcvw0?",
  "                                                                 :d&$$$@#wJcrt~!C$WC`",
  "                                                                  phWo0Yuj/j}  'x*&OI",
  "                                                                  Qkbxt/vQw> `1Uzw8d1",
  "                                                                 !X  ;;~]mn!   'rc*#u",
  "                                                                 ;u]->  _Zb0`  ~uxL&Q",
  "                                                                  ?ab`  `OLXcYcnrfjhd; `:",
  "                                                                   jp~i<uUUtfjxjt\\|cL;I_::",
  "                                                                    XX0z/uvr((f/|)(/[i1(,\":,",
  "                                                                    :uXu|([.   :{1|t}\\?;,,\",I",
  "                                                                   .i1/|}[_  .I_{)\\(}>:,\"`''\":",
  "                                                                   i<<~-+]{xxr{{1(t-\",^`.'`'     ```'",
  "                                                                    ..':;l-){}[{fnnt:`.``.    \"\"\"\"\"^````````'",
  "                                                                        ..'+XzQ0CXux}^\"' '^ ,;,;>~i;,,\"\"^^^^````````'",
  "                                                              `'          '`cCL0LYuj/l!i!l~,!;;<[{-!llIII;;::,,\"\"\"^^^```````'",
  "                                                          ^\"\"\"^```^` `;lli><{UYXvr\\((I+<,I+>l::!++i;;IIIIllllllIII;;::,,\"\"\"^\"^^^````",
  "                                                         ;:II\"`^^^^\"\",;<:><;,)t\\){{|<:>|iIf)l:\"\",,\"^^^\"\"\",,:::;;IIIIlllllIlI,l<i:`'^I.",
  "                                                        ;;:` l,,l!i>><}-;_u!\"<|1(frc!:_c|I)-l:^`'''..''''''````^^^\"\",,:::;i;;+{-I^'`;<",
  "                                                       'I:Ii ;{z+ILU-)0rl)j-\"i1}}w/; ;;,^I<,!:^'..     ...........'''''``:i:,IiI\"'.`:<!",
  "                                                       !;;>+: 1/~`+~I\"li>::\"^!?1LjZ_ :::^;<^,;^'                     ....`i:,::\"`..`;~;",
  "                                                      ;;;!~~l \";\"``^^^^^<;:\"^lu&#-0f \"::^;<^^\"\"'                          >:,::\"`..^I_",
  "                                                     'I:l<+i,. ;,^`^^^^^!I::^Irak-cz '::^;<^^`'....                       >;,\\cuj1,\"l_",
  "                                                     !;;>+>;^' `;\"``^^^^Ii::^;|pw/uU .:;^;<^^`..',i-                      >>ZaMhZUv~i>",
  "                                                    ;;;i+<I^'.  ;,^`^^^^`~;:^:?0Q|(z! ;;^;<^^`..`:>>                      <cdoWkQzn/<^",
  "                                                    I:l~~!\"'. .  ;\"``^^^`!I:\",_JUx)v< I:^;+\"^'..`;<:                      ivmqq0Xxtt_",
  "                                                   I;I<+i:`.  '\" ,,^`^^^`:!:\",+zzj]x[ \":\";[\"^'..^;+^                      :vmqqQzx//_",
  "                                                  ,;;i+<;^'. '\"!, ;\"``^^^^>:,\"<run-j( ^:\";[\"`'..\"l-                       \"vmqwLcr/(I",
  "                                                  I:!~~I^'. .^I<  `,^`^^^'i;,\"itrj-\\| .:\";[\"`'.'\"!]                        LmqwCvj/}",
  "                                                 I:I<~!\"'. .^;+    ;\"``^^'!l:^!|t/{)1, ;\":[\"`..',i~                        ZmpwCvj/;",
  "                                                ,;;>+>:`. .`;<`    ',^`^^`,i:\"lfOO00Q[ I,:]\"`..`:>>                        ZwpmJuft",
  "                                                I:!~<;^.  `:>,      ,\"``^`.>;\"In88888J \"\":]\"`..`;~:                        ZwpmUntf",
  "                                               I:I~~l^'. ',i!        ,^`^^'iI,IfMWWWWk \"::]\"`..^I_\"                        ZwpZYxt?",
  "                                              ,;;I<!,'. '\"!l         \"\"``^':!,I}kkkkkk ';:]\"`.'\"l?                         mwpOXx/+",
  "                                              ;^^``'^` .^l~           ,^`^`.<:l{kkkkkk_ !;?\"^.'\"!]                         mwpOzr/;",
  "                                             :,l>I^'^;\"`I<            ^\"```.!Il{qkkkkk1 <;?\"^.',ii                         OZmLcj/^",
  "                                            I;I-}<,'`:<I~              ,^`^.I!![Lkkbbbu ll?^^.`:<>                         v00Unt|",
  "                                            >:,Il,`.',i_`              '\"``'`>i-z0QCJUu :!?^^.^;~^                        ;d*8dJv\\",
  "                                            !;^`^^`'.\"ll              ' \"^``.i>-\\ft//\\| .~-^^.^I_.                        >mqqLvjt",
  "                                            ^l\"`^\"`'.`;<               ..^``.!<-]~+I\"\"\"  >-^`'\"l?                         !JUXut(|",
  "                                             !:^`(vuj1l~               ^ ^^`.,~-i        i?^`',!-                          trt|{):",
  "                                             .l\"ca&oOYr~`               \" ^`''+_<        \"-^``:>>                           -}[]\"",
  "                                              I_wbodCcx)!               ^ ^^''<_]        ^~^``:<l",
  "                                               ?LQ00Jcxj~                , ^`'I~?        .I\"`^;+^",
  "                                               IuLQOLXnj]                \" .^'\"l_         ;\"`^I-",
  "                                                _CQ0QUvr-                 ; ``^I+^        I,^\"!]",
  "                                                 xL00Ccx\\                 \"  ^^;~^        \",^,i~",
  "                                                 !LQOLXuj                  l `^;<:        ^:\",;,",
  "                                                  cL00Uvr!                 \"` ^:>>       ^,:::,,\",\"",
  "                                                  _LQOCcx1                 .! `:i>      III!!l;:\"\":l\"",
  "                                                   zL0QYuj                :;i\" `i_:\"   !ll>-?+!;,\",Ii:",
  "                                                   _LQ0Jvr:             \"!li+i  '<\":; ;il!~?]+!:\"^\";!_",
  "                                                    CQOLzx?             >l!!;^^\":;I!1J]ilIliil;\"^^\":l~`",
  "                                                    [UXvYcvI           :>llI1}]ux[YJZa?iI:::::,\"^^^,I>!",
  "                                                    [paqLvrr`          l>Il,l;\"Ufi)/nn{iI:,,:::,\"^^,;i-",
  "                                                    1QXLCr(|;          '>lI^        .Ii<l;:,:::,\"^^\":!+^",
  "                                                     /rxxt)-           '<l;:`      `,! !iI:,,::,\"^^^,I<I",
  "                                                      l/\\{?:            ~!;:;;:,^`^:!_  <l;,,:::,\"^^,;i+",
  "                                                        I;\"             +!;:;;:,^`^,l_\" !!I:,:::,\"^^\":!+",
  "                                                                        IiI:;;;,^`^,l_\" '>l:,,::,\"^^^,l<,",
  "                                                                        IiI:;;;,\"^^,l+^  >!;:,:::,\"^^,;><",
  "                                                                        '>I;;;;,\"^^,l+^  ^>I:,,::,\"^^\":!_",
  "                                                                        '<l;;;;,\"^^,l+^   ~!;,,:::\"^^^,l~`",
  "                                                                         <l;:;;,\"^^,I~^   ,iI:,:::,\"^^,I>!",
  "                                                                         ~!;:;;:\"^^,I~^    <l;,,::,\"^^\";i~",
  "                                                                         !!;:;;:\"^^\"I~^    ,iI:,:::,^^^:l+",
  "                                                                         IiI:;;:\"^`\"I<`     <l:,,::,\"^^,I<I",
  "                                                                         ^iI:;;:\"^`\"I<`     !!;:,::,\"^^\";i>",
  "                                                                         '>I;;;:,^`\";<`      >I:,:::,\"^^:l+",
  "                                                                          <l;;;;,^`\";<:      >!;,,::,\"^^,I<`",
  "                                                                          ~l;;;;,^`\";>>      ^>I:,:::\"^^\";il",
  "                                                                          >!;:;;,^`^;>>       il;,,::,\"^^:!_",
  "                                                                          I!;:;;,\"`^:>i       ^iI:,::,,,\",I~`",
  "                                                                          :iI:;;,\"^^:>i        <l;IIIlI:,\";>;",
  "                                                                          '>I:;:,\"\"\":ii        ,iil!+]+l,\":l~",
  "                                                                           <lI;II:,,I>!         ~>l!+-<;\"^,I+.",
  "                                                                           ~il<?+l,\";>i         I>IIll;\"^`\"I+^",
  "                                                                           ~!!~_<;\"^:i!         ^iIIlI:\"^`,l_",
  "                                                                           il>~i;\"``,!!         IiIIlI:\"`^,!]",
  "                                                                          il!<<I\"^`^:<:         IiIIlI,^`^:ii",
  "                                                                         ^il><!:^``,!l          IiIIlI,^`^;<l",
  "                                                                         !li~>;\"``\"I<           I!IIl;,^`\";~^",
  "                                                                        ,!!<<l,^`^:<`           ;!IIl;\"^`\"I_",
  "                                                                        >li~i:^``,i;            !!IIl;\"^`,!_",
  "                                                                       \"!!<>;\"``\"l~             +lIIl:\"`^:ii",
  "                                                                       il><l,^`^;+              ~lIlI:\"`^:>:",
  "                                                                      l!i~i:^``,>,              ~I\"^^'.'^;~\"",
  "                                                                      ;^\"\":\"``\"ll               I`'`'.  `;-",
  "                                                                     ''`'  '\"\";<               `^\"!+i\". ',<",
  "                                                                   `^,~_I' .\"i<               ':\";-}+,. .\"!\"",
  "                                                                  .:\"I-?l' .^!!               ,:^^;I,'  .\"ll",
  "                                                                  ;\":ii:'   ^!i               I,^^\"\"`   .\"!!",
  "                                                                 :\"\"l>I`   .\"i,               l,`^,\"'   .\"!!",
  "                                                                \",\";>!\".   `;<               .I\"`^,\"'   .,ii",
  "                                                                :\":ii:'   .\"i,               \";^`\",^'   ',ii",
  "                                                               ;\",l>I^    `Ii                ,:^`\",^.   ',>>",
  "                                                              ;,\"I>!\".   ',>                 !,^`\",^.   ':>,",
  "                                                             `:\":ii:'    ^l>                 l,`^\"\"`.   `:<`",
  "                                                             !,^;iI^    ':~                  I\"`^,\"`    `:<`",
  "                                                             ,\"`'`'.   .\";^                 `,,''``.    `;:....",
  "                                                           .\";?<ii,,\"\",;!lllII\".^          ;\"<}<ii;,,\"\",li!!!!!\" `,",
  "                                                           \"\"\"-----------------!I`         :^:~----------------+ 'i",
  "                                                           \"\".i--------------ii:!QCCCCCCCCx;` ,--------------<il `<",
  "                                                            ^.                 '           ^`                    ^.",
  "",
  "",
  "",
  "",
];
