/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `sneer` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                        !!",
  "                                                                     n  ?J",
  "                                                                     m? ?a",
  "                                                                 ?n  Ja`J8! n",
  "                                                             `!   mJ ?8nJo|!8  J`",
  "                                                              nm! !8J!8oaQmm8 Ja",
  "                                                               ?8m!noa8|8\\8q8J8|",
  "                                                                ?8qa8ro(J?b]8Qo!n`",
  "                                                               !`!qXqp~X+'{Iv/88n",
  "                                                               !mam8/]-. ^[cpJtkJ`",
  "                                                                 |w0j_]JmJ?!  :\\8a",
  "                                                               n8888mJ?`   `<{jxd8m|",
  "                                                                 ?8-   'l]\\xYwW$%/:*!",
  "                                                                  8U:!1tu0bhM$$BOq,Z?",
  "                                                                  a*+XOaqc)a$B0tjajfJ",
  "                                                                 !@$$$$aw[vo$$$@czo[a",
  "                                                                 !Bhp$$$d}~1B$$bucdX8",
  "                                                                  |0+$$$B{(frfxucXCWo? jQ'",
  "                                                                   Jpkahn/tYYzvzYJCp8(pdWb_",
  "                                                                    mf1rJnxcLLYJLQLbkoOQ&8Wc",
  "                                                                    1ufnCLm@$$$WO00WkCqM&&8&p'",
  "                                                                   +o0JCZmd$$@#dZZaMmaW&8%@@8Q",
  "                                                                  'ohhkpbpwvvcOObWkp8&%B@Bar'  |J%BBBqCC]]i",
  "                                                                  (q@@B&M88Wao*WpYuUW%@BZ)   -h8888%%%BBBBBBBCCu]]`",
  "                                                                     ]\\L@@@bru)1|jncZ8kr?Uf]cM&MakaW&&888%%%%%%BBBBBBCCu]]`",
  "                                                           !nJBBCC!   !??nwBx\\(1(fuzJ**oo*k&*WMhmOp*####MMMWW&&888%%%%%BBBBBBCCu]]!",
  "                                                         'Z88&%%BB%aJBM##oahZttjxzJLLMbk&#da*WWobdaMMM############MMWW&&8888888%%BBm-",
  "                                                        'dW##8%%%%888&MhWahM&QUJQOOLhWhLa#YQ*W88&&8%%%888&&WWWMMM##########M&#haW%B%#+",
  "                                                        LMWB$#&&#*oahhZpMpno8hC0LXcroWdxLMQp*W%BBB@@@@@@BBBBBB%%%888&&&WWMoMMdZp#%@%Wk:",
  "                                                       1#W#o$MOrb#|/p01z*Qzp8a0ZZ]JW$MM&%Mk&oW%B@$$$$$$$$@@@@@@@@@@@BBBBBWoW&#o#8B@BWh)",
  "                                                      '*WMabW$0UkBbkM8#oaWW8%oq0(z}d$WWW%Mh%&M8@$$$$$$$$$$$$$$$$$$$$$$$@@BaW&WW8B@@BWk?",
  "                                                      LMWobk*$8W8B%%%%%%hMW&%*n,Ip1Y$8WW%Mh%%88B$$$$$$$$$$$$$$$$$$$$$$$$$$aW&WW8B@@%Md",
  "                                                     1#W#kbo&@$M&%B%%%%%*#W&%#zi<pxj$BWW%Mh%%%@@@@@$$$$$$$$$$$$$$$$$$$$$$$aW&&&8%B@8*L",
  "                                                    '*WMabaM%@$BW8B%%%%%MoWW%MC-]Jut$@WW%Mh%%B@@B&oL      i[[[[[[[cQQQQQQQhW8n;>{vM&oj",
  "                                                    LMMobk#8B@$$M&%B%%%%%kWW%Wq1)CLjo$MM%Mh%%B@@BWaj                      h&z!:<)jX8k>",
  "                                                   _#W*kk*&B@$@$$W8B%%%%%o#W8&d\\/cQnk$#W%Mb8%B@@%Wk]                      m&u??)jvY8d",
  "                                                  'pWMhbaWB@$$B8$&&%B%%%%W*W8&brjXwvm$8W8Mm8%B@@%Mb>                      v&u??(jc0&L",
  "                                                  cMMabhM%@$$B8*&$W8B%%%%8hW&8hcnupXL$%W8Mm8%@@@8#p                       t&u?](rcmM|",
  "                                                 _#W*kk#8@@$@8#O.&%&%B%%%BaM&8aYczpCL$@W8Wm8%@@@8*w                       .&u?]|xzhq",
  "                                                'pW#hb*&B@$@%Mb: t$W8B%%%B**W%oCYUO00&$M8Wm8%@@B&oz                        8u-]\\nX*?",
  "                                                cMMabaWB@$@%Wk<   b@&%B%%B&aW8*qaaoo*B$#&Ww8%@@BWhj                        8u-[/nX8",
  "                                               _#WobhM%@$$BWh[    >$&8B%%%@hM8#u^^^\"\"n$88Ww8B@@%Mk?                        8n-}/uC8",
  "                                              'pW#kk#8@$$B&or      0$&%B%%@o#&#Y;;;::~$8WWw8B@@%#d>                        8]-}tvZJ",
  "                                              cMM#ho&B@$@8*n       ^$88B%%BWo&#Z~~~~~~$BMWw8B@@8*q                         8]-{fcbn",
  "                                             lM8%%BB8B$@%#0         z$&%B%B@kW#Z~~~~~~p$*Mq8%@B&ow                         8]-1jch?",
  "                                            'b&#a#8B%M8%MZ.         .$%8B%%@*M*O?~~~~~0$hMq8%@B&ar                         8}[(xXW!",
  "                                            CM#pZh&BBWh#k:           v$&%B%@M**m(~~+++u$##q8%@BWhf                         mU1/uwa",
  "                                            aW&##&B@B&ad<            .$B8B%B%hopj)(|\\/n$Woq%%@%Mb>                        !*l^+\\Ya",
  "                                            wW8%88B@@8*x              r$8%BB@aapJXJOZmw$@kp%%@%#d:                        ?w??(xz8",
  "                                            {*&%%8%B@%MO              .@@8BB@*hp0JJ|???b$hp%%@8*q                         ?htjuYZa",
  "                                             wW%%88%%%Wk               j$%%B@&kpr      z$oq%%B&oL                          aZYLqW?",
  "                                             +*&80>i{U#o<              .8$8BBBbpz      }$8p%%BWaj                          `m88a?",
  "                                              CWb+!_|xmWx               j$%%BBhpw      ^$8k8%%Wk)",
  "                                              I##(11\\xX80               .&$8BB#kq       $@#8%%Mb>",
  "                                               C&C)1|juoO                t$@%B8#d       0$M8%8#p",
  "                                               'Mh(1)tnpY                .M$%B%#b>      z$#&%8*w",
  "                                                lhn)1\\rJa                 t$$%%Mk>      }$8&%&oz",
  "                                                 ?h(1(fuM`                .#$%%Mh]      ^$%W8&M0?`",
  "                                                  an11/nk|                 t%$%Whj      '%&WWW&&8&Ol",
  "                                                  |h)1|rQm                 )o$BWaXl    'p##*o*M&&8W#t",
  "                                                   an1)fu8               _dMo8$BodWz' .w**hpqdoW&8&Ma\\",
  "                                                   |O)1/xk?             t*#oba$$@h8WduLa**kqwdoW88&Mod",
  "                                                    8t1(rmJ            Ih***M%8&WM#*M8ko##*aa*W&%%8W*k<",
  "                                                    npfnfX#?           /a#*M0Zwuvmfc8-qo#WWWWW&8%%8&#hx",
  "                                                    |b>?(xUM!          na##&*M8tXaQ0%Owa#W&&WWW&8%%&Mop",
  "                                                    nqf||zLh?          ~h##8$$$$$$$$$$%h*MW&WWW&8%%8W*b<",
  "                                                    `aYvvUQc           ~h*M&B$$$$$$B&o[Uo#W&&WW&88%8&#h|",
  "                                                      ?UJOq?            k*MWMMW&%%%W*d Ih*M&&WWW&8%%&MaQ",
  "                                                       ;nu[             boMWMMW&8%%&*di JoMW&&WW&8%%8W*b.",
  "                                                                        uoMWMMW&8%%&*d> ~a#W&&WW&88%8&#k[",
  "                                                                        na#WMMW&8%%&*b>  ZoMW&WWW&8%%&MaX",
  "                                                                        ~a#WWMM&8%%&#b>  }a#W&&WW&8%%8Wod",
  "                                                                        ~h#MWMM&8%%&#b>   k*M&&WW&&8%8&#k<",
  "                                                                        .k*MWMM&8%%&#b>   /a#W&&WW&8%%&Mar",
  "                                                                         k*MWMMW8%%&#k<   .h*M&&WW&8%%8Wo0",
  "                                                                         UoMWMMW8%%8#k<    /oMW&WWW&8%8W*b:",
  "                                                                         noMWMMW8%%8Mk<    ;h#W&&WW&8%%&#h|",
  "                                                                         }a#WMMW8%%8Mh<     JoMW&WW&8%%8MoY",
  "                                                                         ~h#WMMW&%%8Mh<     Ia#W&&WW&8%8W*b",
  "                                                                         .h#WWMW&%%8Mh]      Z*M&&WW&8%%&#h<",
  "                                                                          k*MWMM&8%8Mhj      }a#W&WW&8%%8Max",
  "                                                                          Z*MWMM&8%8Maj       m*W&&WW&8%8W*d",
  "                                                                          uoMWMM&8%8Waj       }oMW&WW&&&8&#k<",
  "                                                                          /oMWMM&8%%War       .h*M#M#*#W&&Ma|",
  "                                                                          ~a#WMW&888War        /oa*odwb#&8W*0",
  "                                                                          ;h*#M##W&&#ar        .ka*obphM8%&#b:",
  "                                                                           ka*kqb#&8War         na#M#*M8%%8#b>",
  "                                                                           k**kdhM8%Wox         }a#M##W8%%&#d",
  "                                                                          Ia*akoW8%%&or         na#M##W8%%&*w",
  "                                                                          m*okh#&%B%Wh]         no####&8%%Wor",
  "                                                                         {o*hk*W%BB&*x          uo###M&%%8Wh(",
  "                                                                         w*okaM8%B8#O.          uoM##M&%%8Mk>",
  "                                                                        to*hh#&%B%Wk<           uoM##M&%%8#d",
  "                                                                       .a*akoW%B%&o|            J*M##M8%%&*Q",
  "                                                                       t*okhM8%B8#0             b*M##W8%%&or",
  "                                                                      Ia*ak*&%B%Mb.             k*M##W8%%Wh]",
  "                                                                      C*okaW8B%&a]              k#8%%B@B8Mk>",
  "                                                                     lM%88W8%B8*x               #BBBB@$$BMp",
  "                                                                    nBBB@$$B88MO               Y88obo8@$@&h",
  "                                                                   Y8&kd#B$@8oh;              1W8MpZb&@$@8*}",
  "                                                                  )&8#pq#B$$8*r               cW%8M#&@$$@8*x",
  "                                                                 lM8&oaWB$$$8*r               q&%%&8B$$$@8*x",
  "                                                                'd88*a#%$$$$8a]              .*&%%&8B$$$@8or",
  "                                                                X&8Ma*8@$$$BMO               +#8%%&8B$$$@&or",
  "                                                               -W8WoaWB$$$@8a]               fM8%8&8@$$$@&aj",
  "                                                              'M8&*a#%$$$$%#U                cW%%8&%@$$$B&aj",
  "                                                              d&8Ma*&@$$$@&h;                o&%%8&%@$$$BWh]",
  "                                                             jW8WoaWB$$$$%#X                I*&%%&&%@$$$BWh<",
  "                                                             *&8Mo#%$$$$BWk.                _#8%%&8B$$$$BWh<",
  "                                                            |&8BBBB@$$$@8MaLLLL]           -a&&BBBB@$$$$%MW@@@$$L|",
  "                                                           )8Mqkaa&&&8&M***###8@X         'W8hZhaaM&&88&#oooo**8$%c",
  "                                                           z88pppppppppppppppppoM<        _W%Wbppppppppppppppppd$Bo",
  "                                                           z8@appppppppppppppooW*`        -WB$&ppppppppppppppho#$Bh",
  "                                                           \"h@$$$$$$$$$$$$$$$$$o}..........J%$$$$$$$$$$$$$$$$$$$$h+",
  "                                                            ;zk$$&mmmmmU\\\\\\\\\\\\^^^\"\"\"\"\"^^^^^^zM$$$$$$$$$$ZZZZZZ)1{",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"]\\\\]^^````'''..",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^^`````'''...",
  "                                                                           .................",
];
