/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `stomp_l` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                  i",
  "                                                                                          -   )   p   \\i",
  "                                                                                          _z  YI ib  [Z",
  "                                                                                           o+ k| p0 ^B-",
  "                                                                                           Qw &L'$Y`&0",
  "                                                                                         - /Mr8qO@cbM( tr",
  "                                                                                         ]m)Md#k#Mp$JibJ",
  "                                                                                       l{ 0hhM**&k%kO$L`^fvi",
  "                                                                                        faQho8MW8aBb$CUk#|",
  "                                                                                        lQMB@$$$B&**dM%U!",
  "                                                                                        X%$$$$$$$$$$$$dcJ\\",
  "                                                                                       lMB$$$$$@@@@BBpcx~",
  "                                                                                       xM@oOLCCJJUYYXXcj;",
  "                                                                                      v$p\"\"+{///\\\\\\\\-!_kZl",
  "                                                                                      z$w!^  \"/dO[;   ,*Q[",
  "                                                                                      1@avU?  ?mx;',!J$&X;",
  "                                                                                      +Bor    UwQ>   -$*u",
  "                                                                                       8oYn]|J0Yjv{>+u$d[",
  "                                                                                      `qqQU/fJYcr\\jt\\v$O:",
  "                                                                                     I_QOvr)|c){~[\\()v$Y'l",
  "                                                                                   .i1({v|{-|<    i{1f0)};!",
  "                                                                                  `,li:,;_~-/)    i))/\\|_^:!",
  "                                                                                    ```^\",~)1{/x(1))/1<:,,^;I",
  "                                                                         `^^``'`'      ^```//}}{}[{(l:,\"^^``I'",
  "                                                                       \"\":l\"``''^:       ``nmqLvrt/),`'....",
  "                                                                     ',,II i,````````i;:,,,ZmqwLcr/)'..",
  "                                                                    \",;>]{ !;\",:,,,\"\"iIli!:Q00QYnf\\[\"`''    `^^^``'`^",
  "                                                                  ^,:!-{{? :Qz!-Y)l]|_I<i^\"{vnrt(1(i!!I:~;::,:II,^`'`^^",
  "                                                                 ,,I+}{]~I ^>!^l}_:|n{<mul,-\\1}[}\\>ll:`;+;I:I~]?>:`'''```",
  "                                                               \",;>]{}+l,` 'I,^\",^^^^~I>i`;[[]JXv}!lzL~!n>I:l_}?i,^^``''``\"",
  "                                                             .,,!-{{-i:^'.  l,^\",\"^^^<Il\"^!]\\Jpr+ l!]-;}fi;,:I!l,\"\"\"^^``'''`^",
  "                                                            \",I~}{]>;^'.    l,\"\",\"^^`<Il^\"<d&Q}C! I!,`;_;>;\"^`^```^\"\"\"^^``'''`^`",
  "                                                          ^,:>]{[~I\"'..     ,:\"\",\"^^\">Il`,-M*f\\L; I!^^i>^iI\"`'...''`^^\"\"\"^``'''`^`",
  "                                                         ,,!-{}_l,`..    '\" ,:\"\",\"^^I>I;`;/hd(uU .Il`,_:^:l,`.  ...''``^\"\"\"^^``''`^'",
  "                                                       \",I~}{?i:`'.    '^;` .;\"\",\"^^;iI;^!uwO-un ^lI`I-^^`^:`.    ....''`^^\"\"^^``''``^",
  "                                                     .,:>]{]<;^'.    '^;`    ;\"^,,^`;iI,\"<XQz-z1 \"l,^>i^^'..``'..    ...''``^\"\"\"^``'''``",
  "                                                    `^^,<]+I\"'.    .^;`      I\"^\",^`:!I,,-JUr)u- ;!^,-\"^`. .`;>^`'..    ...''`^^\"\"^^`'''`\"",
  "                                                  \"\"::^``:;`.    .^:`        ;,^\",^`I!I^;)Xc))rI Il`I_\"^'. '\"!_    `..    ...''`^^\"\"^^^````'.",
  "                                                 ;:i]-I`'\"!:   .^:;          \",^\",\"'>lI^!tvn}|t^ II^>>^`. .^;+       .'..    ...''`^,:,;I:^'`:,",
  "                                                `l:!+>:''^l_ .^:;            ',\"\",\"'il;\"<jrj-|| .I,:?:^'. ',i~          ''..   ...'\"l:!][<,''\"!;",
  "                                                ,l,\":,`..^l-`::              .:\"\",^.!l:,-0Yvt)] ^l^l~,`. .^I_.             ''.    .ll:I~~l^''\"l?",
  "                                                .l,\":,`..\"!+:                 :\"\",^.!I,;t#*ohb/ ,I\"<i,'..`:>I                 `..  lI,,::^'.'\"l?",
  "                                                '!,\":~_..\"i>                  ;\"\",^.lI,iX##MMMY ;::-;^. '\"l-                     '.ll,,::^'.',i~",
  "                                                 i:rbbmCfI>`                  ^\"\",^.+I:-Lkkhao? l\"l+;'..`:<l                       !l,,_}?+.':<!",
  "                                                 >rbW8pJct<^                 .^\"^\"^.+;l{kkkkkk_ l:~i,. '\"!+                        .l_ZhhwLX~;+.",
  "                                                 IumpqLcrt+                    ,^\"`.~;+tkkkkkk `l:?;^ .`;~:                        .lOh8&pCcx~?",
  "                                                 ;uZwmJvjt-                    ,^\"`.<l[vkkkkkk ,l!_;' ',!<                         .1mqbqLcxt|i",
  "                                                 `uZwmJujt>                  ` ,\"\"'.><?zOZmwqn ll+l: .^;+                          '1mwpZJuj/[:",
  "                                                  nZwmJuff                   . \"\"\"';>?]jrnucz( i!_;^ ',i~                           )mwpZUuf/{.",
  "                                                  )ZwmJuf{                   ' `\"\"';<-~+~~?(|: ~><; .^I_                            ]mwpOYnttl",
  "                                                  >ZwmJuf?                    `.\"\".;?<:        ~_I,.`:>I                            <mwpOXxt|",
  "                                                  >ZwmJuf?                    \" \"\".;+_.       .<-:`'\"l-                             <mwq0Xx/?",
  "                                                  >ZwmJut]                    I \"^'I~]        `~<:.`:<:                             <mqqQzr/i",
  "                                                  >ZwmJnt+                    , ,^'iii        ,_,\"'\"!+                              <mqqLcj/;",
  "                                                   ZwmJnt:                    ; `^`:<:        :i,'`;~:                              <mqqLvj/",
  "                                                   ZmmJnt:                    I '^^I_.        I,,',i<                               <mqwCuft",
  "                                                  .0ZOUnfi                    .' ^\"l]         I,^^I+                                <mqwJnt?",
  "                                                  xdpOUnn\\                    `\"'^,ii        .;,^,i~                                xqwZnnf]",
  "                                                  nUU0v\\)t                 '::::,\"\";:        .;,^I_                                ]pbw0zuuj`",
  "                                                  ^fuvt1{,                lIIllI:,\",;I       ,:\":>I                                1QXLLr||/;",
  "                                                   `f/1]l               .il!<--<I:\"\",;I    . ::\"l-:.                                jucn|}1-",
  "                                                    `I;\"                i!li_[]~l,\"\"\",;l^'lIl: \"<i,;l                                {f\\}]I",
  "                                                                       '<!Ili<>l:,\"\"\"\",:I;`'^   !^\":l>                                ;II",
  "                                                                       '<!;::::,,,,,\"\"\"\":I!<!lI:\".::I>\"",
  "                                                                        <l;,\"^\"\",,,,,\"\"\"\",;l]qr!I.\">:l~",
  "                                                                        \"!:\"^^^^\"\",,,,\"\"\"\",:l?!.  ,>,;iI",
  "                                                                         \";,\"^^^^\"\",,,,,\"\"\",:I:   I,\",I<",
  "                                                                           ::\"^^^^^\",,,,,\"\"\"\",;I^\"\"^^\":!!",
  "                                                                            ^:,\"^^^^\"\",,,,\"\"\"\",;l;,\"^^,I>\"",
  "                                                                              ::\"^^^^^\",,,,,\"\"\",:Il\"\"^\":l>",
  "                                                                               ';,\"^^^^\"\",,,,\"\"\"\":Il,^^\";i:",
  "                                                                                 ::\"^^^^\"\",,,,,\"\"\",;l,^^,I<",
  "                                                                                  `;,\"^^^^\",,,,,\"\"\",:l:^\":!!",
  "                                                                                    \":\"^^^^\"\",,,,\"\"\"\":II^,I>'",
  "                                                                                     .;,\"^^^^\",,,,,\"\"\",;I,:l>",
  "                                                                                       \":\"^^^^\"\",,,,\"\"\",;l;;i:",
  "                                                                                        .;,\"^^^^\",,,,,,,,,;II~",
  "                                                                                          ^:\"^^^^\",::;I;:,\":l!I",
  "                                                                                            ,,\"^\":;;!<_+!:\",I>>",
  "                                                                                             ^::;l>+?[]_!,^\";>~<",
  "                                                                                            ^;I!~-]]-~iI,^`\";>_i\"",
  "                                                                                         .:;l<_][?+iI:\"^^`'^;<>Ii",
  "                                                                                       ^;Ii+?[?+>l:\"^^`''..^I~::!:",
  "                                                                                  ....  ^>]]_<l;,^^`''.. .',i;,\":>",
  "                                                                               .'`,I;^. .\"i!;,\"^`''.. .'`\":i~>;\",Il",
  "                                                                           ..'`,l~]}?I' .^I!^`''.. .'`,;!!!_]~;\"\";>",
  "                                                                        ..'^:!+]}}]+!\".  ^I_'....'^`.  :>l!>iI\"^^:>>",
  "                                                                     `''^;i+]{}]+!:^'    `I_..`^'      ,!li>l,^`^:<:",
  "                                                                    :^,i_[{}]+i;^'       ^l+\"'         <l!>i;\"``\"l+",
  "                                                                   :,\"I?{]+i;^'.  ,il   .,!           ^ili>l,^`^:~",
  "                                                                   l,^\"l!;\"'. ';i----\"  ^,            il!>i;\"``,!!",
  "                                                                   !,`'.'. ^;<-----i` `,              ili>l,^`^;+",
  "                                                                   ,,\". ^l+-----<:   .               l!!>i:^``,iI",
  "                                                                  ,,+[]------<:   .                  >li>l,^`\"I~",
  "                                                                 ,,^I-----+I'   .                   \"!!>i:^``:<^",
  "                                                                 ^,' l--l`   .                      >li>l,^`\"l<",
  "                                                                  ,'       .                       `,^ ``^`^;+",
  "                                                                   .    .                         .``\"`. .\";iI",
  "                                                                                                 ^\",+]i^  ^!~",
  "                                                                                                 ;\":~+l'  `Il",
  "                                                                                                ;\"\"I!:'   `Il",
  "                                                                                               `:\":!I^    ^!I",
  "                                                                                               I\"\"I!:'   ':+",
  "                                                                                              :,\";!I^    ^l!",
  "                                                                                              ;\",ll,'   ':<",
  "                                                                                             ;\"\";!I^    ^l>",
  "                                                                                            `:\",ll,'   ',>`",
  "                                                                                            !,^:!;`    `I~",
  "                                                                                            :\"`'`'.   .,I^",
  "                                                                                          .\"I?<ii,,\"\",;!lllII\"'^",
  "                                                                                          :\"\"-----------------!I`",
  "                                                               `]]]]]]]CCCCCCCCCCCCCCCCCCC}\".i--------------ii:!",
  "                                                                                           ^.                 '",
  "",
  "",
  "",
  "",
];
