/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `stomp_r` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                    `|  !!",
  "                                                                            !   ?n  ?J  a?",
  "                                                                            |J  ?a  JJ |8",
  "                                                                             aJ ?8| 8m`8J",
  "                                                                             |8J`8a?p8ma|`a`",
  "                                                                             `8p|8p8x8Lonan `?",
  "                                                                           !a!nXo8}8<a[88a`na`",
  "                                                                            ?8ao<*,LI[rCqa8a`",
  "                                                                          nJ?mQX+> ;:^})wza!?",
  "                                                                           |8aCamJJJCQOzt88a?",
  "                                                                           `8v        ???{dn",
  "                                                                           n8[ ;llllI\"^^:{d8`",
  "                                                                          nm%\\xxxxxxnnnnnnb8?",
  "                                                                          8 Q$$$@*QOmqaB$$$Ca`",
  "                                                                          8;xkXw$$8<Z$$$$$Qlk!",
  "                                                                          J{CM%$$8|-nB$*pk](a",
  "                                                                          ncLm&$%J])t@$$$B}Cn",
  "                                                                         'rL/(uU1)|uJnQwZa)*`",
  "                                                                        _q&bj\\X0ufjcLUUCLoQ&+",
  "                                                                       _oZakzY0wvb*WWQL0Qa88*+",
  "                                                                      ca0qWM0mdZQ$$$$$wOOWW88*+",
  "                                                                     zkpkW&&*ohCCmho%aLpWWW&88*+",
  "                                                                    luoBB%88&8%WkmC0mOk8&&8%BBBM-",
  "                                                             `]]]]i    ?JBBB%%UfLb8MMho&%B@@@wn!",
  "                                                           ?m%%%%BBa(     ?wBBn[??)jcUOB@BJ|'   |w%%BBBJ?",
  "                                                         |a8&#&%%BB%8mCCqW&&&&f[?](rcUO8&UUUf](k88&&8%BB8bl",
  "                                                       |a8&#a$o&88888888a#*hhMX\\/txzJCZooo#o*&M&Mhdh#8BB%8&r",
  "                                                    `n88W*bmO$WMhW******k*MM&%aXXULOOCo**&8kooMWawOqo&BBBB%8k-",
  "                                                  `n88WapZOmd%$Y)O8)fpw?c*X[m%oC0ZYJrbMkt0&0JoMW#hbaW8%BBBBB%&Y'",
  "                                                !m88MhqOOwb*WB$oo&%#*M8ako*p#8aOwL(vw8MhCZMCZoW888&8%%%%%BBBB%8k)",
  "                                              !m8&#kwOZqh#&%B@$8M8%88%%%#aMM%8hQv-|n&$M#&%#bMoW8BB@@BB%%%%%BBBB%&O'",
  "                                            |m8&*dmOmdoW8B@@$$$$#8%%88%%&aMM%8k<,tU1h$M#8%oa%oM8B@@@@BB%%%%%BBBBB8W(",
  "                                          |a8WapZOwk*&%B@$$$$$$$M&%%88%%%hMM%&dliXJ(a@M#%8ho%8M8B@@@@@@BB%%%%%BBBB%8bl",
  "                                       `na8MhwOZpaM8B@@$$$$$$$B$8W8%88%%%kMM%Wq+-UC/o@M#%&d%%%B%8%B@@@@@@BB%%%%%BBBB%&r",
  "                                     `n8&#kmOmdoW%B@$$$$$$$@%hrQ$M8%88%%BbMM%Ww}{CLjo@M#%Wp%%B@$B88%B@@@@@@BB%%%%BBBB%8k-",
  "                                   !m%%BBWdwk#8B@@$$$$$$@%&Yl  ^$M&%%88%B*MM%MQ|\\LUn*@M#%#b%%B@$B&oq8%B@@@@@@BB%%%%BBBB%&Y'",
  "                                  zWMao&BB&*%B@$$$$$$$B8O-      b%W%%88%Bo#M%#CtfQYv#@MW%oh%%@@@%Mk?'x8%B@@@@@@B%%%%%BBBB8k)",
  "                                 I#WhZpMBB8**$$$$$$@%Z('        t$W8%88%Bo#M%#Jrn0JXM@MW8ha%B@$@8*q   'x8%B@@@@@BB%%%%%BBB%8Z'",
  "                                 u#&W*M%@@8*o$$$@%hrl           ^$W8%%88Ba*M%*UucOLJW@MW&d#%B@$BWh(     'x8%B@@@@@BB%%88%%%BB%x'",
  "                                 {#&8&8B@@8*a$B&Yl               b%&%%88BW*M%oUXY0QQ&@M8Ww&%@$@%#d:       'x8BB@@@@@B&M&#a#8BB8p.",
  "                                 ~o&8&&%@@8*kZ-                  t$W8%88BWoM8aphpqpw8@M&Mb&B@$B&oL          'x8B@@@@BoW#qObWBB8#O",
  "                                  aW888%%B%*r                    ^$W8%88BWaM8k?<||\\Q$@M&*b&B@@%Wk]            'x8B@@&*WWoa#8@@%Mb:",
  "                                  JM80[<\\m8*r                     b%&%%8B&aM&p<I;:::$@M&aa&@$@8*q               'x8BWoW8&&8B@@%Mbi",
  "                                  /Mb<;~|xpMj                     t$&%%8B@hWMm~~~<<>$BM&b#8@$B&aj                 'x&aW88&8B@@%#d",
  "                                  ~#w}[1fvOMj                     ^$88%8B@kW*O~~~~~~$B#WqW%$@%Mb:                   'hM88&8%%B%#p",
  "                                   o8{[1fuOM(                      M@8%%%@bMhC~~~~~~$%*MkWB$B8oL                     v#8ox!-xd8#w",
  "                                   c8\\[{tuO#:                      J$&%%%@a#qz~~~~~~$%o*pW@@BWh(                     {#8[::-\\xkMz",
  "                                   'mv[{/uOJ                       -$88%%@o*qY11{{{}$%aaoW$@8#p                      ~*8}?]|rcZWr",
  "                                    JU[}/nOJ                        @@8%%@oaqQzzcccv$@kb*8$B&ac                       a8}[[|rcZMj",
  "                                    ?w}}\\nOJ                        m$&%%@abpJJJJJJJ$@bq&%@%Mb>                       w8|[[(rcZM]",
  "                                    ?k}[|xOJ                        {$%%%@Mqb>      $@hd&B@8*w                        IWv[[(rcZZ",
  "                                     8}[|x0J                        IB@8%@Mdb>      $@kd&@BWh(                         Jv[[(jvdJ",
  "                                     aj[(x0J                         b$8%B#bd>      $@oo&@%#d:                         |w}[)jvhJ",
  "                                     Jv[)r0J                         u$%%B#kp       $@a*%B&oz                          ?w}])jvh?",
  "                                     n01\\nOm                         +B@%B8*q       $@#8%%Mk?                          !8}]1jvh?",
  "                                     JO<1rzM?                        .M$8B&ow       $@M8B8*q                            8}]1fvh?",
  "                                     8{\\\\uUma                         C$%%&oz       $@M8%Whj                            aj]1fvh?",
  "                                     axftzQdn                         /@$%&ar       $@M8%Md:                            Jv[1fch?",
  "                                     `xvvJOz                          IW$8Whj       $BW8&#k                             mY}1jxqJ",
  "                                       YZp0:                        )OWh$BWhc'     )&WWW&&8&U?                         ?b_]jvcvo?",
  "                                        ++                        'p##*h@$8ka*+  'p##***M&&888&x!                      ?kft(vC0W?",
  "                                                                  w**kaa@$$&M&#|?w**apqboW&&&888&hx`                    JZunY0dJ",
  "                                                                 }a**WhoMMMWWW&%*a**kqwdoMWWW&&&888&Z('                  >JLZq?",
  "                                                                 na#*#Zdp(cdjv8tZa##*aa*MMMMMWWW&&&888&U?                 ;/u;",
  "                                                                 /a#*%B@&Lw8Jw8xpo#WWWW&&&WWMMMMWW&&&&888&x!",
  "                                                                 .h#M8$$$$$$$$@%hoM&88%%%88&&WWMMMMWW&&&&888hx!",
  "                                                                  UoMW8%%%BB@$$@&hM&%BBB%%%%88&&WWMMMMWW&&&888&Z|'",
  "                                                                  Ih#W&&WW&8%%&#hnd&%B@BBBBB%%%888&WWWMMMWW&&&888&Z?",
  "                                                                   JoM&&WW&8%%8MoY'x%B@@@@@BBBB%%%888&&WWMMMWW&&&888&U!",
  "                                                                   Ia#W&&WW&8%8W*b.  ?noB@@@@@BBBB%%%%88&&WWMMMWW&&&888hx!",
  "                                                                    J*M&&WW&8%%&#h[     `]JBB@@@@@BBB%%%%88&&WWMMMWWWWW&&8m(",
  "                                                                    ~a#W&&WW&8%8WoY         !nwB@@@@@BBBB%%%88&&WWM###**M&8&p+",
  "                                                                     Z*M&&WW&8%%&*b.            ?JoB@@@@BBBB%%%88&##*bwpoW8&Mh.",
  "                                                                     }a#W&WW&8%%&Mh[               !\\wB@@@@@BBB%&##adwqk#&%8Ma|",
  "                                                                      m*W&&WW&8%8WoY                   ?uoB@@@@W#*hqwpaM8%%%War",
  "                                                                      }oMW&WW&8%%&*b.                     `|C%M#obwwk*W8%BB%Wh]",
  "                                                                       m*W&&WW88%8Mh[                       _d#apmpaM&%BB@B8#n",
  "                                                                       {oM&&WW&8%8WoY                      j#*kwwb*W8%B@@%&*t",
  "                                                                       .h#W&WW&8%%&#b.                   'Q#odwqhM&%BB@B8MLI",
  "                                                                        /oM&&WW&8%8Mh[                  _d#hqwd*W8%B@B%Wp{",
  "                                                                        .h#W&WW&8%8WoY               ]C@$$$8*hM&%BB@B8#f.",
  "                                                                         /oM&&WW8%%&#b             !mB%&8B$$@&W%B@B%WLI",
  "                                                                         .h#W&WW&8%8Mh[          `n%%WhwdW@$@8*8@B&p{",
  "                                                                          t*W&WWW&&8WoY         |a%8*pZmk&@$$%#h8Mc.",
  "                                                                          ;a#M##o*W&&Mb       !m%%MkmZd*8@$$$%#pqI",
  "                                                                           Joo*kwd#&8Wa[    `n%%&oqZwhWB$$$$$8*X",
  "                                                                           Ih**hkoW8%&ox   |a%8#dZZd*8@$$$$$@&h;",
  "                                                                           Io*ahoW8%%&or  Y8%WhwOwhWB$$$$$$@8d+",
  "                                                                           m*ohaM8%B%Wk; )W8WbZZd#8@$$$$$%M@@#.",
  "                                                                          {o*ah*&%B%&or  p&%WhdaWB$$$$8#bpp%$M~",
  "                                                                          m*ohaM8%B8#0   o&%B%8%@$$&oppppph$@*;",
  "                                                                         {o*ah*&%B%Wk;   #W%@$$@MhppppphW$$$a_",
  "                                                                         w*ohoW8B%&o|   k%*bk*hpppppb#B$$$C!",
  "                                                                        {o*hh#8%B8#0   1&8hwppppppoB$$$*\\`",
  "                                                                        w*ohoW%B%Wk;   f&BBkpppo8$$$$w!",
  "                                                                       {o*haM8%B&o|    IWB$$88$$$$*n`",
  "                                                                       d%88%8%B8#0      -%$$$$$@w?",
  "                                                                     ?oB%B@$$%8Wk:       `/Q0Q\\`",
  "                                                                    _&8opk8$$BMa|",
  "                                                                   'b8&hqh8$$BWb",
  "                                                                   X&8Mo#%$$$BWb",
  "                                                                  _W8Woo&@$$$BM0",
  "                                                                 'b8&*oMB$$$@8a]",
  "                                                                 Q&8Mo*8@$$$BMO",
  "                                                                )W8WooWB$$$@&a]",
  "                                                               'M88#a#%$$$$%#0",
  "                                                               0&8Mo*&@$$$@&a]",
  "                                                              I#88#oMB$$$$%#0",
  "                                                              U&8BBBB$$$$@&MhLLLv!",
  "                                                             X8oqaaa&&&8&#***##M8Bj",
  "                                                             #%#ppppppppppppppppp#o",
  "                                                             d%Bbpppppppppppppboo%w",
  "                                                             ]8$$$$$$$$$$$$$$$$$$w;...........",
  "                                                            ..IXW$$hmmmmmU\\\\\\\\\\]\"\"\"\"\"^^^^^^^^^^````''''...",
  "                                                         ...'''````^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^^^^````'''..",
  "                                                             ...'''`````^^^^^^^^^^^^^^^^^^^^^^`````'''...",
  "                                                                          ..................",
];
