/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `stomp_l` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                  i",
  "                                                                                          ?   (   b   /<",
  "                                                                                          -U  J! ia  [q",
  "                                                                                          .M- ot dq ^$[",
  "                                                                                           Ob Bm`$0`8w",
  "                                                                                         ? f8vBkw$Ck8f fn",
  "                                                                                         }p\\8h&*W8h$O<k0",
  "                                                                                       l) m**8WW%o@*q$m^^fz<",
  "                                                                                        x#Z#M@8%B#$a$ZLhWf",
  "                                                                                        lZ8$$$$$$%WMh&@0<",
  "                                                                                        U@$$$$$$$$$$$$hJCt",
  "                                                                                       l&$$$$$$$$$$$$hCY?",
  "                                                                                       n&$MqZZOO00QQQLCzl",
  "                                                                                      v$d\":]\\uuunnnn{<?hqi",
  "                                                                                      Y$d>^  ,thq{I   ,Mw)",
  "                                                                                      )$#JL]  [dvI`;>O$BLl",
  "                                                                                      _$Mz    Lbw~   ?$WU",
  "                                                                                       BMQX)f0q0cJ|+]Y$a(",
  "                                                                                      IkhwOucO0JznzvnJ$ql",
  "                                                                                     -\\qqJzjnC\\|]\\nxrJ$0;?",
  "                                                                                   ,}xujJxf|n_    _frcqrj?[",
  "                                                                                  I_[{-_?(1|uf.   ~rxvcv\\+-?",
  "                                                                           ....     i~~~+_)rjfuYrjrrvx1-__+]_",
  "                                                                        \">~~~<<~l     :+~~~uuttft/fx]-_++~<~[,",
  "                                                                       ~_-[_~<<<~?^..`' :>~UdkmJzvvx_~<>>>>I;`",
  "                                                                     l__]+ {_~~~~~~<<{?-___pdkbmCzvx<>i;^     ..;`.",
  "                                                                   \"~_?1fx [?+_--___+{][{[-wwwmQYcut_iII:`  i~~~~<<<<\"",
  "                                                                  >_-}/rxt ~wC[|0r[/n|]1}~+jJYXvrjx{}}]-(]--_-]]-+<<<~<\"",
  "                                                                \"__](jxf(]^I{}+]f|?nYj1bU[-tnjt/tu{[[-~?|?]-](ft1-~<<<<~<:",
  "                                                               ~_?1fxj|}_~^,]_+__+~~+(]{}~]jttZQU|[[Lm){U1]-[\\jt1-+~~<<<<~+:",
  "                                                             :_-}/rr/{-~<>: [_+__+~~~)][+~}fumhX] [}/|?jz1]_-]}[-++++~~<<<<~+:",
  "                                                           '~_](jxt1?+<>>iI }-++_+~~~1?[~+(*@Z}Z> ]}_~]\\]1]_~~~~<~+++++~~<<<<~+i",
  "                                                          >_-1fxj(]+<>>iii> >-++__~~_1?[~-t%&rtZI`]}++{1~{]_~<>>><<~~+++++~~<<<~+i",
  "                                                        \"__}/xr\\}_~>>iii><_'<?++__~~]{]?~]c#a|z0 \"][~_\\-~?[_~>i>>>>><<~+++++~~<<<<~i\"",
  "                                                       ~_](jx/{-~>>iii><+]l \"?++__+~?{]?~}Cbp-XX l[]~]/~~~+?~>>iii>>>><<~~++++~~<<<<~<\"",
  "                                                     :_-1fxf)?~<>iiii<+]l   `?_+__+~?}]_+(0mU-C\\ >[_+1{~~<>>~~<>>>ii>>>>><<~+++++~<<<<~<\"",
  "                                                   ^>~+_)f|]+<>iiii<+]l      ]_+__+~-}]_-tO0v|U} -[~-/_~~>>>~]1<~<>>iii>>>><<~~++++~~<<<~+:",
  "                                                  +_--+<<-?<>>iii<+?l        -_+__+<][]+]nLC|\\z! ][~[\\+~<>><_{|  'I~<>>iii>>>><<~+++++~~~~<<I",
  "                                                 --{f/]~<_}-iii>+?_.         >_+__+<1[]~}zUY{jv,`]]+)1+~>>>+]|`     ^!<>>>ii>>>><<~+--_?]-~<~-<",
  "                                                I[-}|)-<>+[/i>+?_.           ;-++_+<{[?+(XXz-xx \"]_-t-~<>><-11         ^><>>>ii>>>>_[-}tj)_<<_}<",
  "                                                >[__-_~>>+}/~?_.             \"-++_+>}]--twQUvr| ![+[|-<>>>+[\\^            ,><>>ii>>[[-[(([+<<_}t",
  "                                                \"}__-_~>>+}\\_.                -++_+>}]_]X&WM*aj >]+){_<>>~-)+                I~<>>i[[__?-+<><_}f",
  "                                                ,}-_-)(>>_{[                  ?++_+>[]_1O&&88&J ---/?+>><_}t                   ';~>}[__?-~<><_{1",
  "                                                 {-zaodZc]);                  i_+_+>|]-two**#M] [_}|?<>>~?(+                      ^[[__|t\\)><-)_",
  "                                                 1Xo%@hOJc(I                 ^i_+_~>(?}xoooooo? [-(1->><_}(                        \"[(p**bmL)]\\^",
  "                                                 -JdhkmJzc|                   ^_+_<>)?\\Xoooooo :[?t?+>>~]|i                        \"[p*@@hZCY(f",
  "                                                 ~JpbdOUzc/                  `'_+_<>)[jLoooooo ![}\\?>><_{{                         \"rbkokmCXcu?",
  "                                                 IJpbdOUzc{                  : -++<>1)fQqpdbkc -[|[->>+]\\`                         ,rdbhdOUzvfi",
  "                                                  XpbdOUcz`                  \" +++<?1tfcXYUJLt ]}\\?+><-11                          'xdbhp0Ucvx^",
  "                                                  \\pbdOUc/                   , !++<?)t1[[[)xxl (1(?>>+[/                            )dbhpQYcc-",
  "                                                  ~pbbOUc1                   ':,++>]t(i        )\\]_>~?)+                            ~dbhqQXvx",
  "                                                  ~pbbOUc)                    l^_+>]\\\\^       \")/-~<_}t                             ~dbhqLXv)",
  "                                                  ~pbbOUc)                    _ _+<[(f        ;)(->~?(i                             ~dkkwCzv~",
  "                                                  ~pbbOYc[                    > _+<{1]        >\\__<_}(                              ~dkkmJzv!",
  "                                                  .pbbOYvl                    + l+~?(i        +{_<~]|i                              ~dkkZJcc",
  "                                                   pbbOYvl                    +`;++[\\^        ]-_<-{{                               ~dkkZUcz",
  "                                                  'qpp0Yz+                    \",^+_}f         ]_++]\\`                               ~dkbOYv1",
  "                                                  uahp0YYn                    I>;+-1]        ,?_~-11                                vkbpYYc(",
  "                                                  z00pJnxc                 ;---__++]~        \"?_+[/                                }hokqLUUz\"",
  "                                                  \"uUJvjjI               ^[??[[]-_+_??       >-+?)+                                |wQmmXxnv!",
  "                                                   \"cuj\\+               \"{][)\\\\1]_++-??^   , +-_}t_,                                cUCUntr1",
  "                                                    ,+~I                }}[{|ft)]_+++_?[!:]?]?i_(1_?]                                \\cntt>",
  "                                                                       ,)}]]{11[-__+++_-]?~>+iii{++-}{                                >~~'",
  "                                                                       ,)[?----_____+++_-]})}[]?_>--]1l",
  "                                                                        )[?_++++_____++++_?}tkX{]>_1-[(",
  "                                                                        i}?_~~~++______+++_?[\\[>>i-)_?{_",
  "                                                                         >?_++~~~++_____+++_-]-ili[_+-[)'",
  "                                                                          `_-_+~~~++_____++++-?[+_++~+?}]",
  "                                                                            i?_++~~~++_____+++_?[?_+~+_]1l",
  "                                                                              _-_+~~~++_____+++_-[[_+~+-[{",
  "                                                                               I?_++~~++_____++++-][_+~_?{>",
  "                                                                                 _-_+~~~++_____+++_?[-~+-[(`",
  "                                                                                  I?_++~~++_____+++_?[-~+?}]",
  "                                                                                    <-_+~~~++____+++_-]]~_]1,",
  "                                                                                     ,?_++~~++_____+++_?[_-[{",
  "                                                                                       ~-_+~~~++____+++_?[??{<",
  "                                                                                        ,]-++~~++_________?][(",
  "                                                                                          i-_+~~~+_---??-_+-[}_",
  "                                                                                           `_-+++_-?[1\\([-+_[1)'",
  "                                                                                             !--?]{|tft|[_+_])|1",
  "                                                                                           \">-?})/ff/(}]_+~+?1\\1l",
  "                                                                                         ;-?[1\\tf/({]-++~<<+?)1[}",
  "                                                                                      `i-]{|tft|1[-_+~<<<>>+[|--}>",
  "                                                                                .:>>>>ii+1ft\\1[-_+~<<<>>>><-{?_+-1'",
  "                                                                             `I><~_]]+>i>_1[?_+~<<<>>>><~_?{({?+_]?",
  "                                                                          \"!><~-}(frt]<i>+[}~<<<>>>><~-]}}[|t(?++?1`",
  "                                                                      .:>><+-}|frrf|{_>i>+[/<>>>><+i;  ~1[}1{?_~~-1]",
  "                                                                     <<<+?{\\fxrf|{?+<ii!i+[/>>~+l\"     i}[{1[_~<~?)i",
  "                                                                    -+_{\\jxrf|{?+<>i!!!!>+}|_l`        1[}1{?+~~_[(",
  "                                                                   +-+[txf|{?+<>ii<+~!l!>-}.          I}[{1[_~<+?(`",
  "                                                                   }-+_[{]+<>ii<+---->!i++            [[[1}-+~~_{?",
  "                                                                   }-~<<<>i><_-----+i!~+             .{[{1]_~<+]\\",
  "                                                                  '-__>i>~_-----+<l!ii\"              -[[1}-+~~-1+",
  "                                                                  -_\\t1------+<!l!>;                '{[{1]_~<+[)",
  "                                                                 <_+]-----_~il!ii^                  i[[1}-+<~-);",
  "                                                                 !-<i~--~ill!<;                     1[{1]_~<_}{",
  "                                                                  +<i!!ll!ii^                      l_~i~~~<~?|",
  "                                                                   !illl<I                        I~~+~>i>_?{+",
  "                                                                                                 i_-|f1~i>+})",
  "                                                                                                ^?+?(\\[<ii+[-",
  "                                                                                                -__]}?<i!i+[-",
  "                                                                                               l-+?}[+>!!>_{~",
  "                                                                                               ]__[}-<i!i<?|",
  "                                                                                              +-+?}]+>!!>+}?",
  "                                                                                             ^?+_[}-<i!i<?(`",
  "                                                                                             -_+]}]~>!!>+}}",
  "                                                                                            l-+-}}-<i!i<-):",
  "                                                                                            }_+?}]~>!!i+[)",
  "                                                                                           \"?_~<~<>i!i<-[~:::,.",
  "                                                                                          :_]/?++<<>><+?--___<<i",
  "                                                                                          ++_-----------------+[:",
  "                                                               `]]\\CCCCCBBBBBBBBBBBBBBBBBBv+>+--------------++~{",
  "                                                                                           ~>!llllllllllllllll<\"",
  "                                                                                            ,:ll;\"\"\"\"\"`",
  "",
  "",
  "",
];
