/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `stomp_l` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                  !",
  "                                                                                          ?`  |   a   |?",
  "                                                                                          ?m  J? !8  ?a",
  "                                                                                          `8| aJ m8 `8n",
  "                                                                                           m8`88`o8`a8`",
  "                                                                                         ?`npm8paY8mqm |J",
  "                                                                                         |anq08x8(8cd?ma`",
  "                                                                                       !| ao8<p+J/J{8a8!`|J?",
  "                                                                                        J8apx-;:l)`0jOmm8J`",
  "                                                                                        !aqC}??]}(//C8La|",
  "                                                                                        Jw]?????]]]]]JaaJn`",
  "                                                                                       !8v    ....'''-J8n",
  "                                                                                       n8{!{(|\\\\//tffjJ8?",
  "                                                                                      nJX$8oahhhhaW8B$$ww?",
  "                                                                                      J}]$%$$&J_{mM$$$&lYJ",
  "                                                                                      |C>8/q$$q[cM@&*0J,k?",
  "                                                                                      ?w}W$$$$/])a$$$$m+8",
  "                                                                                       8}nuwL\\1tXnOhbp8nJ",
  "                                                                                      j&Y(/UY/txzJzUCq8p?",
  "                                                                                    lpdkQnz0Cr0OkmJL0q88rq.",
  "                                                                                   )oOQ*mCOpLh$$$$aO0d8*ZMw.",
  "                                                                                  j&*oW&MdkpJQ$$$$o0pMQCd8WJ",
  "                                                                          i]]]]    !m%B%8&M#wOJcQ0Qp8mhW&&8Mn",
  "                                                                        |a%%%BB%Ul   !n%B%%0k8oad*MoWW&88%B%#~",
  "                                                                      !k&W#8%BBB%W|]]-?!naBu[?tzCLU0&%B@@$@qC-",
  "                                                                    'Y&&#M$o&%%%%BBBBoMW&&&}[?]|rcUQB@*C\\!   `]]C\\]`",
  "                                                                   (h&MhwO$*W8&W&&&88o#*a*&))1(fuYJm&ZUUx- !m%%%%BBBa|",
  "                                                                 'Z&WopOOq$W)r*pfQ*wLd#ho%8OnucYL0Laoo#WkMWW&W#M&%BBB%a|",
  "                                                                (&&#bmOwk#$%ao8#ZpWLvZh[u*&pC0ZmZJa**W%WbM#W#kwqa&%BBBB%ax'",
  "                                                              !k&WhwOZd*&B$B#&88&8%%%k#ao%Mmmw/fxm**j(kovaMW*dmqa&%%BBBBB%8n`",
  "                                                            'x&&*pOZpoW%@@$$#&88&8%%%kM*8%*wJ\\-cb$#*wpMZXaM&W#o#&8888%%BBBB%8n`",
  "                                                           ?h&#bZOwhM%B@$$$$*&88&8%%%hM*%8h_,)Z|*$#o&%MdMaM&%%%BB%%8888%%BBBBB%m!",
  "                                                         'Z&WawOmk#8B@$$$$$$&W88&8%%8hM*%&p;!XJ|W$#o8%oa%aM8B@@@@@BB%8888%%BBBBB%m!",
  "                                                        (&&*pOZd*&B@$$$$$B8$&W88&8%%#aMM%MU<_Lnt$@#*%&dW%W#&B@$$@@@@BB%%8888%BBBBB%m(",
  "                                                      !k&MbZOqoW%@@$$$$@8Mjd@W88&&%%Mo#M%*n]{pnv$8##%Mp%%%8W%@$$$$$@@@@BB%8888%%BBBB%a|",
  "                                                    'x&WawOwhM%@@$$$$@%Mj' t$M88&&%%Wo#&8hf)rpr0$&*&%ao%%B@@%%B@$$$$$$@@@BB%%888%%BBBB%a|",
  "                                                   |a%%&kwb#8B@$$$$@%Wj'   }$M88&&%BWo#&&p\\tc0up$M*%&p8%B@$@%WaZB@@$$$$$@@@@B%%8888%BBBB%8x'",
  "                                                 'k8WW8BBWWB@$$$$@%Wj'      $W&88&8B#*#%MQjr0Qc#$#*%#d8%B@$B&oL  ?JB@@$$$$$@@@BB%8888%%%%%BBJ!",
  "                                                .pWowp#%B8*W$$$@%WLI        $8&88&8Ba*#%*UnuZCY8$#M8ha8B@$@%Mb:    `|wB@@$$$$@@@@B%%&W&M#W%B%Wc",
  "                                                {#W*bh&B@8#d$@%WLI          0B&88&8@o*M8hzczpCL$@#&WqW%@@$B&az        `|oB@$$$$$@@@8*W*wmh&BB&*\\",
  "                                                /#&8W&B@@%*p%WQI            z@W88&8@o#W&qhqm0Qw$8#8#b&B@$@%#d:           !no@@$$$$@*#W#kb#%@@8*q",
  "                                                +*&8W&B@@8*bQI              }$W88&8@*#&MYI\\n0p&$&#8ho&@$$B&a|               !JB@@$$*#&&WW%B@@8*q",
  "                                                ~o&8W&%@@8oj                >$W88&8@*#&aflI;;;f$MWWpM%@$@8#p                   ?JB@*#&&WW%@@@&oc",
  "                                                 aW8oUXk%&a<                 $%88&8@b#Wp(~~<>iq$#8*bWB$@BWh(                     `|w#&&W&%B@BWh)",
  "                                                 h&Z:\"-\\C8k>                 @%88&%$bM*O~~~~~~p$#Wka&@$@8*Q                        +*&8YtnJ#%Mb:",
  "                                                 C&u-?|xz8b                  p$&88B$kMbY~~~~~~$B#WqM%$@%Mk]                        +*8?\",-\\rMMq",
  "                                                 v&u][\\nX8p                  J$&88B@h#mx~~~~~~$&#*dM@$B&oX                         +#w?+?(rcdMr",
  "                                                 {Wu][\\nX8X                  Y$&88B@hhqj1}[]?u$*#b#W$@%Mb:                         +#w]-}/nXao]",
  "                                                  kv][\\nX8;                  +$&88BMaqwCcvnxjL$o*dM%$B&az                          ;#w]-}tuX*h:",
  "                                                  nw][\\nOm                   ~$%88BMkpcJJJm*aB$kakM$@%#d.                           Xw]-{tuY8x",
  "                                                  ?w][\\nOJ                   ;B@88@Mqk]      0$kd#&$BWa|                            ?w]-1fvQa",
  "                                                  ?w][\\uOJ                    8$88@Mbd:      $@kpWB@8*p                             ?w]?1jcZJ",
  "                                                  ?w][\\uZJ                    #$88@#kw       $BkkW@BWh]                             ?w??)rzh|",
  "                                                  ?k][/uhn                    0$&8Boar      }$&d&8@8*Q                              ?w??(xza?",
  "                                                  `8[[/uh?                    u$B8%Wk]      }$Wo&B%Mk]                              ?w??|xX8`",
  "                                                   8[[/uh?                    u$@%%#d:      z$#&&B&oz                               ?w?]\\nJ8",
  "                                                  `8j{tvW|                    +B$%8*w       0$M&%%Mb:                               ?w?]\\uZJ",
  "                                                  Jc-{tuJa                   !j8@8&ar       &@M&%&az                                JL]{vudJ",
  "                                                  mJ/1nJQ8                'rWWWW&&8Mv       $@W&8#d                                |b~]1jnz8!",
  "                                                  !YnnY0w?               _*M#**#W&8&Mp'    >$&W8Wh(                                nqf||cLLW?",
  "                                                   \"YU0w)               +o**kpph#&88&Mp_  lw$WW8*pb)                               `acruCZkJ",
  "                                                    <nu}                mo*admwk#&888&W*f1*#*W$8ka&Mq.                              `rYJZw)",
  "                                                                       ~k*##aha*W&&888&W#M%@%$$$o88W*Z                               .|uu;",
  "                                                                       ~h*MWWWW&&&&&888&WM*h*#MW8@WW#a}",
  "                                                                       .k*M&8888&&&&&8888&M*w?co#@8aW*k.",
  "                                                                        t*W8%%%88&&&&&&888&W#qo$$$&h&Mon",
  "                                                                         zM&8%%%%88&&&&&888&W#W$$$#&8&#h;",
  "                                                                          -bW88%%%88&&&&&8888&M#%888%8WoU",
  "                                                                           'XW&8%%%%88&&&&&888&W*M&8%8&Ma}",
  "                                                                             lbW88%%%88&&&&&888&W#*&8%8W*Z.",
  "                                                                               rW&8%%%888&&&&8888WM*&8%&Mo/",
  "                                                                                lbW88%%%88&&&&&888&M#&%8&#k;",
  "                                                                                  rM&8%%%88&&&&&888&W*W%8WoU",
  "                                                                                   'OW88%%%88&&&&8888W##%&Ma~",
  "                                                                                     )M&8%%%88&&&&&888&M#&W*Z",
  "                                                                                      '0W88%%%88&&&&888&M#MMa\\",
  "                                                                                        )M&8%%%88&&&&&&&&&MM#k.",
  "                                                                                         'XW&8%%%8&WWMMMW&8W*on",
  "                                                                                           -b&8%8WWM*hdb*W8&#ah;",
  "                                                                                            'XWWM#abqmwd*&88MhbZ",
  "                                                                                           (OM#okpwwpko#&8%8Mada}",
  "                                                                                        !rWM*hpwwqba#W88%BB%Whh#m.",
  "                                                                                   i[[\\ZM#abqwqda#W&8%BB@@@%#bWWo/",
  "                                                                                ]C@@@$$$%awwdh*W&8%BB@@$$@B&aM&8Wa;",
  "                                                                            `\\q@@B&#M%@$@8a*M&8%BB@@$$@@%8WakaM&&#J",
  "                                                                         iu*@B%&*kwZq#B$$%#o%BB@@$$@B%&M*o*dwkM88Mh;",
  "                                                                      ]C@@B%WobwZZwbo8@$$%Md@@$$@B%mxl vh*ohaM8%%Waj",
  "                                                                    !aBB8WodwZZwboW%@$$$$%#d$@B8U('    to*ah#&%B%Wh]",
  "                                                                   lW%&odmZZwboW%@$$$$$$$%*b8U-        h*ohoW8%B8*0",
  "                                                                   Q&8#qOwboM8B$$$&o#$$$@&wI          {o*ah#&%B%Wk;",
  "                                                                  .*&%8#oM8B@$@Mopppp8$$%0'           m**hoW8%%&ox",
  "                                                                  .*&B@@@@$%MhpppppoB$B0!            Ia*ah#&%B%Md.",
  "                                                                  ?&&8$$%*bppppphW$$$*(              J**hoW8B%&a(",
  "                                                                 l&&dmwpppppphW$$$@C!               Ia*ah#&%B8#0",
  "                                                                 z&%#pppppb#B$$$*\\'                 t**hoW8B%Wh<",
  "                                                                 f&@$*pp#B$$$@C!                   .a*oh#&%B8*z",
  "                                                                 'kB$$$$$$$o\\'                     j&%$BB%B%Wb.",
  "                                                                  'w$$$$@J!                       UB%8%@$@8Wo|",
  "                                                                    `[[[                         X8&bwa%$$%*0",
  "                                                                                                _W8Wkd#B$$%#n",
  "                                                                                                d88#*WB$$$%#n",
  "                                                                                               jW8W*#%$$$$8o|",
  "                                                                                              'M88#*W@$$$BWb.",
  "                                                                                              Q&8W*#%$$$$%*x",
  "                                                                                             _W8&#*&@$$$@&k:",
  "                                                                                             d&8M*M%$$$$%#Y",
  "                                                                                            jW8&**&@$$$@&h<",
  "                                                                                            *&%W*M%$$$$%#O",
  "                                                                                           |W8BBBB@$$$@&#hLLLL]",
  "                                                                                          )8Mqkaa&&&8&M***###8@X",
  "                                                                                          Q8&pppppppppppppppppo#<",
  "                                                                                          X8@appppppppppppppooW*.",
  "                                                                            ..............Ia$$$$$$$$$$$$$$$$$$o?",
  "                                                                ...'''`````^^^^^^^^^\"\"\"\"\"^^!Xk$$&mmmmmU||((((",
  "                                                             ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^^^^```'''...",
  "                                                                ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                              .................",
];
