/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `strut_2` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                             !   J  `n",
  "                                                                                        |n  !m  |J  a?",
  "                                                                                         8? ?8! mJ J8",
  "                                                                                         J8`?8n!8J?8J",
  "                                                                                         ?8a|qanqmao??m",
  "                                                                                       ?| aXaLp8r8r8J8! !|",
  "                                                                                       `ammr0CnJ/uv8oJ|mJ`",
  "                                                                                     `n!!8po;r!<_\"Z\\8o8J",
  "                                                                                      ?88aQv}[  \"i,c(0m?!",
  "                                                                                       |8]]][JJJCw*Zk88J`",
  "                                                                                      `8w            j8`",
  "                                                                                      n8u`}11{{}}+~~1U8n",
  "                                                                                     Jq$@ohkkbp0000QQq8J",
  "                                                                                     J/0$$$hb(uq&$$$$a[Z|",
  "                                                                                     J[j@*$8m~Q$BooqbJ,q|",
  "                                                                                     |Cx$$$%!~]B$$@UOJ?8",
  "                                                                                     ?0tUqY]]\\nC&$8OhvJn",
  "                                                                                    )Mn1xCn(|vLnvzUCa)*`",
  "                                                                                  lQdJunUZzfrJmYYJLQaqm!.",
  "                                                                                 ja0LhJQwpQ@$*dQL0OQ#8M*n",
  "                                                                        ]]]]i   )Woo&&abk0Xph$$BZZOdWwCM*~",
  "                                                                     !m%%%%BB%U' 'x8%%8&8WOxxUJLmm#aZbM8&h.",
  "                                                                   'U&8WMW8%BB8M1  'x8%%%Qb*dkbhM8&*W&&8%WJ",
  "                                                                  (&8W*dwd*8BB%Wot]-??x8%(]{nCOOOZW8%%B@@@&/",
  "                                                                !h8&#kwOOp*8B@%&*d&bWW&&&[]-]\\nXJdB@$$@LC]]",
  "                                                              'U&&MhqOOwk*&B@@B&*doh#oo#b{{})fuYJkBwJ`",
  "                                                             (&8WopZOmb*W%B@$$B&*dQk#O&%WnrxuXCQCMMWW&hZ\\]no%%BBon'",
  "                                                           !Z8&*bm0ZdoW%B@@$$$B&owOhU1L%#QCQOZZOoo*#8#aBBBBBBBBBB%M_",
  "                                                         'x&&MkwOZpaM8B@@$$$$$BMho***a&8h0wQxv\\k#dCo8k*88%%%BBB%*W8Wz",
  "                                                        (h&WaqOOqhM8B@@$$$$$@B&*#%a**M%Wqbc-fv@%*wrLMf(dMOp&8%&obBB%Wp'",
  "                                                      !Z8WopZOwk#8B@@$$$$$@B8M#&%%o#*&%#x^Ip/q$&o*%8awdMbtY@J}0p8B@B%&d_",
  "                                                    'x&&#bmOmb*&%@@$$$$$@B8MMW&%%%b#*%8h]I|p(p$MoM%Wp%%%B@$@*qpo%%BBBB8M)",
  "                                                   (h&MhwOZd*&%@@$$$$$@B&##&8&&%%Bh#*%Wq>~cC/o$#a8%oa%%%@$$B&obB%%%BBBB8Wz'",
  "                                                 `Z8WaqOZpoW%B@$$$$$@%&dU%M88&&%%&a#M%#z?[Zvj$@*o%&p%%%B@$@%#d%BB%%%BBBB%&d'",
  "                                               `n%%BBWbpaW%B@$$$$$@%&d1 }$M&8&&%%Wo#W8hf)/pjJ$&*M%#k%%B@$@BWh*@@@B%%%%BBB%8M_",
  "                                              -&&MM&%B%MMB@$$$$$@%&d1   }$M&8&&8B#**8Wq\\/cZnp$Mo88bM%%@@$B8op%B@@@BB%%%BBBB8Wj",
  "                                             _#Wawqo8BBWa8$$$$@%W0_     ^$#&8&&8Bo**%#JfjQCc#$#o%Mp8%B@$@%#dtW8B@@@@B%%%%BBB%&0'",
  "                                             mMWodbM%@B&oa$$@%WQl        $8&8&&%@*#M8hcxupYY$@*M8h*%B@$$BWh| 'Y&%B@@@BB%%%BBB%&dl",
  "                                             hM88&&%B@B8*a@%WQI          $8&8&&%@b#W&qucUqUm$%*8Wq&%@@$@8*Q    -k8B@@@@B%%%BBBB8M-",
  "                                             u#&%88%B@@8*qWj'            b8&8&&B@k#&#qkZLCQa$W*%ob&B@$@%Mb:      r&%B@@@BB%%%BBB%Wz",
  "                                             IoW%%88%BB%#p'              0B&8&&B8a#8h}_tOd*@$#M&qM%@$$B&a|        lb8B@@@@B%%%BBB%&d'",
  "                                              CM8%onjvZ8Md               0$&8&&@WoWWw!lIIIl$@#&*dWB@$@8*0           (&%B@@@B%%%%BBB%h-",
  "                                              }*&dl`l}tL8b               L$&8&&@M*&au~~<>i_$8#&b*&@$@%Mb<            'O8B@@@B%W&WM8BB&z",
  "                                               h&u?_[\\xcMa>              Y$&8&8@o*Mw(~~~~~n$MW#dMB$$B&ar               -k%B@@*W*ww*%B%#/",
  "                                               tMO1{1\\rvho<              \\$W8&8$*#aO~~~~~~p$o&haW@$@8*0                 'Y8%&*W#kaWB@%Md",
  "                                               .*8){{|jvd*:              ]$W8&8$b#pz~~~~~~%%oMd#8$@%Mk<                   lkM#W#*WB@@%Mp",
  "                                                c&c1}(fu0O               +$&88B@kapr1{[?-{$&*ab#$$B&or                      LMW##8B@@8o|",
  "                                                 xq1}1tnCa               +$%88B&hpq0YuxrfC$**dM&$@8#p.                      wWWMW%@$BWd",
  "                                                 `8){{\\xc8               ~$%88@MkbX?JJaahB$kab#@@%Wk]                       o&p\\jch%8o|",
  "                                                  mc{{|rvM!              ~BB88@#db>      W$hd*W$B&oX                       +#bi\"<(roWb",
  "                                                  |q1}(fuk?              ~B$88@hhq       $BkdMB@%#d.                       {WC~_(rzaM|",
  "                                                  `8){1tnpn              .B$8%Baaj      }$8qoW@BWh]                        v&\\~?/uUWb",
  "                                                   Jc{{/x0J               M$8%%ob>      z$#pW%B8oX                         18_~{jzpW\\",
  "                                                   ?q1{|xCa               M$8B8*q       b$MaW@%#d:                         ?m+_(nY*L.",
  "                                                    8/[)rnaJ              #$8%&aj       $BW&8BWh(                          Jz~]/vOa",
  "                                                   ?b~_(ncvM!             a$&%Mb>      }$&W&B8*Q                           a\\~{rXa|",
  "                                                   ?ktt)nJ0W?          -YUMB%8#q       z$M&8%Mb:                          `*+_|nC8",
  "                                                    mmvuXLOJ         jMWMWW&&8&pl      b$M&%&a|                           |m~]tcbn",
  "                                                     ?vJ0qc        'L##*aa*M&8&Mo+     $@M&8*0                            Jr~{rYW`",
  "                                                      ./v}         uo*odwwk#&88W*k;  'n$&W8Mbwl                           8}_|umm",
  "                                                                  ;ko#obqdaM&88&#hU]j#MWMB%ak&Mf                         !8{)rX*!",
  "                                                                  ~h*##*o*M&8%%&Mam%B@B%$$$aW8W*c                       ?*1~txJ8",
  "                                                                  ~h*MM##MW8%%%&#hCxk*a#W&8BBW&W#c                      JC/|uJY8?",
  "                                                                  ~h*MM##M&8%%%&#kQYh*OJ?JoW@Mo8W#L.                    ?CtjY0qa",
  "                                                                  ~h*MM##M&8%%%&*bk%B8Bop#B$$Mh88W#w'                    {uz0w/`",
  "                                                                  ~h*MM##M&8%%8W*d0*@$$$$$$$@*W888&#q'                   iCpb(",
  "                                                                  ~h*MM##M&8%%8Wop,'pW&%BB$@&&&&888&Mq'",
  "                                                                  ~h*MM##M&8%%8Moq  'QM&88%88&&&&888&MqI",
  "                                                                  ~h*MM##W&8%%8MaC    jM&88%88&&&&888&Mo+",
  "                                                                  ~h*MM##W&%%%&#hj     _#W&8%88&&&&888&Mo+",
  "                                                                  }a#MM##W8%%%&#k(      'dW&8%88&&&&888&W*_",
  "                                                                  na#MM##W8%%%&*b>        zM&8%%88&&&888&W*_",
  "                                                                  na#MM##W8%%%W*d:         )MW88%88&&&&888W*t",
  "                                                                  na#M##MW8%%8Woq           ldW&8%88&&&&888W#v",
  "                                                                  na#M##MW8%%8WaL            'QW&8%88&&&&888W#c",
  "                                                                  na#M##M&8%%8Mhr              jM&8%88&&&&888&#c",
  "                                                                  na#M##M&8%%8Mhf               _dW88%88&&&888&#c.",
  "                                                                  na#M##M&8%%&#b<                'dW&8%88&&&888&Mq'",
  "                                                                  na#M##M&8%%&*d>                  zM&8%88&&&888&Wq'",
  "                                                                  na#M##M&%%%&*p                    _M&8%88&MMWW&&&p'",
  "                                                                  na#M##M&%%%Wow                     ldW88%***kk#&8Wq.",
  "                                                                  no#MMM&88%8War                      'XW&Wa*hqp*&8&*Y",
  "                                                                  uo#MWMW&8&WMhj                        jM*o##o#&8%&#p",
  "                                                                  ua**hkoW&&Mak<                         _Zo###M8%%&*L",
  "                                                                  ua*hqwhM88Wop>                          noM##M8%%&or",
  "                                                                  m**akaM&%%&*p                           uoM##W8%%Wh]",
  "                                                                 }a*oha#&%B%&*q                           u*M##W8%%Mk>",
  "                                                                 m**ah*W8%B%Wh(                           u*M##W8%8#p",
  "                                                                Ia*ohaM&%B%&*Q                            b*M##&%%8*X",
  "                                                                J**ah*W8BB8Mb:                            k*M#M&%%&or",
  "                                                               Ia*ohaM8%B%Wa|                             k#M#M&%%Wa<",
  "                                                               J**ah*&%B%&*0                              h###M8%%Wk:",
  "                                                              Ia*ohoM8%B8Mk:                              h###M8%8Md",
  "                                                              J**hh#&%B%&a|                              ;o8@@$$@8#X",
  "                                                             Ia*M#oW8%B8#0                               )%%WW%@$BMr",
  "                                                            `ZB@@$$@%%%Wk<                              lW8*mw#@$@&w",
  "                                                           -aB8W&B$$BWMor                               c&%Wa*8$$@&a<",
  "                                                          'M8WdZb&@$@&oO                                q&%8&%@$$@&a<",
  "                                                          0&8Mkdo%$$@8*x                                *8%8&%$$$@&h<",
  "                                                         )W8&*oM%$$$@8*x                               +#8%8&B$$$@&k>",
  "                                                        'M88Mo*8@$$$@&a(                               1M%%88B$$$BWk>",
  "                                                        0&8W*oWB$$$$BMb                                cW%%&8B$$$BWb",
  "                                                       )W8&#o#8@$$$@8o|                                o&%%&8@$$$BMb",
  "                                                      '#88Mo*&B$$$$%Mb.                               .*8%8&8@$$$BMd",
  "                                                      Q&8&*oM%$$$$@8o\\                                +#8%8&%@$$$%#p",
  "                                                     1W88#o*&@$$$$%Mb.                               -8W*BB%B$$$$%#q",
  "                                                     LW%8#*WB$$$$@8oX                                d8aqppa*&$$$8#w[",
  "                                                    x8W8BBBB$$$$$%WW@@@$#C!                          #%&pppppppbaM&@$$pvi",
  "                                                   )&Wqwaaa&&&8&Woooo**#B$&+                         z%$%ohppppppppphoWB@O.",
  "                                                   Q8%Mppppppppppppppppp*$8u                          n$$$$$$8Wohpppppppa&}",
  "                                                   z8@$appppppppppppppoo8$&t                           ^[[Q0W$$$$$B8#obpaW[",
  "                                                   lW@$$$$$$$$$$$$$$$$$$$@O:....................              ,{{00b$$$$@j",
  "                                                    \"q$$$$$$$$$$&ZZmmmU||-^^^^^^^^\"\"\"\"\"^^^^^^^^^^````''''...          {}",
  "                                                       1))I...'''````^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^^^^````'''..",
  "                                                               ...'''`````^^^^^^^^^^^^^^^^^^^^^^`````'''...",
  "                                                                            ..................",
];
