/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `strut_1` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                            !   !   m   ?!",
  "                                                                                            n|  a! !8  `8",
  "                                                                                            ?8` 8| m8 `an",
  "                                                                                             8m 8m!8m`a8`",
  "                                                                                           ! moJ88nqJJqJ !|",
  "                                                                                           mJnz*CO8|8Qo?na`",
  "                                                                                         !`!88L/CuurJt8a8! !n`",
  "                                                                                         `amaQo,(?;t\"kzpJnaa`",
  "                                                                                          ?8qC{[\" '\"<<Cm08n",
  "                                                                                          mv]]]nJJJJJCap8J??",
  "                                                                                         n8<           >ba|`",
  "                                                                                        `a8 >{{{1111111\\b8",
  "                                                                                       `m]QO*ohkkkkkkkkkM%!",
  "                                                                                       `a'YMo$$$WLuzCm*@$$8`",
  "                                                                                        8'mr>{m8$%{h$$*Bzua",
  "                                                                                        m)mnu$$$$}|f@$$$1Cn",
  "                                                                                        J)*zjm*Ln|fcZ8$$u*!",
  "                                                                                       _kQa\\)zQ\\tjuJYUC8Ym",
  "                                                                                     'zkqQZxnCZrnvXOQQQ8L|l.",
  "                                                                                    )oZCk8dUQwZc##MhmOL88boZ",
  "                                                                                   -k*a&&&WpdbLUd&$$$LZ8wC*M/",
  "                                                                          |JwBoC|`   (a%%8&&Mw0OQxuJULoMp*88o~",
  "                                                                        (&8&%%BBB&j    (a%%%q*Mobpkkb#8&&&&8&w.",
  "                                                                       YWWWB*%BBB%8wu]-??|a%u[/nzCpbpW&%%BB@@8c",
  "                                                                     'b&Wao$oW8%%%%%BBoMW&&&}[?]|xzJQ8@$$@pC\\]",
  "                                                                    -k&MkmZ$*um&WWW&&8k#*o#&{{}1/nXJbBoJ`    `]CCCC\\!",
  "                                                                   (WW*dZmb$ovLMY{Q#uvd#q*%&XjxuzCQJkMWW&*Z\\x8%%%%BB%k-",
  "                                                                 'Y&WaqZwhW$WM88#o*&ULbZ1z%MZJL0ZZ0doo#&Mb&W&&#o#&%BB%&O'",
  "                                                                'b&MkmZpo&B$WM88&&%%%#o#hM%oOmmjcfZ*aJd%ab*MWawZd*8BBB%8&(",
  "                                                               -W&*dZmk#8B@$@M88&&%%%Mo*#%&bdJ[/v@@#wjL*cz*WMaqwkM8%BBBB%8kl",
  "                                                              rWWoqZqaW%@@$$@M&8&&%%%a**M%MY`;Onc$B*o%%*qb*W&WM#W8%%%BBBBB%&Y'",
  "                                                            'Y&MhmZd*8B@$$$$@M&8&&8%%o#*&%o(;_p\\J$&o#%&d&o*W8%BBBB%%%%%BBBBB8&(",
  "                                                           'k&#dZwkM%@@$$$@@$#&8&&8%%h#*%8b+~t0\\d$*oW%#h%&oW%B@@@@BB%%%%%BBBB%8kl",
  "                                                          -WWoqZpo&B@$$$@%W&$#&8&&8%Bk#*%MC?[JUfW$#a%8k#%%#M8B@@@@@@B%%%%%%BBBB%&Y'",
  "                                                         X&Mhmmb#8B@$$$B8#v!$#&8&&8%%h#M%on1(pvx$B**%Md%%%@88BB@@@@@@@B%%%%%%BBBB8W(",
  "                                                       'O&#bZwhW%@$$$@%WqI  $&&8&&8%Ma#&8bt/npnZ$&oW8ao%%B@$B88BB@@@@@@BB%%%%%BBBB%8Zl",
  "                                                      lh88app*8B@$$$B8*t    $8&8&&8BWo*8W0fjU0ca$Mo%Wp8%B@$@%MhX8%B@@@@@@BB%%%%%BBBB%&x'",
  "                                                     r888%BB&&@$$$@%WLI     &8&8&&8Ba**%*XxnZCY8$##%oh8%@$$B&oz  |a%B@@@@@@BB%%%%%BBBB%h(",
  "                                                    zW#dd#%B8*&$$B&*{       0B&8&&8@*#M8bvvzpUC$@*&&p#%B@$@8#p.    (h%B@@@@@@BB%%%%%BBB%8Zl",
  "                                                   I*W*qd#%@%#k@%MC.        0@&8&&8@h#&WqkZ0CQp$&o%#b&B@$@%Wk]       (m%B@@@@@@BB%%%8%%%%BBU'",
  "                                                   +*&8&&%B@BWkMp+          z@W8&&%@k#&*f_/Ud#8$MM8ba8@$$B&oX          !m%B@@@@@@B%M&Mo*&%B8#+",
  "                                                   .oW%%8%B@B&an.           }$W8&&BBhM&p?lIIIlq$#&MpM%@$@%#d.            !Z%B@@@@@*MMbOq#%B%Wk.",
  "                                                    t#8%%8B@@8*|            }$W88&@WaW*L~~<>i!$@#8haW@$@BWh]               !U%B@@@aWWoho&B@BWh)",
  "                                                    .o&%%oOmk8MY            }$W88&@&oWpr~~~~~\\$WMWp#%@$B8oQ                  'n%BWoWWMM&B@@BWh)",
  "                                                     t#8d;\"+|C8b            ~$&88&$a**m}~~~~~Y$#WobM@$@%Md:                    'xM*WW#M8B@@%#p",
  "                                                     .a&u?-)juoo:           ~$%888$o#pQ~~~~~~p$aMp#8$$BWh|                       +*WWW&8B@@&oc",
  "                                                      {MO)1)tnm#<           ~$%888@kowz){[?-_$8o*b#B$@8*Q                        {#8O[>[X#%Wb>",
  "                                                       p8t11\\xJ&>           .B%88B@kpqZJvnrfx$Wob*W$@%Mb:                        uMbi\"!{fz8#L",
  "                                                       _&O){(juM`            B$88B%kqL?JJmahM$*oqMB$B&a|                         v&n__{tuY*o]",
  "                                                        !#(1)tnk|            %$88BMqb(      0$bkoM$@8*0                          v&n+-)rcL8p",
  "                                                         JC)1\\xQm            W$88@Mpd:      &@kbW%@%Mb<                          t8?+?|xXpM|",
  "                                                         !#)1(ju8            #$&8BbhL      ^$8kkM$B&ar                           l8-+[/uY*w.",
  "                                                          mz11tno?           #$&%B*h(      }$8kW8@8*0                            ?m_+{fcLa.",
  "                                                          !h)1|rZJ           a$&%%#d:      0$#bW@%Mk<                            |m__)rzpn",
  "                                                           an1)fJa           m$%%&oL       &$MM&B&oz                             Jn+?\\nY*!",
  "                                                           |h))fv8`          v$B%Wh(      ^$BW&B8#p.                             mx+[tv0a",
  "                                                            8n)(/La!        !C$B8#d:      }$8W8%Wk]                              8-+{jzbn",
  "                                                           `8-)/nYpJ     lYWWo@$&oL       z$#&8&oX                              `8__)xXW!",
  "                                                            8uj\\vCZn    c#M**h@$&hdt     !q%W&8&a.                              |w[}/v0a",
  "                                                            !ZzvXQO    vo*aaM#$$$koo\\  l0MWWWW&8&b)                            ?*}l-fzqJ",
  "                                                              \\0mpj   .h**Whk&8%B@B8W])*##oho#W&8W#C                           JX{/rXXU8",
  "                                                               I+I    ~h**MqpocukodW%&a**hqwdoM&8&Mou                          nmj|nCOqa",
  "                                                                      ~h**8@@@vUd|/8)ua**hpqb*W888W#a}                          jnxYOqa`",
  "                                                                      }a##&$$$$$$&&8nbo#M#**#W&8888W#h~                          XOqp[",
  "                                                                      na#M##8%$$$$$$Bho#W&&&&&&&888&W*m.                          ++.",
  "                                                                      na#M##M&8%%8M#LzoM&888&&&&88%8&M*J",
  "                                                                      na#M##M&8%%&#k< w#W&888&&&&88%8&Mou",
  "                                                                      uo#M##M&%%%&*d> 'q#W&888&&&&88%8&#a+",
  "                                                                      uo#M##M&%%%W*q   'q#W&888&&&&88%8W#h.",
  "                                                                      Uo#M##W8%%8WoL    'q#W&888&&&&8888W*m.",
  "                                                                      bo#M##W8%%8Mhj     'q#W&888&&&&888&Mou",
  "                                                                      b*M###W8%%8Mk]      'q#W&888&&&&8%8&Mo{",
  "                                                                      k*M###W8%%&#b>       'q#W&888&&&88%8&#a~",
  "                                                                      k*M##M&8%%&*p         'q#W&88&&&&88%8W#m.",
  "                                                                      k*M##M&8%%Wow          'qMW888&&&&8888W*J",
  "                                                                     ;h*M##M&%%%War           'qMW888&&&&888&Mou",
  "                                                                     ~h#M##M&%%8Mh(            'qM&888&&&&888&Ma+",
  "                                                                     ~h#M##W8%%8Mk>             'qM&888&&&&888&#h.",
  "                                                                     ~a#M##W8%%&#d               'pM&888&&&&8%8W#m.",
  "                                                                     ~a#M##W8%%&*q                'pM&888&&&88%8W*u",
  "                                                                     +a#M##W8%%Wor                 'oM&888&&&&&&&&*{",
  "                                                                     /a#M##&8%%Waj                  +oM&88W#M##W&8&*+",
  "                                                                     no#MWW&88&Mk<                   +oM&Wo*hppoW8&Mw.",
  "                                                                     ua#*aoM&&Mab:                    +*Mao*hqdo&88Wa|",
  "                                                                     uo*bmd#&8Waw                      +*k*##*#W8%%Wox",
  "                                                                    Io*hdk*&%%Woz                       _h*##*M&%%8Whj",
  "                                                                   'q*abk*&%B%&aj                       ~h##**M8%%8Mb>",
  "                                                                   c*obboW%BB%Mb.                       ~a##*#W8%%&*p",
  "                                                                  {**kbaW8BB%Wh<                        +a##*#W8%%&oz",
  "                                                                 Io*hdhM8%B%Wh~                         no##*#&%%%Wh(",
  "                                                                'q*adh#8%B%&a~                          uo##*M&%%8Mb:",
  "                                                                c*abk#&%B%&a~                           u*##*M8%%&*q",
  "                                                               {*obb*&%BB&or                            k*#**W8%%&or",
  "                                                              Io*kboW%BB8*x                             k*#*#W8%%Wh]",
  "                                                             ih%8&MW8BB8*n                             .hM8%%B@B8Mb",
  "                                                           'mBB%B$$B&%8#n                              +&BBB@$$@8*Q",
  "                                                          'k8Wdp#B$@&o#U                              'k%WhkMB$$%Mn",
  "                                                         'b8&aqdM@$@8o0.                              Q&8ommo%$$BWk.",
  "                                                         O8&oba&@$$$8o(                              '*&%&##8@$$BWh<",
  "                                                        Y88*bhW@$$$@&h;                              _M8%8&8@$$$BWk>",
  "                                                       X&8#kkMB$$$$%#n                               cW%%&&%@$$$BMb:",
  "                                                      X&8#kk#B$$$$BWZ.                               o&%%&&%$$$$%Md",
  "                                                     X&8Mkb*%$$$$@&a;                               I#8%8&&B$$$$%#p",
  "                                                    j&8Mhbo8@$$$@8o}                                1M8%8&8B$$$@8*Q",
  "                                                   '#8&abo&@$$$$%MMB@#(                             LW%%&&8@$$$@8ox",
  "                                                   +#8%&M&@$$$$%ohbdh*&}                            *&%%&&%@$$$@&or",
  "                                                   )W8@$$$$%8oappppppb&n                           +#8%8&&%@$$$BWaj",
  "                                                  -8Mda*obppppppppho8@M;                          'a&&BBBB@$$$$BWW@@@$$L|",
  "                                                  d8#ppppppppboWB$$$du'                          'b8aZbaa*&&&8&#oooo**&$Bz",
  "                                                  p%Bbppph#8$$$$dc[                              _W%&kppppppppppppppppp$@*:",
  "                                                  -8$$8B$$$$MQ[`                                 lMB$&ppppppppppppppho#$Ba",
  "                                                   ip$$$M0{,            .....................     U%$$$$$$$$$$$$$$$$$$$$a+",
  "                                                            ...'''`````^^^^^^^^^\"\"\"\"\"^^^^^^^^^`````fM$$$$$$$$$$OOOOOOf}[",
  "                                                         ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^^^^``?|(('..",
  "                                                            ...''''`````^^^^^^^^^^^^^^^^^^^^^^````''''...",
  "                                                                          .................",
];
