/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `strut_1` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                            l   I   L   [,",
  "                                                                                            f]  q` ip  ^b",
  "                                                                                            ~k  W~ pL `#-",
  "                                                                                             #n 8fl$f`&0",
  "                                                                                           ! Lh\\BCv8{OM[ >[",
  "                                                                                           Uj/WZBZ$aq$Yiz0",
  "                                                                                         l.:aqMh&p$w$dQ&0` >j",
  "                                                                                         .mJL#a&&h$#8p$LrXaY",
  "                                                                                          ia#%%B$$B8k&w8B0+",
  "                                                                                          O@$$$$$$@B%8&&Z/}<",
  "                                                                                         rW$$$$$$$$$$$$hxv~",
  "                                                                                        `b&$aOOOOO00000Jnr",
  "                                                                                       '&$b\\l<1ttttttttt\\Y:",
  "                                                                                       .8BQ1!   ~xJz|[!.  Y",
  "                                                                                        WBQ0hO[\" `O<  l_XXt",
  "                                                                                        O@LQn    ZLY'  ,b0+",
  "                                                                                        X@Jzz}l(uCXx}\" ,JX`",
  "                                                                                        f@JJQj)JYzn\\t/|%M|",
  "                                                                                      \"<vBYcv|}cvnf1)()@di",
  "                                                                                    .!}\\]dx/(]}xlI;<[1(WUl!>",
  "                                                                                    ,!i,,,{[_+|/_,   (ft)|!I:",
  "                                                                            .`.       ^``^,?}11{)cn//((/-l\"\"!`",
  "                                                                         ,\",^``'`,`     ```^((}[[1]]}1[l,,,^,!",
  "                                                                       `:::'l```'`\"'      ``nmQUvj(11I,^``'..^,",
  "                                                                      ,,:>! i:^^^`````!;:,,,ZwqwLcr/)\".  .",
  "                                                                     ,,I~[} lu},;::,,\"<I!!l,OOZ0Uuf\\+`'",
  "                                                                    ::l_}[+ !x(ItZ)Iux_I?!`\"fzcnj\\)\\~;::,!^ .\"^^^``'`\"",
  "                                                                  `,:i?}]<; :;\"\"Iil,/|+}0r`;}\\(1}}1_!!l,;+,;,:I!I,^'`^,\"",
  "                                                                 ,,;<[}-!,` :;\"\",,^^^Iil<I^!{[}XxX{li/+^i~l;:i]}_l\"`''`^:",
  "                                                                :,l_}[~I^'. ';\"\",,^^^;!lI`\"+_\\mJx''l]X|!xr!:;i?]~I^``''``\",",
  "                                                              '::i?}?>:`'.  ';\"\",,^^^>ll;`;f%M{ur `l!^^!?+l:,:II:\"^^^`'''`^,`",
  "                                                             `,;<[}_l\"'.    'I,\",,^^^!l!,^!QMd-J\\ ,!I`,_:!l:^```'`^^^^``'''`^:",
  "                                                            ,,I_}]<;^'.   '' I,\",,^^`<I!^\"+bkU1J_ li:`I>^,!:^'...''`^^^^``'''`\",",
  "                                                           ::!?}-i,`.   .`:, I,\",,^^`~Il`;|qm\\/X: li^\"~I^^I;^'.....''`^^^^``''`^,`",
  "                                                         ^:;<[[+I^'.   '\"I:  I,\",,\"^^>II^!v0L-nv `ll`;_^^`'\"\"`'......'``^^^^``''`^:",
  "                                                        \",I+}]>:`..  .`:l    ,,\",,\"`;il,\"+UJu-v{ ,!:^>i^^'. '\"\"`'......'``^^^^`'''`\"^",
  "                                                       \"\"^i--!\"'.   '\"l\"     \",\",,\"`:!l\";1Xz/1x> ;i^:-\"^`. .`;<^\"`'......'``^^^``''`^,.",
  "                                                     .\"\"\"^``,,'.  .^;;       \",\",,\"'ill^!fvu}\\f^ lI^!<\"`'. ',i<   ^`'.....''``^^^``''`^\"",
  "                                                    \":I__I^'\"l,  ',!`        ',\",,^'!l;\"+xxr-/| .l,,-I^'. .^I_      ^`'.....''`^^^^``''`^`",
  "                                                    !:!?_I`'^I~.^;I          .,\",,^.<I,;)0cx\\(- ,!`l+,`. .`:<,        '^'.....''`^^^\"^^^`'`'",
  "                                                   .l,\",,^'.`:~;I.           .:\",,`.~I\"!X*ohb0[ ;I\"~i\"'. ',!<           `^'.....''^;,;il,`'^I.",
  "                                                    i:^^\"^'.',>l              :\"\",``>I,-q*###*? I,;-;`. .^I_              `^'.....l;;+{?l^'`;<",
  "                                                    \"I\"`^^`,.\"!;              :\"\",':i:l|kkkho* 'I\">i:. .`:<,                '^''..i;:!<!,'.`:>l",
  "                                                     i,^(ZbwC|ii              :\"\",.,!:-ckkkkkJ :;:-I^. '\"!+                    ^`:!::II,`..`:<!",
  "                                                     \"I|bM8dCcf+            ' ,\"\",.ill}Zkkkkkt I;i+I' .^I+                       I!::I;\"'..^I-",
  "                                                      iumqqQXnj[            ' `\"\"\".!l-(bkkkkk_ >;-I\" .`:>I                       .l:-rvr]\"',i~",
  "                                                      `)LQOQYur1`           ' ^\"\"^.<i]j0Omqpd ^il+I' '\"!+                        `lzh#amJc<:~\"",
  "                                                       >CL00Jcxt^            `^\"\"`.~-?/rnvzXc :!+l: .^;+                         ;/pa8*ZYuj>_",
  "                                                        \\LQOLznj             ` \"\"'^~?-\"++?||- !i?I'.`,>I                         :cqddZYnf/}:",
  "                                                        .CQ00Yur!            ` \"\"';?+l        ~~!; '\"l~                          :UqdpQzr\\f-",
  "                                                         \\L0OJcx1            : \"\".;-_.       .<+;^.^;~^                          \"wqbqCvj\\(I",
  "                                                         ,LQOLXnj            I \"\"'+<_        ^<~; ',ii                           `wpbmUnt\\_",
  "                                                          rL00Uur:           I ,^`!<l        \"~:\"'\"l~                            <qpdOXx/(",
  "                                                          ,LQOCcx]           > ,^^I_.        I+:'`;~`                            ]qddQcj\\+",
  "                                                           zL0QXn\\           i ^^,!_         ;I,',i<                             rqbqCuf/`",
  "                                                           _L0QXxt           : `^:<l        `:,`^l_                              zqbmUx/(",
  "                                                            LQ0LUUj`         I `\"I_.        \":\"`:<,                              wpbOzr\\+",
  "                                                            wpQUuft?      `::i' \"!_         I,^,i<                              .qddQvf/`",
  "                                                            UzXJn|1~    ,IIl!>' ,<_\"       `:,\",>                               ]ZmZUn/(",
  "                                                            `(rxj({    ;!l>iII   ~ii:   ,;;;::,\",,.                            <b*#pXjj]",
  "                                                              _1[-i    <!l:<~,\"`''`\": .!Ili>iI:\"\":II                           jwOJzffrf",
  "                                                                .     '<l!;?_!ru<!_>t|>ll<?[_i;\"\",;!;                          }YzCv\\{(|",
  "                                                                      '>ll\"'..nt_L0wMnill<-?~!:\"^\":Ii^                          }vvt{}{",
  "                                                                      ^>lI,      ,~Uz+iI;I!!I:,\"^^\":l>'                          }{?-;",
  "                                                                      l>l;II\"^     ,+_iI:,,,,,,\"\"^^,:li                           ..",
  "                                                                      IiI;Il;,\"``\";I;\"iI,\"\"\",,,,\"\"^\",;!l",
  "                                                                      IiIIIl;,^`^,I~^ !l:,\"\"\",,,,\"\"^\",;iI",
  "                                                                      IiIIIl;,^`^,l_\"  lI:,\"\"\",,,,\"\"^\":I>.",
  "                                                                      IiIIll;,^`^:!?    lI:,\"\"\",,,,\"^^\":l<",
  "                                                                      !!IIlI:\"^`^:i_     lI:,\"\"\",,,,\"^^\":li",
  "                                                                      +!IIlI:\"^`\";>i      lI:,\"\"\",,,,\"^^,;!;",
  "                                                                      ~!IIlI:\"^`\"I~:       lI:,\"\"\",,,\"\"^\",;i^",
  "                                                                      ~!IIlI:\"``,I+^        lI:,\"\"\",,,\"\"^\",I>'",
  "                                                                      ~lIIlI,^`^,l-          lI:\"\"\"\",,,\"\"^\":l!",
  "                                                                      <lIIl;,^`^:!]           lI:\"\"\",,,,\"^^\":ll",
  "                                                                      <lIIl;,^`^:ii            lI:\"\"\",,,,\"^^,;!I",
  "                                                                     '<l;Il;\"^`\";<l             II:\"\"\",,,,\"^^,;i.",
  "                                                                     '>lIIl;\"^`\"I~^              I;,\"\"\",,,,\"^\",I>",
  "                                                                     '>IIlI:\"^`\"l_                I;,\"\"\",,,\"\"^\":li",
  "                                                                     '>IIlI:\"`^,!?                 I;,\"\"\",,,\"\"^\":!;",
  "                                                                     'iIIlI:\"`^:i!                  !;,\"\"\",,,,,,,,!^",
  "                                                                     :iIIlI,^`^:>>                  .!;,\"\":I;II;,\",!.",
  "                                                                     IiI;::,\"\",;<^                   .!;,:il>-_i:\",I!",
  "                                                                     IiIl>i;,,Ii+.                    .!;>!l<?_!:^\";i;",
  "                                                                     ;!!+[_l\"\":i]                       !~!Il!I:\"`^:i!",
  "                                                                     il>_~l,^^:i<                        <lIll;,^`^;>>",
  "                                                                    lli+~l,^``,ii                       '<lIll;\"^`\"I~^",
  "                                                                   :li++!:^``^;~                        '>lIll:\"``,l-",
  "                                                                  `!!~+i:^`'^:<`                        'iIIlI:\"`^,i<",
  "                                                                  il<_>;\"`'^:>`                         IiIIlI,^`^:>l",
  "                                                                 ll>+<I\"`'`,>'                          I!Ill;,^`\"I+.",
  "                                                                :li+~l,^'`,i'                           ;!Ill;\"^`\"l?",
  "                                                               `!!~+!,^``,!!                            ~lIll:\"`^,ii",
  "                                                               i!~+i:^``\"!l                             <lIll:^`^:<:",
  "                                                              ^^\",;:^``\"ll                              <;\"^`''`\"I+",
  "                                                            ''``'  `,^^lI                              .,''''. .\"l+",
  "                                                           ,^;_-I' .,iIi                               \"^:><;`  `;l",
  "                                                          ,\",i-_;' .\"i+                               :,\"i[[i`  ':<",
  "                                                         \"\",!+>,.  .\"iI                               l\"^,lI^.  ':<`",
  "                                                        `\"\"l+<:'   .,<                                I\"^\",\".   ':<^",
  "                                                       ^\"\"l~<;'    `II                               ,:^^,,^.   `;+.",
  "                                                      ^,\"I~~I`    ':>                                !,^^,,`.   `I_",
  "                                                     ^,\";<~l^    ',>                                 l\"^\",,`    ^I-",
  "                                                    `,\";<+!\".   .\"!\"                                ';\"^\",\"'   .\"l+",
  "                                                    I\",i+i,.    ^;;'.                               ;:^^\",^'   .\"!!",
  "                                                    I\"`,;\"'    ^!>+_<l,^                            !,^^,,^.   ',ii",
  "                                                   .:\"'    `\"i>------+\"l                           .I\"`^,,`.   ':>>",
  "                                                   \";+>li+--------<i\"'I                            `,,`'``.    `::....",
  "                                                  ;^l--------+i:'                                 ,\">}~iil,,\"\",Ii!!!!!, `\"",
  "                                                  ;^`+---<I\"                                      ;^,~----------------- '!",
  "                                                   \"  \"'      }[]]]CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCX;` ,--------------<il '>",
  "                                                                                                  ^^                    ^.",
  "",
  "",
  "",
  "",
];
