/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `strut_2` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                             ;   X  ^(",
  "                                                                                        ))  ;U  \\u  a;",
  "                                                                                         h! +a` d/ 0O",
  "                                                                                         vp +W]l$([B}",
  "                                                                                         <#Y]8cu%f$Z:}z",
  "                                                                                       +[ moY%Z@#a%u0k` >[",
  "                                                                                        OUcWp&b$b$m**[tqj",
  "                                                                                     'f;,kaaMW*$a8qMZ@a}",
  "                                                                                      !papMBBB$$8a&qBL\\}I",
  "                                                                                       {&$$$$$@B%&WMhko\\",
  "                                                                                      'M%$$$$$$$$$$$$mr",
  "                                                                                      uW$BZ0OOOZZbbk0zr_",
  "                                                                                     Ch ._|ttffffjjjjru(",
  "                                                                                     YW1,  >1pU(>;   B$q<",
  "                                                                                     z$Z?! \"[b) 'i!?/$&Xi",
  "                                                                                     )$v   ^okw`  .tJ$kn",
  "                                                                                     -oY/?twwJv|, \"{q$O+",
  "                                                                                    .(J0c|uLCn(unjt\\p$X",
  "                                                                                   :+\\uu/}rXz\\}ff\\()bM(",
  "                                                                                 `i)(>\\(]-)' l_((1{)am~!I",
  "                                                                                .:ii,,i+~|j-<  `}}1(j/\\;l'",
  "                                                                      '^^^``'`'   .\"`^\",-||vvt\\([{)\\)+;\"\">",
  "                                                                    '\"\":;:\"^''\";`   .\"`^`/t|}][[}}+!:,,\"^:!",
  "                                                                   ,\":!+]_l\"`'^:i,    .\"^LwmUxt/|}:\"^`''..,,",
  "                                                                 \"\",I~[1{-!\"''`,!_,+::,,,mwpwJvj\\_`.  .",
  "                                                               '\",;>?{{]~l,`'.`,l_!<I!!l+OZZ0Ynt/<`.",
  "                                                              ,\":i-{1[+!:^'...',l_)~I{,`:vzvnf|)|I;::,<`   ````''",
  "                                                            `\",l+}1}_i:^'..   ',i]{</0(^l)|){}}{ii!I\"I>```''```''^;",
  "                                                          .\",I<]1}->;^`..     `;<!l!l>,\"<1[(cxJ~l_|i\"~l\"^^^````^l:\";\"",
  "                                                         ^\";>?{{?<;\"`'.     .`\"!l^>ll;`:?+xpXx'`l]c|;XL_;{-,^`,i+'`^:;",
  "                                                       `\":!_{{]~I\"`'.     .`\";I,^^!l!,`lc%#-J] ,!l^^>]_;+Ut.\\Z1-\"'''^,:",
  "                                                     .\",I+}1[+l,`'.     .`\"I;:,^^`+I!^\"<w#L-Q- ;i;`:-^^^`. .!?-i^``''`\";.",
  "                                                    ^,;<]1}_!,`'.     .`,Il,\",,^^`<I!`:?abx|Ji li\"^!>^^`'. ',i+`^^``''`^:\"",
  "                                                  `\":i?{{-i:^'.     .`,:'^;\"\",,^^:>II`Irqm}xX .l!`,-^^^'. .^I_^'``^^`'''^,;",
  "                                                 ^``':+->;^'.     .`,;'   ;\"\",,^`;il:\"<Y0U-z/ ,!;`l<^^`. .`:<l..''`^^``''`\"I",
  "                                               ,,;;\"`'^;;'..    .`,;'     I,\",,^`I!l\":?CJx}u- Ii\"\"+;^`'. '\"!-`'..''``^^`''`^:`",
  "                                              I:>]?!\"'`:>\"    .^:,        I,\",,^'ill`I\\Xz)|rI l!`I-\"^'. .^I+\":^`'..''`^^`'''^,,",
  "                                             i;:i_+I^'',i>  .^::          \",\",,^'!l;\">xvu-ft .l;\"<!^`. .`:>I  `,`'..''`^^``''`\":",
  "                                             <;\"\",,^'.'\"!i'^::            \",\",,^.+I:,?nxt?/[ ^!\":?,^'. '\"!+     \"\"`'..'``^^`''`\";",
  "                                             ;I,^^\"^'.'\"l];`              \",\",,`.<I,IfQcf|)i :!^i~,'. .^;+       ',^'..''`^^`'''^:\"",
  "                                              i:^^\"]?_!^I-                ',\",,`\">I^>Z*ahdC> l;,?;^. .`:>I         ,\"`'..'``^``''`,;",
  "                                              I;\"|bhbZJfi_                .,\",,.:i::]o####*^.l,l+:`. '\"l+            ,^'..''`^^^````^",
  "                                              ^l}d*%#ZYvt~                .,\",,.;!,>nkkhaop \"I\"+!,. .^;~^             \"\"`'..'^:,:;\"`'\"\"",
  "                                               >umqdmJcxf?^              ` ,\",\".il;]Lkkkkkv ;:I_I`. ',ii                \"^'..l:!]]!^'^I:",
  "                                               ,(Q0ZOJcxf[^                :\",\".!I>{kkkkkk_ i,<>:. '\"l~                  `\"`:l:I<>:`.^I_",
  "                                                ~Q0OOCznj).                :\"\"\".+I-rkkkkkk^^!;_I^ .`;~`                    \"II:Il:`..`I-",
  "                                                ,vQOZQXuj}               . ,\"\"`.<>-c0ZmqpO ,li+I. ',i!                      ;;:lI\"'..\"iI",
  "                                                 ?Q0Z0Uvr|               . `\"\"',>-?frnvzY\\ !l_I\" .^l-                       !:i1{-,.`;_",
  "                                                  Q0OOJvxf               ' `\"\".;~++\"+~{||; ~i+I..`:<:                       !rkob0Y[\"!I",
  "                                                  xQOOCzxf`              '`'\"\".l_+^        <_l: ',i<                       .]po8hLcx++",
  "                                                  _Q0ZQXnf:              '` \"\"'><?        `<_;'.^I_                        `rpkdQcj/1I",
  "                                                   Q0Z0Yuj~               ` \"^`>>i        \"?!:.`:<,                        ;JpkqUn//?",
  "                                                   /QOOJvr?               ; \"^^!+^        I-:^'\"!>                         ;qdkOXr\\|;",
  "                                                   iQ0ZCvr|               I \"`\"l?         ;i:.^I_                          <qbdLvt\\<",
  "                                                    0OmQczv[              I \"^,>i        `;,\"`:>I                          rpkqUx\\(",
  "                                                   <qkdQvxnj`             i \"^;+^        \"::`\"!+                           QdkOzj\\i",
  "                                                   iLYYQv\\)/;           ''I`^\"l?         ;:^^;+                           .qbdLu/t",
  "                                                    (rxnj({-         `;;;;:,,\",I         ;,^:>I                           [pkqYr\\~",
  "                                                     \"(\\1?+         ;lI!>>!;,\",;!.      .;\"\"l+                            rdkOcf\\",
  "                                                       :;^         ;ili_[]~l,\"\":l<      ,:\";~!                            qbdCn/{",
  "                                                                   <!li+?_>I,^\",I>i `lI:I'^i~,I\"                         ;mOQzf\\`",
  "                                                                  '<!IIl!l;,^^^,I>[/-'`^   i:\":l:                       ~bakYcxj",
  "                                                                  '<!I;Il;:\"^`^,I<|Yu(>I:,^`':\":l,                      f0ULn\\tt;",
  "                                                                  '<lI;Il;,\"^`^,I<(f|j{\\q\\i:.;!\":II                     !zYXt1{)",
  "                                                                  '<lI;II;,\"^`^,l+[?<;`i-I'. ;<\"\":Il                     }uj1]i",
  "                                                                  '<lI;II;,\"^`^:!_,..       .!:\"^\":Il                    \"--+I",
  "                                                                  '>l;;II;,\"^`\":!-. I:,^'' .\",,,\"^\",Il",
  "                                                                  '>l;III;,^``\";i?   :;,\"^^\"\",,,,\"\"\",;I",
  "                                                                  '>l;III;,^``\";>-    `;,\"^^\"\",,,,\"\"\",;!.",
  "                                                                  '>l;III:,^`^,I<i      I:\"\"^^\",,,,\"\"\",;!.",
  "                                                                  ^>l;III:\"^`^,I~l       ;:,\"^^\",,,,\"\"\",;!",
  "                                                                  l>l;IlI:\"^`^,l+^        \";,\"^^\"\",,,\"\"\"\":l",
  "                                                                  l>l;IlI:\"^`^:!_.         .I:\"^^\"\",,,\"\"\"\":l\"",
  "                                                                  l>l;IlI:\"^`^:!?            ;:\"\"^^\",,,,\"\"\":l:",
  "                                                                  l>l;IlI:\"^`\";i_             :;,\"^^\",,,,\"\"\":I:",
  "                                                                  l>I;Il;,\"^`\";>i              `;,\"^^\",,,,\"\"\",I,",
  "                                                                  IiI;Il;,\"``\"I<>                ::\"^^\"\",,,\"\"\",I,",
  "                                                                  IiI;Il;,^`^,I~^                 ;:,^^\"\",,,\"\"\",Il",
  "                                                                  IiI;II;,^`^,l_\"                  \";,\"^^\",,,\"\"\",:l",
  "                                                                  IiI;II;,^`^,!-                     I,\"^^\",;;:::,,;",
  "                                                                  IiI;II;,^`^:i]                      ;:\"^^ll!~~l,\":l",
  "                                                                  IiI;I;,\"^`^:i!                       ^:,:>l<?-!,^,!>",
  "                                                                  IiI;;;:,\",:I>>                        `;!iII!l,^^\"l-",
  "                                                                  I>ll<~i;\"\";i~`                          >iIIl;\"^`,!_",
  "                                                                  Iil>?]<;\"\":!-^                          I!IIl;\"^^,ii",
  "                                                                  i!l><iI,^^,!-                           I!IIl:\"`^:>:",
  "                                                                 ^il!<>I,^``,!?                           ;!III:\"`^;~\"",
  "                                                                 i!l><!:\"``^:>I                           ;lIlI:^`\"I_",
  "                                                                 ili<>I\"^``,!+                            +lIlI,^`\"l>",
  "                                                                l!l><!:^``\"I+                             ~lIlI,^`,!i",
  "                                                                ili<i;\"^`^:>I                             <lIl;,^^:>`",
  "                                                               l!l><l,^``\"l~                              <IIl;\"^^:~.",
  "                                                               >li<i;\"``^;~                               <IIl;\"`^;_",
  "                                                              l!!>>l,^``,i;                               !^..  .^l>",
  "                                                              >l;Ii:\"``\"l~                               .^^:;^. ';!",
  "                                                             ^'..  .^`^;~^                               :\"![]I' .,!",
  "                                                            ``\":,'  ':;i!                               ,:^:i!^  .\"i`",
  "                                                           ;^:_}~,. '\"i~                                I,`^,^.  .,>`",
  "                                                          ,,\";~_!^  .\"!!                                l\"`\",`.  .,<^",
  "                                                         .:\",li;`   .\"!!                               .I\"`\",`   ':<^",
  "                                                         I\"\";il\".   .,iI                               ';^`\"\"`   ':~\"",
  "                                                        ,,\":!!:`    `;+                                ,:^^,\"'   ':+",
  "                                                       ':\"\"IiI^.   .\"i;                                i,`^,\"'   `;+",
  "                                                       I\"\";!!,'    `;+                                 l\"`^,^.   `;_",
  "                                                      :,\",li;^    .\"!;                                .I\"`\",^.   `I-",
  "                                                     ';\"\"Iil,'    `;~                                 \":l``^'    ^I?",
  "                                                     ;:^\"I!;`    .\"!<                                :\"i]--il,   ^Il",
  "                                                    .\":\"''`'.    `::....                             I`\"-------+i;\"..",
  "                                                   .,:?]iii,,,\",:!i!!!!l' ,.                         \"^ `i<--------->!:`.\"",
  "                                                   :\"^I-----------------l \";                                 \":i<-------i,^",
  "                                                   \"\". i--------------ii\" ,fCCCCCCCCCCCCCCCCCCCCCCCC\\]][[[        `\"li+-i:,",
  "                                                    :.                   .:                                             .`",
  "                                                     .",
  "",
  "",
  "",
];
