/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `sway_l` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                             !!  !   n?   `",
  "                                                                             ?m  J? `8   J?",
  "                                                                             !8! 8| J8  Jm",
  "                                                                              8a`8J!8J J8!",
  "                                                                            n 8qmoamQJJ8n  `",
  "                                                                            mJmX8r8wOac8`|a?",
  "                                                                          m||o8)Z-bl*}Jaa8?",
  "                                                                          !888|f?'?i])8L8??nmn",
  "                                                                          !aQC/]} .I;1[*8w8J`",
  "                                                                          JC?]][nJJCC*w8La!",
  "                                                                         n8[           !w88m",
  "                                                                        !a8 <)111{{{-+-\\b8`",
  "                                                                       !$$$ohkkkkbbm0ZOQo8`",
  "                                                                       !%U%$$a('/h$$$$BoJra",
  "                                                                        8?8o$8J\"8%$Wm0Yo[1a",
  "                                                                        8C$$$Q!>/$$$&vz8 Qn",
  "                                                                        z/cqt]{ujOo*hXU8:8`",
  "                                                                      _Qj1nLx(fvJrucYJC8xn",
  "                                                                     chduuJmvfrLOvzUCQqaoq.",
  "                                                                   'zkQoC0qqp$$&dYCQO0q88&w.",
  "                                                                  'qdQhWabhOrQa$$#ZmOZW&&8&w.",
  "                                                                  b&o&8&&&&8JvvQCmmZk8&&&8%&q.",
  "                                                          `]]]]]   |wBBB%8%#b*ddbh*8&&8%B@@@m1",
  "                                                        (m%%%%BB%U'  `\\wBBBm]?xvUQZY&@@@BJ?'",
  "                                                      '0&&WMM8%BB8M)]_??xa%Y]?-1fvUXBon?     !no%BB*J!",
  "                                                      QMW*dwd*8BB%WaM#*####v{}{\\xzJLWWWWWwCCw%B%8%BB&&X'",
  "                                                     zMW#kwZd*8B@%&ob*oMaa&qrxucUQLqokhMoa%%%%%%%%8kW%Wd'",
  "                                                    jMW#hpph#8B@@B&*pQoaza%#0L0ZmL0##aM8hkMMMWWW8&op@B%&#_",
  "                                                   _#WMhpphM8B@$@B&oqCdbnC%*00Zcvxq##[naZ[z*c1w%jUdoBBB%8M1",
  "                                                  l#WMappk#8B@$$$BWaq%hMM8%owpX?UM$##**Wma#&hdW@mmw&%BBBB8Wz",
  "                                                 'dWMadpk#8B@$$$B8#b*%kMM88at~-Z)*$##&%Mk%%%B@$B&ad%%%BB@B%Wp'",
  "                                                'pWWodpk#8B@$$$B8#k#%%bMM88h];(p1h$##&%*k%%%@$@%Mb#B%%%BB@B%&dl",
  "                                                zMWodqk#8B@$$$B8#b*%%%kMM88k{</J|a$##&8ao%%B@$@8*p@@BB%%%BBB%8M_",
  "                                               zMW*bqb*8B@$$@B&*k&8%%%o#M8&b?]rLto$##%&bW%%B@@BWhh@@@BB%%%BB@B8Mj",
  "                                              _MW*bqb*8B@$$@B&*k&%88%%o#M8&p1)uQr*$##%Wq8%B@$@8#pW%B@@@B%%%BB@B%Wz'",
  "                                             _#W#kqb*&B@$$@B&*dM%%88%%a#M8Ww\\/L0n*$##%Mk8%B@$B&azr&%B@@@BB%%%BBB%&d'",
  "                                            '#W#kpd*&B@$$@B&oqBM8%88%B**M%MOjr0Oc#$#M%*p8%@@@%Mb? lb8B@@@BB%%%BBBB8b_",
  "                                           'dWMhpdo&B@$$@BWon^$W8%%88BWoM%MQnu0LYM$#W8aa8B@$@8*q    r&%B@@@B%%%BB@B8M1",
  "                                           QWMhpdo&B@$$@%Wax  b%&%%88BWoM%#LczOQCW$#W8bo8B@$BWh(     lb8B@@@BB%%%BBB%Wz",
  "                                          zWMapdo&B@$$@%Wa|   t$W8%88BMaM%*LYUQQ0&$#W&q&%@$@%#d:       r&%B@@@B%%%BBB%80'",
  "                                         jW8&WMM&B@$$@%Mh~    ^$W8%88B%hM%o000oo*@$#8Md&%@$B&oz         lb8B@@@BB&888%BBh_",
  "                                        -&8&&%BB8&$$@%Mk~      b%&%%8B@hM8h],,,::w$M8#p&B@@%Mk?           r&%B@@WWMbd#%B%#+",
  "                                       _MWapbM%B%M#@%Mm<       t$W%%8%@kM&d)>i!lIw$#&aa&@$@8*q             'O8B%oW*qp*%@%Md",
  "                                       aMMbmdM%@%Wh*#Z.        ^$88%8%@bMMw}~~~~~p$*&ko&@$B&aj               (&W*WM*M%@@BMd",
  "                                      ~aW&WMW%B@BWabZ.          M@8%%%@*#*Z~~~~~~p$*WpW8$@%Md:                'q#W##&B@@%#Q",
  "                                       aM8%88%B@B&oQ.           v$&%%%@o#hO~~~~~~p$aMqWB$B&oL                  cMW##8@$@&h?",
  "                                       t#&%%8%%B@8*X            -$88%8@o*pm-_____d$h*dWB@%Wk]                  aW&dZw%@%#Q",
  "                                       .aW%%8OZw#8#p             @@8%8@*oqLffttt/a$kahW$@8#p                  .*8/^!1nM&h?",
  "                                        t#8*+^l}/w&b             J$&%%@Wawphhhhmm8$kka8$B&ac                  +Mm~<[tvwWQ",
  "                                        ;o&n+>?|rv8h:            1$%%%@Mbqf `????b$kd88@%Mb>                  tWz~-|nYa*]",
  "                                         JWO){1\\rvko<            IB@8%BMqk)      0$ap8B@8*Q                   {8{~[tvL80",
  "                                         I*#)1{|jup*>             b$8%BWpk>      0$ab8BBWh(                   `*++1rXk#<",
  "                                          L&x1{)fn0M              u$%%B%db>      0$oh8@8#p:                   |m~-|uUWl",
  "                                          'Uq){1/xc8              +B@8B%hd>      0@Ma8B&oz                    Jx~[fcpm",
  "                                            8t1{\\rvM!              M$8%8#p       0@M&%%Mk?                    8}+1xY*!",
  "                                            nJ1{(juk?              J$%%8*q       0@M&%8*q                    !*+-\\u0a",
  "                                            !#){)tnmJ              {B$%&*w       0@M&%Wh(                    |C~[fza|",
  "                                             ax1{\\xCm              _W$88oL       0@M&%#d:                    mr~)xC8",
  "                                             |q1{|rv8           'rkWW&&&8b)      0@M8&oL                     8??/vbn",
  "                                             `8){)fuo?         _pMM##MW&8&ML'   '#@M8Wka&r'                `mY>(rJW`",
  "                                              JL/jjn0m`       +a**hpdh#&88W*m. _*&#8$&qW8Wp+               nw1fvzuM?",
  "                                              aci]|xnZJ       Zo*admwk#&88&#hCC&88%$$$&%8&#k.              |C/|vL0W!",
  "                                              8xf(|zLwa      ;ko#*akh*W8%%&Maqq8Mooo**M@8MMou               /jnCmdn",
  "                                              ?#vuuU0*?      ~h*MWWMMW&8%%8ModrY8cw[nd*@%h&#h~              }L0qQ",
  "                                               !zYU0w[       .koMW&WWW&8%%8W*bmo8*8qh8$$%k8W*Z.              It+.",
  "                                                 [nu[         ua#W&WWW&8%%8&#ka$$$$$$$$$W&%&Mo/",
  "                                                              ~h*MWWWWW88%%&#hxvM8%BBB%8&8%8&#h;",
  "                                                               koMW&WWW&8%%8Maq C*W&88&&&88%8W*Z",
  "                                                               na#W&WWW&8%%8Wod 'w#W&8&&&&88%&Ma\\",
  "                                                               ;h*MWWWW&8%%8W*k< IoMW88&&&&8%8&#h.",
  "                                                                ZoMW&WWW&8%%&#h|  +oM&88&&&88%8W*U",
  "                                                                /a#W&WWW&8%%&Max   v*W&8&&&&88%&Ma}",
  "                                                                ;h*MWWWW&8%%8Wop    C#W&8&&&&8%8&#m.",
  "                                                                 ZoMWWWWW8%%8W*d:   'q#W88&&&&8%8Wou",
  "                                                                 }a#W&WWW&8%%&#k<    IoM&88&&&88%&Ma~",
  "                                                                 .h*MWWWW&8%%&#hr     +*M&8&&&&8%8&#m",
  "                                                                  UoMWWWW&8%%8MaX      v*W&8&&&&8%8Wo/",
  "                                                                  }a#W&WWW88%8Wop       C#W&8&&&88%&Mh;",
  "                                                                  .k*MWWWW&8%%&*b:      'qM&88&&&8%8&*Z",
  "                                                                   uoMWWWW&8%%&#k<       IoM&8&&&&8%8Wo}",
  "                                                                   ~a#W&WW&8%%8Mar        {*W&8&&&88%&#h.",
  "                                                                    k*MWWWW&8%8WoX         v#W&8&&&&88&*U",
  "                                                                    uoMWWWW&8%8W*d          w#W8W#M#MW8&*+",
  "                                                                    Ih#WMMWWW&8W*b:         'qMMo*kqk#&8Mw.",
  "                                                                     m**#*hh*W8&Mh<          +oao*kphM88Wa|",
  "                                                                     /ho*kwqaW88War           {k*##*W8%%Waj",
  "                                                                     ~h**hkaM&%8WoL            k*#*#W8%%Wh<",
  "                                                                     /o*ohaM&%B%&oz            h##*#&%%8Mb",
  "                                                                    .h**hh*W8%B8Mk]           ;h##*#&%%8#Q",
  "                                                                    /o*ahaM8%B%&oX            ~a##*M&%%&or",
  "                                                                    w**hh#&%BB8#d.            +a##*M8%%Wh<",
  "                                                                   {o*ahoW8%B%Wh]             /o##*W8%%Mb",
  "                                                                   w*ohh#&%B%&oX              uo###W8%8#0",
  "                                                                  {o*ahoW8BB8#d.              u*#*#&%%&or",
  "                                                                  w*ohaM8%B%Wh]               Z*#*M&%%&a<",
  "                                                                 {o*Ma*&%B%&ox                k#&W&%B%Wb,",
  "                                                                !h@@$$$B8B8#O.                #B@@@$$%#q",
  "                                                               x%%&W%@$$%MMh<                Y%&aa&@$BWu",
  "                                                              )&8*wwo%$$BWhx                1W8omqM@$@&a.",
  "                                                             'M88*db#B$$BWh<                L&%&MWB$$@&a<",
  "                                                             0&8Woo&B$$$BWh<                *8%8&%$$$@&h<",
  "                                                            jW8&*oM%$$$$BWb:               +#8%&&B$$$@Wk>",
  "                                                           lM88Mo*8@$$$@8*X                fW%%&&B$$$BWb",
  "                                                           d&8WooWB$$$$BWk:                L&%%&8B$$$BMd",
  "                                                          jW8&#o#8@$$$@8*X                 *&%8&8@$$$%#q",
  "                                                         lM88Mo*&B$$$$BWk;                +#8%8&%@$$$%*X",
  "                                                         p&8W*oM%$$$$@8*X                 fW%%&&%$$$$8*x",
  "                                                        +#8%W**&@$$$$BWk;                 LW%%&&B$$$@8obLLLLu'",
  "                                                       'a&&BBBB@$$$$@8&8@@$$L\\           `M&%@@@$$$$@WM#*ooWBb.",
  "                                                       b8oZkaa*&&&8&Moooo**W$BQ         'k8khMMaooobppppppppkW~",
  "                                                      +M%&kppppppppppppppppp@@#<        f&8bpppppppppppppboo8#;",
  "                                                      IM%$&bpppppppppppppho#$@o`        j&@*pppppooo88B$$$$$wl",
  "                                                       Y%$$$$$$$$$$$$$$$$$$$$8[.........;k@$B8$$$$$$$$OO1{\"",
  "                                                        t#$$$$$$$$$$mmmmmmn\\|^\"\"\"\"\"^^^^^^!X$$$$hZY(-...",
  "                                                       ...l(||``^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^^^^```'''...",
  "                                                          ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                        .................",
];
