/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `sway_l` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                             i:  l   u;   `",
  "                                                                             _X  Y; `o   C!",
  "                                                                             ;o\" &~ QQ  0x",
  "                                                                              Mz'%1!$1 Op`",
  "                                                                            / *duBnd*[OM_  `",
  "                                                                            CjLMwBO$Ob@c tql",
  "                                                                          J]]*d8bBk@Z$QYWw;",
  "                                                                          \"bdk*&hBWa%dq$J:[zC(",
  "                                                                          lm#BB$%$@#MaMOW$k)",
  "                                                                          Y@$$$$$@B%&W*&#x'",
  "                                                                         rW$$$$$$$$$$$$*cdoX",
  "                                                                        ik&$hQ000OOZpbpCxj",
  "                                                                       lt ,+(ttttffff)/jjJ.",
  "                                                                       IotI  >LBL[;   \"q$&v",
  "                                                                        %q>~ \"\\8^` :[1fo$wt",
  "                                                                        &\\   )oaU   ,nrB$C+",
  "                                                                        YUr-YwOuX{!l<jt$Wv",
  "                                                                       ,X0u(cLYx\\zurf/|$b_",
  "                                                                     ,>_nn\\[nXz({xj/|)v$C+",
  "                                                                    ,~(i\\)??-  ,_t\\){1c8t,!",
  "                                                                   I_)>:i+_fz)>  I{}{)\\]I\",l",
  "                                                                  :,!,\",,,<zcnn(\\[[}1|<,,\"^,l",
  "                                                                    .''`^\"^~r(1{[[[{_;\"`'..'''",
  "                                                         '^^^``'`'     .''`[wqJzxt\\t,'..`",
  "                                                       \",,:I;\"`'`\"I.     ``fwqp0Xxtf`'         '```.",
  "                                                      :;:!_]_l\"`'^:i;llIlIIxOZOCcr/(;:::;!  .^``^^`'\",^",
  "                                                     \";:I~]}_l\"''`:!+l!;ii,?zcur/)(?i<>;!>^^^`````\"<:^:;",
  "                                                    ^;:I<--<I\"`..`,!-)i>j>^I1|1}[(1IIi;\"<~;;;:::\",!-''^,I",
  "                                                    I:I>--<I\"'...`,!-|_+v|^l))}xnc?IImui}mjlr0]`z/_i'''`\";'",
  "                                                   I:;>--<I\"'.  .`:i?^>;I\"^!]-fq/; II!l:[iI,<_:.[[[,``''`\":\"",
  "                                                  ;:;i_-~I\"'.  .'\"I~l^<;I\"^iYbp}Q! II,`I~^^^'..',>_`^``'''^:I",
  "                                                 ;:;i_-~I\"'.  .'\"I~I^^~;I\"\">wML-0> II,^!~^^`'..^;+I``^^`'''^,;",
  "                                                \";:!_?~l\"'.  .'\"l+l^^`<II\"\"~OkU\\C> II\"^>!^^`. '\"!-.''`^^``''`\"I",
  "                                               \";:!+?+l\"'.  .`,l<,\"^^`!I;\",+qwz|Yi II^,+:^^'..`:<>'..'``^``''`\";^",
  "                                               ;:l+?+l\"`.  .`,l~,^\"\"^`iI;\",-0Qu(z! II`:]^^`...^I-:`'..''`^^`'''^:\"",
  "                                              I:I~?+!\"`.  .`,!+;^^\"\"^`il;\":]JU()ul II`;~^^'..',i~',^''.''`^^``''^,;",
  "                                             I:I~-_!,`.  .`,!l`;\"^\"\"^`!l;`;{Xz)1rI II^l-^`'..^;~:  ,\"`'..'``^``''`\":",
  "                                            ;:I<-_!,`.  .`:il  :\"^^\"^`:!;^I(vu1(t; I:^>i^`. '\"l?    ',^''.''`^^`''`\";'",
  "                                           ,:;>-_i,`.  .`:i!   ^,^^\"\"`:i;^l(xr{)|: I:\"~!^'..`:>l      ,\"`'..'`^^`'''^:\"",
  "                                          \";;>-_i,`.  .`:>;     :^^\"\"`;i;^l(t/))1, I::?,^...^I_.       ',^'..'``^``''^\"\"",
  "                                         `:\",:;I,`.  .^;<'      :\"^^\"``>;^iO*ah0L> I\";_,`..',i<          ,\"`'.''`,\"\"\"^``^",
  "                                         ,\",\"^``\",  .^;<`       `,^^\"`.<;\">w&&&WW] I\"l-,'..`;~:           ',^'..::;~_l^'^l.",
  "                                        ;:>-+;^'^;l.^;i`         :^^\"`.~;,_0aoo*#] I,ii,..'\"l?              ^\"``!:l?-l^'`;_",
  "                                       i;;~[_;`'`:<lI>           \"\"^\"^.+;;]Zkkkkk_ l,~!\"..`:>>                ,;l:;l;^'.`;_",
  "                                      'i:\":;:^'.`:>+<            '\"^^^.lIl}kkkkkk_ !:-:\"..^I+.                 lI:Il,`..^l+",
  "                                       >;\"^^\"^'.',!_              ,^^^.!I<{kkkkkk_ iI?:`.'\"!_                  :;:lI\"'.',<:",
  "                                       ,l,^^\"^_!'\"l>              ^^^^.il-[pddddd_ <l_:'.`:<:                  >>zdqQjI`I+",
  "                                        i:^~CbpOU{I-             ..\"^^.!!?|XYYYUU> ~i<:..\"l-                   +Zo%oOXni>:",
  "                                        \"I+d*%*mUv(+               ,^^.:>]{|||||\\; <<>\".',i~                  .)qbhmYnf)+",
  "                                         iuwdhqCcxf_.            ' ^^^.;+?>  \"\"\"\"  <_\"^.^;+^                  ,cpkpCvf\\{:",
  "                                         ltQQO0Jcnf[^             `.\"^'I?<l        >-\"''\"!_                   `0dkmYx/t~",
  "                                          ?LQOOCznj)^             : \"^':-~^        i+\"'`:<l                   .qbb0cj\\1`",
  "                                          ;vQ0OQYur/              ; ^^'^_+^        !>\".^I-.                   [pkpCut/.",
  "                                           ]QQO0Uvxf              .'.^`^>_\"       ';>\"',i~                    rpkmYr\\1",
  "                                            LQOOCcnf`              ; \"`\"l-        ';,^`;~:                    qdb0cf\\`",
  "                                            {Q0OLXnj:              l ``\"l?        ';,^\"l?                    ;qbpCn/|",
  "                                            ,LQO0Yur]              ^' ^\"!]        ';,^:>I                    [pkmXj\\i",
  "                                             zQOOJvx{               :.\"\"i-        ';,^I_.                    zdb0vtt",
  "                                             _Q0OLzxf            ',:::,\"\":.       ';\",i-                     mqqJx\\~",
  "                                              LQOQXnf;          ;IIllI:,\",;;      ';\";~>,'                 .YhhLcjt",
  "                                              |JUzXuv\\        .ill<-_<I:\"\":li   l,l\" ,?;\":I.               (w0Xnjnj;",
  "                                              QdoqLvux]       >!li_[]~l,\"\",I>l \"^\"^   ,^\",l~               _XULx|1\\`",
  "                                              Q0XLCr||\\       <!Il><<l:\"^^,I>?Ln?ii!!lI'\";;iI               \\zv|[1~",
  "                                              luxnn/1(:      '<!;::;;:,\"^^\";i_zxjr]wu_l.^<,I>'              <|1?_",
  "                                               .[t/1];        ~!;:::::,\"^^\":!+11}!^?>^  ^~\":l>                ,.",
  "                                                 ,I;\"         IiI:::::,\"^^^:l<+^        :,^,;i:",
  "                                                              '>l;:::::\"^^^,I>!;;\"````^\",\"^\",I<",
  "                                                               ~!;:::::,\"^^\";i? Il:,\"\",,,\"^^\":!>",
  "                                                               IiI:,:::,\"^^\":!_  !I:,\",,,,\"^^,;i:",
  "                                                                <l;::::,\"^^^:l~`  iI:\"\",,,,\"^\",I<",
  "                                                                >!;:::::,^^^,I<I  .!;,\"\",,,\"\"^\":!!",
  "                                                                :iI:,:::,\"^^\";>!   :l;,\"\",,,\"^^,;>\"",
  "                                                                 <l;::::,\"^^\";i-    Il:,\",,,,\"^\",li",
  "                                                                 >!;:::::\"^^\":!+.    lI:\"\",,,\"\"^\":!I",
  "                                                                 ^>I:,:::,^^^,l~`     i;,\"\",,,\"^^,I>'",
  "                                                                  <l;::::,\"^^,I>i     .!;,\"\",,,\"^^,l>",
  "                                                                  !!;::::,\"^^\";i<      :l:,\",,,,\"^\":!:",
  "                                                                  ^>I:::::\"^^\":!-       II:\"\",,,\"^^,I>",
  "                                                                   <l;::::,\"^^,l+.       lI,\"\",,,\"^^:l>",
  "                                                                   Ii;::::,\"^^,I<`        i;,\"\",,,\"^\";i^",
  "                                                                   '>I:::::\"^^\";>i        `!;,\",,,\"^^,I<",
  "                                                                    ~l;::::,^^\":i>         :l:\"\",,,,\"\",l!",
  "                                                                    Ii;::::,\"^^:!_          !I:\":I;I;:\",!'",
  "                                                                     >I:;;:::,\":l~           l;;il<?~I,\";!",
  "                                                                     >l!ll<<l:\",I<`          .!>!l~-<;\"^:iI",
  "                                                                     ,<il<]]>:\"\";i!           `~lIll;\"^^:ii",
  "                                                                     '<l!>~>I,^^:!_            ~lIll:\"`^:<`",
  "                                                                     ,ili<>I\"^`^,i<            <lIlI,^`\"I+",
  "                                                                     <l!><l:^``^;<:            >IIlI,^`\"l+",
  "                                                                    ,ili<i;\"^`^,i<            '>IIl;\"^`,!i",
  "                                                                    !l!<<l,^``\"I_             'iIIl;\"`^:>`",
  "                                                                   `ili<i:\"``^;<,             :iIll:\"`^;+",
  "                                                                   !l!<>I,^``,!<              I!Ill:^`\"I+",
  "                                                                  `il><!:^``\"I_               ;!IlI,^`,!i",
  "                                                                  !l!<>I\"^`^:<:               >lIlI,^`:>`",
  "                                                                 `il;il,^``,!!                ~l,:,^`^;~.",
  "                                                                 ^...  '^`\"I<                 I'''.  ^I?",
  "                                                               .^`,:^. .^;;<`                `^,>>,. ':I",
  "                                                              .,^l]]i^  `:<!                ':\"![?;. .,>",
  "                                                              I\"\"!_+I'  ':>^                ;,^\";:'  .\">`",
  "                                                             ,,\":!!,'   ':<`                l\"`\",^.  .,<^",
  "                                                            `:\",li;`    `;~.               .I\"^,,`   ':~\"",
  "                                                            ;\"\"Iil\".   .\"!>                ^;^^,,'   ':+",
  "                                                           ;,\":!!:`    `:~                 ;,^^,\"'   `;_",
  "                                                          `:\",liI^.   .\"!>                 l\"`\",\".   `I?",
  "                                                          ;\"\";i!,'    `:~                 .I\"`\",^.   ^l<",
  "                                                         ;,\":!i;^.   .\"!>                 ^;^^,,`.  .\"!!",
  "                                                        .I\"^:!l\"'    `:<                  ;:^^,,`   .\"i,",
  "                                                        `,,`'``'    .\",\"...               ;,`...    .:II!!i;`,",
  "                                                       :\"i}~iil,,\"\",I!!!!!!: ':          \"\"~>;;iiii+--------~:'",
  "                                                      .;^,~-----------------'.l`        ^,\"+-------------+ii^l",
  "                                                       I` ,+-------------<il 'iQCCCCCCCC/,'l-----iii\"\"'     .",
  "                                                       ^^                    \"           ,' `\"",
  "",
  "",
  "",
  "",
];
