/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `sway_r` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                   c  /+",
  "                                                                                               {  _O  a;",
  "                                                                                          !x   h^ ?d \\a`",
  "                                                                                           Ux  0u Uk:MQ `;",
  "                                                                                           .ac ca<mhX$z`aI  .",
  "                                                                                            (*J|&X8a#WnWX }0",
  "                                                                                          {~ 0#ZWbWoWdha)kb;",
  "                                                                                           Lwch*aM&*$w@J$wi",
  "                                                                                         !. Y*h&W$$8%#dBOmLY",
  "                                                                                         ,L*w#8$$$$$B8&W*@t",
  "                                                                                           rW$$$$$$$$$$$$Or`",
  "                                                                                           o&$$8#**oahhkmUx]",
  "                                                                                          [&8kXzcvunxrrjffvq:",
  "                                                                                         -$$Z\\  ^!-cYXc|_>  ~",
  "                                                                                         ;&%QLC|[   [n'  >{n(",
  "                                                                                          dB0Qbz>  IYJ[   fm[",
  "                                                                                          c@ZCO[  `tJYf\"  \"z:",
  "                                                                                          _BwYUYfvCYzx|f/w$Y",
  "                                                                                          I8pvCU/\\zvnj|)(QBr",
  "                                                                                        `i1kkxxf{{n(]_+1)zo]\"!l",
  "                                                                                       I-1_1nt)[_)t:   '\\rt_(!l'",
  "                                                                                       .^`^\",[[~-)){r|[?/|f{>\"\">",
  "                                                                              .```.       ^``^<{}[[[|1]}{)~,,,\",i",
  "                                                                            ,\",\"^`'`\",      ^``fvf1[))1{~I\"^``''\":",
  "                                                                          ^:::'!^`````'. ;`'``^zZwwLcr/),'.. .",
  "                                                                         \",:i? !;\"\"\"^^^^`ilII;:OZwmLcrt1'",
  "                                                                        ,,;<]} :ujII{~;;:>Il!I\"uJUYvj\\|?::,,\"`  ^^^^^`'`\"'",
  "                                                                       :,l+[[+ ,\\}!?CfIrQ)Ic|:\"_jf/({1}liiI:+,::,;!l:^`'^:l",
  "                                                                     '::!-}]<; 'I,\",I\"\"!_+>t)::](}/|/t!l~<`;-lI:l_}]>,`'`,Ii",
  "                                                                    `:;>]}-i,` 'I,\"\",\"^^^<Il\"^l[-)Ovt;l!CX-+ci;:l+]-!,`''^,l:",
  "                                                                   ,,I~[[+l\"'.  l,\"\",\"^^`<Il^^>umkUj: l!II,[[i;,,;I;\"``'''^:l;",
  "                                                                  ,:l_}]<;^'.   l,\"\",\"^^I>Il`,_8Mj/Q; I!\"^l<;i;\"^```^^``'''^:!.",
  "                                                                 ::i?}-i,`..  . ,:\"\",\"^^;iI;`;/*h(xJ .l!`\"~I^i;\"`'''`^^`'''`\":i.",
  "                                                               ^:;<][+l\"'.   '^ ,:\"\",\"^^;!I:^!cdw-cf ,lI`;?^^:l,^`'''`^^`'''`\";>",
  "                                                              \",I+[]<;^'.  .`,! .:\"\",\"^`I!I,\"~COX-X) \"!:^!>^^`\"I:^`'''`^^`'''`\";!",
  "                                                             ,:l-}?i,`.   .^;I  .;\"\",,^`>ll\":?LCj)v~ l!^,_;^`'.'I:\"`'''`^^`'''`\"II",
  "                                                            ::i][_I^'.   `,!^    ;\"\",,^'ill`I\\YX)\\xI I!`I+\"^'. .\"l:\"`'''`^^`'''`,l;",
  "                                                          ',,I<[<:`.   .^;I      ;\"\",,^'!I;^ixcv]tf .l;^>>^`...`:<i:\"`'''`^^`'''^,l,",
  "                                                         `^\"^`'^;'.   ',!^       ,,\",,^'<I;,+nnj-t) ^l,:_,^'. '\"!+ \";\"`'''`^^`'''^:!.",
  "                                                        ::i_>,``:>  .^;I         \",\"\",`.+I\";1rj/1|+ \"!^l+,`. .^;~^  \";\"`'''`^^`'''^:i",
  "                                                       :;;~]<,'',il',!^          `,\"\",`.<I,lzhqQcr! ;;\"~i\"'. ',i<    ,;\"`'''`^^`'''^;l",
  "                                                       ~;\",:\"`.'\"!<;I            .,\"\",`.<I\"<mM##*a- l:;_;^. .^I_      ';\"`'''`^^`'''\";!",
  "                                                       \"I\"`^\"`'.^I_.              :\"\",`;>;;[hao*#M\"'I\"i+:'..`:>I        I,^'''`^^`''`\"I:",
  "                                                        i,^^\"^'.`;+               :\"\",':i:>jkkkkkh ^I,-!\". '\"l+          I,^'''`^^```'`::",
  "                                                        \"I\"IrdqQr><               ,\"\",.:!;?Ykkkkkv :;I_;` .`;~:           ;,^''`:\":;,^'`:\"",
  "                                                         i,Oo%*OYu_`              ^\"\",.I!![Zkkkkkt l;<i:. ',i<             ;,^^I:l-[<,`'\"!\"",
  "                                                         \"{mqbwJvr)!             .^\"\",.il-)pdbbbk_ <;-;\" .^I+               ;,ll:l__!\"''\"l-",
  "                                                          ~LQ00Jcxj>             ` \"\"^.ii?\\YUCL0Ol <!+;..`,>I                :iI:;l;\"'..^l-",
  "                                                          \"uL0OLznj-             ; ,\"^.!+_(|\\tfjx .>+l: '\"l-                  !;:;l:`..'\"!<",
  "                                                           +LQOQYur!             ' ,\"^'~]?  \"\"\"+> l>_;`.`:<:                  >;:-{]+..`;~;",
  "                                                            zL00Jvx?             ^ ,\"`'-+~        !~~; '\"!_                   i>ZhhwLu>\"l_",
  "                                                            _LQOLznj             ; `\"'`-<l        >?:\".^;+                   '!Oh8&pCcx><:",
  "                                                             CQOQYuj`            ^ `\"`^<_.        >+:'',ii                   .1qdhpLcrt(+",
  "                                                             {L0OJvr+            .'.\"`;!]        .il,.^I_                    ,rqdbZYnt\\[:",
  "                                                              LQOLzx1            '` \"`,>i        ^!,^`:<l                    ^cqbdQzr\\f-",
  "                                                              rQ00Ynj             ; \"`;~:        \":,`\"!+                      wpbqCvf\\1,",
  "                                                              ,L0OUuf;            ; \"^l-         I,\"^;~^                     .qdbmUn//,",
  "                                                               vzOCzzr            < ^,!-         I,^,i<                      <qdb0zr\\{",
  "                                                               wbwJujr{       .,::< ':<>        ':,^I_.                      |qbpLvf\\i",
  "                                                               CUXQv\\){      ;II!i<. ,+<:     `:::,,\"^'                      zpbwUn/t",
  "                                                               ;\\rxr|{      ;!liI;,   <;i:  ,I;IlI;,\"\":l                     qpbOXr\\]",
  "                                                                 -|1?-      <!l:_-I:,\"^`'. ;!li+-+!;,\",;i'                  ;qddQvf\\`",
  "                                                                  ';^      '<l!:+<lcz[}\\/mc>l!<?[-i;\"^\";!~                  <wpwJn/|",
  "                                                                           '<l!\".  [{!XUZbfilI!<<iI,\"^\",IiI                ~bokQzrti",
  "                                                                           '<l;:       Irx[iI;::::,,\"^^\":l<                LpmJnnur1",
  "                                                                            ~!;;I;^`.  . ,liI:,\",,,,\"\"^^,;!<               zUYQu|)|1",
  "                                                                            ~!;;II:\"^`^:!- >l:,\"\",,,,\"^^\":I>\"              Iuzc\\}}1",
  "                                                                            ~!;;;I:\"^`^:!- .iI:,\"\",,,,\"^^\":!~               l\\)]?;",
  "                                                                            +!I;;I:,^`^:!?  \"!;:\"\",,,,\"\"^^,IiI                ,,",
  "                                                                            ;iI;;I:,^`^:!?   Il;,\"\",,,,\"^^\":l<",
  "                                                                            IiI;;I:,^`^:i]    !l:,\"\",,,,\"^^\";!<",
  "                                                                            IiI;;I;,^`^:i]     iI:,\",,,,\"\"^\",I>\"",
  "                                                                            liI;;I;,^`^:i<     `!I:\"\",,,,\"^^\":l~",
  "                                                                            '>I;;I;,^`^:i!      :!;,\"\",,,,\"^^,;i:",
  "                                                                            '>I;;I;,^`^:i!       !l:,\"\",,,\"\"^\":l<",
  "                                                                            '<l;;I;,^`^;>i        >I:,\",,,,\"^^\";!!",
  "                                                                             <l;;I;,^`^;>i        .iI:\"\",,,,\"^^,I>\"",
  "                                                                             <l;;I;,^`^;>>         ;!;,\"\",,,\"\"^\":l>",
  "                                                                             ~l;;I;,^`\";>>          Il:,\",,,,\"^^\";i:",
  "                                                                             ~!;;I;,^`\";<:           lI:,\",,,,\"^^,I<",
  "                                                                             >!;;I;,^`\";<`           .iI,\"\",,,\"\"^\":!!",
  "                                                                             ;!;;I;,^`\";<`            ,!;,\"\",,,\"\"\",;>\"",
  "                                                                             I!;;I;,^`\";<^             :l:,\",;:::,\"\"Ii",
  "                                                                             IiI;::,,,,I~^              !I:\"IIliiI,\",l,",
  "                                                                             ^>ll><l:\":!+^               iI!!!+[-i:\",I<",
  "                                                                             '>l>??i:\",l_\"               .i<ll>~>I\"^\";>I",
  "                                                                             ,!l><!:\"^\"I+\"                ;>lli!;\"^`^:>>",
  "                                                                             <l!<i;\"``\"I-                 ;!l!il:\"``\"I+",
  "                                                                            ,!l><l,^``,>I                 <lliiI,^`^,i<",
  "                                                                            <li<i;\"``\"l~                 '>l!i!;\"``\";~",
  "                                                                           `!l><I,^`^;~                  ;!l!il,^``,!<",
  "                                                                           !li<i:^``,iI                  <llii;\"^`^;~:",
  "                                                                          `!l>>I\"``\"I~                  '>l!i!:^``,!_",
  "                                                                          !li<!:^`^:~                   I!l!iI,^`^;<:",
  "                                                                         `!!>>;\"``\"!;                   <lli!;\"``\"l+",
  "                                                                         !li<l,^`^I<                    >::;:^^`^:<:",
  "                                                                        '\"'  `^``:<^                   ''...  .^,l+",
  "                                                                       ``^,^. .\":!!                   \"^\"l!,'  `;<:",
  "                                                                      :\":_[i` .^!~                   `,\"![}i^  `:~",
  "                                                                     .:\";~~;'  ^ll                   I\"\";>i,'  ':>`",
  "                                                                     ;\",l!,'   ^l!                  `:^\";I\".   ':<^",
  "                                                                    ,,\"IiI`   .\"i,                  I\"^:I;`    `;_",
  "                                                                   .:\":!!\".   `;<                  ^:^\";I,'   .\"!<",
  "                                                                   ;\",li;`   .\"i,                  I\"^,I;^.   ',>,",
  "                                                                  ,,\";il\".   `;<                  ^:^\";I:`    `;+",
  "                                                                 .:\",!!:'   .\"i,                  l,^,I;\".   .\"!>",
  "                                                                 I\"\"IiI^    `;<                  ^:\"\":I:`    ',>I",
  "                                                                .;^\"Il,'   .\"i\"                  !,^\";I,'    `;+.",
  "                                                                ^;l`.'.    `;i                  .\":`''`'    .\";\"....",
  "                                                               ;\"<?--+iil\":,\"'..               '\";]?>ii,,\"\",:!i!!!!I..,",
  "                                                               ;`:------------+<>I^\".          l^\"i-----------------, ::",
  "                                                               ;` \"iiii------------,1CCCCCCCCCC_^.'+-------------+ii. ;\"",
  "                                                                '          `\"\"\":ii;,^           \".                   ',",
  "                                                                                   .",
  "",
  "",
  "",
];
