/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `sway_r` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                   J  |?",
  "                                                                                               |  ?a  a?",
  "                                                                                          !J   8! ?8 |8!",
  "                                                                                           mJ  mm J8?a8 `!",
  "                                                                                           `8m`J8|m8mp8`a?  `",
  "                                                                                            noanpa8|8caaa ?m`",
  "                                                                                          |? aX8LY8[mt8oJm8?",
  "                                                                                          `aamp[*;c!<X(*qo|",
  "                                                                                         !``apq(>  ^^<)fU8Jm",
  "                                                                                         !a8a8QJJJJJL0OO88m",
  "                                                                                           J8            t8!",
  "                                                                                           8q  \"Il!i>><~[/8J",
  "                                                                                          ?8L~fjrnuULLQ0Om88!",
  "                                                                                         ?w;qW$$$$BOXzYq#$$$$",
  "                                                                                         !a^mc|Lm$$$muB$$$bYa",
  "                                                                                          alZx+ra$$#t/m$$$OcJ",
  "                                                                                          JfOu{m$$BY\\fX&$$8k?",
  "                                                                                          ?C0X/tXx|trcLXUaj8`",
  "                                                                                         lp8QC\\tUCrxvXCQLkoa '",
  "                                                                                        ja0*80cYOOvQwdb0Qw8ZOon",
  "                                                                                      lppOdW8kQmdQUW$$$BCL8dL**~",
  "                                                                                      !U%B%8&8okpQ0OcCmqJw8Oa88a.",
  "                                                                            `|w%BB*J!   `n%B%888abmmCOwZk8&&&&8&m.",
  "                                                                           (&8&8%BBB80'   'x8%BUYm*8akho&&88%B@@8v",
  "                                                                          XWWWBo%BBBBBBqCLYUZm8j}][(rcUQ&@@$$@qC]!",
  "                                                                        'O&Waq$*M8888%%%%a##MMW{}][|rcU0BqC]!    ?uCCCu]",
  "                                                                       lb&MhwZ$WuX#MZbMMWa#**M8u\\/fxzJCqW&&&Oj](h%%%%BBB8r",
  "                                                                      -W&#bmmb$&CZ*q|X#z)0#xCW8pzYJQOOZ#ooMWd&WW&M**W8BB%Wq.",
  "                                                                     rWWopZwhM$B#&8&#88odbhYQWWwLZUCUUo*kh%Mp*#W#dZwa&%BB&#m.",
  "                                                                   'Y&WawZpo&B$B#&8&&8%%%k#*&%#mp01nYM*o|jpbxaMW*dwpo&B@B%&#v",
  "                                                                  'b&Mkmmb#8B@$$#&88&8%%%h#*%8an[~tXW$#o##&mmaM&&M#M8%BB@B%W*u",
  "                                                                 -k&*dZwhM%@@$$$*&88&8%%#a#*%&d\";zJ(M$#o8%#hMaM8%BB%%%%B@@B%Wo+",
  "                                                                (WWoqZpo&B@$$$@$&W88&8%%Mo#M%MUl<Lc\\$@#o%8k#%oM8BB@BB%%%B@@B8Wo+",
  "                                                               XWMhwmb#8B@$$$@8$&W88&8%%Wo#W%*x_]pxX$&*#%Wq%%W#&8BB@BB%%%B@@B8Ma'",
  "                                                             'O&#bmwhW%@$$$$B&o*@W88&&%%#*#&8k|{fpf0$8*W%oh%%B8MW8BB@BB%%%B@@B8Mw.",
  "                                                            lkW*pZqo&B@$$$@8MC.z@M88&&%Ba*#8Wq(|XQxk$#o%&dW%%@$@#W8BB@BB%%%B@@B&#C",
  "                                                           -WWaqmd#8B@$$$B&o{  }$M88&&%Bo#*%#JtfQJv#$#*%Mb8%B@$@8*W8BB@BB%%BB@@%&#v",
  "                                                          r&&#kwhW%@$$$@%MC.   >$M88&&%B*#M%acrxwUX$@#M8ha%%@$@BWhaW8BB@BB%%BB@B%&*t",
  "                                                        'Z88%%B%MB@$$$B&o{      $&&8&&%@k#M&buuzpYQ$8*&Wd&%B@$@8*Q zW8%B@BB%%BB@B%W*+",
  "                                                       'dWoda&BBWa$$@%MC.       $8&8&&%@b#&WqcXUOCb$&*%*b&B@$@%Mb<  zM8%B@BB%%BB@B%WoI",
  "                                                       vMMbwk&BB&a#B&o{         0%&88&B@k#&*COhadp*$MM8ka8@@$B&oz    cM8%B@BB%%BB@B8Wq.",
  "                                                       kM8&W&B@@8*kMC.          0$&88&B@h#8h[;Il/n&$#WMdW%@$@%#d.     1M&%B@BB%%BB@B8Mw.",
  "                                                       t#8%88%@@%#d+            }$W88&BWaWMw<i!lII8@M&obW@$$BWh(       _#&%B@BB%%BB@B8Mv",
  "                                                       .o&%%8%B@BWb             }$W88&@WoWaX~~~~~<$%M&p*8@$@8*0         _#&%B@BB%%%%BB%Wv",
  "                                                        tM8%8dZw8&h:            _$&88&@WoMqt~~~~~n$WW#dMB$@%Mk]          _d&%B@%W8WM&%B%Wf",
  "                                                        .o&8/^!{nM*~            ;$%88&@M*om}~~~~~Y$#MhoW@$B&oX            'd&%%#W*pmh&BB8*}",
  "                                                         tWw?+]/x0Wx             @%88&$a*p0-_++~~p$hMpM8$@%Md:             'p&*#W*dpo8B@8#p",
  "                                                         .*#(11\\xX8Y             %$88%@ooqCf/\\(){#$h*bM@$B&a|               'Qo#WM#M8B@@8#p",
  "                                                          f&C){|juMU             W$&8%@obddhdO0Cv$@hb#W$@8#p                  wMWM#W%@$@&oz",
  "                                                          'bh){)tnk|             U$&8%@kwq  ???Jq$#hdM%@%Wk]                  aMWMM&%@@BWb?",
  "                                                           'an11\\x0J             X$&8%Bpbz      }$*kkM$B8oQ                   oW8UtnJMB8*L",
  "                                                            |q){|jX8             u$B8BBph)      0$hq&8@%Mb:                  ~*8?\",_|vMWk?",
  "                                                             8t1)tuo!            {$B8B%kd:      0$abWBB&ar                   +#m_<-(rcqWQ",
  "                                                             nO11\\xpn            +B@8BM*w       $@o*&@8#p                    /WL_+}tvU#o]",
  "                                                             `#){(rQm            ~B$8%&aj      ^$8o&%BWh(                    {Wx+_)rzL8p",
  "                                                              mJ1)fu8            ;M$8%Mk?      }$8W&B8*Q                      8{~?|nXkM[",
  "                                                              !h)1/uo?            M$88#p       z$#&8%Mk<                     `8_~[tvUW-",
  "                                                               aU{|r0a`         `?h$%&oL       0$M&%&oz                      ?m_+1jzOm",
  "                                                               8|]\\nzwm       )bWWk$BWhX       &@W&%Md:                      nX+-|nXa|",
  "                                                               8cf)xJZm     'L##oah@$&bkc    lYWWW&&8hr'                     mx~]/vL8",
  "                                                               ?QcvzLO`     vo*a#M&$$$hMo/  z#M###M&&8W#_                    8_+{jzpJ",
  "                                                                 |C0qC     ;h**WdpMW&8%BB@CL*#obpboM&8&Ma+                  !*__(xYW!",
  "                                                                  +v}      ~h**Wbh#xjwZJMhpa**kqmpaM888W*k.                 ?m-]/v0a",
  "                                                                           ~h**8@$$mOojc8[Xa*#ohka#&8%8&Man                ?*{~(jca|",
  "                                                                           ~h*MW$$$$$$$8%wqa#WWWWW&&8%%8W*h;               a/[\\uvnmm",
  "                                                                            k*MMMW8B@$$$$$Ma#W&8&&&&88%8&MoO               act(uC0pm",
  "                                                                            k*MMMMW&%%%W*p.a#W&88&&&&88%8&#a}              ?LrxJZpa`",
  "                                                                            boMMMMW&%%%Wop +o#W&8&&&&&8%%8W*b.              +CQwq{",
  "                                                                            boMMMMW&%%%Woq  toMW&8&&&&88%8&Man               It/.",
  "                                                                            uoMMMMW&%%8Woq   C*M&88&&&&88%8W#h;",
  "                                                                            uo#MMMW&%%8Wow   .w#W&88&&&&8%%&MoO",
  "                                                                            na#MMMW&%%8Wow    Ia#W&8&&&&88%8&#a}",
  "                                                                            na#MMMW&%%8Woz     {oMW&8&&&&88%8W*b.",
  "                                                                            ~a#MMMW&%%8Wax      v*M&88&&&&8%%&Mo/",
  "                                                                            ~a#MM#W&%%8War      .w#W&8&&&&88%8W#h;",
  "                                                                            ~h#MM#M&%%8War       'a#W&8&&&&88%8WoU",
  "                                                                            ;h#MM#M&%%8War        +oM&88&&&&8%8&Ma}",
  "                                                                             k*MM#M&%%8Maj         v*M&88&&&88%8W*Z.",
  "                                                                             k*MM#M&%%8Mhj          C*W&8&&&&88%&Mo/",
  "                                                                             b*MMMM&%%8Mh]          'w#W&8&&&&8%8&#h;",
  "                                                                             Z*MMMM&%%8Mh<           +oM&88&&&&8%8W*U",
  "                                                                             uoMMMM&%%8Mh<            t*M&8&&&&888&Ma}",
  "                                                                             uoMMMM&%%8Mk<             v*W&8&WWWW&&&#m.",
  "                                                                             noMMWW&&&&#k>             .w#W&##*aoM&8&*/",
  "                                                                             }a*#ah*W8W*b>              IoM*o*bmpoW8&Mh;",
  "                                                                             ~h*aqqaW8&#d>               +oh**abaM&%8Ma|",
  "                                                                             to*ahoW8%8#bi                ua#*aoM8%B%Whj",
  "                                                                            .h*ohaM8%B8#p                 uo#oa*W8%B8Mb:",
  "                                                                            /o*ah*&%B%&a|                 h**oo#&%B%&oX",
  "                                                                            h*ohoW8%B8#0                 +a#*aoW8%B8Mk:",
  "                                                                           {o*ah#&%B%Mk:                 uo#oa#&%B%&oX",
  "                                                                           w*ohoW8B%&o|                  k**ooM8%B8Mk?",
  "                                                                          {o*hh#8%B8#0                  ~a#*a*W8%%&*Q",
  "                                                                          w*oho&%B%Wk;                  uo#oa#&%B%Wk?",
  "                                                                         {o*haM8%B&o|                   k**aoW8%%&*Q",
  "                                                                         w*ah*&%B%MO                   IaWWMW8%B%Wh]",
  "                                                                        r8@$$B%%%Wh<                   UB@@@$$@%&#0",
  "                                                                      'mB%&%@$@8W*r                  'k%8#*&B$$%Mh]",
  "                                                                      d8Wdma%$$8*O                   j&8omma%$$BWk",
  "                                                                     )W8MkkMB$$%#x                  '#88Mao&@$$BWh<",
  "                                                                    'M8&*o&@$$$%*x                  jW88MM8@$$$BWh<",
  "                                                                    0&8#oM%$$$$8a]                 '#88W#W%$$$$%Md",
  "                                                                   )W8Wo*&@$$$BMO                  jW88M#&B$$$@8*X",
  "                                                                  'M8&*oMB$$$@8o[                 '#&%&#M%@$$$B&h]",
  "                                                                  0&8Mo#8@$$$BMO                  jW88M#WB$$$$%Mb",
  "                                                                 )W8&*oWB$$$@8o[                 '#&%&#M8@$$$@8*X",
  "                                                                '#88#o#%$$$$BMO                  jW88W#W%$$$$B&a(",
  "                                                                )M88M#&@$$$@8o[                  *&%8M#&B$$$$%Mb:",
  "                                                               -%M*B@@@$$$$BMa[`                U8W%BBBB$$$$@8M8@@@$pu'",
  "                                                              'M8kqppboo#8W&8B@@$#L!           r8Mwqaaa&&&8&Woooo**#@@b.",
  "                                                              IMBWppppppppppppbhhM88+          *88oppppppppppppppppp&$W\\",
  "                                                               dB$8oooopppppppppppp&v          d8@Bbpppppppppppppboo$$M[",
  "                                                               \"w$$$$$$$$$$B888WooW&(..........}&@$$$$$$$$$$$$$$$$$$$Bz",
  "                                                                 I((((UZZmmmmm&$$$bt^\"\"\"\"\"^^^^^^-d$$$$$$$$$$hZZZZZY)1,",
  "                                                              ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"i\\\\|i^````'''..",
  "                                                                 ...''''`````^^^^^^^^^^^^^^^^^^^^^^`````'''...",
  "                                                                               .................",
];
