/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `tune_up` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                  !J   `",
  "                                                                                                  ?m  n?  ?n",
  "                                                                                                  J8 `8? ?8`  |!",
  "                                                                                               `` m8!m8 ?8n `mJ",
  "                                                                                               ?a`8QJo8?8a n8J",
  "                                                                                             n? 8maY8zaoomw8J",
  "                                                                                             !8n8pJtnjm/8LpJ`?n",
  "                                                                                             ?8oai}-I|,O-O8m8J`",
  "                                                                                            n8<)XwJ{>:>:wC0w? ??!",
  "                                                                                           n8|   .!jQpCf!m8w88m?",
  "                                                                                         |$$b:+?<I^  '-zpQQqn`",
  "                                                                                         ab$$8bCc/)}+l\" ^-M8mn",
  "                                                                                        !a\"*8$&YXdkwJx\\1)z8n",
  "                                                                                        |q$$$$Zn~pb8$$BhOk8!",
  "                                                                                        zup%$a>;]$$W*$$h8Jo?",
  "                                                                                    _. :|\\Y0+<~|r$$$kzYb|lq|",
  "                                                                                  'QodIxfzOC}}tL\\Y*$8UQa`wJ",
  "                                                                                 _oZm8bYCmpj|\\zZrucYJLotCJ",
  "                                                                               'zkCm#&8qdpc@$@pzcXJL0wa/J",
  "                                                                              lbap*&&&&8W8}\\w$$aJLOZO#p&.",
  "                                                                       `]]i    !U%B%8&&8%8UnzCqpOmmZb88&m.",
  "                                                                    'na%%BBBJ!   `n%B%%Bo\\J*qdZmmbaW88%%Wu",
  "                                                                   -W&W#%BBB%&Yi .`'|aB8j+i?UdM8*8%B@@$@*J.",
  "                                                                  XWW*$MW%%%BBBBBM*&&h&d-<!-|nYL0$@@C\\?    ]]]]`",
  "                                                                'O&Woq&B#&8&&&888#o#oo#m{{}(rzCJo8Zx?_  (m%%%BBBa(",
  "                                                               lk&MhwZ#BJ]QWuua#Oqo##W%orxncUQQ0**#MMk%W&8WMW8%BB&dI",
  "                                                              (W&#dZmb&$dqo8YQam)XoX{w%*LL0ZmOZ#o#W8ao*WW*dqkM8BB8Wo'",
  "                                                             Y&WoqZwhM%$#W88&8%%Mh*kq#8hQmLnn(h#wjZ&mb*WMhmZd#8B@B8Wq'",
  "                                                           'b&MhwZpo&B@$&W88&8%%%h*#M%&pbJ[jz$@#dOd#j0*W&#aa#8%B@@B8Wq'",
  "                                                          -k&#dZmb#8B@$$8M88&&%%%a*#W%MX`;OrQ$&**%8hoa*W8%%%%%%BB@@B8Wq'",
  "                                                         (WWoqZqaW%@@$$$@M88&&%%%o##&%*t;_p\\J$8*M%Wd%**W%B@BB%%%BB@@B8Wq'",
  "                                                       'Y&MhwZd*8B@$$$@$$#&88&8%%o##&8h{<tpUb8M*&%*k%8*W%B@@@B%%%%B@@B8Wq'",
  "                                                      'k&#bZmkM%@@$$$@8&$#&88&8%Ba#*%&q?tLkmUdM#a8k#%%%MW8BB@@BB%%%BB@B8Wq'",
  "                                                     -WWoqZqo&B@$$$@%Wq+$W&88&8%Bb##W*hdZmkUnqWMbap8%%@BWW8%B@@BB%%%BB@B8Wq'",
  "                                                    r&Whwmb#8B@$$$@8#v. &&W8&WW#apOCXczU0qo##W8Wdpb%%B@$@WM&%B@@BB%%%BB@B8Wq'",
  "                                                  'O&#bZwhW%@@$$@%&#0JJq&@*bQJXzXCOpa#W8%&o&%BBMk**%B@$@%Mh*&%B@@BB%%%BB@B8Wq.",
  "                                                 lk8WM##W%%%%%%*O0n/\\I;;uWbm0qoM&8%BB@@B*#qhMZQn|xxww#%%8M0'0W8B@@BB%%%BB@B8Wq.",
  "                                                x8888&WMM8Y/{lI;;I~1tzCpwoh*WBB@B%%%WmvcLZJaY--(x;-???](uYwwa&&8%BBBBB%%BB@B8Mw.",
  "                                               zW#bkbddd&j,;i~_rLO0LUJzY0$W&%%8BMaM8*qO0JL0M#unzu\\/|){[]????][fuUww%%%BBBBBBB%Wc",
  "                                              {#Whmpha*M81{(tjxucYJLqb*kJ$8&88&BWa#8h\\/Y0h*$@8aodOYcuxjt\\(1}[??-??]]{LM%%%BBBBB%X'",
  "                                              u#&&W&%BB@%duzULOpa*aJ|?   0@&88&@WoWWwII;;II$@#8oa&%#awLYcvnrf/|){}]?1jz8W&&88%BB&q.",
  "                                              {#8B@@@$$$$@%o*%B%O.       0$&88&@&o&ov~<>i!_$8M&d*8@$@8WMokmJYzvnrft\\rcU8&WWWW&BB8*Y",
  "                                               Q8@$$$$$$$$$$L/]          \\$&88&@&*Wdt~~~~~n$WWMqM%$@BWh] ?|JkoqOJYzcUQb%B%%88%@@8#p",
  "                                                xB$$$$$#L[i              ]$W88&@a*#w}~~~~~Y$oWahM@$@8*Q      lh%%#hdhMB@@@@@@@$@8#q",
  "                                                  ][[]`                  ~$%888$a#kZ~~~~~~p$aMpM8$@%Mk]        i/Q$@$$$$$$$$$$$@8or",
  "                                                                          $%88%$o*qU}[??-_dBa*dMB$B&oX             i/Q$$$$$$$$$@WJ",
  "                                                                          %$88%@ohwJunrjf/$8ahhW$@%Mb:                 i/Q$$$$$h)",
  "                                                                          k$&8%@oddcJaaahd$WaqW8$B&az                      i[[`",
  "                                                                          U$&8%@dpw      v$#hkWB@%#d",
  "                                                                          u$88%Bqkr      }$*b*W$BWh(",
  "                                                                          {$B8B%qk]      0$hp&%@8*p",
  "                                                                          +B@8B%ad:      0$akW@%Wh]",
  "                                                                          ~8$8B8*w       $@a*8@8*Q",
  "                                                                           M$8%&ar       $Bo&%%Mk?",
  "                                                                           *$8%Wk]      }$&W&B&oz",
  "                                                                           k$B8#d:      }$WW8%Mb:",
  "                                                                         ?Uq$B8*w       z$#&%&ar",
  "                                                                       jMWMa@$&a0l      p%W&8&oI",
  "                                                                      c*#akk%$@kko+   jMWWWW&&8&0'",
  "                                                                     /o*oM%B@$$8#W*`'L##*aa*M&8&Mo+",
  "                                                                     bo*MbLho*#MW&%B*o*odwqk#&88W*k.",
  "                                                                     ko*WM*&X]zQ\\bajh**obqdaM&88&MaY",
  "                                                                     bo#W@$$%b&hL%Cnh*MM***M&8%%8W#h~",
  "                                                                     Uo#W8$$$$$$$$%kh*M&&&&&&88%8&MoZ",
  "                                                                     na#WMMM&%@@BB%ah*W&88&&&&88%8&#a\\",
  "                                                                     na#MMMM&8%%&#hj+o#W&8&&&&&8%%8W*k.",
  "                                                                     ~a#MMMM&8%%8Mhf voMW&8&&&&88%8&Man",
  "                                                                     ~h#MMMM&8%%8Mhf  C*M&88&&&&88%8W#h;",
  "                                                                     ~h*MMMMW8%%8Mhf  'w#W&88&&&&8%%&MoO",
  "                                                                      k*MWMMW8%%8Mh]   +o#W&8&&&&88%8&#a}",
  "                                                                      k*MWMMW8%%8Mh<    toM&&8&&&&88%8W*b.",
  "                                                                      ZoMWMMW8%%8Mk<     C*M&88&&&&8%8&Mo/",
  "                                                                      uoMWMMW8%%8Mk<     .w#W&8&&&&88%8W#h;",
  "                                                                      noMWMMW8%%8Mk<      Ia#W&8&&&&88%8WoU",
  "                                                                      }a#WMMW8%%8Mk<       {oM&88&&&&8%8&#a}",
  "                                                                      ~a#WMMW&%%8Mk<        v*M&8&&&&88%8W*Z.",
  "                                                                      ~h#MMMW&%%8Mk<        .w#W&8&&&&88%&Mo/",
  "                                                                      .h#MMMW&%%8Mk<         'a#W&8&&&&8%8&#h;",
  "                                                                       k*MMMW&%%8Mk<          +oM&88&&&88%8WoU",
  "                                                                       b*MMMM&%%8Mk<           v*M&8&&&&8%%&Ma~",
  "                                                                       u*MMMM&%%8Mk<            w#W&8&&&&&88&*Z",
  "                                                                       uoMMMW&8%8Mk<            'q#W&&MMMMW&8&*/",
  "                                                                       no#MMMW&8W*k>             +oMWo#obdoW8&Mh.",
  "                                                                       +a**bdaW8&*b>              t*ao*hqqaW88Wox",
  "                                                                       ~h*odpaW88#k>               Cho#*o*M8%%Woq",
  "                                                                       }o*oa*W8%8Mk>               .k*#**M&%B%Woz",
  "                                                                       J**aaM8%B8#p                ;h*#**M8%B8Mk]",
  "                                                                      Ia*oa*W%B%Wa(                +a##o*W8%%&#p",
  "                                                                      to*aaM8%B8#0                 uo#*o#&8%%Woz",
  "                                                                      h*oa*W%B%Wh]                 J*#**M&%B8Mk?",
  "                                                                     {o*aa#8%B8#Q                  k*#**M8%%8#p",
  "                                                                     J**aoW8B%Wk;                 ;h##o*W8%%&or",
  "                                                                    Ia*oa#&%B8*X                  +a#*o#&%B8Mk>",
  "                                                                    t**aoW8B%Wk:                  no#**M8%%8#q",
  "                                                                    h*oa#&%B8*r                   J#&%%BBB%&oj",
  "                                                                   1&B$$@BB%Mb.                  `MB@B@$$@8Mk:",
  "                                                                  x%%&8@$$8Mo|                  'k%&ahMB$$%MO",
  "                                                                 j&8hmb&$$BMO                   Q&8omma%$$BWk.",
  "                                                                '#8&ab*%$$BWb                  '#8%W*#8@$$BWh<",
  "                                                                j&8W*MB$$$BMd                  1M8%&W8@$$$BWk<",
  "                                                               lM88##8@$$$%#X                  Q&%8WW%@$$$BMb",
  "                                                               Q&8W*M%$$$@&a<                 I#8%8W&B$$$$%#p",
  "                                                              _M8&##&@$$$BMd                  fM8%&W8B$$$@8*x",
  "                                                              p&8W*M%$$$$8o|                  p&%8WW8@$$$@&aj",
  "                                                             1W8&##&@$$$BWk:                 I#8%8W&%$$$$BWh<",
  "                                                            'd&8W*M%$$$$%#Y                  cW8%&W&B$$$$%Mb:",
  "                                                            _M88M#&@$$$@&a]                  o&%8WW8@$$$@8#p",
  "                                                           'kW%BBB@$$$$%W#LLLL/`            U8W%BBBB$$$$@8MB@@@$pu'",
  "                                                           b8hpaa*&&88W***###MB8_          r8Mwqaaa&&&8&Woooo**#@@b.",
  "                                                          +M%*pppppppppppppppppWZ          *88opppppppppppppppppM$W\\",
  "                                                          'MB8bpppppppppppppboo&U          p8@Bbpppppppppppppboo$$M[",
  "                                                           |%$$$$$$$$$$$$$$$$$$J;..........}&@$$$$$$$$$$$$$$$$$$$Bz",
  "                                                            +0&$$hmmmmmn\\\\\\\\\\]^^^\"\"\"\"\"^^^^^^-d$$$$$$$$$$hZZZZZY)1,",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"i\\\\|i^````'''..",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^^`````'''...",
  "                                                                           .................",
];
