/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `tune_up` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                  ln   ^",
  "                                                                                                  ]X  c!  }/",
  "                                                                                                  UZ `M: }b   \\;",
  "                                                                                               '' ww`dZ }8_ ^q|",
  "                                                                                               ~Z Bpf$z[$n z&{",
  "                                                                                             f> Mv@d*Mz$Zv8h[",
  "                                                                                             ;a)Mp$b$w$aO$m]`}/",
  "                                                                                             ?oh#&$h$*&p@Cmbo|",
  "                                                                                            n$$&#*#&WWhWm@*n: [}:",
  "                                                                                           xB$$$$@%W*abwowb$Bkcl",
  "                                                                                         \\{]aWbqhM%$$@8Maokn~",
  "                                                                                         M~  _jnzUQZb#8$%pcZC(",
  "                                                                                        !$8-; ;cJufrvXC0Qnj~",
  "                                                                                        \\a    }vb-~l;;I)xjr`",
  "                                                                                        JJ-^ ihWw  :!  ]W$pI",
  "                                                                                       lLCf1bhbCz   ~rfq$*ci",
  "                                                                                   :!; cXr1\\ZZY|Jfl \"tj$BY]",
  "                                                                                  !}[\"~f|[-zCJj}curt\\(k$Q]",
  "                                                                                \"~|}I,\"?_-r' '-rrf/(1x$p]",
  "                                                                               ,i-l,,,,\"]CZJ]  i\\({}{#Mj",
  "                                                                                .^``^,,\"^uXur|?-{[[}\\orIi",
  "                                                                      `^``'`.      ^``^`!QU\\)[{[[[}1_\"^`:;",
  "                                                                    :\":I```'`,`      ``\"zbodv\\{[{+l'.. ...",
  "                                                                  ^::l.;:^```````I!,,\",_phopCut(1..'",
  "                                                                 \",:i?\"'l,\",,\"\"\"\"IiI!!l[OZZLzr|\\!\"`      '^^```'`",
  "                                                                ,,;<]}I`\\w):un>l{?!Il:`izcuxt)(1lll;I~`:,\":;:\"`'`\";",
  "                                                               :,l+}[+, _?i\"t(>[Qj!fO[^!(|1}[{}I!l:^>!l;:!_?~I^''^:i",
  "                                                             `,:i?}]<;` l:\"\",\"^^;<!~?I\"<)[(uuQ<I]X},[+l:;<[}_I^''`\";I",
  "                                                            ,,;<]}-!,`. ,:\"\",\"^^^>lI;`,-+/mzj .l_{_Iz1l:,IiiI\"`'''`\";I",
  "                                                           ,,l+}[~I\"'.  \";\"\",,^^^>ll:`;f%M{z) ,ll^\"<iil:\"^^^^^^`'''`\";I",
  "                                                          ::i?}?>:`'.   ';\"^\",^^^ill,^!UMd-C/ \"l;`:_^ll:^'''``^^`'''`\";l",
  "                                                        `,;<]}_l\"'.   .. I,^\",^^`!Il\"\"<OkU-t+\";!,^l<^\"!:^`''''`^^`'''`\";l",
  "                                                       ,,I+}[~;^'.   '\", I,^\",\"^`>Il`,-qU|~[/_;l>\"<I^^`;:^`''''`^^``''`\";l",
  "                                                      ::!?}?i,`.   .`:I. :,^\",\"^`+Il:l<_}[~/u?:;+i-^^`''::\"`''''``^``''`\";l",
  "                                                    ':;<[}+I^'.   '\"I:   ,:\",::I>-{\\frj/1?ill:\":_-+^^'. ';;\"^''''``^``''`\";l",
  "                                                   \",I+}]<:`'.. .;[)|rx0_.!+)\\frf\\{_>I:\"^,!,^`'I||1;`. .`;<l,^`'''``^``''`\";l",
  "                                                  \"\":IlI:`<]tuvqdkho*#MMu:+[1?i;,\"^`''''!I??]}(uCmwO0Yft?}? ,:^`'''``^``''`\";l",
  "                                                .\"^\"\",:;<Zaao#MMM#k0Yj|-]!>!:`'''^^^:[xr(}\\YmppLcWpqqqwmZO0QXx\\-+`'''````'''^;l",
  "                                               \":I~~~+__Ok&Mokpc({)(t\\rt1 :,`^\"`;>I\"!nzn\\|)[XcuruJUCQOmwqqqqwmmZO0Quf],'''''`^:,",
  "                                              `l:>[_<ilI0OOQUzvnrf\\(1}}-i ^,^\",':iI\"<m*ahqC,I1{}\\/frnvzYJL0ZmqqpqqwwZJx<``````'^^",
  "                                              ;I,,;,^`''}vnr/|){}[->:^    ',^\",.:i::]#MMMM# .I\"i+~~}1(\\frnvzYUCQOmwq0Xu/:,,\"\"^``,l",
  "                                              ^l\"''..    i-}[+<I!         .,^\",.,!,!xkkhaod \";,_l\". ^!-[{1(/frnvcXUJzxtt,::;;,''\"l>",
  "                                               :\"'                         :\"\",.,!:_Ukkkkkv ::I?;`..`:<, ^:i?{1(/frr/)))``^\"\"^''^l-",
  "                                                .'                         :\"\",.>lI]Zkkkkkt !:><;. '\"!+       l>_}{{[{~^...''. .^l?",
  "                                                                         ' `\"\"\".il~}kkkkkk_ >;-;\" .`;~:           \",:          .\"ii",
  "                                                                           ^\"\"^.il?tZmqqpd_'>l_;' ',!<                         ':!",
  "                                                                          ` \"^^.!>]\\nvczYU \">>>: .^;+                         .^'",
  "                                                                          \" \"^^.!__~~}(||\\ :>?:\" ',i~",
  "                                                                          ' ,^^'_-]      ' l<~;'.^I_",
  "                                                                          ; \"^^'?<i        !+!:.`:>I",
  "                                                                          ^ `\"'`?<:        <-,^'\"l-",
  "                                                                          .'.\"'^i_.        >~:'`:<:",
  "                                                                          '^ \"`\"!]        .>!\"'\"!+",
  "                                                                           ; \"`,ii        `i,^`;~:",
  "                                                                           ! \"^:<:        ,:,`,i<",
  "                                                                           < '^I_.        ::\"^I+",
  "                                                                          'l '\"!]         I,^,ii",
  "                                                                       `;;;>' ,i~        `:,\",i",
  "                                                                      ,lli~~^ '<<!.   `;;;;:,,\":,",
  "                                                                     ,iliI^'.  ^I:!  ;lI!>>l;,\",;!.",
  "                                                                     ~!l;+(<!lI;:\"I-l!li_[?<I,\"\":l~",
  "                                                                     ~!l:;l,fwj)Jvdb<!li+?_>;,^\",Iii",
  "                                                                     +!I;.  `+\"<|YCv<lIIl!l;,\"^^\":l<'",
  "                                                                     !iI;^       !({<l;,,,,,,\"\"^^,;!<",
  "                                                                     IiI;;I;,^''````<l;,\"\",,,,\"^^\",I>:",
  "                                                                     l>I;;I;,\"^^\"I<>.iI:,\"\",,,,\"^^\":!~",
  "                                                                     '>l;;I;,\"^^\"I<> ;!;:\"\",,,,\"\"^^,;iI",
  "                                                                     '>l;;I;,\"^^\"I<>  Il;,\"\",,,,\"^^\":l<",
  "                                                                     '<l;;;;:\"^`\"I<<   !l:,\"\",,,,\"^^\";!<",
  "                                                                      ~l;;;;:\"^`\"I<:   .iI:,\",,,,\"\"^\",I>\"",
  "                                                                      ~!;;;;:\"^`\"I<`    ,!;:\"\",,,,\"^^\":l~",
  "                                                                      >!;;;;:\"^`\"I<`     ll;,\"\",,,,\"^^,;i:",
  "                                                                      IiI;;;:\"^`\"I<`      !l:,\"\",,,\"\"^\":l<",
  "                                                                      IiI;;;:\"^`\"I<`       iI:,\",,,,\"^^\";!!",
  "                                                                      ^iI;;I:\"^`\"I<`       `!;,\"\",,,,\"^^,I>\"",
  "                                                                      '>I;;I:\"^`\"I<`        :l;,\"\",,,\"\"^\":l>",
  "                                                                      '>l;;I:\"^`\"I<`         !l:,\",,,,\"^^,;i:",
  "                                                                       <l;;I;,^`\";<`          iI:\"\",,,,\"^^,I<",
  "                                                                       ~l;;I;,^`\";~^          .!;,\"\",,,\"^^\":!!",
  "                                                                       +!;;I;,^`\";~^           ;!;,\",,,,\"^^,I>'",
  "                                                                       ;!;;I;,^`\";~^            !l:,\",,,,,\"\",l>",
  "                                                                       I!;;;:,\"^\";~^             lI:\",;;;;:,\",!:",
  "                                                                       IiI;;;:,\":l~^             .i;:il!++i:\"\";>",
  "                                                                       '>!!~_i:\",l+^              \"!iil<??>:\"\":il",
  "                                                                       '<li_-i:^\"I~^               I<!Ili!;\"^^:!?",
  "                                                                       ^ili>l:^`^;~^                ~lIl!I,^`^:i<",
  "                                                                       l!l>i;\"``\"I_                 >lI!!;\"^`\";<:",
  "                                                                       >l!>!:^`^:>I                'ill!l:\"``\"l-",
  "                                                                      ,!liiI\"``\"I~                 IiIl!I,^`^:i~",
  "                                                                      <l!>!:^`^:>:                 !!Il!I,^`^;~:",
  "                                                                     ^ili>I\"``\"l+                  ~lI!!;\"^`\"l-",
  "                                                                     ll!>!:^`^:<                   >ll!l:\"`^,ii",
  "                                                                     ili>I\"^`\"l<                  'iIl!I,^`^;~^",
  "                                                                    ,!l>!:^`^:~.                  I!Il!;\"^`\"l?",
  "                                                                    <l!>I,^`\"!!                   !l:^^````,ii",
  "                                                                   ',`  '``^;+                    ;'''.. .^;~",
  "                                                                  .``\"^' .^;iI                   \"^,i>;'  `;~",
  "                                                                 `,\"<[+,. `;<                   :,\"i[[i^  ':<",
  "                                                                 I\",i+!^  ';+                   l\"^:!l\".  ':>`",
  "                                                                `,^:l;`   ';_                  ';\"^,:\".   ':<^",
  "                                                                ;\"\"Il\".   `I>                  ::^\"::^.   `;+",
  "                                                               :,^:l;`   .\">`                  I\"^\":,`    ^I-",
  "                                                               ;\",Il,.   `;_                  ^;^^,:\"'   .\"!!",
  "                                                              ;,\":l;`   .\"!;                  I,^\"::^.   ',ii",
  "                                                             ':\",Il,.   ':~.                  I\"^\"::`.   `:<`",
  "                                                             ;\"\";l;`    ^l>                  ,;^^,:,'    `;+.",
  "                                                             ;^\"Il,'   ',>,                  !,^^::\"'   .^l-",
  "                                                            \":^''`'    `:I                  .\":`''`'    .\"I`....",
  "                                                           :\"<->il,,\"\":lllllI;'\"           '\";]?>ii,,\"\",:!i!!!!I..,",
  "                                                          .;^!-----------------:>          l\"\"i-----------------; ::",
  "                                                           ;`^+-------------+ii,\\CCCCCCCCCC_^.'+-------------+ii. ;\"",
  "                                                           .`                  `            ,.                   ',",
  "",
  "",
  "",
  "",
];
