/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `twist` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                   j  !n",
  "                                                                               -   pI c|",
  "                                                                           t   j)  &[ B1",
  "                                                                           |u  ~hl 8c|8} f",
  "                                                                            YZ\" *J %0po[Qu `1",
  "                                                                             dbiJ*zBw$pU&>[kI",
  "                                                                           l >ahZWwBb$O@L0%{",
  "                                                                           (C{uoao#Wa$hMo%r;{",
  "                                                                            id*k*W$$%%&b%OWd;",
  "                                                                          1XxJ#8@$$$$$B%&%BJ",
  "                                                                           \"x#$$$$$$$$$$$$wn+",
  "                                                                            j*@$%%8*oahkbZCvr",
  "                                                                            O#8wYzcunxrjft/YQ<",
  "                                                                           o$Mn\\  ^;-uUzv\\?~",
  "                                                                           L@kvbQ\\[\"  `J' ^}x|;",
  "                                                                           {%ocpkp[   xYx.  ^1",
  "                                                                           .WMzmmx   -YXx_\" ?-",
  "                                                                            Q8Y0UJrnJXcxt\\\\%o}",
  "                                                                            t%JYULj)cuxft{(ah<'.",
  "                                                                          'i|80vxr([jj]-<]xm0]_l.",
  "                                                                         ,<(?czr({?]/1    'xft!\"l.",
  "                                                                        :l<l,,I(1~+{1}\\c)-(|\\-,\"\"l'",
  "                                                                          '``^\";-{}[[[1)]]{)?,\"^`^l'",
  "                                                                            .````Cxf1[|)1]<:`'..'",
  "                                                                     ^^^^```\"` '`0ZmmLcxt)`...",
  "                                                                   \"::;:```i;:::,0ZmmLzxt1^^             '^^^``'`",
  "                                                                  \"I:! ,:\"\">ll>>;fJUXvj\\|}lll:!>````'  \",\":;;,^`''`'",
  "                                                                  iI:I !}I{[~[;I^<ff/({1)I!!;\"~l\"^^^^^I;:l_]_!\"``''''`.",
  "                                                                  <I,\" )zj0jXYnZt>|1}/\\X<Il,\\|}lI-+I;I!;:i?}-!,\"^^``'''``",
  "                                                                  lI,\" ';\"I<ii;ll~}?fUn>,Il\"n/];>Zxil>!;,;!iI,\",,\"\"^^``'''`'",
  "                                                                  ;l,\" ';\"\"l!;;`,-rLw0/ .Il^^i>^^;;\"\"!!:\"^^^```^\"\",,\"\"^^``'''`.",
  "                                                                  ^!:\"''I\"\"l!;;`:[8MjzQ .Il^\"~I^^^^^^,i;\"`'...''``^\"\",,\"\"^```''``",
  "                                                                  'i:\"' I,\"l!;;`Ix*h-vJ ^II`:?^^^^^^^^I;\"'.  ....''``^\"\",,\"\"^``'''`'",
  "                                                                   >;\"' I,\"li;;^lxdq-nu ,I;`I~^^^^^^^`.,\"'       ...''``^\"\",\"\"\"^``'''`",
  "                                                                   <;\"\" ;,\"li;:^iXZ0-Y) ,I:^!>^^^^^^`'. `^..        ...''``^\"\",\"\"^^`````'",
  "                                                                   lI,\" \",\"li;:\"<zCX-c{ \"I,\"~l^^^^^^`. .^I+  ..        ....''`^\"\",,,\"\",\"`'`,",
  "                                                                   ;l,\" \",\"li;\"\"+XYj-n} \"I\":?\"^^^^^`'..`,>I      '.       ....''`^l:I+-i,``,!'",
  "                                                                   ^!,\" ^,\"!>;\",-cvt{j] \"I`;+\"^^^^^'. '\"l~           .        ...;l:!?]>,''\"l~",
  "                                                                   '!:\" .:\":>;\";}nx\\}/- ll^!<\"^^^^`. .`;~`              ..       ll,,;;,`..^I_",
  "                                                                    i:\" .:\"\"<;\"I)jf|{(l I:\"<!\"^^^`'. ',i<                   .    :l,^^\"^`..^I_",
  "                                                                    <;\"' :\"\"<;,lnO0Xnr\" I:,?:\"^^^'. .^I_                       ..'>:\"^\"\"`'.`;+.",
  "                                                                    lI\"' :\"\"<;\"imWMM#*? I\";-:\"^^`. .`:<I                          !I\"lcdpOc{;~\"",
  "                                                                    ;I,^ :\"\"~;,+O*#MWW] I\"!_:^^^'. '\"!+                           '!iZo8MwJc\\<^",
  "                                                                    ^l,I \"\"\"~;;]qkkkkh- I,<<:^^`. .^;+                             !jwbadLznf?^",
  "                                                                    '!,, ^\"\"+;!{kkkkkk_`l:-:,^`'..`,>i                             ,(00ZOJcxf]`",
  "                                                                     i;, ^\"\"+;~|kkkkkk `l;_:,^'. '\"l~                               ~Q0ZZCznf)^",
  "                                                                     <I:`.\"^+I?rbbkkkk ^!!+:,`. .`;~:                               ;U0OZLXnj)",
  "                                                                     l;:` \"^!!]jLQ00OZ ^i<>:,'. ',i<                                 |0OZQYuj?",
  "                                                                     :;\": ,^!<]\\tfjjrx ^>-,:\". .^I_                                  ,00Z0Uvrj",
  "                                                                     `I^; ,^!?_Xpcxrjj ^<_,:` .`:<I                                   Q0ZOJvrf",
  "                                                                      \"\"\" ,^i?-wdwOZZU ,+~,:. '\"!+                                    /0OZCcxf",
  "                                                                        ; ,^>+]XzcYJQf ,-i,\" .^;+                                     i0OZQznf;",
  "                                                                        ; `^+i+{|/rnc( ,+\",` ',ii                                      Q0Z0Ynf:",
  "                                                                        ; `^!>< ,!?(/[ \">\": '\"l-)                                      n0ZOUuj+",
  "                                                                        I `^l<l     :I \"l\"\".`:<uJ0mz]                                  _LCJcxr|",
  "                                                                        ^' ^;+^        l,\"`',!1UJhCzr\\                                 \\bMa0Xzu1",
  "                                                                        .' \"I_\"        l,\"'^I_/f0zCYnj{                                0OCLCr|\\f",
  "                                                                        .: \"l?         I,\"`:>iicut/\\t([\"                               ]zuvu/1)~",
  "                                                                        :: ,!]         ;,^\"I+  '~}??-+;                                 l(rf([i",
  "                                                                     ,;;!; ,i-.     .\":::,,\",'                                            l-+;",
  "                                                                   .!Il>~i  i_I:   :IIlll;,\"\":l`",
  "                                                                   !!!i;;`  ':\"I\" !!li_?+!;,\",;i^",
  "                                                                  ^>ll;}-ii!!lI>t1>l!~?[_i;\"^\":l~",
  "                                                                  l>I!:<!>qX+QZwW/ilI!><!;,\"^\",;i!",
  "                                                                  '>II^   >>^?}Uz]iI:::::,,\"^^\":I>^",
  "                                                                   ~!;,        ,+-iI:\"\"\",,,,\"^^\":l~",
  "                                                                   IiI:,:::`'''^:>!I:,\"\",,,,\"\"^^,;i!",
  "                                                                    >l:,:::,^^^:l+^iI:,\"\",,,,\"^^\":I>\"",
  "                                                                    >!;::::,\"^^,I<`.!I:,\"\",,,,\"^^\":l~",
  "                                                                    :iI:,::,\"^^\";>! ;!;,\"\"\",,,,\"^^,;i!",
  "                                                                     <l:,:::,^^\":i+  :l;,\"\",,,,\"\"^\",I>'",
  "                                                                     !!;::::,\"^^,l+   !l:,\"\",,,,\"^^\":li",
  "                                                                     ^>I:,::,\"^^,I<`   lI:,\"\",,,,\"^^,;iI",
  "                                                                      ~l;,:::\"^^\";>i    iI:,\"\",,,\"\"^\",I>'",
  "                                                                      ,i;::::,\"^^:!>    .!;:\"\",,,,\"^^\":li",
  "                                                                       >I:,::,\"^^,l_     \"!;,\"\",,,,\"^^,;iI",
  "                                                                       >!;,:::\"^^\"I~`     :l;,\"\",,,,\"^^,I>'",
  "                                                                       ^iI::::,^^\";>I      !l:,\"\",,,\"\"^\":li",
  "                                                                        <l:,::,\"^^:!>       lI:\"\"\",,,\"^^\";iI",
  "                                                                        !!;,:::\"^^,l_        iI:\"\",,,,\"^^,I>",
  "                                                                        'iI::::,^^\"I~^       .!;,\"\",,,,\"^\":l>",
  "                                                                         <l:,::,\"^\";>,        `!;,\"\",,,,,\"\":!,",
  "                                                                         ,!;,::,\"^^:!l         :l:,\":I;;;:,\":i",
  "                                                                          >I::::,,\",l_          II:;il>_+!:\",Ii",
  "                                                                          >lIII!l:,,I~           lI>!l~]-!:\"\";>,",
  "                                                                          ^>il~]_l,\":>,           i<lI!il:\"^^:ii",
  "                                                                           <!!<+i:\"^:!!           \">lI!!;\"^`^;>I",
  "                                                                          ^il>~!:^``,ii           '>lI!l:\"^`\"I+.",
  "                                                                          !li<>I\"``^:<            IiIl!l:^`^,!+",
  "                                                                         `!!<<l,^``,i!            !!Il!I,^`^:>I",
  "                                                                         >li~i:\"``\"l~             ~lIl!;\"^`\"I+.",
  "                                                                        \"!!<<I\"^`^;+              <lI!l:\"``,!_",
  "                                                                        il>~!,^``,>,             '>ll!l:^`^:>l",
  "                                                                       l!!<>;\"``\"ll              ^iIl!I,^`\"I+.",
  "                                                                       il><l,^`^;<               I!Il!;\"^`,l_",
  "                                                                      Ili~i:^``:<`               >l,^^```^:>l",
  "                                                                     .,^\"\"^^``\"!;                :'''.. .\"I+.",
  "                                                                    '``^`. ',\"I~                \"^,i<;'  `;~",
  "                                                                   :^:_?l` .\"!+                :,\"i[[i^  ':<",
  "                                                                  \",\"I_+;'  ^!;                l\"^:!l\".  ':>`",
  "                                                                  :\":ii,.   ^!i               ';\"^,:\".   ':<^",
  "                                                                 :\",!>;`   .\">`               ::^^::^.   `;+",
  "                                                                ,,\"I>l^.   `Ii                l\"^\":,`    ^I-",
  "                                                               `:\":ii,'   .,>                ';\"^,:\"'   .\"!<",
  "                                                               ;\",!>;`    ^l>                l:^^::^.   ',ii",
  "                                                              :\"\"I>l\".   ':<                 l,^\"::^.   ':<:",
  "                                                             `,\";ii:'   .^!:                ^;\"^,:,`    `;i^'^' '",
  "                                                             :\"^:!;`    `;+                 l:^^,:\"'    ^!i~_-I `l",
  "                                                            ,:-<>;.    .\"i;                 i:^''`'.  .:<?----- 'i",
  "                                                           ,,^<----<l` `,;                 .^::. ',li-------+i` `l",
  "                                                           ',.,-------->I`.               ',,_[?--------+i\"     .",
  "                                                            `'  `:i+------+>:. `cCCCCCCCCC},^:------+i\"",
  "                                                                     \"l<------<\"I         ^,' ,++i\"",
  "                                                                         `:i--+\":          ,'",
  "                                                                               ,",
  "",
  "",
];
