/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `twist` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                   n  !J",
  "                                                                               ?   a? nJ",
  "                                                                           n   nn  8n 8J",
  "                                                                           nJ` ?8? 8a|8J n",
  "                                                                            ma! 8a`8omqJJm `|",
  "                                                                            `88?mpaa0aQa8|?a?",
  "                                                                           ! ?oQ8zpCt/Oo8m8J",
  "                                                                           nm|mxxq~z_IU[8Xa!|",
  "                                                                            ?8o8[? ;^^,)ib88?",
  "                                                                          |JnmoqJJJJJCQOZ888",
  "                                                                           !m8[           ]Mn",
  "                                                                            n8I `^\"li><~+}|d8`",
  "                                                                            m8\"]tjrnzLQ0OkhM%L^",
  "                                                                           a|npa$$$$BLvXUZo$$$0",
  "                                                                           m{~8+(Cm8$$B\\B$$Mva?",
  "                                                                           |Ci8-~-w$$$vtc@$$%B`",
  "                                                                           `8;8[[c$$$ptjvd8$h*",
  "                                                                            m|8)t/cu\\fxcYJJ8(J",
  "                                                                           _bQ8tt(zQrncXUOL*8xr+",
  "                                                                          1om88xvzLmXzwphwvk8od#+",
  "                                                                         zhLq&80LOqwU0$$$$@cho*8*+",
  "                                                                       `b*h*&&&8kbbO0ZJx0pQL#&&88*~",
  "                                                                        `noBB%8&8WkdmmqQwwd#8&8%B%*~",
  "                                                                      ]uCCCJwBBB%/Qw*8bkhM&8BB@@@qn?",
  "                                                                    (h%8%%BB8YxoB1}[[|rcUQ%@@oJ?          `]]]]]",
  "                                                                   zWWMWBBBaMWWW&1}[[(rcYO%h(??;        !m%%%%BBBJ?",
  "                                                                  t#W*$&W88h#*haMX\\/fxzJCZ**#WoaBBBBoCCO&&WMM&%BBBBon`",
  "                                                                  m#WM$om#OmkmM#%hXYJQOOQM*oM8k*88%%%%#MW*dwd*8%BBBBBBw|",
  "                                                                  h#&8$Qjz1Xftu{YhC0ZJJjhM*&CCZ##pbMM#oMWoqZp*&88%%BBBBB%J!",
  "                                                                  J#&8$@M8MkoaM*#bZqX/ua&M*8uUwMh{ca#hoW&W*o#&8&&88%%BBBBBBon`",
  "                                                                  u*&8$@M88#*MM%&pc(])U$@M*%%oa%%MM88ooW8%%%BB%%88&&88%%BBBBBBw?",
  "                                                                  }*W8B@M&8#*MM%Wm\";Xj($@M#%8k#%%%%%%&oW8B@@@@@BB%%88&&88%%BBBBB%n!",
  "                                                                  ~oW8B$#&8#oMW%Mc!<px\\$8##%Wq%%%%%%%%#M8B@$$$@@@@BB%%88&&88%%BBBBBo|`",
  "                                                                  .aM8B$#&8*oMW%*c_]pun$&#M%Mb%%%%%%%B@&&B$$$$$$$@@@@BB%%88&&88%%BBBBBJ?",
  "                                                                   hM88$M&8*oMW%of{)ptQ$&#W%oh%%%%%%%@@$B%@$$$$$$$$$$@@@BB%%88&&88%%BBBBoC?",
  "                                                                   J#&8$8&8*aMW8hr|fprO$8#&8k*%%%%%%B@$@%Mb(u*@$$$$$$$$$@@@@B%%88&&&88&8%B%k_",
  "                                                                   u#&8$8&8*aM8&bffzpum$8#8&q8%%%%%%@$$B&a|   `\\C@$$$$$$$$$@@@@BB%*WMbpa&BB&o~",
  "                                                                   }*&8$%&8*aM8&prxYOzw$8#%Mb8%%%%%B@$@8*0        !uq@$$$$$$$$@@@W*W*qwa&BB8#0",
  "                                                                   ~oW8$@&8WaM8WZuvJZUp$##%oh8%%%%B@$@%Mk<           `]C*$$$$$$$$*#&&MM&B@@8#d",
  "                                                                   .aW8$@W88hM8#0zXCOL#$#W8ko8%%%%@$$B&oz                !\\q@$$$$W*&%888B@@%Md",
  "                                                                    hM8B$W88hM&*phadpd8$#W&qW8%%%B@$@%#d.                    ]u*@BaW8%88B@@%Mb,",
  "                                                                    JM8B$W88kM&o[:;|\\x&$#8MpW8%%B@$@BWh(                        `\\w#8%8dZw#%Wk>",
  "                                                                    u#&%$W88kM&b{lI;;:w$M8*dW8%%B@$@8*Q                           +*&81^I]\\O&k>",
  "                                                                    {*&M$888kMMw?~~~<<p$#&hhW8%B@$@%Mb:                            w&L+i_(rv*a<",
  "                                                                    ~o&&$%88bW*O~~~~~~pB#WpW&%%@$$B&ar                             tMq1}{\\xvho<",
  "                                                                    .aM&$%88bMkC~~~~~~$%*MpW&%B@$@8*0                              ;*#1{{|rvk#<",
  "                                                                     h#W%@8%d#qz+~~~~~$%o*bW&%@$@%Wk]                               L8x{}(juOd",
  "                                                                     CMW%$8%*oqX())1{}$8ohaW&@@$B&oz                                'Z0{})fuOJ",
  "                                                                     vM8W$&%*kwO00Xzcv$%ap&W8@$@%#d.                                 !k1}1/nC8",
  "                                                                     {#8M$&%oqdu)0wwqh$8hd&WB$$BWh(                                   8/{{\\xc8",
  "                                                                      z88$&%oqp]_[1}{/$&bk&W@$@8*Q                                    JJ{}|rc8`",
  "                                                                       !d$&%abwUrrf\\)X$&pa&8$@%Mb:                                    ?q1}(jvh?",
  "                                                                        u$B%bob%hZzurL$&b8&B$B&ar                                      81}1fuk?",
  "                                                                        u$B8oaXCoB%hZm$8a&W$@8#pY`                                     mc{{/npn",
  "                                                                        u$B%*h)  `[[|q$8*&8@%Wknvwmpn`                                 |p|\\xcZm`",
  "                                                                        {B$8Mb>      }$#&&%B&o0//<|rU0                                 nZI>)frqm",
  "                                                                        +B$8#d>      z$#&&B%#d0Y1r|tuzX                                8v\\||cCm8",
  "                                                                        +W$8*q       0$#&8BWhxn#zYUJYLm>                               nduxnU0an",
  "                                                                      '?QW$&*w       0$M&88#Q  !JMhdpb|                                 |JzXQm/",
  "                                                                    '0MW*M$&op)     )kWWW&&8&r'                                           (pb\\",
  "                                                                   +o#*aka$$od#v  'Q#M#*#M&&8W#{",
  "                                                                  .w**aMMB$$BW8#z]w**adqboW&8&Ma}",
  "                                                                  }a**MZpaoo*##W%#a**kqmdoW888W*k.",
  "                                                                  na#oWh*h?fb(j8)Ua##*hhoM&8%8&MoU",
  "                                                                  ~a##%$$$aa%qa8uwo#WWWWW&&88%8W#a}",
  "                                                                   k*M&$$$$$$$$$B*o#W88&&&&&8%%8W*k.",
  "                                                                   uoMW&WW&BB@B%Whw#W&88&&&&88%8&MoU",
  "                                                                   ;h#W&WWW&8%8W*b}o#W&88&&&&88%8&#a}",
  "                                                                    Z*MWWWW&8%%&#k<+oMW&88&&&&88%8W*k.",
  "                                                                    /a#W&WW&8%%8Mar v*M&88&&&&&8%8&MoU",
  "                                                                    .h*W&WWW&8%8Wo0  v*M&88&&&&88%8&#a~",
  "                                                                     UoMWWWW&8%%&*d   w#W&88&&&&88%8W*m.",
  "                                                                     }a#W&WW&8%%&#k<  'q#W&88&&&&8%8&Mou",
  "                                                                      k*W&WWW8%%8Mar   Io#W&88&&&&8%8&#a~",
  "                                                                      /oMWWWW&8%8WoY    +oM&88&&&&88%8W*m.",
  "                                                                      ;h#W&WW&8%%&*d     t*M&88&&&&88%&Mon",
  "                                                                       Z*W&WWW8%%&#k<     v*W&88&&&&8%8&#a~",
  "                                                                       }oMWWWW&8%8Ma|      w#W&88&&&88%8W*m.",
  "                                                                       .h#W&WW&8%8WoX      'q#W&8&&&&88%8Mon",
  "                                                                        J*M&WW&8%%&*d       IoMW88&&&&8%8&#h;",
  "                                                                        ~aMWWWW&8%8#k>       +oM&88&&&&8%8W*Z",
  "                                                                         k#W&WW&8%8Ma[        {*M&88&&&&&88Wo/",
  "                                                                         /oM&WW&8%%Wox         v*W&8WMMMMW&8WaI",
  "                                                                         ;a#WWWW&&8&*d          C#WWo#adb*W8&#m",
  "                                                                          Z*###**W&&#k:         'q#ao*kwpoW88Ma[",
  "                                                                          }ao*kwd#&8Wa[          'ok*#*o*W8%8War",
  "                                                                          .h*okboW8%Wox           }h*#**M&%B8Wh(",
  "                                                                          {o*akoW8%%&or           +a##**W8%%8#b:",
  "                                                                          w*okaM8%B%Wk;           no##*#W8%%&*Q",
  "                                                                         {o*hk*&%B%&or            Uo#**#&%B%Wh(",
  "                                                                        .a*akaW8BB8#0             k*#**M8%B8Mb:",
  "                                                                        t**hh#8%B%Mb.            .h*#**W8%%&*Q",
  "                                                                       'a*ako&%B%&a[             ~a##*#&8%%Wa(",
  "                                                                       J*okaM8%B8*x              }o#**#&%B8Mb:",
  "                                                                      Io*hh#&%B%MO.              uo#**M8%%&*Q",
  "                                                                      C*okoW%B%Wh<               Z#&%%BBB%Wa(",
  "                                                                     )&%88%8%B8o|               `WB@B@$$@8Mb:",
  "                                                                   'mB%8B$$B&8#0               'k%&ahMB$$%M0",
  "                                                                   b8Wdq*B$@8ob.               Q&8ommo%$$BWk.",
  "                                                                  z&8#dbM@$$8*|               '#8%W*#8@$$BWh<",
  "                                                                 _W8Woo&@$$$8*r               1M8%&W8@$$$BWk<",
  "                                                                'b8&*aMB$$$@8a<               QW%8WW%@$$$BMb",
  "                                                                0&8#a*8$$$$BMU               '#&%8W&B$$$$%#p",
  "                                                               jW8Woo&@$$$@&h;               1M8%&W8B$$$@8*X",
  "                                                              lM8&*aMB$$$$%#Y                qW%8&W8@$$$@&ar",
  "                                                             'b88#a*8@$$$BWk.               I#&%8WW%@$$$BWh] i[`",
  "                                                             j&8MaoWB$$$$8*\\                fM8%&W&B$$$$%Mo%B%@$w'",
  "                                                            ?W&%W*M%$$$$BWb.                qW%%&W8B$$$$%*okdp#$Bq",
  "                                                           l&WphaM@$$$$@8o|                 oW%BBBB$$$@Whqppppp$Bo",
  "                                                           c&%kpppph#B$B&M/i               x8WW@$@&*opppppppboB$%J",
  "                                                           1&@&ppppppppa#%$$#vi           1&&dmqppppppppbo8$$$$#x.",
  "                                                            Y@$$BWobppppppdaW@$Z`         z&%Wppppppbo8$$$$$d/i",
  "                                                             }0W$$$$$8#hppppppk8c.........x&@$&bbo8$$$$$M0{",
  "                                                             ...'((Ok$$$$BWoppb8r\"\"\"\"\"^^^^!kB$$$$$$$$br_..",
  "                                                          ...'''```^^^?|ZZ$$$$$Z!\"\"\"\"\"\"\"\"\"\"\"XW$$$MY(```'''...",
  "                                                             ...''''`````^^i||?^^^^^^^^^^^^^^^`|```''''...",
  "                                                                           .................",
];
