/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `wind_4` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                !!  |",
  "                                                                                            |`  J? `8",
  "                                                                                        m`  |n  aJ mJ",
  "                                                                                        !a` ?8``8J!8n",
  "                                                                                         ma`?8m?8mao??a",
  "                                                                                         !8w!8oax8Lon8| |?",
  "                                                                                       ?| mXq8|8]8<88a!ma",
  "                                                                                        JaJo~*,b\"ftJY88a`",
  "                                                                                      !` mpox+~:\"\"-~m\\q|n`",
  "                                                                                      !m8m8QJJJJJ1\\f|k8a?",
  "                                                                                        J8    `???????za`",
  "                                                                                        8q  ````````^+t8n",
  "                                                                                       n8CI(ttffjrrxxnn8J",
  "                                                                                      |m_$$MW%q0ZwqaB$$*qJ",
  "                                                                                      ?C:aoo$$8t}bB$$$$)/a",
  "                                                                                      `8,kqp8$q|)kB$kL8 Ln",
  "                                                                                       8iM&$$$u](c$$$$8`*!",
  "                                                                                       J(n/cn{1tuYXmwQ8-a",
  "                                                                                      )Md/(X0/tjvQXUCL8cn",
  "                                                                                    lppZkvzQmxnOLOJL0Q8q!!t",
  "                                                                                   YMdmo*LOpZQ$$$$#Z0m8&db#\\",
  "                                                                          !]]]]`   'Z%%%8akdCJOQ*#aLpWhOCd8o;",
  "                                                                        (a%%%BBBh-   lZ%%%88hq0zQZ0pWmOkM&8&Z",
  "                                                                      '0&&&#%BBB%&z    !m%%qYb8#**#pW#&&&88%M/",
  "                                                                      cMWa$MM%%BBBBBBMMUUU8U[]?1fvYXW&%B@@$$@W.",
  "                                                                     _#W#h%M#&8&88%%%Mo#MWWu[]?)jvYX&$$@LC]]",
  "                                                                    'pMMab%B|/ma/LMMqh***M8J(|\\fuYCQ88U??`  !nJoB*C\\`",
  "                                                                    cMW*kbBBaoM*YZMv)L#xXW8bvcXUQOCp*#MW*owZ8888%BBB8r'",
  "                                                                   _#W#hba@B#&8&&8%&#b#JZ&WqLOLm0ChooM%&p%M&W*hoM8BB%Wq.",
  "                                                                  'pWMabhM@B#&8&&8%%%h#o8%#wp0\\rxp*onY**0oMWoqOqo&BB%&*Y",
  "                                                                  cMWobk#8$$#&8&&8%%#a#*%8ku}[fYM$*aZqMQroMW*bpk#8B@B&*d:",
  "                                                                 _#W#kbo&B$$#&8&&8%%Mo*M%W0^ICX/$@*a8%#hkoW&&WW&%B@@B8#b<",
  "                                                                'pWMhbaW%@$$#&8&&8%%a**W%*fl~pjz$&o*%8b&MoM8%888%B@@B8#k)",
  "                                                                cMMobhM%@$$$#&8&&8%%*#o%8b-_fm/m$MaW%#p%8hM&%888%B@@@8Mhj",
  "                                                               _#W*kk#8B@$@$W&8&&8%Bb#*%ML[{CJj&$*a%8k#%%o#&8%888B@@@%Mar",
  "                                                              'pW#hbo&B@$@%$8&8&&8%@h##%on(\\pvn$@**%Md%%%#oW8%8&8%B@@%Waz",
  "                                                              cMMabaWB@$$BW$8&8&&8BMa#&&dftuwuZ$&o&8h*%%B8aM8%888%B@@%Wow",
  "                                                             _#WobhM%@$$B&aB8&8&&8BWo*%MQjrLQza$*a%Wq8%B@$k#&%888%B@@B&*p",
  "                                                            'pW#kk*8@$$@8ox0B&8&&8@o*#%aznvwJU%$*#%ak8B@$$**W8%88%B@@B&*d",
  "                                                            cMMhbo&B@$@8*0 0@&8&&8@a#M&pXzXZJO$B*8WpW%@@$@MoW8%888B@@B8#b>",
  "                                                           _M8&8&8%@$@%#O. 0@&8&W%@b#&#JOhawwh$&*%ok&B@$@%#hM8%8&8%@@@8Mk>",
  "                                                          'b&WM8BB8W@%Mb.  v@W8&WB%h#8h}Il_tO&$*M&bM8@$$B&ab#&%888%B@@%Mk]",
  "                                                          qW*qwo%B%#aWk<   }$W8&W@WaWMQ<>!lII8@#&*dWB@$@8*0/*W8%88%B@@%Whj",
  "                                                         IoWMkhWB@%Mbh<    }$W8&W@MoWkr~~~~<]$8M&do&@$@%Mb:;aW8%88%B@@BWar",
  "                                                         ~o&%88%B@BWh(     }$W8&8$o*#w{~~~~~Y$MW#b#B$$BWa|  kM&%8&8B@@B&oz",
  "                                                          wW8%88B@@8o[     ]$W8&8$a#bQ~~~~~~p$oWboW@$@8*Q   u*&%888%@@B&*w",
  "                                                          {*&%%8%BB%#x     +$W8&%@k*qu-_++~~$%o#d#B$@%Mb:   +oW8%88%B@@8*p",
  "                                                           wW%8p\\rJ#Wd     +$%8&B%hdqnf/|){j$o*kaM$$BWh|     aM888%%BBB8#d",
  "                                                           +*8ZI,_\\cMh     +$%8&@Mhqd*hd0Cvw$h*p#8$B8*Q      J#M&&MM8%B%Mb>",
  "                                                            C&c{}(fuk*<    +$%8&@#dd?  ??nJ$$hhoM$@%#d:      {*MWhmq*8B%Wh<",
  "                                                            I#h(1)tx0M(    ~B%88@abp       $@kbM8@BWh]       1MWopqkM%@B&a|",
  "                                                             L8n11\\rX8:    ~B$8%Bbac      }$&dkM$B&oX       'dWoppaWB@$B&aj",
  "                                                             'kh){(fuo?    ~B$8%%bb>      z$#pW8@%#d.       dWMakaWB@$$BWh]",
  "                                                               at11/npn    ~B$8B8*q       b$ohM@BWh]       z&oUjup8@$$@8*Y",
  "                                                               nO){|rJa    ~M$8%&aj      ^$B*&8B&oX       )W*+`;[/C%$B&on",
  "                                                               `8t1)fu8`   ~M$8%Mb>      }$8WWB8#d.      I#*_,l?\\xz*%Wh~",
  "                                                                nC11/nk?   ~M$88*Q       0$#&8%Wh]       to_,l]tuU08Mm.",
  "                                                                !#){|rQJ'(YbM$8Wh(       &@M&%&oX       `a/,l]tvUZW#u.",
  "                                                                 mJ1)fz8MMMMo$8#d/      ^$BW88#d.      `at,l[tvJwW#}",
  "                                                                 !h(|rX8Mhbko$$*q*u    (OWW&&8WQ'      mt,l[tvJp8ZI",
  "                                                                  8/-)|u#MW%@@$BoWa; _dMM##MW&8&#f    JU:l[fcCbm`",
  "                                                                 ?81t(xJMbChodMW8%BBko#*hdbaM&8&Mou  J0:l[fcCoJ",
  "                                                                  aUxjzOM8&%U}Xq/q8Zho*apmqh#&88W#o{nO:I[fzLoJ",
  "                                                                  `/zzY0a@$$BM&kJ8v/h*#*hbh*W8888WMMb!l}jz0W?",
  "                                                                    >wdbaWB@$$$$$$Mkh*MWMMWW&&8888o[I?|rXOW?",
  "                                                                     bo#MM#M&8BB@BB&h#W&88&&&&&888ttxzncpa`",
  "                                                                     uo#M##M&8%%&*d>m#W&888&&&&&8w\\)xJOUan",
  "                                                                     uo#M##M&%%%&*d,'qMW&888&&&&8zjuLwqka`",
  "                                                                     uo#M##W&%%%W*p  'q#W&888&&&&bOwdkMM/",
  "                                                                     uo#M##W&%%%Woq   'q#W&888&&&&&MW8&Ma+",
  "                                                                     uo#M##W&%%8WoL    'q#W&888&&&&8888W#a+",
  "                                                                     no#M##W&%%8War     'L#W&888&&&&8888W#w.",
  "                                                                     no#M##W8%%8Maj       c#W&888&&&&8888W*m.",
  "                                                                     na#M##W8%%8Mhj        c#W&888&&&&888&W*v",
  "                                                                     na#M##W8%%8Mk<         c#W&888&&&&888&M*u",
  "                                                                     na#M##W8%%8#k>          c#W&888&&&&888&Mo{",
  "                                                                     na#M##W8%%&#b>           c#W&888&&&&888&Ma+",
  "                                                                     }a#M##W8%%&#d             f#W&888&&&&888&#a'",
  "                                                                     +a#M##W8%%&*p              _#W&888&&&&888&#w.",
  "                                                                     ~a#M##W8%%&*q               _*W&888&&&&888W#m",
  "                                                                     ~a#M##W8%%&oL                _*W&888&&&&&&&&#v",
  "                                                                     ~a#M#MW8%%Wor                 _*W&888MMMMM&&&#t",
  "                                                                     ~a#MMW&8%8War                  _*W&8***bphM&8Wo+",
  "                                                                     ~a*MM#W&8W#a(                   _*M#a*apqkM88&*d",
  "                                                                     ~h*odpaW8&*b<                    'paa##ooM&%%&#b>",
  "                                                                     +a*addo&%8#b>                     'mo##*#W8%%&*p",
  "                                                                     C*ohh#&%B8Mb>                      Z*#**#&%%%Woz",
  "                                                                    +o*akoW8BB8#0                       k*#**M&%B8Mk?",
  "                                                                    w*okhM8%B%Wk<                      ~h##**W8%%8#p",
  "                                                                   {o*hk*&%B%&a|                       ~a##*#W8%%&oz",
  "                                                                  .a*akoW8BB8*Y                        no##*#&%B%Wh]",
  "                                                                  t*okh#8%B%MZ.                        uo#**M&%%8#d",
  "                                                                 Ia*ak*&%B%Wh<                         k*#**W8%%&oz",
  "                                                                 C*okaW8BB&or                          h*#*#W8%%Wh]",
  "                                                                +o*hh#8%B8#0                          ~aM8%%BBB8Md",
  "                                                                d888&&%B%Wb.                          (8@BB@$$B&*X",
  "                                                              ?oBBB@$@8%&a~                          -8%Mha&@$@8*[",
  "                                                             -&8odo%$$%*ox                          '#8&kZqMB$$%#Y",
  "                                                            'M8Wbwa%$$BMd                           1M88M*M%$$$%Md",
  "                                                            d88*a#%$$$BMp                           LW%8WW%$$$$%#p",
  "                                                           z&8Ma*8@$$$%#X                          '*&%8W&B$$$$8*X",
  "                                                          -W8WoaWB$$$@&h;                          1M8%&W8B$$$@8or",
  "                                                         'M8&*a#%$$$$%#X                           LW%%&W8@$$$B&a]",
  "                                                         d&8#a*8@$$$BWk.                          '*&%8W&%@$$$BWk<",
  "                                                        z&8WaaWB$$$$8*\\                           1M8%8W&B$$$$%Mb",
  "                                                       lW8&*a#%$$$$BMZ.                           LW%%&W8B$$$@%#p",
  "                                                       zW%Wo*8@$$$@8o[                            *&%8WW%@$$$@8*Q",
  "                                                      !h&%BBB@$$$$%WWLLLL]                      'm8WBBBB@$$$$@&WB@@$$pu'",
  "                                                     l&&dbaaM&&8&W***###W$k.                    08#mbaa*&&&8&Moooo**M@@d.",
  "                                                     f&8kppppppppppppppppb&\\                    #%8appppppppppppppppp%$M~",
  "                                                     1&@&ppppppppppppppho*W}                    #%@Bbpppppppppppppboo$$#;",
  "                                                      U@$$$$$$$$$$$$$$$$$Bx...................  }8$$$$$$$$$$$$$$$$$$$$%t",
  "                                                       t0$$$ZZZZZZ||||||i^^^^^^^^\"\"\"\"\"^^^^^^^^^``)#$$$$$$$$$$kZOOOOj{}^",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^^^i|||'''...",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
