/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `wind_1` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                           >,  ]^",
  "                                                                                       (\"  C! `h",
  "                                                                                   t<  ?u  o1 zY",
  "                                                                                   .hi _h^'B1!@{",
  "                                                                                    /h!~Wf-B)bk:^q",
  "                                                                                     ap_&mm%m$J[*- ^?",
  "                                                                                  lf.|Mm*o*8h&Y$U;Xb",
  "                                                                                   ?axbMh&oW&p8qw$Q:",
  "                                                                                 }?;/oa&#$%&B**#%X~}",
  "                                                                                  1h#oWBBBB8&M*#q#b]",
  "                                                                                   J&$$$$$$$$$$$$Z\\",
  "                                                                                  'M%$$BBB%%%%%8wXji",
  "                                                                                  nMBaUUYXzccvunxnv|",
  "                                                                                 x$d  ;-/Yzvnx{!^ ao[",
  "                                                                                 1B#{~^  <YZ~   ,[MO[",
  "                                                                                 I8WYf-i ?wQ? '!(%@Ci",
  "                                                                                  M&Y'   nwJ\\   .B8z",
  "                                                                                  X%YUrxOQYnfu[]/B#|",
  "                                                                                 'roUQj)UYzx)ft\\(Bh_                                 ```.",
  "                                                                                \"~rknr([vj{11\\(1(Bwil;                           ':,,;:^``''",
  "                                                                               I]|<u|1-[/.   l{1|j/(>;I                       ^^\"!:I_[+;\"^^```'.",
  "                                                                              ,;i:\",>~_(\\()+I_()\\f)<\"\"I^                  ^^\",Ii~!:I~->::::}OdwQu(_'",
  "                                                                                ```^\"l}{}1j)}11\\[!:,,\"\"!'             ^^\",;!<-[}?!,\"\",^^^\"jkM8hwmZ0Qv{!",
  "                                                                    .^^^``'`      '``^-cj[[[[{\\I:\"\"``'.'l         `^^\":l>_][}[-~i!,`'...''mqhawwqqqwmZOQx{!",
  "                                                                   :,;l^``'`\":      .^?ZmqOYnft:^....         `^^\",Ii~-[}[]_>l:\"`I:`.     XCJUXUCQOmwqqwmZOQn{l:i",
  "                                                                  l:l`,I^^``````Ii::::[ZmqOYnft^'         `^^\",;!<_]}}[-~iI,^`'.. ^^.     ixjffrnvcXUCQOmwqqwZQbwLtI",
  "                                                                 I;;i`'l,\":::,,,liIi>;?LLCYuf\\f::,,,I  \"\"\",:l>+?[}}]_<!;\"^''..       ...   '>_}{)(/fjxucXUC0ZQwhCXxr,",
  "                                                                ,I:l~l jmf\"nU?lv/iI{I`;txj/({(+!>!:l<,;,;i~-]}}[?+>l:\"`''..        .^          .:;>+{1)|tjxuvxZcJXvr(.",
  "                                                                l:I<+l <>I\"}?~+r|<tL(^!()}[{f-I!i;\"<<!;;>]{}]-~iI,^`'...        .`.                   ^:>+{1)xct\\(|{].",
  "                                                               I;;i+<I ,:\"^,\"^^^I!I>,\"<{?(Lc\\;I?Zx:j/!;:!+-<!;,^`'..         .`'                            `[({?-+;'",
  "                                                              ,;:!~~l\" \";\"^\"\"^^^;!II`,_rzQU| .I!!;I1_!:\"\"::\"^`'..         .''                                  ``.",
  "                                                              l:I<+i,` 'I\"^\",^^^;!I;`;)%M|zU `Il^\">!l!:^`'''..         .'`",
  "                                                             I;;>+>;^'  I,^\",^^^!!I:^lu#h-vr ,lI`,?^\"i:^'..          '^",
  "                                                            ,;;!+<I^'.  ;,^\",\"^^>lI,^iLbO-C| \"l;`I+^^,;\"'         '`.",
  "                                                            I:l~~!\"'. . ,:^\",\"^`>lI,\"~LZc[Y[ ;l,^>i^^'`\"'      .`'",
  "                                                           I;I<+i,`. .` `:\"\",\"^`ilI^:?QCj)cl I!`,-\"^`'..`^`",
  "                                                          ,;;i+>;`.  ',`.;\"^\"\"^`ilI`I\\UY)\\nI Il`I+^^'. '\"!+",
  "                                                          I:!~~I^'. '\"!! ;\"^\",^'!II^!fzv}/j .II^>>^`...`;~:",
  "                                                         I;I<+!\"'. .^l~  :\"^\",^'!I:\"<rux-f/ .I,,-,^'. '\"!_",
  "                                                        ,;;>+i,`. .^I_   \",^\",^'!I:,_xjf}\\{ ,l^I+,`. .`;~:",
  "                                                        I:!+<;`. .`;~^   ',^\",^.iI,;)OQvn1< \"l^i>,'. ',!_",
  "                                                       ;,\"::,^'  `:<`     :\"\",^.+I,luM#*oav :;,_;\". .^;+",
  "                                                      \",,:,`'^:'',>I      :\"^,^.+I,<O*#MMM] I,;-:`. ',i<",
  "                                                     ';;+[<,'`:>\"!!       \"\"^\"^.+I:]qkkkha- I,i+:. .^I+.",
  "                                                     !;;<+l^'',><l        ^\"^\"`.~;!{kkkkkk!`l:_l\". ',i~",
  "                                                     >:\"^\"^`.'\"!_          ,^\"`.~;_xkkkkkk `l;-;` .^I_.",
  "                                                     \"I\"`^\"`'.^I>          ,^\"'.<l]Ybkkkkk ;li~;..`,>i",
  "                                                      i:^^\"]-+:;+        ' ,^\"'.<<?cQ0OZmx !l+l, .^I_",
  "                                                      \"I\"[mab0Y{<        . `\"\"''<??tfjxnu1 !!_:`.`:>I",
  "                                                       i_po8aQzx[,        .'\"^',~_~\"I~~~?l +><; .\"l-",
  "                                                       ,}OZmOUvx)l        ` \"^'I-+>        +_I\".`:<l",
  "                                                        iCL00Jcnj>        I \"^'I?+^        >_,`'\"l?",
  "                                                        \"/LQOLXuj<        ^ ,^'I~-        .!>:'`:<:",
  "                                                         ;CQ00Uvr~        ; `^'I!]        `i;\"'\"l+",
  "                                                          \\L0OCcx\\        ^''^`,>i        ,i,^`;~:",
  "                                                          ,LQOQXnj        '^ \"`;~:        \":,`\"!+",
  "                                                           rL00Uvr!        ; \"^I_\"        ;,\"`;~:",
  "                                                           !LQOCcx?        i ^\"l?         I,^\"!_",
  "                                                            zQOQXnj      .'> ',i~         I,^;+",
  "                                                            _L00Uvr;   \";;Ii' :<_       `::,,\"I.",
  "                                                             CLQYxf_  lll<+~   <>!,   ;;;II;:,\",I^",
  "                                                             )mbOYXc[,ill;,`''.`\"^;  ill>++iI,\"\":!;",
  "                                                             ZwCLXf/t~!!;_|<>1~!lI(n>!li-[]~l,\"\":I>^",
  "                                                             [zvXu\\1[~!l:,:^r0t{q0dp<!l!<+~!;\"^^\":l<",
  "                                                              <\\rj(}\"~!I;.  ','^_uXf<l;;;I;:,\"\"^^,;!>",
  "                                                               \"??_! ~!I;,'.     '~+<l;,\"\",,,,\"\"^\",IiI",
  "                                                                     +!I;II;,^`^^,!'ll;,\"\"\",,,,\"^^\":I>'",
  "                                                                     +!I;II;,^`^:l_  lI:,\"\"\",,,,\"^^\":l<",
  "                                                                     +!I;II:,^`^:!-   lI:,\"\"\",,,,\"^^,;!!",
  "                                                                     +!I;II:\"^`^:!?    iI:,\"\",,,,\"\"^\",Ii,",
  "                                                                     !!I;II:\"^`^:i_    .!I:\"\"\",,,,\"\"^\":I>'",
  "                                                                     ;!I;II:\"^`\";i!     .!;:\"\"\",,,,\"^^\":li",
  "                                                                     IiI;II:\"^`\";>i       !;,\"\"\",,,,\"^^,;!;",
  "                                                                     IiI;II:\"^`\";<>       `!;,\"\"\",,,,\"^\",;i^",
  "                                                                     IiI;II:\"^`\"I<`        :l;,\"\"\",,,\"\"^\":I>",
  "                                                                     IiI;II:\"^`\"I~^         :l;,\"\"\",,,\"\"^\":li",
  "                                                                     IiI;II:\"^`\"I+^          :l:,\"\",,,,\"^^\";!I",
  "                                                                     IiI;II:\"^^,l_            ,l:,\"\",,,,\"^^,;i.",
  "                                                                     IiI;II:\"^^,l-             !I:,\"\",,,,\"^\",I<",
  "                                                                     IiI;II:\"^^,!?              lI:\"\"\",,,\"\"^\":l>",
  "                                                                     liI;II:\"`^:!_               lI:\"\"\",,,\"^^\";!,",
  "                                                                     ^iI;II:\"`^:i!                lI,\"\"\",::,,,,:i'",
  "                                                                     'iI;II,\"`^:ii                 !;,\"\"IIIlI:,\":l",
  "                                                                     'iI;;:,\"^\":>>                 .!;,!!!~?+l,\",l!",
  "                                                                     '>l;II;,\";l<`                   !I<l!+-~I,^\"I<",
  "                                                                     '>li--i:\",l+^                    >>lIll;,^`\";<`",
  "                                                                     .il>_+l,^\"I+\"                    ^>IIll:\"^`\"I+^",
  "                                                                     il!<<I,^`\"I_                     ^iIIlI:\"``,l-",
  "                                                                    `!l>~!:^``\"l+                     IiIIlI,^`^:i<",
  "                                                                    !li~>;\"``^;+                      I!IIlI,^`^:>l",
  "                                                                   \"!!<<l,^`^:>,                      ;!IIl;,^`\";~^",
  "                                                                   >l>~i:^``\"!l                       >!Ill;\"^`\"l-",
  "                                                                  l!!<>I\"``^I<                        ~lIll:\"``,!<",
  "                                                                  il><l,^`^:<                         <lIll:\"`^:>l",
  "                                                                 Ili~i:^``,iI                         <lIlI,^`^;~^",
  "                                                                ^!!<<I\"``\"l>                         '>;\"^`''`\"I_",
  "                                                                :\"^\",\"^`^;>                          .,''`'. .\"l<",
  "                                                               ''`'. .\"^,>`                          \"^:>~I`  `;l",
  "                                                              \"\"i_i^  ^l!!                          :,\"![[i^  ':<",
  "                                                             ;\":+]>^  `I~                           l,^,II^.  ':>`",
  "                                                            :\"\"l>I^   `;-                           I\"`\",\"'   ':<^",
  "                                                           \",\"I>!\".   `l<                          ^;^`\",^.   `:~^",
  "                                                           :\":ii:'   .,<                           ;:^^,,`.   `;+",
  "                                                          ;\",!>I`    ^ll                           l,^^,,`    ^I_",
  "                                                         ;,\"I>!\".   ':~                            I\"`^,\"'    ^I-",
  "                                                        \",\":ii:'   .\"!;                           :;^`\",\"'   .\"l?",
  "                                                        ;\",!>I^    `;>                            l:^^\",^'   .\"!<",
  "                                                       ,:^:!!\".   .\"i,                            !,^^,,^.   ',!!",
  "                                                       \",`'``.    `;:                            '\":`'``'    ',:`...",
  "                                                      ,,_+>i;,,\",:!lllII;.,                     ,\"l[+>il,,\"\",;!!!!!!;..:",
  "                                                     ^,^~----------------+,:                    I^\"i-----------------^.;'",
  "                                                     ',.,--------------<il:cCCCCCCCCCCCCCCCCCCCCl^.'+-------------+ii..I",
  "                                                      `'                 '^                      \"                    `\"",
  "                                                                                                  .",
  "",
  "",
  "",
];
