/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `wind_3` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "                                                                         +(u}",
  "                                                                        ]r\\vLY!",
  "                                                                       JmuuY0ZM?",
  "                                                                       8(L0mp0OJ",
  "                                                                       aYv0wQLon",
  "                                                                       `81I_/z8",
  "                                                                        8}[)rc8`",
  "                                                                        8}[)jvh?    |",
  "                                                                        8}[1fvh|m  |J   J`",
  "                                                                        8}[1fuOa8  aJ  Jn",
  "                                                                        8}[{tuO88?|8? J8`",
  "                                                                        8{[{/nz8onao?J8n",
  "                                                                        8{[}/nz8Q8q*aq8``J!",
  "                                                                       f8{[}\\xchbW]8CUJn8?",
  "                                                                       a8{[}|xch#u>J+8oan !|n",
  "                                                                       a8{[}|rcZWni^jj0aJ88|",
  "                                                                      .o811)/nzmWqQO0d88oJ`",
  "                                                                      ~o&0xuzJQ#Wb:   :waJJ`",
  "                                                                      +*&8*dda&%Wh|>>+(d8J`",
  "                                                                      +*&8&&%B@B&oOCLQLb8|",
  "                                                                      }*&8&&%B@@8*wW8$$a}b!",
  "                                                                      u*&88&%B@@%#p%8WMJIk?",
  "                                                                      {*&%BB@@$@%#qBB%8bn8",
  "                                                                      .p&B@$$$$@8aaBBBB%&bl",
  "                                                                       'WB$$$$$BM*%%%BBBB%&Ol",
  "                                                                     .Q)vL%$$$@%%B%%%%BBBBB8W0'",
  "                                                                    .wk&zzQ#%B@@@@BB%%%%BBBB%8Wr'",
  "                                                                    wkOWdOqdw8%@@@@@B%%%%%BBBB%8Wr'",
  "                                                                   ckOo&MoooLz*%B@@@@BB%%%%BBBBB%&b)",
  "                                                                  cMkM8&&&&%#m0h8B@@@@@BB%%%%BBBBB%&b)",
  "                                                                 `]C@@BB%%%%}Ymb8&%B@@@@@B%%%%%BBBB%8&Ol",
  "                                                             i]`     !\\C@@B&}[?[\\xp8B@@@@@BB%%%%BBBBB%8Wc",
  "                                                          |w%%BBBJ!   -??m%&}[?}\\nzZ#%B@@@@@BB%%%%BBBB%&*n",
  "                                                        lk&&88%BB%BB%%hMoaa*\\\\tjuXCJhW8B@@@@@BB%%%%%B@B&#b:",
  "                                                       '*WW%#8%888&&&Wh#Mao%pXYJQZQOMMa*%B@@@@@BB%%B@@B8#b<",
  "                                                       LMW#$MM&WaawhhZQ*ajw%*QQZXUjZMM{z*8B@@@@@@BB@@$B8#b>",
  "                                                      1#W#h&$q]z8v|Oo(zdbzO%#ZOm/Xw$MM*W&a&%B@@@@@$$$$B&*p",
  "                                                     '*WMaba$ophB&#W88%bMW&%#qpt)/Z$8WW%Wq%&8B@@$$$$$$BWh|",
  "                                                     LMWobk*@$#&%%%8%%%o#WW%Mv\";pft$&WW%Wq%%&&B$$$$$$@8*/",
  "                                                    1#W#kbo&B$WW%B%8%%%**WW%MJ!>Lr|$@WM%Ww%%%%%@$$$$$%XI",
  "                                                   '*WMhbaW%@$$M8%%%%%%WaWW%Ww-?Uc/@@MM%Wm%%%@$@%Wa[i",
  "                                                   LMMobk#8@@$$W&%B%8%%%kMW%Wq{1CLjo$MM%Mq%%B@$B&oz",
  "                                                  1#W*kk*8B@$@$$M8%%8%%%o#W%Wp|\\XQx*$MM%Mk8%B@@BWh(",
  "                                                 '*W#hbo&B@$$B&$W&%B%8%%#*W8&dfjX0vm$&M%Mk8%B@@%Mb>",
  "                                                 LMMabhW%@$$B&o#$W8%%8%%&aW8&bxnUwXq$8W%#b8%@@@8#p",
  "                                                1#Wobk#%@$$@8*0.&8&%%%8%BkM&&kccYpUO$%W8#b8B@$B&oL",
  "                                               '*W#kb*8B@$@%#O. t$W8B%8%B*M&8kYYUmL0$@W8#d8B@@BWaj",
  "                                               LMMhbo&B@$@%Mb<   &B&%%%8BM*W8hdaqpdb$@M8*d&B@@%Mk?",
  "                                              1#WobhW%@$$BWk<    t$W%B%8B&aW8a((((((h$M8*p&@@@8#d:",
  "                                             '*W*kk#%@$$B&a[      &B8%%%B@kW&h[:::,,w$#8*p&@$@8*w",
  "                                             LW&&WM8B@$B&or       t$&%B%%@*M&k)~~~<<x$W&oh&@$B&ar",
  "                                            )&8&8%B%8B@8*x         &B8%%8@**Wbc~~~~~n$WWo*&@@%Wk)",
  "                                           I#Whqh&BBWa%#0          t$&%%%BWoWpc~~~~~}$W#o*&@@%Md>",
  "                                           CMMkqa8BB&aaO.          .$B8%%B@kMwz~~~~~~$%*ao&$@8*q",
  "                                           hM88&8B@@8*q.            v$&%%B@a#qY{{1)((W@hao8$B&oC",
  "                                           t#8%%8%@@%#Y             .$B8B%@*op0czXYLO&$kho8@BWhj",
  "                                           .o&%%8%B@BWb              m$8%%@MhwdJJJJJ|Q$hka%@%Mb>",
  "                                            tM8%8OZw#&h>             I$@%B@Bbqw      }$Mba%@8#p",
  "                                            .o&8t^l{fa#[              m$8%BBhbw      }$&ba%B&ow",
  "                                             tMw[-}/x0Wx              {$@%B@obq       $Bk8%B&aj",
  "                                             .o8t11\\rv8q               h$8%B#dp       $@*8%%Wk?",
  "                                              tWO){(fuoJ               t$@%B8#p       b$M8%%#d>",
  "                                              .d#(1)tnmn               .&$8B8#d:      0$#&%8*q",
  "                                                mC)1\\rJa                t$@%%#d>      z$#&%&oz",
  "                                                !#){(fuM`               IW$8%Mb>      }$8&%&a(",
  "                                                 mn11/nk|                C$@%Mb>      }$WWW&&8hx'",
  "                                                 |h){|rQJ               lXM$8Mk/     IpMM##MW&8&Mf",
  "                                                  an1)fu8             'zMMa$$Wkob_  Io#*hbbaM&8&W*u",
  "                                                  |O)1/no?           'q#*hbW$$&d8M|]mo*apmwk#&88W#h}",
  "                                                   8t1\\nkn           Jo*o#%%%88&WM8Mh*#*hbkoW8%8&MoZ.",
  "                                                   JO)|)ca|          ko*MbLpZYOZ|dm|h*MWMMMW&88%8&#a/",
  "                                                   JX}/jXC8          k**WW*&L\\Cavkpzh*M&8&&&&&8%%8W*k;",
  "                                                   nmr\\rU0q          bo#M@$$$%$$$$@Ba*M&&8&&&&88%8&MoU",
  "                                                   `XUccCO[          uo#W8$$$$$$$@%0]w*W&88&&&&88%8W#h[",
  "                                                     !QZpQ           na#WWMM&8%%8Mhj +a#W&8&&&&&8%%&M*Z",
  "                                                      .++            }a#WWMM&8%%8Mhr  {oMW&8&&&&88%8&#a\\",
  "                                                                     ~h#MWMMW8%%8Mhr   v*M&88&&&&88%8W*k.",
  "                                                                     .k*MWMMW8%%8Mar   .w*W&88&&&&8%%&MoY",
  "                                                                      k*MWMMW8%%8Mar    Ia#W&8&&&&88%8&#h~",
  "                                                                      ZoMWMMW8%%8Mar     {oMW&8&&&&88%8W*Z",
  "                                                                      uoMWMMW&%%8War      v*M&88&&&&8%8&Ma}",
  "                                                                      /a#WMMW&%%8Wax       w*W&8&&&&88%8W*k.",
  "                                                                      ~a#WMMW&8%8Wox       'a#W&8&&&&8%%&Mon",
  "                                                                      ~h#WWMM&8%8Wox        +oM&88&&&&8%8&#h;",
  "                                                                       k*MWMM&8%%Wox         v*M&8&&&&88%8W*U",
  "                                                                       b*MWMM&8%%Wow          m*W&8&&&&8%%&Ma}",
  "                                                                       UoMWMM&8%%Wow          'w#W&8&&&&8%8W*m.",
  "                                                                       noMWMMW8%%&ow           +oM&88&&&88%8Mo/",
  "                                                                       }aMWMMW8%%&*q            t*M&8&WWWW&&&Mh;",
  "                                                                       ~a#WMMW8%%&*q             C*W&W#M**MW8&#J",
  "                                                                       ;h#WMMW8%%&*q             .w##a*aqqhM88Ma~",
  "                                                                        k*WMWW&88&*p              Ioho#adboW88WoX",
  "                                                                        Z*#M##W&8Mop               {hoMM##W8%%&ow",
  "                                                                        ua*appo&8Wop                JoMM#M&8%%Woz",
  "                                                                        v**kpb#&%&*p                uoMM#M&8%%War",
  "                                                                       +o*hdhM8%B8#p                uoMM#M&8%8Mh(",
  "                                                                      'q*abk#&%BB8*z                uoMM#M&%%8Mk<",
  "                                                                      C*obb*&%BB8#Z.                uoMM#M&%%8Mb>",
  "                                                                     {*okboW%BB%MZ.                 uoMM#M&%%8#d",
  "                                                                    Io*hbaW8BB%Mk.                  uoMM#M&%%&#p",
  "                                                                   'q*abhM8%B%Wh<                   uoMM#M8%%&*Q",
  "                                                                   v*abk#8%B%Wh~                    noMM#W8%%&or",
  "                                                                  {*obb*&%B%&a~                     noW8%B@@BWaj",
  "                                                                 '*W#ko&%BB&o[                      u&BBBB@$@8o<",
  "                                                               `u*@@$$B8BB8*x                      'k%&hb#%$$BWt",
  "                                                              'h%W*MB$$%#&*n                       Q&8*wma%$$B&h;",
  "                                                             'b8WbOb8$$BMhn                        o&%8MM8@$$@&a<",
  "                                                            'b8&obaW@$$BMd                         *&B%88B$$$@&a<",
  "                                                            Y88*ba&@$$$BM0                        +#8B%8%@$$$@&a]",
  "                                                           X88*khWB$$$$%*[                        _M8B%8%@$$$@&aj",
  "                                                          X&8#kkMB$$$$BMU                         fM8B%8%@$$$@&aj",
  "                                                         X&8Mkk#%$$$$BWm.                         cW%B%8%@$$$B&aj",
  "                                                        )&8Mhb*8$$$$@&a~                          LW%B%8%@$$$B&ar",
  "                                                       lW8Wabo8@$$$$%*/                           o&%B88%@$$$B&ar",
  "                                                       zW%Wao&@$$$$BMZ                            *&%B88%@$$$B&ar",
  "                                                      !h&%BBB@$$$$B&WwLLL]                      'm8WBBBB@$$$$B&W%@@$$pu'",
  "                                                     l&&dbaaM&&8&W***###W$k.                    08#mbaa*&&&8&Moooo**M@@d.",
  "                                                     f&8kppppppppppppppppb&\\                    #%8appppppppppppppppp%$M~",
  "                                                     1&@&ppppppppppppppho*W}                    #%@Bbpppppppppppppboo$$#;",
  "                                                      U@$$$$$$$$$$$$$$$$$Bx...................  }8$$$$$$$$$$$$$$$$$$$$%t",
  "                                                       t0$$$ZZZZZZ||||||i^^^^^^^^\"\"\"\"\"^^^^^^^^^``)#$$$$$$$$$$kZOOOOj{}^",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^^^i|||'''...",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
