/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `wind_2` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "                                                                                                                             ;I\"",
  "                                                                                                                         nq0j1rJ)",
  "                                                                                                                        JO_j|xJmj",
  "                                                                                                                       ?o?1UC0qdY",
  "                                                                                                                     `J0i,1cmqqon",
  "                                                                                                                    ?q|^l}fcmk#n",
  "                                                                                                                  `J0i\"<)xYmk?",
  "                                                                                          `                      |o}^;-/uJpa`",
  "                                                                                  n   |  `J   n               !\\mY:^!}fcLhJ`",
  "                                                                                  m?  8  nJ  Jn             'Y8o}^,+(xXQoJ",
  "                                                                                  na`?8!`8J ?8!            (W8U:^I]/uUZW?",
  "                                                                                  ?8J?8nn8J?8m           lb&*{\"\">{fcCwk?",
  "                                                                                !! 8oJomaqJao!`n`      'OWMWX~!_(rzLd&~",
  "                                                                                 anmr8r8CO8(a?aJ      rWW*daO|\\fuYQhWO",
  "                                                                               n`|o8jU1Z_w1d8aJ !nn  dWMhwmb8ZXUQmo&w.",
  "                                                                               ?8m8|XI+_:i[mn8Ja8|  t#WhmwhW%%%*M8Wc.",
  "                                                                                J8wt[?]})<~iOc0a`   mM&Mo*&B@$$$BMv",
  "                                                                               ?8[???]]]nJJJJJ8JJ?  kM8%BB@@$$@%Mv",
  "                                                                               a8           ^|8m`  .h#8B@$$$$@%#U",
  "                                                                              ?8C^[((|||||||\\f8J   +o#&B$$$$$%#kf",
  "                                                                             |m)$@*ahhhhhhhhoo%a!  t*W&8$$$$B&Mht",
  "                                                                             ?JIoo$$$m++zhW$$$j)a  J#&&WW8@@@%Wk?",
  "                                                                             ?w;8xq8$axfM$$kZ% Yn  hM&&MW8B@@%Mk<",
  "                                                                              8;M@$$$n?1O$$$#8\"#! ;aM&WMW%B@@%Mk>",
  "                                                                              8}xjw0\\{|cxq#Mq8[a  }oW&WM&%@@@%Mb>",
  "                                                                            _phY(/UY\\/rzJzYJ08Yx  u*W&WM&%@@@%#b>",
  "                                                                           _ob8Qnz0Crxv00JLQqo8#+ m#&&WM&%@@@8#d>",
  "                                                                          ca0p&mLZpCk$$8kmO0d888#{aM&&WW8B@@@8#di",
  "                                                                         zkQdW&MbkwYUba$$kOwW*W88*oM&&MW8B@@B8*pi",
  "                                                                        z&*B%8&&&8*wOXvQLQp8&&&8%**W&WMW8B@@B8*p,",
  "                                                                         `\\oBB%%8%YbWobdhM8&8%B@@**W&WMW8B@@B&*q",
  "                                                               `nw%BB*J!    !uoBB8[]-uYLOUbB@@BJ?h#&&WM&%B@@B&oq",
  "                                                              r&8&8%BBB8Z]](YUUh8b[]-}/nXUh%aU  ;aM&&WM&%B@@B&ow",
  "                                                             cMW&MW%%%%%%%%%hM***m111|jcUUkMMMWbWoM&&WM&%@@@BWow",
  "                                                            _#W#&$*&8WWWWWWWkM*oW&vxuzUQQQ#hhMWqo*W&&MW&%@@@%Wam",
  "                                                           'pMMoh$*fU#ktLaLrmMuCW&pJ0ZmOUoMhqW#mh#W&WMW8B@@@%Wam",
  "                                                           cMW*kb$&QwWa0pMmJwMYQ*WqQZrjj0#MctOo[h#&8&W&8B@@@%WaZ",
  "                                                          _#W#hba%$#&%%88%%%o#MW%WwdQ+xp$&M##8hbk#&%BBBB@$$@%Mhc",
  "                                                         'pWMabhM%$#W%%88%%%a#MW%MU~:pjC$&MM%&d%##&%@@@$$$$@%#b?",
  "                                                         cMWobk*8B$8M8%88%%%a*MW%#u;iprU$&MM%Wp%8*W%@$$$$$$@&ox",
  "                                                        _#W#kbo&B@$$#8%%88%%#*MW%*u<_pjC$&MM%#b%%%&%@$$$$$$%Mt",
  "                                                       'pWMhbaW%@$$$W&%%88%%MoMW%or]{p/L$&MW%oa%%B@@B@$$$$ox'",
  "                                                       cMMobhM%@$$@$BW8%88%%MoMW8aj)|pj0$&M&8ha%%@@@%Wk]",
  "                                                      _#W*kk*8B@$@%B$M8%88%%MaMW8hx/fpnZ$&M&&dM%B@$@8#p",
  "                                                     'pW#hbo&B@$@BWo$&&%%88%@hMW8kxrXpcm$8M&Ww8%B@$B&aj",
  "                                                     cMMabaW%@$$B&arbBW%%88%@kMW&dnuUpYq$8M%Mb8%@$@%Mb>",
  "                                                    _#W*bkM%@$$B&ox t$W8%88%@bMW&pczCZCd$8M%*b8B@$@8*Q",
  "                                                   'pW#kb*8B@$@8*Q  ^$&8%%8%@kMWWwZLJQ0h$8M8aa8B@@BWh(",
  "                                                   cMMabo&B@$@%#O.   0B&%%8%@*#WMUxQ00M&$8W&b#8@$@8#p",
  "                                                  _#&Mo*WB@$@%MZ.    }$W8%8%@o#&#u::,,,/$8&WqW%@$B&az",
  "                                                 'b888%B%8@$BWk<      $88%88@a#&av<>ii!f$&&MkWB@@%Mb?",
  "                                                 zW#bkWBB&*%Wh<       0@&%%8@M*Wbv~~~~~n$WW*pW@$@8*q",
  "                                                {#WawdMB@8*ka[        \\$&%%8@WoMq|~~~~~n$WWaaW@$BWh(",
  "                                                u#&&W&%@@%#px         I$88%8@Wo#m(~~~~~n$MMko8$@%#d:",
  "                                                }*&%%8%B@BWk           *@8%8BMaaw\\?----u$##q&%$B&oz",
  "                                                 wW%%8%B@B&a<          Y$&%%B%hbqnrjjjfL$o*d&B@%Mk?",
  "                                                 }*&%88Zw88*|          +$%8%B@hqqaaaaahM$Mad&@@8*q",
  "                                                  CW8O,:?\\bWY           %$8%B@bqw      }$#ko&$B&aj",
  "                                                  I*8)+-(rv8b           O$&%BBpdm      }$8d*8@%Md:",
  "                                                   C&z){(juoa:          {$B%BBkkr      }$8q8%B&oL",
  "                                                   I#h(1)tnm#,          IB$8BBkaj      }$8d8B%Wk]",
  "                                                    z8n11\\rJW            p$8%Bhhf      }$8a8B8#p",
  "                                                     xq){(juM`           u$B%%Wk]      }$8#8B&ac",
  "                                                      at11tnk|           +%$%%Mk>      }$8&8%Mb>",
  "                                                      nO)1\\rQJ           .#$8%Mb>      }$8&88*Q",
  "                                                      `8(1(ju8            C$B8#d>      }$W&%Wh(",
  "                                                       nC11/no?         lxq%$8#p       \\%W&&&8m('",
  "                                                       !#){|rZn       'QMM*#$%*qb_   'QMMMMMW&8&Mf",
  "                                                        mz1(j0a      'q#*hda$$BwWo{ 'q#*abbaM&8&W*u",
  "                                                        !#r1fraJ     Jo*oW&%%%BBBBBBho*admwk#&88W#h}",
  "                                                        ?b~)jczo?    ko*MpLbwCwbLh80ko#*kdboM&%8&MoZ.",
  "                                                        ?kj\\\\zLb?    k**W&W8X|C01oU/h*MMM#MW&88%8&#a/",
  "                                                         nUcvY0z     k*#W@$$$&B$&%Mph*M&8&&&&&8%%8W*k;",
  "                                                           cQmp?     k*MM&@@$$$$$$$$**M&88&&&&88%8&MoU",
  "                                                           .{t;      k*MM##W&%%%&*di'w#W&88&&&&88%8W#h}",
  "                                                                     boMM##W&%%%W*p  +a#W&8&&&&&8%%8W*Z.",
  "                                                                     boMM##W8%%%Woq   {oMW&8&&&&88%8&Ma/",
  "                                                                     boMM##W8%%8Wow    v*M&88&&&&88%8W*k;",
  "                                                                     boMM##W8%%8War    .w*W&88&&&&8%%&MoU",
  "                                                                     boMM##W8%%8Mar     'a#W&8&&&&88%8&#h}",
  "                                                                     UoMM##W8%%8Mhj      +oMW&8&&&&88%8W*Z.",
  "                                                                     uoMM##W8%%8Mk]       v*M&88&&&&8%8&Ma/",
  "                                                                     uoMM##W8%%8#k<        C*W&88&&&&8%8W#h;",
  "                                                                     uoMM#MW8%%&#b>        'w#W&8&&&&88%8WoU",
  "                                                                     uoMM#MW8%%&#d:         +oMW&8&&&&8%8&#a[",
  "                                                                     uoMM#MW8%%&*p           {oM&88&&&&8%8W*Z.",
  "                                                                     noMM#MW8%%&*q            v*W&8&&&&88%&Mo/",
  "                                                                     noMM#MW8%%&ow            .w#W&8&&&&8%8&#h;",
  "                                                                     noMM#M&8%%Wox             Ia#W88&&&&8%8W*U",
  "                                                                     noMM#M&8%%War              +oM&88&WWW&&8Wa[",
  "                                                                     no#M#M&8%%Waj               v*W&&#M#*#W&&Mm.",
  "                                                                     \\a#MMW&8%8Mh]                w#Ma*opwk#&8Wo/",
  "                                                                     +a#M##W&8M*k<                'qaa#obdaW8%&*d",
  "                                                                     +h*appoW8&*d>                 +ba#M##W8%%&#d",
  "                                                                     {o*hdb#&%&#d                   no#M##W8%%&*p",
  "                                                                     w*okh#&%B8#p                   no#M##W8%%&oL",
  "                                                                    to*hk*&%BB8*X                   no#M#M&8%%Wor",
  "                                                                   .a*akaM8%B8Md.                   no#M#M&8%%Waj",
  "                                                                   t**hh#&%B%Wh<                    no#M#M&8%8Mh<",
  "                                                                  Ia*akoW%BB&ox                     no#M#M&%%8Mk>",
  "                                                                  C*okaM8%B8#0                      noMM#M&%%8#d",
  "                                                                 Io*hk*&%B%Wk:                      +oMM#M&%%8#p",
  "                                                                 w*okoW8B%&a[                       +oMM#M&%%&*Q",
  "                                                                {o*hhM8%B8*n                        +oW8%BB@B&or",
  "                                                               .d888&8%B%MZ.                        _&BBBB@$$%*j",
  "                                                              ?oBBB@$@8%&h<                        'k%&ab*%$$BWv",
  "                                                             -88ado%$$%#o|                         j&8#qmh8$$@&a;",
  "                                                            lM8Wbwa%$$%#Y                          o&%8MM8@$$@&o|",
  "                                                           'd8&*aM%$$$BMq                          *&%%88B$$$@&aj",
  "                                                           X&8Ma*8$$$$%*x                         I#8B%88B$$$@&aj",
  "                                                          -W8WooW@$$$@&h;                         +#8B%8%@$$$@&aj",
  "                                                         'M8&*aM%$$$$%*\\                          1M8B%8%@$$$@&ar",
  "                                                         d&8#a*8@$$$BWk.                          cM%B%8%@$$$@&ar",
  "                                                        z&8WaoWB$$$@8o|                           LW%B%8%@$$$@&ar",
  "                                                       lW8&*a#%$$$$BMZ                            o&%B88%@$$$B&ar",
  "                                                       zW%Wo*8@$$$@&a[                            *&%B88%@$$$B&or",
  "                                                      !h&%BBB@$$$$%MWLLLL]                      'm8WBBBB@$$$$B&W%@@$$pu'",
  "                                                     l&&dbaaM&&8&W***###W$k.                    08#mbaa*&&&8&Moooo**M@@d.",
  "                                                     f&8kppppppppppppppppb&\\                    #%8appppppppppppppppp%$M~",
  "                                                     1&@&ppppppppppppppho*W}                    #%@Bbpppppppppppppboo$$#;",
  "                                                      U@$$$$$$$$$$$$$$$$$Bx...................  }8$$$$$$$$$$$$$$$$$$$$%t",
  "                                                       t0$$$ZZZZZZ||||||i^^^^^^^^\"\"\"\"\"^^^^^^^^^``)#$$$$$$$$$$kZOOOOj{}^",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^^^i|||'''...",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
