/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `wind_4` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs` from `design/gen.js`; change the generator, not
 * this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                >,  (",
  "                                                                                            |   J! `p",
  "                                                                                        L.  ((  a1 d\\",
  "                                                                                        Im  _k 'B)i%-",
  "                                                                                         JZ ~Wf-BtMb:[Q",
  "                                                                                         :oQ:WmZBw$Jt&i t~",
  "                                                                                       -} z#C*ok%a&Q$n>dX",
  "                                                                                        xwjk#k&h88d8mo@n",
  "                                                                                      i. u*hMo$W88#oWMr(r",
  "                                                                                      \"YoC*&BB%%8%WoWm8w;",
  "                                                                                        rW$$$$$$$$$$$$h/",
  "                                                                                        *8$$BBBBBB%%%bYr+",
  "                                                                                       n&%#LUYXXzzccvuvr{",
  "                                                                                      )$@  ;~1vzvnx\\-;;zM|",
  "                                                                                      _BW\\~!  \"Ym~`   [0mt",
  "                                                                                      .8&U/-\" ?CQ<' ~(%$L+",
  "                                                                                       M8U,   nwQr    %BX`",
  "                                                                                       X%UUrvO0Yufj[](BMj",
  "                                                                                      .roULf1UYzx)jt\\(Bh_",
  "                                                                                     ;-xhnr)[cu{({\\(1(@m` \"",
  "                                                                                   `;_[iu({-{)    l{1(v{;+I:",
  "                                                                                    ^^`^\">~_\\\\{)lI>()\\}{|_\"i",
  "                                                                         `^^^`'`^     `^`^i}{}1j)}11\\t1~;,^,>",
  "                                                                       ,,,,I``''`,\"     `^`?c\\[}[[{/lI,,,\"^^I:",
  "                                                                      ,;:i ;;^``````';;'''\"/mwq0Xxtj;,`''.. .:",
  "                                                                      l:I<^;I,\",\"\"^^^;!I;;:nmwq0Xxtj,  .",
  "                                                                     I;;i+`'CU[>U(;;?<l!l;\"/LLCXnf\\(^\"'        '`.",
  "                                                                    ,;:!~~''>!;!t{;xQ(lvj:\"+xxj/){|-lI;:li.^\"^\"\"^`'`\"'",
  "                                                                    I:I<+i.'I,\",,\"^,l+I\\},:?({([1|>!!;^,-^;,:l>i;^`'^:l",
  "                                                                   I;;>+<;''I,\",,\"^^^<I!\"^l]-1Czc-livf!l)!;:!?{?i,`'`,!i",
  "                                                                  ,;;!+~l\"  I,\",,\"^^Iil!^\"<uZmYt; l>{?I)c!;:l+-~I^'.`,l+.",
  "                                                                  I:l~+!,`  l,\",,\"^^;!lI`:)8#|jU .li\"`l<<!;,,:;,^'..'\"l+^",
  "                                                                 I;I>+>:`.  l,\",,\"^^il!:^!X*k-zr ,!l`\"+,;i;\"^^\"\"^'..'\"I~l",
  "                                                                ,;;i+<;^'.  l,\",,\"^`!l!^\"~pdX[J} Ii:`I-^\">I,^^\"\"^`'.'^;<>",
  "                                                                I:l~~l\"'. . :,\",,\"^'~Il`;|mO\\/z: l>^\"~I^^il,^^\"\"^`'.'^;>i",
  "                                                               I:I<+!,'. .` \",\",,\"^'<II^!uLC-xu .!!`;_^^`l!:\"^\"\"\"`'..^:i<",
  "                                                              ,;;>+>:`. .`: \",\",:\"`;il,,_YYn]u} ,i,^>l^^'\"i;\"^\"\"\"^'..`:i]",
  "                                                              I:!+<;^.  ',i'\",\",:\"':!l^;)zc|)r> li`:?\"^'. <I,^^\"\"^'..`,!-",
  "                                                             I:I~~l\"'. '\"!l ',\",:\"'ill^irun]\\/^ ll^i~\"`. .!l:^^\"\"^`'.'\"l_",
  "                                                            ,;;>+!,'. .\"l+  .,\",:^.>l;,-urf}\\{ `!\":-:^'. ';i:\"^\"\"^`'.'\"I+^",
  "                                                            ;\",^:\"^. .^I<   .:\",:^.~I,IxkwLnt< ,!^!~,'. .^I>;\"^\"\"\"`'.'^I~^",
  "                                                           :\":;\"`'\":.`;+    .:\",:``<I\"<Z#**ak_ l;,+;^. .`,>+I,^^\"\"^'..^;<:",
  "                                                          l:l?]!^'^Ii:~`     :\",:':i:;)hao*##^'I,l_;'. '\"l+,!:^^\"\"^'..`:>>",
  "                                                          !:I<<;`.`;+>`      :\",:.;!:~ckkkkhw \";,_!,. .^;+  i;\"^\"\"^`..`:ii",
  "                                                         '!,^^\"^'.':<l       :\",\".ilI[Zkkkkkt I:l+I` .`:>I  <I\"^\"\"\"`'.`,i<",
  "                                                          !;^`^^`.'\"i,       :\",\".>I+)kkkkkk_ i:+!:. '\"!+   ;l,^^\"\"`'.',!]",
  "                                                          ^l,`^~]-+^ll     . :\",`.~!?npdbbkk ^!I_I` .^I+    .!:^^\"\"`'.'\"l-",
  "                                                           !:^chopLz-_     . `\",`^>_?vYJCQOz !l~>; .`:>I     >;\"\"\"^``''\"l_",
  "                                                           .ljd#&dJvr_     . `\",.;<-[||/tjn] >!-I\" '\"!+      lI;,,;;\"`'^I+\"",
  "                                                            Ix0ZZLXur}`    ' `\",.I+_:  \"\"i+` <<!; .^I+       ^!;:>[?!^'`:<^",
  "                                                             -LQO0Uvx(l    ''`\"^.>+-        .~+;^.`:<,       ';:i-?~;`'`,iI",
  "                                                             ;XL0OCcnj     '` \"^'+i~        \"_~; '\"!>        ::!-->:`..',ii",
  "                                                              {LQOQXuj;    '` \"^^~~^        I-:\".^I_        ;:-|\\+:`.  ':<:",
  "                                                               zL00Uvr~    '` \"`\"l?         !<;'`:<,       \"{ZkdZJf\"  '\"li",
  "                                                               }LQOCcx\\    '; \"`:>>        `l,\"',!<       .1b*%MmUct ',!l",
  "                                                                CQOQXuj    '; \"^;+^        \"::'^I_        ]bo&#qJvrt<:>'",
  "                                                                {L00Uvr:   '; \"\"!_         I,\"`:<,       !mo&#wUnt(/ii",
  "                                                                \"LQOLcx?  ',; \":<l        .;,^,i<       .Oo&#wUn/)|-;",
  "                                                                 rL0QYnj;;;;! \"I_:        `:\"^I_       .Oa&#mYx\\))?^",
  "                                                                 ,CLCcjx+>+~!  l?l;     ^::,,\"::       Ya&#mYx\\)(:",
  "                                                                  OwpQCXt;:^'. 'i:>   ;;;II;:,\",I\"    naW#mYx|)[",
  "                                                                 >Z0YQv\\;+|<!_;:\"^`ilil!<_+i;,\",;!;  nhW#mXr|)-",
  "                                                                  nvvzr{;\",^/Zf]JnZd<!l>-[?<I,\"\":Ii^\\hW#mXr((?",
  "                                                                   <jrt1i'  `;\"~\\OOU<!I!<+<l:\"^^\":?nd*#mXj((,",
  "                                                                    \"]_+i:'.     >j}>l;:;;::,,\"^^}k#MqCcf(|:",
  "                                                                     +iI;II;,^''''\"l>l:,\"\",,,,\"\"lq0Yvrvx(1",
  "                                                                     ;iI;II;,^`^,l+^il:,\"\"\",,,,\"lJJ0v\\{/\\+",
  "                                                                     IiI;II;,^`^,l_. II:,\"\"\",,,,\"uzn(]]1)",
  "                                                                     IiI;II;,^`^:!-   II:,\"\"\",,,,~{]_+--,",
  "                                                                     IiI;II;,^`^:!?    lI:,\"\"\",,,,,;:\",Ii.",
  "                                                                     IiI;II:\"^`^:i_     lI:,\"\"\",,,,\"\"^\":I>'",
  "                                                                     IiI;II:\"^`^;i!      ;I:,\"\"\",,,,\"\"^\":I!",
  "                                                                     IiI;II:\"^`\";>i       ,I:,\"\"\",,,,\"\"^\":li",
  "                                                                     IiI;II:\"^`\";<>        ,I:,\"\"\",,,,\"^^\":l:",
  "                                                                     IiI;II:\"^`\"I<`         ,I:,\"\"\",,,,\"^^,;!;",
  "                                                                     liI;II:\"^`\"I~^          ,I:,\"\"\",,,,\"^\",;!^",
  "                                                                     liI;II:\"^`\"I+\"           ,l:,\"\"\",,,,\"^\",;i.",
  "                                                                     ^iI;II:\"^`,l_             ^l:,\"\"\",,,,\"^\",I>",
  "                                                                     'iI;II:\"^^,l-               l:,\"\"\",,,,\"^\":I!",
  "                                                                     '>I;II:\"^^,!?                l:,\"\"\",,,\"\"^\":li",
  "                                                                     '>I;II:\"^^,!_                 l;,\"\"\",,,,,,,,I;",
  "                                                                     '>I;II:\"`^:i!                  l;,\"\"\";;;I;:\",I\"",
  "                                                                     '>I;;:,\"^^:ii                   l;,\"ll!~-<I,\":!'",
  "                                                                     '>lIII;,\":l>l                    !;l>li-?~I\"^,l_",
  "                                                                     '<l!_->:\",l+`                     I>iIl!!;,^^,l+\"",
  "                                                                     'il>__!,^\"I+^                      i!Il!I:\"``,l-",
  "                                                                     l!!<<l,^`\";+\"                      >!Il!I,^`^:i~",
  "                                                                    .il>~i:^``\"I~                       <lIl!;\"^`\";~:",
  "                                                                    !li~>I\"``^;~^                      '>lI!l:\"``\"l-",
  "                                                                   `!!<<l,^``,iI                       '>Il!l:^`^,i<",
  "                                                                   >li~i:^``\"l>                        IiIl!I,^`^;<:",
  "                                                                  \"!!<<I\"``^;>                         ;!Il!;\"^`\"I_",
  "                                                                  il>~!,^``:<`                         ~lIll;\"``,!<",
  "                                                                 Ili~>;^``\"!!                          <lI!l:^`^:<:",
  "                                                                .i!<<I\"``^I~                          '>;\"^`'``\"I_",
  "                                                                ;\"^\":,^`^:~                            ^'''.  ',!<",
  "                                                               ''`'. .\"^,>`                           \"^;<i,. .\"!,",
  "                                                              \"\"!_i^  ^li!                           I\",~{?I'  ^Ii",
  "                                                             ;\":+]>^  `;_                           ';^^;!;`   `I_",
  "                                                            :\"\"l>I^   `;-                           ;:^^::^.   ^I-",
  "                                                           \",\";>!\".   `I>                           l,^\":,`   .^l>",
  "                                                           :\":ii:'   .,>                           ';\"^,:\"'   .\"ii",
  "                                                          ;\",!>I`    ^l>                           ;:^^,:^.   ',>,",
  "                                                         ;,\"I>!\".   ':~                            l,^\":,`.   `:~^",
  "                                                        \",\":ii:'   .^!;                           ';\"^\":,`    `;+",
  "                                                        ;\",!>I^    `;>                            ;:^^,:\"'   .^l-",
  "                                                       ,:^:!!\".   .\"i\"                            l,^^::^.   .\"!_",
  "                                                       \",`'``.    `;:                            '\":`'``'    ',:`...",
  "                                                      ,,_+>i;,,\",:!lllII;.,                     ,\"l[+>il,,\"\",;!!!!!!;..:",
  "                                                     ^,^~----------------+,:                    I^\"i-----------------^.;'",
  "                                                     ',.,--------------<il:cCCCCCCCCCCCCCCCCCCCCl^.'+-------------+ii..I",
  "                                                      `'                 '^                      \"                    `\"",
  "                                                                                                  .",
  "",
  "",
  "",
];
