/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `wind_1` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                           !!  ?!",
  "                                                                                       |!  J? `8",
  "                                                                                   n?  ?m  aJ na",
  "                                                                                   `8? ?8!`8J!8J",
  "                                                                                    n8??8m?8Jmo?`a",
  "                                                                                    `8o|8oar8qo|an `?",
  "                                                                                  !n`nXo8r8>8<888!n8`",
  "                                                                                   |8Jo<o,0:nfw0aa8?",
  "                                                                                 |?!Joqx< ^,`-~aro|?`",
  "                                                                                  n8880JJJJCL0Zub88n",
  "                                                                                   mL      ?????{Qa",
  "                                                                                  `8L  '````^^^^]U8|",
  "                                                                                  n8f>/tffjrxnuzC08J",
  "                                                                                 nJz$$MWoL0ZwqW$$$uQn",
  "                                                                                 |vI&o%$$hf}k$$$&$InJ",
  "                                                                                 !w:8Qpa$q])q$@*L8.m|",
  "                                                                                  8>M@$$$v]\\C$$$$8\"8`",
  "                                                                                  J|n/cc1)tuYumwU8?m",
  "                                                                                 1Md/(X0/fjcQXUCL8cn'.                             ?J%BB*C]",
  "                                                                               'zkmkvcLmxzOO0JL0Q88b*v                         ?nmW&&MW%BBBBq\\`",
  "                                                                              _pwCk*LOpmU$$$$#Z0m&hLaMn                    !|J%%8*WMdmbW88%%BBBou]",
  "                                                                             -&MaW8&akdLCLQbMdLpWZQh88#}               !|J%%8&#ak*WMkpaWWWW&8Omw%%8r",
  "                                                                      ]]]]`   '|aBB%888hqOz0Z0dWooW&&88*~          `|J%%8&M*kpwZq*&88&%%888O;\"<][jUwkn?",
  "                                                                   !U%%%%BBa(    ?m%B%pYw8W**Wd&W88%B@@B*`     `?Ja%88W#adqmZwpkoo&%@@@@@B81<>]]???][jUwmn?",
  "                                                                  -W&M#%%BBB8b]]-??xJ%q}[?{tuXYW%@@$@qu?`  `?Ja%%8&MokpmZmwdh#W8BMW%@$$$$$%f\\tf/|){}]??][fYwmn?!?`",
  "                                                                 _#W#B&M%%%%%%%B#aWWWWm}[?{tuXY%BC\\!    !Ja%%8&M*hdwmZmpbo#&%B@@@$%%$$$$$$@MCYXcvnrf/|){[]??]j0UXqm?",
  "                                                                'pMMo%B#&8WWW&&&*aMoaMq(|\\fnXCYWW&&&uu?k88&W#abqmZmwdh*M&%B@@$$$$$$$$@@@$$$$B%oaqmJYzvnrf/|){(]<\\jcw<",
  "                                                                cMW*k#$z[X8v/q*xJoMZ#%MYczUQOLdoaoW#h&M&WokpwZZmqba#W8%B@@$$$$$$$$$@%n!   i][LLM@JJmoawmUXcuxv{r\\fxcL:",
  "                                                               _#W#hb#$ha#8mqkbcChU(L%*QQZmOYp#*aM8hhoMWawOZwpkoM&8BB@@$$$$$$$$$@BJ?                 `?|Jm#apCrYCLCOw:",
  "                                                              'pMMabh#$&W88&8%%%Mo#a&8hOqL(xJM#q}vWXU*WW*bph*M&%B@@@$$$$$$$$$@Bm|                          `?m*bhawu~",
  "                                                              cMW*bk*&$8M888&%%%Mo#M%&dcj)tC$@#**M#0d*W8&WW&%B@@@$$$$$$$$$@Bw|'                               `??!",
  "                                                             _#W#kbo&B$@M888&%%%M*#M%WQ^;Cj/$B#*%8ho**W8BBB@@@$$$$$$$$$$Ban!",
  "                                                            'pWMabhM%@$$#&88&8%%o*#W%#ul>pxc$&##%&q%8oW8B@$$$$$$$$$$$@%n!",
  "                                                            cMWobk#8@@$$M&88&8%%a*#&%a(+{p\\L$8*W%#b%%&M8B$$$$$$$$$@%J?",
  "                                                           _#W*kb*8B@$@$&W88&8%%a*#&8b(}xmfw$M*&8ao%%BB8B$$$$$$@%m|",
  "                                                          'pWMhbo&B@$$B$BW88&8%Ba##%Wq(|zQx*$#*%&p8%%@$@%%B$$MC|'",
  "                                                          cMMabhM%@$$B&B@W88&8%Bo##%MC/fQJv#$#*%#b8%B@$@8*Q",
  "                                                         _#W*bk#%@$$@8**$M888&%Bo##%*YrxZJX$@#M8aa%%@$@%Wk]",
  "                                                        'pW#kb*8B@$@8#Ol$W&88&%@*#W8hcuvpXJ$@#&&p&%B@$B8oQ",
  "                                                        cMMaba&B@$@%Md. &8&88&%@*#W&pczXmCZ$&#8Mb&%@$@%Mk?",
  "                                                       _#WobhW%@$@%Mk<  0B&88&%@a#&Mqhhwq0h$&*%ah&B@$B&oL",
  "                                                      'p&8WW&%@$$BWh<   t$W88&%@d#&#u;~\\n0k$WW&dW8@$@%Mb:",
  "                                                      z&&W&%B%WBB&a|    }$W88&%@b#&k{lII;;w$#&MpW%@$B&oz",
  "                                                     1MMbmh&BBWa8ox      $888&%@bMWw?~~<<>p$#&obW@$@%Mb:",
  "                                                     wMMhb*%@B&akn       $%888B$kWoO~~~~~~*B#Wd*8@$B&az",
  "                                                     hW8888B@@8oL        p$&88B@kMdc~~~~~~$B#MpM%$@%#d:",
  "                                                     t#8%%8%@@%#Y        J$&88B@h*wf~~~~~~$M#okM@$B&ar",
  "                                                     .oW%%8%BB%Wb        r$&88B@hhqr)1{}[c$*#d#&$@8#p",
  "                                                      t#8%onjUh&h:       +$%88B@hqqO0Ycun0$oodW%$BWh|",
  "                                                      .a&*-^i)jo#[       ;$B88B&kdz?|JJJmB$bahW$@8#p",
  "                                                       tMw}[1tn0Wx        %$88BMpbf      0$bdM8$BWh(",
  "                                                       .a8t11\\rv8X        #$88B#qb>      0$ad&B@8*q",
  "                                                        tWO){(fuof        X$&8B#bp       $@ohW@BWh]",
  "                                                         X#(1)tnmn        u$B8B#ow       $BoM8@8*Q",
  "                                                          JC)1\\rJa        {B@8B&aj      >$&o&%%Wk]",
  "                                                          !#){(fu8`       +%$8%Wk?      }$8W&B8*Q",
  "                                                           mn11/nk|       ;M$8%#d>      t$M&8%Mk?",
  "                                                           ?h){|rQJ        o$%8*q       0$#&%&oL",
  "                                                            an1)fz8     lxYh$B&oz       0$M&%Mb:",
  "                                                            |q)1/no?  'zMMMa@$WhQ_     -aWW&&8#x'",
  "                                                             8t(tvhn .q#*hbb$$$ha*/  ldMM##MW&8&Mf",
  "                                                             nq~{tnbJto**M&%B@@%&%M((o#*hbbaM&8&W*u",
  "                                                             8n||fXJ8ko*MdCkh0ko*#8%ao*apmwk#&88W#a}",
  "                                                             nwnfuJ0Cko*W&W%z1YO?dO)h*#*hbkoW8888W*h.",
  "                                                              jxczLZikoMM@$$B&B%d&pXh*MWMMMW&88%8&M*Z",
  "                                                               iJqdr boMM&@@$$$$$$@&h*W&88&&&&88%8&Mou",
  "                                                                 I   boMM##W&%%%8&*rC*W&888&&&&88%8W#a~",
  "                                                                     boMM##W&%%%&*p 'q#W&888&&&&88%8W*k.",
  "                                                                     boMM##W&%%%W*p  'q#W&88&&&&&8%8&M*J",
  "                                                                     boMM##W&%%%Woq   Io#W&88&&&&88%8&Mo/",
  "                                                                     UoMM##W8%%8WoL    +oMW&88&&&&88%8W#h~",
  "                                                                     uoMM##W8%%8War     +oMW888&&&&88%8W*m.",
  "                                                                     uoMM##W8%%8Maj      _*M&888&&&&888&Mou",
  "                                                                     uoMM##W8%%8Mhf       {*M&888&&&&8%8&Ma}",
  "                                                                     uoMM##W8%%8Mk<        v*M&888&&&88%8&#h;",
  "                                                                     uo#M##W8%%8#k>         v*W&88&&&&88%8W*m.",
  "                                                                     no#M##W8%%&#b>          c#W&88&&&&888&Mou",
  "                                                                     no#M##W8%%&#d            c#W&88&&&&888&Ma+",
  "                                                                     no#M#MW8%%&*p            .w#W&88&&&&8%8&#h.",
  "                                                                     na#M#MW8%%&*q             'q#W888&&&&8%8W*Z",
  "                                                                     na#M#MW8%%&oL              'qMW888&&&88%8Mo/",
  "                                                                     }a#M#MW8%%Wor               'qM&888&&&&&&&Wo~",
  "                                                                     +a#M#M&8%%War                IoM&88M#M##W&8Wq.",
  "                                                                     +a#MMW&8%8Waf                 +oM&o**kqb*&8&#U",
  "                                                                     ~a#MM#W&8W*h<                  +*#h**bpk#&%&#k;",
  "                                                                     ~h*oppoW8&*d>                   _ah#M**M&%%8Mk<",
  "                                                                     +o*adb*&%&#d>                    {a##*#W8%%8#b>",
  "                                                                     m*okh#&%B8#d                     }a##*#W8%%&*p",
  "                                                                    {o*hkoW%BB8*Q                     no##*#&8%%Woz",
  "                                                                   .w*okaM8%B%Mb.                     uo##*M&%%%Wh(",
  "                                                                   to*hh#&%B%Wa[                      uo##*M&%%8Mb>",
  "                                                                  .a*akoW8BB8*x                       Z*M#*M8%%8#p",
  "                                                                  J*okhM8%B8#O                        k*M##W8%%&oz",
  "                                                                 Io*hk*&%B%Wk;                        k*M*#W8%%Wa(",
  "                                                                 C*okaW8BB&o|                         h##*#&8%8Mk>",
  "                                                                {o*hh#8%B8#Y                         ~hM8%%B@B8#p",
  "                                                                d888&8%B%MZ.                         +&BBB@$$@8*X",
  "                                                              ?oBBB@$@8%&h<                         'k%WhkMB$$BMn",
  "                                                             -88odo%$$%*or                          Q&8ommo%$$BWh.",
  "                                                            lM8Wbwa%$$BM0                           *&%&#M8@$$BWh<",
  "                                                            d8&*a#%$$$BMp                          +#8%8&8@$$$BWh<",
  "                                                           X&8Ma*8@$$$%#X                          fM%%8&%@$$$BWk>",
  "                                                          -W8WoaW@$$$@&h;                          LW%%&&%@$$$%Mb",
  "                                                         'M8&*a#%$$$$%*x                          .*&%%&&B$$$$%Md",
  "                                                         d&8#a*8@$$$BWk.                          +#8%8&8B$$$$%#p",
  "                                                        z&8WaaWB$$$$8o\\                           cM8%8&8B$$$@8*q",
  "                                                       lW8&*a#%$$$$BMZ                            qW%%8&8@$$$@8*X",
  "                                                       zW%Wo*8@$$$@&a[                            *&%%&&%@$$$@&ox",
  "                                                      !h&%BBB@$$$$%WWLLLL]                      'm8WBBBB@$$$$B&WB@@$$pu'",
  "                                                     l&&dbaaM&&8&W***###W$k.                    08#mbaa*&&&8&Moooo**M@@d.",
  "                                                     f&8kppppppppppppppppb&\\                    #%8appppppppppppppppp%$M~",
  "                                                     1&@&ppppppppppppppho*W}                    #%@Bbpppppppppppppboo$$#;",
  "                                                      U@$$$$$$$$$$$$$$$$$Bx...................  }8$$$$$$$$$$$$$$$$$$$$%t",
  "                                                       t0$$$ZZZZZZ||||||i^^^^^^^^\"\"\"\"\"^^^^^^^^^``)#$$$$$$$$$$kZOOOOj{}^",
  "                                                          ...'''```^^^^^\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"^^^^i|||'''...",
  "                                                             ...''''`````^^^^^^^^^^^^^^^^^^^^^`````''''...",
  "                                                                           .................",
];
