/*
   Copyright (C) 2026 Afri Blanck (@l5yth)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @file Frame `wind_2` of the ASCII Punk sprite sheet (SPEC D10). Generated
 * by `design/render.mjs`; edit the design project, not this file.
 */

/** Rows of the frame, top to bottom, right-trimmed on a 168 by 128 grid. */
export const rows = [
  "",
  "",
  "",
  "                                                                                                                             lI'",
  "                                                                                                                         \\OLC0c/!",
  "                                                                                                                        xkdzCc\\[>",
  "                                                                                                                       ~pqO/|1??-",
  "                                                                                                                     .na8&0x[??(+",
  "                                                                                                                    ~Z#%#mXr)}1<",
  "                                                                                                                  .na&8hQvt){^",
  "                                                                                          `                      }b#%WpJn\\1{",
  "                                                                                  /   )  `z   f                ^YaW%oZXr|1+",
  "                                                                                  Ll  d  ct  L)              `|b*8&bLcf))_",
  "                                                                                  fQ _o`'@1 }k`             >ChW%#wJu/1(,",
  "                                                                                  ~#(_W?n&}[@\\            ,iZo88aOXx\\1{,",
  "                                                                                I; #qf8tWb\\$O``u        \":;rqkodLcj(1(\"",
  "                                                                                 m)CMwBQ$O&Mt}a)      '::l_xLCJXut)1}_",
  "                                                                               f.]*q&p@a$w$U*&{ >v(  ;:;<][?jxj/({)}!",
  "                                                                               ikJp#M#BMW%dM*zJMp>  \"I:>[]<;,<-[[_i,",
  "                                                                                u#&@$$$BWMkop$bf    iI,;!l,`.   `;:",
  "                                                                               -W$$$$$$$$$$@B%QOXi  <I\"``''.  .^;;",
  "                                                                               b8$$$$$$$$$$$%Lr|    <I\"'.    .^Ii",
  "                                                                              [W%%mLLLLCCCCCCYr[   .!I,'     `I<<",
  "                                                                             ($@^.>{////////??U0,  ,l:,\"    ',I<<",
  "                                                                             _@M}~   [dbj<:   Xbj  lI,,;:^...`:<:",
  "                                                                             +BMzX?\" icY;  ~}#$L+  >;,,;:^'..`;~^",
  "                                                                              %Mz.   uq01   I$8z`  i;,:;:^'..^;~^",
  "                                                                              W#YX]1COCrv?I;?$of  ^!:,:;,^'..^I+^",
  "                                                                             ;LpLU/fJUcr/rt\\t$w<  ;l:,:;,`'..^I+^",
  "                                                                            i~cOuj1|cvx))/()v$Ui. iI,,:;,`'.'\"I_\"",
  "                                                                          ,>1--u|{-|<  \"<[{1xk/\"I^>;,,;;\"`..'\"l_\"",
  "                                                                         ,<)_:,;+~]t/+>  <1)/_:\"\"!i;,,;:\"`..'\"l-\"",
  "                                                                        \",l`^\",,I?)1{fn(|()/i,,\"^l!:,:;:\"'..'\"l-'",
  "                                                                           '''`^^`c/}}1}[{}I\"`'..ll:,:;:^'..',!?",
  "                                                                 .```.        ''`\"mwpYuf\\/+'..`  <I,,:;,^'..`,!?",
  "                                                              ',\",^^```\"^   `''^^~mwpZUuf/<``'   >;,,:;,^'..`,!]",
  "                                                             ,;:\";:`````````<;!!l[00OLzx//~;;;:+:i;,,;;,`'..`:i]",
  "                                                             l:I,.l,\"::::;;;~;li:,nvnr/))(I<>I;?i!:,,;:\"`'..`:i[",
  "                                                            I;;i< lXtI~U(i|c[;u|:,-\\1}[{/!I<?:I}<l:,:;:\"`'..`:i[",
  "                                                           ,;:!~+ ,(]:i1-;[\\]If)l:?)}zzz1IIxU{im<I,\",:,\"`...^:>}",
  "                                                           l:I<+>` l,^^\"\"^^^iI;:`;]_)bc- ,III\"<+<I,^```'.. .^;<+",
  "                                                          I;;>+<I` I:^^\"\"^^^iI;:`;tkW-X\\ ,I;`,_^ll,^'...   .^I+:",
  "                                                         ,;;!~~l\"' \";\"^^\"^^^>l;:^InMo-c/ ,I;`:-^\"l:^.      ',!l",
  "                                                         I:l~+!,`.  I\"^^\"^^^l!;:^lnkd-z\\ ,I;`I+^^^,^.      ^I,",
  "                                                        I;;>+>:`..  :,^^\"\"^^;!;:^!zwZ-U( \"I:^!>^^`.''.    '.",
  "                                                       ,;;i+<I^'. . `:^^\"\"^^;i;:^izQC-z1 \"I,\"<i^`'..`:~:",
  "                                                       I:l~~l\"'. .^` ;\"^^\"^^I>;:\"<vUY-u} \"I,,_;^`...\"l-",
  "                                                      I;I<+i,`. .`:i ,,^^\"^`'<;:\"~vzf-x[ \"I,:]\"^'..',>i",
  "                                                     ,;;i+>:`. .`,>i ':^^\"\"`'<;:,_vu/-f? \"I`I+\"`'..^;+^",
  "                                                     I:!~<I^'. ',i!   ;\"^\"\"^'~;:,-xr|}\\_ \"I^!+\"`. '\"!_",
  "                                                    I:I~~l\"'. '\"!+    ,\"^^\"^'<I::]cj\\)1< \"I^>>\"'..`:<l",
  "                                                   ,;;>+i,'. .^l~     ',^^\"^.!I:;t#*oamt \":\"+I\"...^I-",
  "                                                   I,;!l:`. .^I>       :^^\"^.!I,IuW&&&&U \",:?:^..',i~",
  "                                                  :\"^^`'`^'.`;~^       \"\"^^\".il,inhaao*X ,,;~:`..^;~:",
  "                                                 \":I+<:`',l^:<`        ',^^\".;l:+nkkkkkv ::l-:' '\"l?",
  "                                                ^l:>[_;`'\"l~>,          ,^^\".:!;?Lkkkkkv ;:>i:..`:>l",
  "                                                ;I,,:,^'.^I-!           \"\"^\".:il[Lkkkkkv I;~!\"..^I_.",
  "                                                ^l,^^\"^'.`:~           ..\"^^';ii]Jqppppn ll?,^.',i<",
  "                                                 !;^`^^`.',>`          ` ,^^'^>+?uzzzXX( !!_,`.`;~:",
  "                                                 ^l,`|JpOc]!;          . `^^''<??(((|||_ ;>_,.'\"l?",
  "                                                  I:jk&WqJc{>           ` \"^''+?]        I<!,.`:>>",
  "                                                   lmwbpQznj+           \" \"^`'-_[        \"_l\".^I+.",
  "                                                   IvL0OLXnj[.          ^ `^`'~<i        \"]\"^'\"!_",
  "                                                    -LQOQYvr\\.           ` ^``~>>        \"_\"``:<:",
  "                                                    \"XL00Jcxf            ; \"``><>        \"i\"`\"l-",
  "                                                     -LQOLXnj            ; '^`;<:        \"I\"',i~",
  "                                                      zL00Uvr!           .^ ^^;~^        \",^^;+^",
  "                                                      }L0OCcx?            l \"^I+\"        \",^\"!_",
  "                                                       CQOQXnj            l '\"I_\"        :,^:<l",
  "                                                       {L00Uur:          .l` \"l-        ^:,,,\"`",
  "                                                       ,LQOCcx~        ,;;lI ^l?:     :;;II;:,\",I^",
  "                                                        rL0Qzx|       lll<_i  `]:!^  lll>+~iI,\"\":!;",
  "                                                        \"XU0YYz}     !il!;,^`````''i>!li_[]~l,\"\":I>\"",
  "                                                        <qkQzrrj:    ~!l;-|+]|[~(tOm<!l!<_~i;\"^^,;!>",
  "                                                        !CzJCr((;    ~!l:,;^fC\\10LOJ<!;;;I;:,\"^^\",I>:",
  "                                                         _jrnt)-     ~!I;.   ,' ,~r|<l;,\",,,,,\"^^\":l<",
  "                                                           )([-:     ~!I;,'.      .\"!!;,\"\",,,,\"\"^^,;i!",
  "                                                            `,       ~!I;II:,^`^,l_\" !l;,\"\",,,,\"^^\":I>\"",
  "                                                                     ~!I;II:\"^`^:!-  .iI:,\"\",,,,\"^^\";!>",
  "                                                                     +!I;II:\"^`^:!?   `!I:,\",,,,\"\"^^,Ii:",
  "                                                                     +!I;II:\"^`^:i]    :!;,\"\",,,,\"^^\":l<",
  "                                                                     +!I;II:\"^`\";i!     !l;,\"\",,,,\"^^,;!!",
  "                                                                     +!I;II:\"^`\";>i      iI:,\"\",,,\"\"^\",I>\"",
  "                                                                     !!I;II:\"^`\";<>      .iI:\"\",,,,\"^^\":!>",
  "                                                                     ;!I;II:\"^`\"I<:       ;!;,\"\",,,,\"^^,;i:",
  "                                                                     ;!I;II:\"^`\"I~^        Il;,\"\",,,\"\"^\":l<",
  "                                                                     IiI;II:\"^`\"I+^         lI:,\",,,,\"^^\";!!",
  "                                                                     IiI;II:\"^^,l_.         .iI:\"\",,,,\"^^,I>\"",
  "                                                                     IiI;II:\"^^,l-           `!;,\"\",,,\"\"^\":l>",
  "                                                                     IiI;II:\"^^,!?            :l;,\"\",,,\"^^\";i:",
  "                                                                     IiI;II:\"`^,!]             !I:,\",,,,\"^^,I<",
  "                                                                     IiI;II,\"`^:i!              iI:\"\",,,\"\"^\":!!",
  "                                                                     IiI;II,\"`^:ii              .!;,\"\",:::,,\";i\"",
  "                                                                     liI;II,^`^:>>               :l;,,lIl!I:\",;i",
  "                                                                     :iI;;:,\"^\";<:                !l;ili-]~I,\":!:",
  "                                                                     .il;II:,\";l<^                 liil!+_i;\"^,l_",
  "                                                                     '>li--i:\",!_^                 .~iI;II:\"^^,l_",
  "                                                                     ^il>_~l,^,l_                   IiI;II:\"^^,l-",
  "                                                                     !l!<>I\"^`\"I_                   IiI;II:\"`^,!_",
  "                                                                    ,!l><!,^``\"!<                   liI;II,\"`^:i!",
  "                                                                    >li~i;\"``^I_                    liI;II,^`^:>>",
  "                                                                   \"!!<<I,^`^:<`                    liI;II,^`^;<`",
  "                                                                   il>~!:^``,!!                     liI;I;,^`\";~^",
  "                                                                  l!!<>;\"``\"I~                      liI;I;,^`\"I_",
  "                                                                  il><l,^`^;~                       .iI;I;,^`\"l-",
  "                                                                 !li~i:^``,i,                       .iI;I;,^`,l_",
  "                                                                `!!<<I\"``\"ll                        .i:^^`'.`,!!",
  "                                                                :\"^\",\"^`^;<                          ,''`'. .^!>",
  "                                                               ''`'. .\"^:<`                         ,^,>+l^  '::",
  "                                                              \"\"i_!^  ^Ii;                         `,\"l][>^  ',i",
  "                                                             ;\":+]i^  `Ii                          i,^\";;\".  ',iI",
  "                                                            :\"\"l>I`   `I?                          !,``\"\"'   ',i>",
  "                                                           ^,\"I>!\".   `l!                          l\"``\"^'   ',ii",
  "                                                           :\":ii:'   .,<                          .I\"`^\"^'   ',ii",
  "                                                          ;\",!>I`    ^l:                          `;^`^\"^'   ',ii",
  "                                                         ;,\"I>!\".   ':~                           ,;^`^\"^.   ',ii",
  "                                                        \",\":ii:'   .\"!;                           ;:^`^\"^.   ',ii",
  "                                                        ;\",!>I`    `;>                            i:^`^\"^.   ',ii",
  "                                                       ,:^:!!\".   .\"i,                            !,``\"\"`.   ',ii",
  "                                                       \",`'``.    `;:                            '\":`'``'    ',:`...",
  "                                                      ,,_+>i;,,\",:!lllII;.,                     ,\"l[+>il,,\"\",;!!!!!!;..:",
  "                                                     ^,^~----------------+,:                    I^\"i-----------------^.;'",
  "                                                     ',.,--------------<il:cCCCCCCCCCCCCCCCCCCCCl^.'+-------------+ii..I",
  "                                                      `'                 '^                      \"                    `\"",
  "                                                                                                  .",
  "",
  "",
  "",
];
